/home/aakash/mlpack/src/mlpack/bindings/go/CMakeLists.txt File Reference
Functions
CMake go AppendModel cmake get_property (MODELS GLOBAL PROPERTY GO_MODELS) foreach(models IN LISTS MODELS) append_model(`$
 if (NOT BUILD_GO_SHLIB) macro(add_go_binding name) endmacro() return() endif() endmacro() macro(post_go_setup) if(BUILD_GO_BINDINGS) file(APPEND `$
src mlpack bindings go src mlpack org v1 mlpack models go *n import C n n import (\n` ` \`runtime\`\n` ` \`unsafe\`\n` `)\n\n`) include(`$
 macro (not_found_return message) message(STATUS `$
Function Documentation
get_property()
CMake go AppendModel cmake get_property (MODELS GLOBAL PROPERTY GO_MODELS)
Definition at line 26 of file CMakeLists.txt.
if()
if (NOT BUILD_GO_SHLIB)
Definition at line 3 of file CMakeLists.txt.
Referenced by HeInitialization::Initialize(), LecunNormalInitialization::Initialize(), mlpack::bindings::python::PrintDefn(), mlpack::bindings::julia::PrintDoc(), mlpack::bindings::python::PrintDoc(), mlpack::bindings::go::PrintDoc(), mlpack::bindings::julia::PrintInputParam(), and mlpack::bindings::python::PrintInputProcessing().
import()
src mlpack bindings go src mlpack org v1 mlpack models go* n import C n n import (\n` ` \`runtime\`\n` ` \`unsafe\`\n` `)
Definition at line 19 of file CMakeLists.txt.
macro()
macro (not_found_return message)
Definition at line 1 of file CMakeLists.txt.