CartPole Class Reference
Implementation of Cart Pole task.
Classes
class Action
Implementation of action of Cart Pole.
class State
Implementation of the state of Cart Pole.
Public Member Functions
 CartPole (const size_t maxSteps=200, const double gravity=9.8, const double massCart=1.0, const double massPole=0.1, const double length=0.5, const double forceMag=10.0, const double tau=0.02, const double thetaThresholdRadians=12 *2 *3.1416/360, const double xThreshold=2.4, const double doneReward=1.0)
Construct a Cart Pole instance using the given constants.
 State InitialSample ()
Initial state representation is randomly generated within [-0.05, 0.05].
bool IsTerminal (const State &state) const
This function checks if the cart has reached the terminal state.
size_t MaxSteps () const
Get the maximum number of steps allowed.
size_t & MaxSteps ()
Set the maximum number of steps allowed.
double Sample (const State &state, const Action &action, State &nextState)
Dynamics of Cart Pole instance.
double Sample (const State &state, const Action &action)
Dynamics of Cart Pole.
size_t StepsPerformed () const
Get the number of steps performed.
Detailed Description
Implementation of Cart Pole task.
Definition at line 26 of file cart_pole.hpp.
Constructor & Destructor Documentation
CartPole()
 CartPole (const size_t maxSteps = 200, const double gravity = 9.8, const double massCart = 1.0, const double massPole = 0.1, const double length = 0.5, const double forceMag = 10.0, const double tau = 0.02, const double thetaThresholdRadians = 12 * 2 * 3.1416 / 360, const double xThreshold = 2.4, const double doneReward = 1.0) [inline]
Construct a Cart Pole instance using the given constants.
Parameters
maxSteps The number of steps after which the episode terminates. If the value is 0, there is no limit.
gravity The gravity constant.
massCart The mass of the cart.
massPole The mass of the pole.
length The length of the pole.
forceMag The magnitude of the applied force.
tau The time interval.
thetaThresholdRadians The maximum angle.
xThreshold The maximum position.
doneReward Reward recieved by agent on success.
Definition at line 117 of file cart_pole.hpp.
Member Function Documentation
InitialSample()
 State InitialSample () [inline]
Initial state representation is randomly generated within [-0.05, 0.05].
Returns
Initial state for each episode.
Definition at line 207 of file cart_pole.hpp.
References CartPole::State::State().
IsTerminal()
bool IsTerminal (const State & state) const [inline]
This function checks if the cart has reached the terminal state.
Parameters
state The desired state.
Returns
true if state is a terminal state, otherwise false.
Definition at line 219 of file cart_pole.hpp.
References CartPole::State::Angle(), and CartPole::State::Position().
Referenced by CartPole::Sample().
MaxSteps() [1/2]
size_t MaxSteps () const [inline]
Get the maximum number of steps allowed.
Definition at line 240 of file cart_pole.hpp.
MaxSteps() [2/2]
size_t& MaxSteps () [inline]
Set the maximum number of steps allowed.
Definition at line 242 of file cart_pole.hpp.
Sample() [1/2]
double Sample (const State & state, const Action & action, State & nextState) [inline]
Dynamics of Cart Pole instance.
Get reward and next state based on current state and current action.
Parameters
state The current state.
action The current action.
nextState The next state.
Returns
reward, it's always 1.0.
When done is false, it means that the cartpole has fallen down. For this case the reward is 1.0.
Definition at line 151 of file cart_pole.hpp.
References CartPole::Action::action, CartPole::State::Angle(), CartPole::State::AngularVelocity(), CartPole::IsTerminal(), CartPole::State::Position(), and CartPole::State::Velocity().
Referenced by CartPole::Sample().
Sample() [2/2]
double Sample (const State & state, const Action & action) [inline]
Dynamics of Cart Pole.
Get reward based on current state and current action.
Parameters
state The current state.
action The current action.
Returns
reward, it's always 1.0.
Definition at line 196 of file cart_pole.hpp.
References CartPole::Sample().
StepsPerformed()
size_t StepsPerformed () const [inline]
Get the number of steps performed.
Definition at line 237 of file cart_pole.hpp.
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/methods/reinforcement_learning/environment/ cart_pole.hpp