GaussianInitialization Class Reference
This class is used to initialize weigth matrix with a gaussian.
Public Member Functions
 GaussianInitialization (const double mean=0, const double variance=1)
Initialize the gaussian with the given mean and variance.
template<typename eT >
void Initialize (arma::Mat< eT > &W, const size_t rows, const size_t cols)
Initialize the elements weight matrix using a Gaussian Distribution.
template<typename eT >
void Initialize (arma::Mat< eT > &W)
Initialize the elements weight matrix using a Gaussian Distribution.
template<typename eT >
void Initialize (arma::Cube< eT > &W, const size_t rows, const size_t cols, const size_t slices)
Initialize randomly the elements of the specified weight 3rd order tensor.
template<typename eT >
void Initialize (arma::Cube< eT > &W)
Initialize randomly the elements of the specified weight 3rd order tensor.
Detailed Description
This class is used to initialize weigth matrix with a gaussian.
Definition at line 28 of file gaussian_init.hpp.
Constructor & Destructor Documentation
GaussianInitialization()
 GaussianInitialization (const double mean = 0, const double variance = 1) [inline]
Initialize the gaussian with the given mean and variance.
Parameters
mean Mean of the gaussian.
variance Variance of the gaussian.
Definition at line 37 of file gaussian_init.hpp.
Member Function Documentation
Initialize() [1/4]
void Initialize (arma::Mat< eT > & W, const size_t rows, const size_t cols) [inline]
Initialize the elements weight matrix using a Gaussian Distribution.
Parameters
W Weight matrix to initialize.
rows Number of rows.
cols Number of columns.
Definition at line 51 of file gaussian_init.hpp.
References mlpack::math::RandNormal().
Referenced by GlorotInitializationType< Uniform >::Initialize().
Initialize() [2/4]
void Initialize (arma::Mat< eT > & W) [inline]
Initialize the elements weight matrix using a Gaussian Distribution.
Parameters
W Weight matrix to initialize.
Definition at line 67 of file gaussian_init.hpp.
References mlpack::math::RandNormal().
Initialize() [3/4]
void Initialize (arma::Cube< eT > & W, const size_t rows, const size_t cols, const size_t slices) [inline]
Initialize randomly the elements of the specified weight 3rd order tensor.
Parameters
W Weight matrix to initialize.
rows Number of rows.
cols Number of columns.
slices Number of slices.
Definition at line 84 of file gaussian_init.hpp.
Initialize() [4/4]
void Initialize (arma::Cube< eT > & W) [inline]
Initialize randomly the elements of the specified weight 3rd order tensor.
Parameters
W Weight matrix to initialize.
Definition at line 102 of file gaussian_init.hpp.
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/methods/ann/init_rules/ gaussian_init.hpp