AMF< TerminationPolicyType, InitializationRuleType, UpdateRuleType > Class Template Reference
This class implements AMF (alternating matrix factorization) on the given matrix V.
Public Member Functions
 AMF (const TerminationPolicyType &terminationPolicy=TerminationPolicyType(), const InitializationRuleType &initializeRule=InitializationRuleType(), const UpdateRuleType &update=UpdateRuleType())
Create the AMF object and (optionally) set the parameters which AMF will run with.
template<typename MatType >
double Apply (const MatType &V, const size_t r, arma::mat &W, arma::mat &H)
Apply Alternating Matrix Factorization to the provided matrix.
InitializationRuleType & InitializeRule ()
Modify the initialization rule.
const InitializationRuleType & InitializeRule () const
Access the initialization rule.
TerminationPolicyType & TerminationPolicy ()
Modify the termination policy.
const TerminationPolicyType & TerminationPolicy () const
Access the termination policy.
UpdateRuleType & Update ()
Modify the update rule.
const UpdateRuleType & Update () const
Access the update rule.
Detailed Description
template<typename TerminationPolicyType = SimpleResidueTermination, typename InitializationRuleType = RandomAcolInitialization<>, typename UpdateRuleType = NMFMultiplicativeDistanceUpdate>
class mlpack::amf::AMF< TerminationPolicyType, InitializationRuleType, UpdateRuleType >
This class implements AMF (alternating matrix factorization) on the given matrix V.
Alternating matrix factorization decomposes V in the form $ V \approx WH $ where W is called the basis matrix and H is called the encoding matrix. V is taken to be of size n x m and the obtained W is n x r and H is r x m. The size r is called the rank of the factorization.
The implementation requires three template types; the first contains the policy used to determine when the algorithm has converged; the second contains the initialization rule for the W and H matrix; the last contains the update rule to be used during each iteration. This templatization allows the user to try various update rules, initialization rules, and termination policies (including ones not supplied with mlpack) for factorization. By default, the template parameters to AMF implement non-negative matrix factorization with the multiplicative distance update.
A simple example of how to run AMF (or NMF) is shown below.
extern arma::mat V; // Matrix that we want to perform LMF on.
size_t r = 10; // Rank of decomposition
arma::mat W; // Basis matrix
arma::mat H; // Encoding matrix
AMF<> amf; // Default options: NMF with multiplicative distance update rules.
amf.Apply(V, r, W, H);
Template Parameters
TerminationPolicy The policy to use for determining when the factorization has converged.
InitializationRule The initialization rule for initializing W and H matrix.
UpdateRule The update rule for calculating W and H matrix at each iteration.
See also
NMFMultiplicativeDistanceUpdate, SimpleResidueTermination
Definition at line 78 of file amf.hpp.
Constructor & Destructor Documentation
AMF()
 AMF (const TerminationPolicyType & terminationPolicy = TerminationPolicyType(), const InitializationRuleType & initializeRule = InitializationRuleType(), const UpdateRuleType & update = UpdateRuleType())
Create the AMF object and (optionally) set the parameters which AMF will run with.
The minimum residue refers to the root mean square of the difference between two subsequent iterations of the product W * H. A low residue indicates that subsequent iterations are not producing much change in W and H. Once the residue goes below the specified minimum residue, the algorithm terminates.
Parameters
initializeRule Optional instantiated InitializationRule object for initializing the W and H matrices.
update Optional instantiated UpdateRule object; this parameter is useful when the update rule for the W and H vector has state that it needs to store (i.e. HUpdate() and WUpdate() are not static functions).
terminationPolicy Optional instantiated TerminationPolicy object.
Member Function Documentation
Apply()
double Apply (const MatType & V, const size_t r, arma::mat & W, arma::mat & H)
Apply Alternating Matrix Factorization to the provided matrix.
Parameters
V Input matrix to be factorized.
W Basis matrix to be output.
H Encoding matrix to output.
r Rank r of the factorization.
Referenced by BatchSVDPolicy::Apply(), NMFPolicy::Apply(), SVDCompletePolicy::Apply(), and SVDIncompletePolicy::Apply().
InitializeRule() [1/2]
InitializationRuleType& InitializeRule () [inline]
Modify the initialization rule.
Definition at line 125 of file amf.hpp.
InitializeRule() [2/2]
const InitializationRuleType& InitializeRule () const [inline]
Access the initialization rule.
Definition at line 122 of file amf.hpp.
TerminationPolicy() [1/2]
TerminationPolicyType& TerminationPolicy () [inline]
Modify the termination policy.
Definition at line 119 of file amf.hpp.
TerminationPolicy() [2/2]
const TerminationPolicyType& TerminationPolicy () const [inline]
Access the termination policy.
Definition at line 116 of file amf.hpp.
Update() [1/2]
UpdateRuleType& Update () [inline]
Modify the update rule.
Definition at line 130 of file amf.hpp.
Update() [2/2]
const UpdateRuleType& Update () const [inline]
Access the update rule.
Definition at line 128 of file amf.hpp.
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/methods/amf/ amf.hpp