ScalingModel Class Reference
The model to save to disk.
Public Types
enum ScalerTypes {
 STANDARD_SCALER,
 MIN_MAX_SCALER,
 MEAN_NORMALIZATION,
 MAX_ABS_SCALER,
 PCA_WHITENING,
 ZCA_WHITENING
 }
Public Member Functions
 ScalingModel (const int minvalue=0, const int maxvalue=1, double epsilonvalue=0.00005)
Create an object.
 ScalingModel (const ScalingModel &other)
Copy constructor.
 ScalingModel (ScalingModel &&other)
Move constructor.
 ~ScalingModel ()
Clean up memory.
template<typename MatType >
void Fit (const MatType &input)
template<typename MatType >
void InverseTransform (const MatType &input, MatType &output)
 ScalingModel & operator= (const ScalingModel &other)
Copy assignment operator.
 ScalingModel & operator= (ScalingModel &&other)
Move assignment operator.
size_t ScalerType () const
Get the Scaler type.
size_t & ScalerType ()
Modify the Scaler type.
template<typename Archive >
void serialize (Archive &ar, const uint32_t)
Serialize the model.
template<typename MatType >
void Transform (const MatType &input, MatType &output)
Transform to scale features.
Detailed Description
The model to save to disk.
Definition at line 29 of file scaling_model.hpp.
Member Enumeration Documentation
ScalerTypes
enum ScalerTypes
Enumerator
STANDARD_SCALER
MIN_MAX_SCALER
MEAN_NORMALIZATION
MAX_ABS_SCALER
PCA_WHITENING
ZCA_WHITENING
Definition at line 32 of file scaling_model.hpp.
Constructor & Destructor Documentation
ScalingModel() [1/3]
 ScalingModel (const int minvalue = 0, const int maxvalue = 1, double epsilonvalue = 0.00005)
Create an object.
ScalingModel() [2/3]
 ScalingModel (const ScalingModel & other)
Copy constructor.
ScalingModel() [3/3]
 ScalingModel (ScalingModel && other)
Move constructor.
~ScalingModel()
~ ScalingModel ()
Clean up memory.
Member Function Documentation
Fit()
void Fit (const MatType & input)
Referenced by ScalingModel::ScalerType().
InverseTransform()
void InverseTransform (const MatType & input, MatType & output)
Referenced by ScalingModel::ScalerType().
operator=() [1/2]
 ScalingModel& operator= (const ScalingModel & other)
Copy assignment operator.
operator=() [2/2]
 ScalingModel& operator= (ScalingModel && other)
Move assignment operator.
ScalerType() [1/2]
size_t ScalerType () const [inline]
Get the Scaler type.
Definition at line 75 of file scaling_model.hpp.
ScalerType() [2/2]
size_t& ScalerType () [inline]
Modify the Scaler type.
Definition at line 77 of file scaling_model.hpp.
References ScalingModel::Fit(), ScalingModel::InverseTransform(), and ScalingModel::Transform().
serialize()
void serialize (Archive & ar, const uint32_t) [inline]
Serialize the model.
Definition at line 93 of file scaling_model.hpp.
References CEREAL_POINTER.
Transform()
void Transform (const MatType & input, MatType & output)
Transform to scale features.
Referenced by ScalingModel::ScalerType().
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/methods/preprocess/ scaling_model.hpp