Pendulum Class Reference
Implementation of Pendulum task.
Classes
class Action
Implementation of action of Pendulum.
class State
Implementation of state of Pendulum.
Public Member Functions
 Pendulum (const size_t maxSteps=200, const double maxAngularVelocity=8, const double maxTorque=2.0, const double dt=0.05, const double doneReward=0.0)
Construct a Pendulum instance using the given values.
double AngleNormalize (double theta) const
This function calculates the normalized angle for a particular theta.
 State InitialSample ()
Initial theta is randomly generated within [-pi, pi].
bool IsTerminal (const State &) const
This function checks if the pendulum has reaches a terminal state.
size_t & MaxSteps ()
Set the maximum number of steps allowed.
size_t MaxSteps () const
Get the maximum number of steps allowed.
double Sample (const State &state, const Action &action)
Dynamics of Pendulum.
double Sample (const State &state, const Action &action, State &nextState)
Dynamics of Pendulum.
size_t StepsPerformed () const
Get the number of steps performed.
Detailed Description
Implementation of Pendulum task.
The inverted pendulum swingup problem is a classic problem in the control literature. In this version of the problem, the pendulum starts in a random position, and the goal is to swing it up so it stays upright
Definition at line 31 of file pendulum.hpp.
Constructor & Destructor Documentation
Pendulum()
 Pendulum (const size_t maxSteps = 200, const double maxAngularVelocity = 8, const double maxTorque = 2.0, const double dt = 0.05, const double doneReward = 0.0) [inline]
Construct a Pendulum instance using the given values.
Parameters
maxSteps The number of steps after which the episode terminates. If the value is 0, there is no limit (Default: 200 steps).
maxAngularVelocity Maximum angular velocity.
maxTorque Maximum torque.
dt The differential value.
doneReward The reward recieved by the agent on success.
Definition at line 118 of file pendulum.hpp.
Member Function Documentation
AngleNormalize()
double AngleNormalize (double theta) const [inline]
This function calculates the normalized angle for a particular theta.
Parameters
theta The un-normalized angle.
Definition at line 212 of file pendulum.hpp.
References M_PI.
Referenced by Pendulum::Sample().
InitialSample()
 State InitialSample () [inline]
Initial theta is randomly generated within [-pi, pi].
Initial angular velocity is randomly generated within [-1, 1].
Returns
Initial state for each episode.
Definition at line 197 of file pendulum.hpp.
References Pendulum::State::AngularVelocity(), M_PI, mlpack::math::Random(), Pendulum::State::SetState(), and Pendulum::State::Theta().
IsTerminal()
bool IsTerminal (const State &) const [inline]
This function checks if the pendulum has reaches a terminal state.
Parameters
* (state) desired state.
Returns
true if state is a terminal state, otherwise false.
Definition at line 227 of file pendulum.hpp.
References Log::Info.
MaxSteps() [1/2]
size_t& MaxSteps () [inline]
Set the maximum number of steps allowed.
Definition at line 244 of file pendulum.hpp.
MaxSteps() [2/2]
size_t MaxSteps () const [inline]
Get the maximum number of steps allowed.
Definition at line 242 of file pendulum.hpp.
Sample() [1/2]
double Sample (const State & state, const Action & action) [inline]
Dynamics of Pendulum.
Get reward based on current state and current action
Parameters
state The current state.
action The current action.
Returns
reward, The reward.
Definition at line 185 of file pendulum.hpp.
References Pendulum::Sample().
Sample() [2/2]
double Sample (const State & state, const Action & action, State & nextState) [inline]
Dynamics of Pendulum.
Get reward and next state based on current state and current action.
Parameters
state The current state.
action The current action.
nextState The next state.
Returns
reward, The reward for taking the action taken for current state.
Definition at line 140 of file pendulum.hpp.
References Pendulum::Action::action, Pendulum::AngleNormalize(), Pendulum::State::AngularVelocity(), mlpack::math::ClampRange(), M_PI, Pendulum::State::SetState(), and Pendulum::State::Theta().
Referenced by Pendulum::Sample().
StepsPerformed()
size_t StepsPerformed () const [inline]
Get the number of steps performed.
Definition at line 239 of file pendulum.hpp.
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/methods/reinforcement_learning/environment/ pendulum.hpp