RegressionDistribution Class Reference
A class that represents a univariate conditionally Gaussian distribution.
Public Member Functions
 RegressionDistribution ()
Default constructor, which creates a Gaussian with zero dimension.
 RegressionDistribution (const arma::mat &predictors, const arma::rowvec &responses)
Create a Conditional Gaussian distribution with conditional mean function obtained by running RegressionFunction on predictors, responses.
 mlpack_deprecated RegressionDistribution (const arma::mat &predictors, const arma::vec &responses)
Create a Conditional Gaussian distribution with conditional mean function obtained by running RegressionFunction on predictors, responses.
size_t Dimensionality () const
Return the dimensionality.
 GaussianDistribution & Err ()
Modify error distribution.
const GaussianDistribution & Err () const
Return error distribution.
double LogProbability (const arma::vec &observation) const
Evaluate log probability density function of given observation.
const arma::vec & Parameters () const
Return the parameters (the b vector).
void Predict (const arma::mat &points, arma::rowvec &predictions) const
Calculate y_i for each data point in points.
 mlpack_deprecated void Predict (const arma::mat &points, arma::vec &predictions) const
Calculate y_i for each data point in points.
double Probability (const arma::vec &observation) const
Evaluate probability density function of given observation.
 regression::LinearRegression & Rf ()
Modify regression function.
const regression::LinearRegression & Rf () const
Return regression function.
template<typename Archive >
void serialize (Archive &ar, const uint32_t)
Serialize the distribution.
void Train (const arma::mat &observations)
Estimate the Gaussian distribution directly from the given observations.
void Train (const arma::mat &observations, const arma::rowvec &weights)
Estimate parameters using provided observation weights.
 mlpack_deprecated void Train (const arma::mat &observations, const arma::vec &weights)
Estimate parameters using provided observation weights.
Detailed Description
A class that represents a univariate conditionally Gaussian distribution.
Can be used as an emission distribution with the hmm class to implement HMM regression (HMMR) as described in https://www.ima.umn.edu/preprints/January1994/1195.pdf The hmm observations should have the dependent variable in the first row, with the independent variables in the other rows.
Definition at line 31 of file regression_distribution.hpp.
Constructor & Destructor Documentation
RegressionDistribution() [1/3]
 RegressionDistribution () [inline]
Default constructor, which creates a Gaussian with zero dimension.
Definition at line 43 of file regression_distribution.hpp.
RegressionDistribution() [2/3]
 mlpack_deprecated RegressionDistribution (const arma::mat & predictors, const arma::vec & responses) [inline]
Create a Conditional Gaussian distribution with conditional mean function obtained by running RegressionFunction on predictors, responses.
Parameters
predictors Matrix of predictors (X).
responses Vector of responses (y).
Definition at line 52 of file regression_distribution.hpp.
RegressionDistribution() [3/3]
 RegressionDistribution (const arma::mat & predictors, const arma::rowvec & responses) [inline]
Create a Conditional Gaussian distribution with conditional mean function obtained by running RegressionFunction on predictors, responses.
Parameters
predictors Matrix of predictors (X).
responses Vector of responses (y).
Definition at line 64 of file regression_distribution.hpp.
References LinearRegression::ComputeError(), GaussianDistribution::Covariance(), and LinearRegression::Train().
Member Function Documentation
Dimensionality()
size_t Dimensionality () const [inline]
Return the dimensionality.
Definition at line 156 of file regression_distribution.hpp.
References LinearRegression::Parameters().
Err() [1/2]
 GaussianDistribution& Err () [inline]
Modify error distribution.
Definition at line 92 of file regression_distribution.hpp.
Err() [2/2]
const GaussianDistribution& Err () const [inline]
Return error distribution.
Definition at line 90 of file regression_distribution.hpp.
LogProbability()
double LogProbability (const arma::vec & observation) const [inline]
Evaluate log probability density function of given observation.
Parameters
observation Point to evaluate log probability at.
Definition at line 130 of file regression_distribution.hpp.
References RegressionDistribution::Probability().
Parameters()
const arma::vec& Parameters () const [inline]
Return the parameters (the b vector).
Definition at line 153 of file regression_distribution.hpp.
References LinearRegression::Parameters().
Predict() [1/2]
void Predict (const arma::mat & points, arma::rowvec & predictions) const
Calculate y_i for each data point in points.
Parameters
points The data points to calculate with.
predictions Y, will contain calculated values on completion.
Predict() [2/2]
 mlpack_deprecated void Predict (const arma::mat & points, arma::vec & predictions) const
Calculate y_i for each data point in points.
Parameters
points The data points to calculate with.
predictions Y, will contain calculated values on completion.
Probability()
double Probability (const arma::vec & observation) const
Evaluate probability density function of given observation.
Parameters
observation Point to evaluate probability at.
Referenced by RegressionDistribution::LogProbability().
Rf() [1/2]
 regression::LinearRegression& Rf () [inline]
Modify regression function.
Definition at line 87 of file regression_distribution.hpp.
Rf() [2/2]
const regression::LinearRegression& Rf () const [inline]
Return regression function.
Definition at line 85 of file regression_distribution.hpp.
serialize()
void serialize (Archive & ar, const uint32_t) [inline]
Serialize the distribution.
Definition at line 78 of file regression_distribution.hpp.
Train() [1/3]
void Train (const arma::mat & observations)
Estimate the Gaussian distribution directly from the given observations.
Parameters
observations List of observations.
Train() [2/3]
void Train (const arma::mat & observations, const arma::rowvec & weights)
Estimate parameters using provided observation weights.
Parameters
observations List of observations.
weights Probability that given observation is from distribution.
Train() [3/3]
 mlpack_deprecated void Train (const arma::mat & observations, const arma::vec & weights)
Estimate parameters using provided observation weights.
Parameters
observations List of observations.
weights Probability that given observation is from distribution.
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/core/dists/ regression_distribution.hpp