ZCAWhitening Class Reference
A simple ZCAWhitening class.
Public Member Functions
 ZCAWhitening (double eps=0.00005)
A constructor to set the regularization parameter.
const arma::vec & EigenValues () const
Get the eigenvalues vector.
const arma::mat & EigenVectors () const
Get the eigenvector.
double Epsilon () const
Get the regularization parameter.
template<typename MatType >
void Fit (const MatType &input)
Function to fit features, to find out the min max and scale.
template<typename MatType >
void InverseTransform (const MatType &input, MatType &output)
Function to retrieve original dataset.
const arma::vec & ItemMean () const
Get the mean row vector.
template<typename Archive >
void serialize (Archive &ar, const uint32_t)
template<typename MatType >
void Transform (const MatType &input, MatType &output)
Function for ZCA whitening.
Detailed Description
A simple ZCAWhitening class.
Whitens a matrix using the eigendecomposition of the covariance matrix. Whitening means the covariance matrix of the result is the identity matrix.
For whitening related formula and more info, check the link below. http://ufldl.stanford.edu/tutorial/unsupervised/PCAWhitening/
arma::mat input;
Load("train.csv", input);
arma::mat output;
// Fit the features.
ZCAWhitening scale;
scale.Fit(input)
// Scale the features.
scale.Transform(input, output);
// Retransform the input.
scale.InverseTransform(output, input);
Definition at line 47 of file zca_whitening.hpp.
Constructor & Destructor Documentation
ZCAWhitening()
 ZCAWhitening (double eps = 0.00005) [inline]
A constructor to set the regularization parameter.
Parameters
eps Regularization parameter.
Definition at line 55 of file zca_whitening.hpp.
Member Function Documentation
EigenValues()
const arma::vec& EigenValues () const [inline]
Get the eigenvalues vector.
Definition at line 98 of file zca_whitening.hpp.
References PCAWhitening::EigenValues().
EigenVectors()
const arma::mat& EigenVectors () const [inline]
Get the eigenvector.
Definition at line 100 of file zca_whitening.hpp.
References PCAWhitening::EigenVectors().
Epsilon()
double Epsilon () const [inline]
Get the regularization parameter.
Definition at line 102 of file zca_whitening.hpp.
References PCAWhitening::Epsilon().
Fit()
void Fit (const MatType & input) [inline]
Function to fit features, to find out the min max and scale.
Parameters
input Dataset to fit.
Definition at line 63 of file zca_whitening.hpp.
References PCAWhitening::Fit().
InverseTransform()
void InverseTransform (const MatType & input, MatType & output) [inline]
Function to retrieve original dataset.
Parameters
input Scaled dataset.
output Output matrix with original Dataset.
Definition at line 88 of file zca_whitening.hpp.
References PCAWhitening::EigenValues(), PCAWhitening::EigenVectors(), and PCAWhitening::ItemMean().
ItemMean()
const arma::vec& ItemMean () const [inline]
Get the mean row vector.
Definition at line 96 of file zca_whitening.hpp.
References PCAWhitening::ItemMean().
serialize()
void serialize (Archive & ar, const uint32_t) [inline]
Definition at line 105 of file zca_whitening.hpp.
Transform()
void Transform (const MatType & input, MatType & output) [inline]
Function for ZCA whitening.
Parameters
input Dataset to scale features.
output Output matrix with whitened features.
Definition at line 75 of file zca_whitening.hpp.
References PCAWhitening::EigenVectors(), and PCAWhitening::Transform().
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/core/data/scaler_methods/ zca_whitening.hpp