JuliaOption< T > Class Template Reference
The Julia option class.
Public Member Functions
 JuliaOption (const T defaultValue, const std::string &identifier, const std::string &description, const std::string &alias, const std::string &cppName, const bool required=false, const bool input=true, const bool noTranspose=false, const std::string &=``)
Construct a JuliaOption object.
Detailed Description
template<typename T>
class mlpack::bindings::julia::JuliaOption< T >
The Julia option class.
Definition at line 37 of file julia_option.hpp.
Constructor & Destructor Documentation
JuliaOption()
 JuliaOption (const T defaultValue, const std::string & identifier, const std::string & description, const std::string & alias, const std::string & cppName, const bool required = false, const bool input = true, const bool noTranspose = false, const std::string & = ``) [inline]
Construct a JuliaOption object.
When constructed, it will register itself with IO. The testName parameter is not used and added for compatibility reasons.
Definition at line 45 of file julia_option.hpp.
References IO::Add(), ParamData::alias, IO::ClearSettings(), ParamData::cppType, ParamData::desc, IO::functionMap, IO::GetSingleton(), ParamData::input, ParamData::loaded, ParamData::name, ParamData::noTranspose, ParamData::persistent, mlpack::bindings::julia::programName, ParamData::required, IO::RestoreSettings(), IO::StoreSettings(), ParamData::tname, TYPENAME, ParamData::value, and ParamData::wasPassed.
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/bindings/julia/ julia_option.hpp