TestOption< N > Class Template Reference
A static object whose constructor registers a parameter with the IO class.
Public Member Functions
 TestOption (const N defaultValue, const std::string &identifier, const std::string &description, const std::string &alias, const std::string &cppName, const bool required=false, const bool input=true, const bool noTranspose=false, const std::string &testName=``)
Construct an Option object.
Detailed Description
template<typename N>
class mlpack::bindings::tests::TestOption< N >
A static object whose constructor registers a parameter with the IO class.
This should not be used outside of IO itself, and you should use the PARAM_FLAG(), PARAM_DOUBLE(), PARAM_INT(), PARAM_STRING(), or other similar macros to declare these objects instead of declaring them directly.
See also
core/util/io.hpp, mlpack::IO
Definition at line 40 of file test_option.hpp.
Constructor & Destructor Documentation
TestOption()
 TestOption (const N defaultValue, const std::string & identifier, const std::string & description, const std::string & alias, const std::string & cppName, const bool required = false, const bool input = true, const bool noTranspose = false, const std::string & testName = ``) [inline]
Construct an Option object.
When constructed, it will register itself with IO.
Parameters
defaultValue Default value this parameter will be initialized to (for flags, this should be false, for instance).
identifier The name of the option (no dashes in front; for --help, we would pass `help`).
description A short string describing the option.
alias Short name of the parameter. `` for no alias.
cppName Name of the C++ type of this parameter (i.e. `int`).
required Whether or not the option is required at runtime.
input Whether or not the option is an input option.
noTranspose If the parameter is a matrix and this is true, then the matrix will not be transposed on loading.
testName Name of the test (used for identifiying which binding test this option belongs to)
Definition at line 61 of file test_option.hpp.
References IO::Add(), ParamData::alias, IO::ClearSettings(), ParamData::cppType, ParamData::desc, IO::functionMap, IO::GetSingleton(), ParamData::input, ParamData::loaded, ParamData::name, ParamData::noTranspose, ParamData::persistent, ParamData::required, IO::RestoreSettings(), IO::SetPassed(), IO::StoreSettings(), ParamData::tname, TYPENAME, ParamData::value, and ParamData::wasPassed.
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/bindings/tests/ test_option.hpp