GoOption< T > Class Template Reference
The Go option class.
Public Member Functions
 GoOption (const T defaultValue, const std::string &identifier, const std::string &description, const std::string &alias, const std::string &cppName, const bool required=false, const bool input=true, const bool noTranspose=false, const std::string &=``)
Construct a GoOption object.
Detailed Description
template<typename T>
class mlpack::bindings::go::GoOption< T >
The Go option class.
Definition at line 39 of file go_option.hpp.
Constructor & Destructor Documentation
GoOption()
 GoOption (const T defaultValue, const std::string & identifier, const std::string & description, const std::string & alias, const std::string & cppName, const bool required = false, const bool input = true, const bool noTranspose = false, const std::string & = ``) [inline]
Construct a GoOption object.
When constructed, it will register itself with IO. The testName parameter is not used and added for compatibility reasons.
Parameters
defaultValue Default value this parameter will be initialized to (for flags, this should be false, for instance).
identifier The name of the option (no dashes in front; for --help, we would pass `help`).
description A short string describing the option.
alias Short name of the parameter. `` for no alias.
cppName Name of the C++ type of this parameter (i.e. `int`).
required Whether or not the option is required at runtime.
input Whether or not the option is an input option.
noTranspose If the parameter is a matrix and this is true, then the matrix will not be transposed on loading.
* (testName) Is not used and added for compatibility reasons.
Definition at line 60 of file go_option.hpp.
References IO::Add(), ParamData::alias, IO::ClearSettings(), ParamData::cppType, ParamData::desc, IO::functionMap, IO::GetSingleton(), ParamData::input, ParamData::loaded, ParamData::name, ParamData::noTranspose, ParamData::persistent, mlpack::bindings::go::programName, ParamData::required, IO::RestoreSettings(), IO::StoreSettings(), ParamData::tname, TYPENAME, ParamData::value, and ParamData::wasPassed.
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/bindings/go/ go_option.hpp