BindingInfo Class Reference
The BindingInfo class is used by the Markdown documentation generator to store multiple documentation objects, indexed by both the binding name (i.e.
Static Public Member Functions
static util::BindingDetails & GetBindingDetails (const std::string &bindingName)
Return a BindingDetails object for a given bindingName.
static BindingInfo & GetSingleton ()
Get the singleton.
static std::string & Language ()
Get or modify the current language (don't set it to something invalid!).
Public Attributes
std::unordered_map< std::string, util::BindingDetails > map
Internally-held map for mapping a binding name to a BindingDetails.
Detailed Description
The BindingInfo class is used by the Markdown documentation generator to store multiple documentation objects, indexed by both the binding name (i.e.
`knn`) and the language (i.e. `cli`).
Definition at line 30 of file binding_info.hpp.
Member Function Documentation
GetBindingDetails()
static util::BindingDetails& GetBindingDetails (const std::string & bindingName) [static]
Return a BindingDetails object for a given bindingName.
GetSingleton()
static BindingInfo& GetSingleton () [static]
Get the singleton.
Referenced by ExampleWrapper::ExampleWrapper(), LongDescriptionWrapper::LongDescriptionWrapper(), ProgramNameWrapper::ProgramNameWrapper(), SeeAlsoWrapper::SeeAlsoWrapper(), and ShortDescriptionWrapper::ShortDescriptionWrapper().
Language()
static std::string& Language () [static]
Get or modify the current language (don't set it to something invalid!).
Referenced by mlpack::bindings::markdown::DefaultParam(), mlpack::bindings::markdown::GetPrintableType(), and mlpack::bindings::markdown::PrintTypeDoc().
Member Data Documentation
map
std::unordered_map<std::string, util::BindingDetails> map
Internally-held map for mapping a binding name to a BindingDetails.
Definition at line 44 of file binding_info.hpp.
Referenced by ExampleWrapper::ExampleWrapper(), LongDescriptionWrapper::LongDescriptionWrapper(), ProgramNameWrapper::ProgramNameWrapper(), SeeAlsoWrapper::SeeAlsoWrapper(), and ShortDescriptionWrapper::ShortDescriptionWrapper().
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/bindings/markdown/ binding_info.hpp