Pendulum::State Class Reference
Implementation of state of Pendulum.
Public Member Functions
 State ()
Construct a state instance.
 State (const arma::colvec &data)
Construct a state based on the given data.
double AngularVelocity () const
Get the angular velocity.
double & AngularVelocity ()
Modify the value of angular velocity.
arma::colvec & Data ()
Modify the internal representation of the state.
const arma::colvec & Encode ()
Encode the state to a column vector.
void SetState ()
Updates the theta transformations in data.
double Theta () const
Get the theta.
double & Theta ()
Modify the value of theta.
Static Public Attributes
static constexpr size_t dimension = 3
Dimension of the encoded state.
Detailed Description
Implementation of state of Pendulum.
Each state is a (cos(theta), sin(theta), angular velocity) vector.
Definition at line 38 of file pendulum.hpp.
Constructor & Destructor Documentation
State() [1/2]
 State () [inline]
Construct a state instance.
Definition at line 44 of file pendulum.hpp.
State() [2/2]
 State (const arma::colvec & data) [inline]
Construct a state based on the given data.
Parameters
data Data for the cos(theta), sin(theta) and angular velocity.
Definition at line 53 of file pendulum.hpp.
Member Function Documentation
AngularVelocity() [1/2]
double AngularVelocity () const [inline]
Get the angular velocity.
Definition at line 65 of file pendulum.hpp.
Referenced by Pendulum::InitialSample(), and Pendulum::Sample().
AngularVelocity() [2/2]
double& AngularVelocity () [inline]
Modify the value of angular velocity.
Definition at line 67 of file pendulum.hpp.
Data()
arma::colvec& Data () [inline]
Modify the internal representation of the state.
Definition at line 57 of file pendulum.hpp.
Encode()
const arma::colvec& Encode () [inline]
Encode the state to a column vector.
Definition at line 70 of file pendulum.hpp.
SetState()
void SetState () [inline]
Updates the theta transformations in data.
Definition at line 73 of file pendulum.hpp.
Referenced by Pendulum::InitialSample(), and Pendulum::Sample().
Theta() [1/2]
double Theta () const [inline]
Get the theta.
Definition at line 60 of file pendulum.hpp.
Referenced by Pendulum::InitialSample(), and Pendulum::Sample().
Theta() [2/2]
double& Theta () [inline]
Modify the value of theta.
Definition at line 62 of file pendulum.hpp.
Member Data Documentation
dimension
constexpr size_t dimension = 3 [static]
Dimension of the encoded state.
Definition at line 80 of file pendulum.hpp.
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/methods/reinforcement_learning/environment/ pendulum.hpp