RandomInitialization Class Reference
This class is used to initialize randomly the weight matrix.
Public Member Functions
 RandomInitialization (const double bound)
Initialize the random initialization rule with the given bound.
 RandomInitialization (const double lowerBound=-1, const double upperBound=1)
Initialize the random initialization rule with the given lower bound and upper bound.
template<typename eT >
void Initialize (arma::Cube< eT > &W)
Initialize randomly the elements of the specified weight 3rd order tensor.
template<typename eT >
void Initialize (arma::Cube< eT > &W, const size_t rows, const size_t cols, const size_t slices)
Initialize randomly the elements of the specified weight 3rd order tensor.
template<typename eT >
void Initialize (arma::Mat< eT > &W)
Initialize randomly the elements of the specified weight matrix.
template<typename eT >
void Initialize (arma::Mat< eT > &W, const size_t rows, const size_t cols)
Initialize randomly the elements of the specified weight matrix.
Detailed Description
This class is used to initialize randomly the weight matrix.
Definition at line 24 of file random_init.hpp.
Constructor & Destructor Documentation
RandomInitialization() [1/2]
 RandomInitialization (const double lowerBound = -1, const double upperBound = 1) [inline]
Initialize the random initialization rule with the given lower bound and upper bound.
Parameters
lowerBound The number used as lower bound.
upperBound The number used as upper bound.
Definition at line 34 of file random_init.hpp.
RandomInitialization() [2/2]
 RandomInitialization (const double bound) [inline]
Initialize the random initialization rule with the given bound.
Using the negative of the bound as lower bound and the positive bound as upper bound.
Parameters
bound The number used as lower bound
Definition at line 45 of file random_init.hpp.
Member Function Documentation
Initialize() [1/4]
void Initialize (arma::Cube< eT > & W) [inline]
Initialize randomly the elements of the specified weight 3rd order tensor.
Parameters
W Weight matrix to initialize.
Definition at line 109 of file random_init.hpp.
References Log::Fatal, and RandomInitialization::Initialize().
Initialize() [2/4]
void Initialize (arma::Cube< eT > & W, const size_t rows, const size_t cols, const size_t slices) [inline]
Initialize randomly the elements of the specified weight 3rd order tensor.
Parameters
W Weight matrix to initialize.
rows Number of rows.
cols Number of columns.
slices Number of slices.
Definition at line 91 of file random_init.hpp.
References RandomInitialization::Initialize().
Initialize() [3/4]
void Initialize (arma::Mat< eT > & W) [inline]
Initialize randomly the elements of the specified weight matrix.
Parameters
W Weight matrix to initialize.
Definition at line 72 of file random_init.hpp.
References Log::Fatal.
Initialize() [4/4]
void Initialize (arma::Mat< eT > & W, const size_t rows, const size_t cols) [inline]
Initialize randomly the elements of the specified weight matrix.
Parameters
W Weight matrix to initialize.
rows Number of rows.
cols Number of columns.
Definition at line 56 of file random_init.hpp.
Referenced by RandomInitialization::Initialize(), GlorotInitializationType< Uniform >::Initialize(), KathirvalavakumarSubavathiInitialization::Initialize(), NguyenWidrowInitialization::Initialize(), OivsInitialization< ActivationFunction >::Initialize(), and JacobianTest().
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/methods/ann/init_rules/ random_init.hpp