Acrobot::State Class Reference
Public Member Functions
 State ()
Construct a state instance.
 State (const arma::colvec &data)
Construct a state instance from given data.
double AngularVelocity1 () const
Get value of Angular velocity (one).
double & AngularVelocity1 ()
Modify the angular velocity (one).
double AngularVelocity2 () const
Get value of Angular velocity (two).
double & AngularVelocity2 ()
Modify the angular velocity (two).
arma::colvec & Data ()
Modify the state representation.
const arma::colvec & Encode () const
Encode the state to a column vector.
double Theta1 () const
Get value of theta (one).
double & Theta1 ()
Modify value of theta (one).
double Theta2 () const
Get value of theta (two).
double & Theta2 ()
Modify value of theta (two).
Static Public Attributes
static constexpr size_t dimension = 4
Dimension of the encoded state.
Detailed Description
Definition at line 35 of file acrobot.hpp.
Constructor & Destructor Documentation
State() [1/2]
 State () [inline]
Construct a state instance.
Definition at line 41 of file acrobot.hpp.
Referenced by Acrobot::InitialSample().
State() [2/2]
 State (const arma::colvec & data) [inline]
Construct a state instance from given data.
Parameters
data Data for the theta and angular velocity of two links.
Definition at line 48 of file acrobot.hpp.
Member Function Documentation
AngularVelocity1() [1/2]
double AngularVelocity1 () const [inline]
Get value of Angular velocity (one).
Definition at line 65 of file acrobot.hpp.
Referenced by Acrobot::Sample().
AngularVelocity1() [2/2]
double& AngularVelocity1 () [inline]
Modify the angular velocity (one).
Definition at line 67 of file acrobot.hpp.
AngularVelocity2() [1/2]
double AngularVelocity2 () const [inline]
Get value of Angular velocity (two).
Definition at line 70 of file acrobot.hpp.
Referenced by Acrobot::Sample().
AngularVelocity2() [2/2]
double& AngularVelocity2 () [inline]
Modify the angular velocity (two).
Definition at line 72 of file acrobot.hpp.
Data()
arma::colvec& Data () [inline]
Modify the state representation.
Definition at line 52 of file acrobot.hpp.
Encode()
const arma::colvec& Encode () const [inline]
Encode the state to a column vector.
Definition at line 75 of file acrobot.hpp.
Theta1() [1/2]
double Theta1 () const [inline]
Get value of theta (one).
Definition at line 55 of file acrobot.hpp.
Referenced by Acrobot::IsTerminal(), and Acrobot::Sample().
Theta1() [2/2]
double& Theta1 () [inline]
Modify value of theta (one).
Definition at line 57 of file acrobot.hpp.
Theta2() [1/2]
double Theta2 () const [inline]
Get value of theta (two).
Definition at line 60 of file acrobot.hpp.
Referenced by Acrobot::IsTerminal(), and Acrobot::Sample().
Theta2() [2/2]
double& Theta2 () [inline]
Modify value of theta (two).
Definition at line 62 of file acrobot.hpp.
Member Data Documentation
dimension
constexpr size_t dimension = 4 [static]
Dimension of the encoded state.
Definition at line 78 of file acrobot.hpp.
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/methods/reinforcement_learning/environment/ acrobot.hpp