HeInitialization Class Reference
This class is used to initialize weight matrix with the He initialization rule given by He et.
Public Member Functions
 HeInitialization ()
Initialize the HeInitialization object.
template<typename eT >
void Initialize (arma::Cube< eT > &W)
Initialize the elements of the specified weight 3rd order tensor with He initialization rule.
template<typename eT >
void Initialize (arma::Cube< eT > &W, const size_t rows, const size_t cols, const size_t slices)
Initialize the elements of the specified weight 3rd order tensor with He initialization rule.
template<typename eT >
void Initialize (arma::Mat< eT > &W)
Initialize the elements of the weight matrix with the He initialization rule.
template<typename eT >
void Initialize (arma::Mat< eT > &W, const size_t rows, const size_t cols)
Initialize the elements of the weight matrix with the He initialization rule.
Detailed Description
This class is used to initialize weight matrix with the He initialization rule given by He et.
al. for neural networks. The He initialization initializes weights of the neural network to better suit the rectified activation units.
For more information, the following paper can be referred to:
@article{Delving2015,
  title = {Delving Deep into Rectifiers: Surpassing Human-Level Performance
             on ImageNet Classification},
  author = {Kaiming He and Xiangyu Zhang and Shaoqing Ren and Jian Sun},
  journal = {2015 IEEE International Conference on Computer Vision (ICCV)},
  year = {2015},
  pages = {1026-1034}
}
Definition at line 45 of file he_init.hpp.
Constructor & Destructor Documentation
HeInitialization()
 HeInitialization () [inline]
Initialize the HeInitialization object.
Definition at line 51 of file he_init.hpp.
Member Function Documentation
Initialize() [1/4]
void Initialize (arma::Cube< eT > & W) [inline]
Initialize the elements of the specified weight 3rd order tensor with He initialization rule.
Parameters
W Weight matrix to initialize.
Definition at line 131 of file he_init.hpp.
References Log::Fatal, and HeInitialization::Initialize().
Initialize() [2/4]
void Initialize (arma::Cube< eT > & W, const size_t rows, const size_t cols, const size_t slices) [inline]
Initialize the elements of the specified weight 3rd order tensor with He initialization rule.
Parameters
W Weight matrix to initialize.
rows Number of rows.
cols Number of columns.
slices Number of slices.
Definition at line 112 of file he_init.hpp.
References HeInitialization::Initialize().
Initialize() [3/4]
void Initialize (arma::Mat< eT > & W) [inline]
Initialize the elements of the weight matrix with the He initialization rule.
Parameters
W Weight matrix to initialize.
Definition at line 87 of file he_init.hpp.
References Log::Fatal, and if().
Initialize() [4/4]
void Initialize (arma::Mat< eT > & W, const size_t rows, const size_t cols) [inline]
Initialize the elements of the weight matrix with the He initialization rule.
Parameters
W Weight matrix to initialize.
rows Number of rows.
cols Number of columns.
Definition at line 65 of file he_init.hpp.
Referenced by HeInitialization::Initialize().
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/methods/ann/init_rules/ he_init.hpp