ContinuousMountainCar::State Class Reference
Implementation of state of Continuous Mountain Car.
Public Member Functions
 State ()
Construct a state instance.
 State (const arma::colvec &data)
Construct a state based on the given data.
arma::colvec & Data ()
Modify the internal representation of the state.
const arma::colvec & Encode () const
Encode the state to a column vector.
double & Position ()
Modify the position.
double Position () const
Get the position.
double & Velocity ()
Modify the velocity.
double Velocity () const
Get the velocity.
Static Public Attributes
static constexpr size_t dimension = 2
Dimension of the encoded state.
Detailed Description
Implementation of state of Continuous Mountain Car.
Each state is a (velocity, position) vector.
Definition at line 36 of file continuous_mountain_car.hpp.
Constructor & Destructor Documentation
State() [1/2]
 State () [inline]
Construct a state instance.
Definition at line 42 of file continuous_mountain_car.hpp.
State() [2/2]
 State (const arma::colvec & data) [inline]
Construct a state based on the given data.
Parameters
data Data for the velocity and position.
Definition at line 50 of file continuous_mountain_car.hpp.
Member Function Documentation
Data()
arma::colvec& Data () [inline]
Modify the internal representation of the state.
Definition at line 54 of file continuous_mountain_car.hpp.
Encode()
const arma::colvec& Encode () const [inline]
Encode the state to a column vector.
Definition at line 67 of file continuous_mountain_car.hpp.
Position() [1/2]
double& Position () [inline]
Modify the position.
Definition at line 64 of file continuous_mountain_car.hpp.
Position() [2/2]
double Position () const [inline]
Get the position.
Definition at line 62 of file continuous_mountain_car.hpp.
Referenced by ContinuousMountainCar::InitialSample(), ContinuousMountainCar::IsTerminal(), and ContinuousMountainCar::Sample().
Velocity() [1/2]
double& Velocity () [inline]
Modify the velocity.
Definition at line 59 of file continuous_mountain_car.hpp.
Velocity() [2/2]
double Velocity () const [inline]
Get the velocity.
Definition at line 57 of file continuous_mountain_car.hpp.
Referenced by ContinuousMountainCar::InitialSample(), and ContinuousMountainCar::Sample().
Member Data Documentation
dimension
constexpr size_t dimension = 2 [static], [constexpr]
Dimension of the encoded state.
Definition at line 70 of file continuous_mountain_car.hpp.
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/methods/reinforcement_learning/environment/ continuous_mountain_car.hpp