CartPole::State Class Reference
Implementation of the state of Cart Pole.
Public Member Functions
 State ()
Construct a state instance.
 State (const arma::colvec &data)
Construct a state instance from given data.
double & Angle ()
Modify the angle.
double Angle () const
Get the angle.
double & AngularVelocity ()
Modify the angular velocity.
double AngularVelocity () const
Get the angular velocity.
arma::colvec & Data ()
Modify the internal representation of the state.
const arma::colvec & Encode () const
Encode the state to a column vector.
double & Position ()
Modify the position.
double Position () const
Get the position.
double & Velocity ()
Modify the velocity.
double Velocity () const
Get the velocity.
Static Public Attributes
static constexpr size_t dimension = 4
Dimension of the encoded state.
Detailed Description
Implementation of the state of Cart Pole.
Each state is a tuple vector (position, velocity, angle, angular velocity).
Definition at line 33 of file cart_pole.hpp.
Constructor & Destructor Documentation
State() [1/2]
 State () [inline]
Construct a state instance.
Definition at line 39 of file cart_pole.hpp.
State() [2/2]
 State (const arma::colvec & data) [inline]
Construct a state instance from given data.
Parameters
data Data for the position, velocity, angle and angular velocity.
Definition at line 47 of file cart_pole.hpp.
Member Function Documentation
Angle() [1/2]
double& Angle () [inline]
Modify the angle.
Definition at line 66 of file cart_pole.hpp.
Angle() [2/2]
double Angle () const [inline]
Get the angle.
Definition at line 64 of file cart_pole.hpp.
Referenced by CartPole::IsTerminal(), and CartPole::Sample().
AngularVelocity() [1/2]
double& AngularVelocity () [inline]
Modify the angular velocity.
Definition at line 71 of file cart_pole.hpp.
AngularVelocity() [2/2]
double AngularVelocity () const [inline]
Get the angular velocity.
Definition at line 69 of file cart_pole.hpp.
Referenced by CartPole::Sample().
Data()
arma::colvec& Data () [inline]
Modify the internal representation of the state.
Definition at line 51 of file cart_pole.hpp.
Encode()
const arma::colvec& Encode () const [inline]
Encode the state to a column vector.
Definition at line 74 of file cart_pole.hpp.
Position() [1/2]
double& Position () [inline]
Modify the position.
Definition at line 56 of file cart_pole.hpp.
Position() [2/2]
double Position () const [inline]
Get the position.
Definition at line 54 of file cart_pole.hpp.
Referenced by CartPole::IsTerminal(), and CartPole::Sample().
Velocity() [1/2]
double& Velocity () [inline]
Modify the velocity.
Definition at line 61 of file cart_pole.hpp.
Velocity() [2/2]
double Velocity () const [inline]
Get the velocity.
Definition at line 59 of file cart_pole.hpp.
Referenced by CartPole::Sample().
Member Data Documentation
dimension
constexpr size_t dimension = 4 [static], [constexpr]
Dimension of the encoded state.
Definition at line 77 of file cart_pole.hpp.
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/methods/reinforcement_learning/environment/ cart_pole.hpp