LecunNormalInitialization Class Reference
This class is used to initialize weight matrix with the Lecun Normalization initialization rule.
Public Member Functions
 LecunNormalInitialization ()
Initialize the LecunNormalInitialization object.
template<typename eT >
void Initialize (arma::Cube< eT > &W)
Initialize the elements of the specified weight 3rd order tensor with Lecun Normal initialization rule.
template<typename eT >
void Initialize (arma::Cube< eT > &W, const size_t rows, const size_t cols, const size_t slices)
Initialize the elements of the specified weight 3rd order tensor with Lecun Normal initialization rule.
template<typename eT >
void Initialize (arma::Mat< eT > &W)
Initialize the elements of the weight matrix with the Lecun Normal initialization rule.
template<typename eT >
void Initialize (arma::Mat< eT > &W, const size_t rows, const size_t cols)
Initialize the elements of the weight matrix with the Lecun Normal initialization rule.
Detailed Description
This class is used to initialize weight matrix with the Lecun Normalization initialization rule.
For more information, the following papers can be referred to:
@inproceedings{Klambauer2017,
  itle = {Self-Normalizing Neural Networks.},
  author = {Klambauer, Günter and Unterthiner, Thomas
            and Mayr, Andreas and Hochreiter, Sepp},
  pages = {972-981},
  year = {2017}
}
@inproceedings{LeCun1998,
  title = {Efficient BackProp},
  author = {LeCun, Yann and Bottou, L{\'e}on and Orr, Genevieve B.
            and M\"{u}ller, Klaus-Robert},
  year = {1998},
  pages = {9--50}
}
Definition at line 49 of file lecun_normal_init.hpp.
Constructor & Destructor Documentation
LecunNormalInitialization()
 LecunNormalInitialization () [inline]
Initialize the LecunNormalInitialization object.
Definition at line 55 of file lecun_normal_init.hpp.
Member Function Documentation
Initialize() [1/4]
void Initialize (arma::Cube< eT > & W) [inline]
Initialize the elements of the specified weight 3rd order tensor with Lecun Normal initialization rule.
Parameters
W Weight matrix to initialize.
Definition at line 137 of file lecun_normal_init.hpp.
References Log::Fatal, and LecunNormalInitialization::Initialize().
Initialize() [2/4]
void Initialize (arma::Cube< eT > & W, const size_t rows, const size_t cols, const size_t slices) [inline]
Initialize the elements of the specified weight 3rd order tensor with Lecun Normal initialization rule.
Parameters
W Weight matrix to initialize.
rows Number of rows.
cols Number of columns.
slices Number of slices.
Definition at line 118 of file lecun_normal_init.hpp.
References LecunNormalInitialization::Initialize().
Initialize() [3/4]
void Initialize (arma::Mat< eT > & W) [inline]
Initialize the elements of the weight matrix with the Lecun Normal initialization rule.
Parameters
W Weight matrix to initialize.
Definition at line 93 of file lecun_normal_init.hpp.
References Log::Fatal, and if().
Initialize() [4/4]
void Initialize (arma::Mat< eT > & W, const size_t rows, const size_t cols) [inline]
Initialize the elements of the weight matrix with the Lecun Normal initialization rule.
Parameters
W Weight matrix to initialize.
rows Number of rows.
cols Number of columns.
Definition at line 69 of file lecun_normal_init.hpp.
Referenced by LecunNormalInitialization::Initialize().
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/methods/ann/init_rules/ lecun_normal_init.hpp