Concat< InputDataType, OutputDataType, CustomLayers > Class Template Reference
Implementation of the Concat class.
Public Member Functions
 Concat (const bool model=false, const bool run=true)
Create the Concat object using the specified parameters.
 Concat (arma::Row< size_t > &inputSize, const size_t axis, const bool model=false, const bool run=true)
Create the Concat object using the specified parameters.
 ~Concat ()
Destroy the layers held by the model.
template<class LayerType , class... Args>
void Add (Args... args)
void Add (LayerTypes< CustomLayers... > layer)
template<typename eT >
void Backward (const arma::Mat< eT > &, const arma::Mat< eT > &gy, arma::Mat< eT > &g)
Ordinary feed backward pass of a neural network, using 3rd-order tensors as input, calculating the function f(x) by propagating x backwards through f.
template<typename eT >
void Backward (const arma::Mat< eT > &, const arma::Mat< eT > &gy, arma::Mat< eT > &g, const size_t index)
This is the overload of Backward() that runs only a specific layer with the given input.
size_t const & ConcatAxis () const
Get the axis of concatenation.
arma::mat const & Delta () const
Get the delta.e.
arma::mat & Delta ()
Modify the delta.
template<typename eT >
void Forward (const arma::Mat< eT > &input, arma::Mat< eT > &output)
Ordinary feed forward pass of a neural network, evaluating the function f(x) by propagating the activity forward through f.
template<typename eT >
void Gradient (const arma::Mat< eT > &, const arma::Mat< eT > &error, arma::Mat< eT > &)
template<typename eT >
void Gradient (const arma::Mat< eT > &input, const arma::Mat< eT > &error, arma::Mat< eT > &gradient, const size_t index)
arma::mat const & Gradient () const
Get the gradient.
arma::mat & Gradient ()
Modify the gradient.
arma::mat const & InputParameter () const
arma::mat & InputParameter ()
Modify the input parameter.
std::vector< LayerTypes< CustomLayers... > > & Model ()
Return the model modules.
arma::mat const & OutputParameter () const
Get the output parameter.
arma::mat & OutputParameter ()
Modify the output parameter.
const arma::mat & Parameters () const
Return the initial point for the optimization.
arma::mat & Parameters ()
Modify the initial point for the optimization.
bool Run () const
Get the value of run parameter.
bool & Run ()
Modify the value of run parameter.
template<typename Archive >
void serialize (Archive &ar, const uint32_t)
Serialize the layer.
size_t WeightSize () const
Get the size of the weight matrix.
Detailed Description
template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat, typename... CustomLayers>
class mlpack::ann::Concat< InputDataType, OutputDataType, CustomLayers >
Implementation of the Concat class.
The Concat class works as a feed-forward fully connected network container which plugs various layers together.
Template Parameters
InputDataType Type of the input data (arma::colvec, arma::mat, arma::sp_mat or arma::cube).
OutputDataType Type of the output data (arma::colvec, arma::mat, arma::sp_mat or arma::cube).
CustomLayers Additional custom layers if required.
Definition at line 45 of file concat.hpp.
Constructor & Destructor Documentation
Concat() [1/2]
 Concat (const bool model = false, const bool run = true)
Create the Concat object using the specified parameters.
Parameters
model Expose all network modules.
run Call the Forward/Backward method before the output is merged.
Concat() [2/2]
 Concat (arma::Row< size_t > & inputSize, const size_t axis, const bool model = false, const bool run = true)
Create the Concat object using the specified parameters.
Parameters
inputSize A vector denoting input size of each layer added.
axis Concat axis.
model Expose all network modules.
run Call the Forward/Backward method before the output is merged.
~Concat()
~ Concat ()
Destroy the layers held by the model.
Member Function Documentation
Add() [1/2]
void Add (Args... args) [inline]
Definition at line 147 of file concat.hpp.
Referenced by DuelingDQN< OutputLayerType, InitType, CompleteNetworkType, FeatureNetworkType, AdvantageNetworkType, ValueNetworkType >::DuelingDQN().
Add() [2/2]
void Add (LayerTypes< CustomLayers... > layer) [inline]
Definition at line 154 of file concat.hpp.
Backward() [1/2]
void Backward (const arma::Mat< eT > & , const arma::Mat< eT > & gy, arma::Mat< eT > & g)
Ordinary feed backward pass of a neural network, using 3rd-order tensors as input, calculating the function f(x) by propagating x backwards through f.
Using the results from the feed forward pass.
Parameters
* (input) The propagated input activation.
gy The backpropagated error.
g The calculated gradient.
Backward() [2/2]
void Backward (const arma::Mat< eT > & , const arma::Mat< eT > & gy, arma::Mat< eT > & g, const size_t index)
This is the overload of Backward() that runs only a specific layer with the given input.
Parameters
* (input) The propagated input activation.
gy The backpropagated error.
g The calculated gradient.
index The index of the layer to run.
ConcatAxis()
size_t const& ConcatAxis () const [inline]
Get the axis of concatenation.
Definition at line 197 of file concat.hpp.
Delta() [1/2]
arma::mat const& Delta () const [inline]
Get the delta.e.
Definition at line 187 of file concat.hpp.
Delta() [2/2]
arma::mat& Delta () [inline]
Modify the delta.
Definition at line 189 of file concat.hpp.
Forward()
void Forward (const arma::Mat< eT > & input, arma::Mat< eT > & output)
Ordinary feed forward pass of a neural network, evaluating the function f(x) by propagating the activity forward through f.
Parameters
input Input data used for evaluating the specified function.
output Resulting output activation.
Gradient() [1/4]
void Gradient (const arma::Mat< eT > & , const arma::Mat< eT > & error, arma::Mat< eT > &)
Gradient() [2/4]
void Gradient (const arma::Mat< eT > & input, const arma::Mat< eT > & error, arma::Mat< eT > & gradient, const size_t index)
Gradient() [3/4]
arma::mat const& Gradient () const [inline]
Get the gradient.
Definition at line 192 of file concat.hpp.
Gradient() [4/4]
arma::mat& Gradient () [inline]
Modify the gradient.
Definition at line 194 of file concat.hpp.
InputParameter() [1/2]
arma::mat const& InputParameter () const [inline]
Definition at line 177 of file concat.hpp.
InputParameter() [2/2]
arma::mat& InputParameter () [inline]
Modify the input parameter.
Definition at line 179 of file concat.hpp.
Model()
std::vector< LayerTypes<CustomLayers...> >& Model () [inline]
Return the model modules.
Definition at line 157 of file concat.hpp.
OutputParameter() [1/2]
arma::mat const& OutputParameter () const [inline]
Get the output parameter.
Definition at line 182 of file concat.hpp.
OutputParameter() [2/2]
arma::mat& OutputParameter () [inline]
Modify the output parameter.
Definition at line 184 of file concat.hpp.
Parameters() [1/2]
const arma::mat& Parameters () const [inline]
Return the initial point for the optimization.
Definition at line 168 of file concat.hpp.
Parameters() [2/2]
arma::mat& Parameters () [inline]
Modify the initial point for the optimization.
Definition at line 170 of file concat.hpp.
Run() [1/2]
bool Run () const [inline]
Get the value of run parameter.
Definition at line 173 of file concat.hpp.
Run() [2/2]
bool& Run () [inline]
Modify the value of run parameter.
Definition at line 175 of file concat.hpp.
serialize()
void serialize (Archive & ar, const uint32_t)
Serialize the layer.
Referenced by Concat< InputDataType, OutputDataType, CustomLayers >::WeightSize().
WeightSize()
size_t WeightSize () const [inline]
Get the size of the weight matrix.
Definition at line 200 of file concat.hpp.
References Concat< InputDataType, OutputDataType, CustomLayers >::serialize().
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/methods/ann/layer/ concat.hpp