OneStepQLearningWorker< EnvironmentType, NetworkType, UpdaterType, PolicyType > Class Template Reference
Forward declaration of OneStepQLearningWorker.
Public Types
using ActionType = typename EnvironmentType::Action
using StateType = typename EnvironmentType::State
using TransitionType = std::tuple< StateType, ActionType, double, StateType >
Public Member Functions
 OneStepQLearningWorker (const OneStepQLearningWorker &other)
Copy another OneStepQLearningWorker.
 OneStepQLearningWorker (const UpdaterType &updater, const EnvironmentType &environment, const TrainingConfig &config, bool deterministic)
Construct one step Q-Learning worker with the given parameters and environment.
 OneStepQLearningWorker (OneStepQLearningWorker &&other)
Take ownership of another OneStepQLearningWorker.
 ~OneStepQLearningWorker ()
Clean memory.
void Initialize (NetworkType &learningNetwork)
Initialize the worker.
 OneStepQLearningWorker & operator= (const OneStepQLearningWorker &other)
Copy another OneStepQLearningWorker.
 OneStepQLearningWorker & operator= (OneStepQLearningWorker &&other)
Take ownership of another OneStepQLearningWorker.
bool Step (NetworkType &learningNetwork, NetworkType &targetNetwork, size_t &totalSteps, PolicyType &policy, double &totalReward)
The agent will execute one step.
Detailed Description
template<typename EnvironmentType, typename NetworkType, typename UpdaterType, typename PolicyType>
class mlpack::rl::OneStepQLearningWorker< EnvironmentType, NetworkType, UpdaterType, PolicyType >
Forward declaration of OneStepQLearningWorker.
One step Q-Learning worker.
Template Parameters
EnvironmentType The type of the reinforcement learning task.
NetworkType The type of the network model.
UpdaterType The type of the optimizer.
PolicyType The type of the behavior policy.
EnvironmentType The type of the reinforcement learning task.
NetworkType The type of the network model.
UpdaterType The type of the optimizer.
PolicyType The type of the behavior policy. *
Definition at line 35 of file one_step_q_learning_worker.hpp.
Member Typedef Documentation
ActionType
using ActionType = typename EnvironmentType::Action
Definition at line 39 of file one_step_q_learning_worker.hpp.
StateType
using StateType = typename EnvironmentType::State
Definition at line 38 of file one_step_q_learning_worker.hpp.
TransitionType
using TransitionType = std::tuple< StateType, ActionType, double, StateType>
Definition at line 40 of file one_step_q_learning_worker.hpp.
Constructor & Destructor Documentation
OneStepQLearningWorker() [1/3]
 OneStepQLearningWorker (const UpdaterType & updater, const EnvironmentType & environment, const TrainingConfig & config, bool deterministic) [inline]
Construct one step Q-Learning worker with the given parameters and environment.
Parameters
updater The optimizer.
environment The reinforcement learning task.
config Hyper-parameters.
deterministic Whether it should be deterministic.
Definition at line 51 of file one_step_q_learning_worker.hpp.
OneStepQLearningWorker() [2/3]
 OneStepQLearningWorker (const OneStepQLearningWorker< EnvironmentType, NetworkType, UpdaterType, PolicyType > & other) [inline]
Copy another OneStepQLearningWorker.
Parameters
other OneStepQLearningWorker to copy.
Definition at line 71 of file one_step_q_learning_worker.hpp.
OneStepQLearningWorker() [3/3]
 OneStepQLearningWorker (OneStepQLearningWorker< EnvironmentType, NetworkType, UpdaterType, PolicyType > && other) [inline]
Take ownership of another OneStepQLearningWorker.
Parameters
other OneStepQLearningWorker to take ownership of.
Definition at line 101 of file one_step_q_learning_worker.hpp.
~OneStepQLearningWorker()
~ OneStepQLearningWorker () [inline]
Clean memory.
Definition at line 203 of file one_step_q_learning_worker.hpp.
Member Function Documentation
Initialize()
void Initialize (NetworkType & learningNetwork) [inline]
Initialize the worker.
Parameters
learningNetwork The shared network.
Definition at line 214 of file one_step_q_learning_worker.hpp.
operator=() [1/2]
 OneStepQLearningWorker& operator= (const OneStepQLearningWorker< EnvironmentType, NetworkType, UpdaterType, PolicyType > & other) [inline]
Copy another OneStepQLearningWorker.
Parameters
other OneStepQLearningWorker to copy.
Definition at line 131 of file one_step_q_learning_worker.hpp.
operator=() [2/2]
 OneStepQLearningWorker& operator= (OneStepQLearningWorker< EnvironmentType, NetworkType, UpdaterType, PolicyType > && other) [inline]
Take ownership of another OneStepQLearningWorker.
Parameters
other OneStepQLearningWorker to take ownership of.
Definition at line 168 of file one_step_q_learning_worker.hpp.
Step()
bool Step (NetworkType & learningNetwork, NetworkType & targetNetwork, size_t & totalSteps, PolicyType & policy, double & totalReward) [inline]
The agent will execute one step.
Parameters
learningNetwork The shared learning network.
targetNetwork The shared target network.
totalSteps The shared counter for total steps.
policy The shared behavior policy.
totalReward This will be the episode return if the episode ends after this step. Otherwise this is invalid.
Returns
Indicate whether current episode ends after this step.
Definition at line 243 of file one_step_q_learning_worker.hpp.
References TrainingConfig::Discount(), TrainingConfig::GradientLimit(), TrainingConfig::StepLimit(), TrainingConfig::StepSize(), TrainingConfig::TargetNetworkSyncInterval(), and TrainingConfig::UpdateInterval().
The documentation for this class was generated from the following files:
/home/aakash/mlpack/src/mlpack/methods/reinforcement_learning/ async_learning.hpp
/home/aakash/mlpack/src/mlpack/methods/reinforcement_learning/worker/ one_step_q_learning_worker.hpp