NearestNS Class Reference
This class implements the necessary methods for the SortPolicy template parameter of the NeighborSearch class.
Static Public Member Functions
static double BestDistance ()
Return what should represent the best possible distance with this particular sort policy.
template<typename TreeType >
static double BestNodeToNodeDistance (const TreeType *queryNode, const TreeType *referenceNode)
Return the best possible distance between two nodes.
template<typename TreeType >
static double BestNodeToNodeDistance (const TreeType *queryNode, const TreeType *referenceNode, const double centerToCenterDistance)
Return the best possible distance between two nodes, given that the distance between the centers of the two nodes has already been calculated.
template<typename TreeType >
static double BestNodeToNodeDistance (const TreeType *queryNode, const TreeType *referenceNode, const TreeType *referenceChildNode, const double centerToCenterDistance)
Return the best possible distance between the query node and the reference child node given the base case distance between the query node and the reference node.
template<typename VecType , typename TreeType >
static double BestPointToNodeDistance (const VecType &queryPoint, const TreeType *referenceNode)
Return the best possible distance between a node and a point.
template<typename VecType , typename TreeType >
static double BestPointToNodeDistance (const VecType &queryPoint, const TreeType *referenceNode, const double pointToCenterDistance)
Return the best possible distance between a point and a node, given that the distance between the point and the center of the node has already been calculated.
static double CombineBest (const double a, const double b)
Return the best combination of the two distances.
static double CombineWorst (const double a, const double b)
Return the worst combination of the two distances.
static double ConvertToDistance (const double score)
Convert the given score to a distance.
static double ConvertToScore (const double distance)
Convert the given distance into a score.
template<typename VecType , typename TreeType >
static size_t GetBestChild (const VecType &queryPoint, TreeType &referenceNode)
Return the best child according to this sort policy.
template<typename TreeType >
static size_t GetBestChild (const TreeType &queryNode, TreeType &referenceNode)
Return the best child according to this sort policy.
static bool IsBetter (const double value, const double ref)
Return whether or not value is `better` than ref.
static double Relax (const double value, const double epsilon)
Return the given value relaxed.
static double WorstDistance ()
Return what should represent the worst possible distance with this particular sort policy.
Detailed Description
This class implements the necessary methods for the SortPolicy template parameter of the NeighborSearch class.
The sorting policy here is that the minimum distance is the best (so, when used with NeighborSearch, the output is nearest neighbors).
This class is also meant to serve as a guide to implement a custom SortPolicy. All of the methods implemented here must be implemented by any other SortPolicy classes.
Definition at line 31 of file nearest_neighbor_sort.hpp.
Member Function Documentation
BestDistance()
static double BestDistance () [inline], [static]
Return what should represent the best possible distance with this particular sort policy.
In our case, this should be the minimum possible distance, 0.0.
Returns
0.0
Definition at line 142 of file nearest_neighbor_sort.hpp.
BestNodeToNodeDistance() [1/3]
static double BestNodeToNodeDistance (const TreeType * queryNode, const TreeType * referenceNode) [static]
Return the best possible distance between two nodes.
In our case, this is the minimum distance between the two tree nodes using the given distance function.
Referenced by NearestNS::IsBetter().
BestNodeToNodeDistance() [2/3]
static double BestNodeToNodeDistance (const TreeType * queryNode, const TreeType * referenceNode, const double centerToCenterDistance) [static]
Return the best possible distance between two nodes, given that the distance between the centers of the two nodes has already been calculated.
This is used in conjunction with trees that have self-children (like cover trees).
BestNodeToNodeDistance() [3/3]
static double BestNodeToNodeDistance (const TreeType * queryNode, const TreeType * referenceNode, const TreeType * referenceChildNode, const double centerToCenterDistance) [static]
Return the best possible distance between the query node and the reference child node given the base case distance between the query node and the reference node.
TreeType::ParentDistance() must be implemented to use this.
Parameters
queryNode Query node.
referenceNode Reference node.
referenceChildNode Child of reference node which is being inspected.
centerToCenterDistance Distance between centers of query node and reference node.
BestPointToNodeDistance() [1/2]
static double BestPointToNodeDistance (const VecType & queryPoint, const TreeType * referenceNode) [static]
Return the best possible distance between a node and a point.
In our case, this is the minimum distance between the tree node and the point using the given distance function.
Referenced by NearestNS::IsBetter().
BestPointToNodeDistance() [2/2]
static double BestPointToNodeDistance (const VecType & queryPoint, const TreeType * referenceNode, const double pointToCenterDistance) [static]
Return the best possible distance between a point and a node, given that the distance between the point and the center of the node has already been calculated.
This is used in conjunction with trees that have self-children (like cover trees).
CombineBest()
static double CombineBest (const double a, const double b) [inline], [static]
Return the best combination of the two distances.
Definition at line 147 of file nearest_neighbor_sort.hpp.
CombineWorst()
static double CombineWorst (const double a, const double b) [inline], [static]
Return the worst combination of the two distances.
Definition at line 155 of file nearest_neighbor_sort.hpp.
ConvertToDistance()
static double ConvertToDistance (const double score) [inline], [static]
Convert the given score to a distance.
This is the inverse of the operation provided by ConvertToScore(). For nearest neighbor search, there is no need for any change.
Definition at line 192 of file nearest_neighbor_sort.hpp.
ConvertToScore()
static double ConvertToScore (const double distance) [inline], [static]
Convert the given distance into a score.
Lower scores are better, so in the case of nearest neighbor sort where lower distances are better, we just return the distance.
Definition at line 182 of file nearest_neighbor_sort.hpp.
GetBestChild() [1/2]
static size_t GetBestChild (const VecType & queryPoint, TreeType & referenceNode) [inline], [static]
Return the best child according to this sort policy.
In this case it will return the one with the minimum distance.
Definition at line 111 of file nearest_neighbor_sort.hpp.
GetBestChild() [2/2]
static size_t GetBestChild (const TreeType & queryNode, TreeType & referenceNode) [inline], [static]
Return the best child according to this sort policy.
In this case it will return the one with the minimum distance.
Definition at line 121 of file nearest_neighbor_sort.hpp.
IsBetter()
static bool IsBetter (const double value, const double ref) [inline], [static]
Return whether or not value is `better` than ref.
In this case, that means that the value is less than or equal to the reference.
Parameters
value Value to compare
ref Value to compare with
Returns
bool indicating whether or not (value <= ref).
Definition at line 43 of file nearest_neighbor_sort.hpp.
References NearestNS::BestNodeToNodeDistance(), and NearestNS::BestPointToNodeDistance().
Relax()
static double Relax (const double value, const double epsilon) [inline], [static]
Return the given value relaxed.
Parameters
value Value to relax.
epsilon Relative error (non-negative).
Returns
double Value relaxed.
Definition at line 170 of file nearest_neighbor_sort.hpp.
WorstDistance()
static double WorstDistance () [inline], [static]
Return what should represent the worst possible distance with this particular sort policy.
In our case, this should be the maximum possible distance, DBL_MAX.
Returns
DBL_MAX
Definition at line 133 of file nearest_neighbor_sort.hpp.
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/methods/neighbor_search/sort_policies/ nearest_neighbor_sort.hpp