RAWrapperBase Class Reference
RAWrapperBase is a base wrapper class for holding all RASearch types supported by RAModel.
Public Member Functions
 RAWrapperBase ()
Create the RAWrapperBase object.
virtual ~RAWrapperBase ()
Destruct the RAWrapperBase (nothing to do).
virtual double Alpha () const =0
Get the value of alpha.
virtual double & Alpha ()=0
Modify the value of alpha.
virtual RAWrapperBase * Clone () const =0
Create a new RAWrapperBase that is the same as this one.
virtual const arma::mat & Dataset () const =0
Return a reference to the dataset.
virtual bool FirstLeafExact () const =0
Get whether to do exact search at the first leaf.
virtual bool & FirstLeafExact ()=0
Modify whether to do exact search at the first leaf.
virtual bool Naive () const =0
Get whether naive search is being used.
virtual bool & Naive ()=0
Modify whether naive search is being used.
virtual bool SampleAtLeaves () const =0
Get whether to do sampling at leaves.
virtual bool & SampleAtLeaves ()=0
Modify whether to do sampling at leaves.
virtual void Search (arma::mat &&querySet, const size_t k, arma::Mat< size_t > &neighbors, arma::mat &distances, const size_t leafSize)=0
Perform bichromatic rank-approximate nearest neighbor search (i.e.
virtual void Search (const size_t k, arma::Mat< size_t > &neighbors, arma::mat &distances)=0
Perform monochromatic rank-approximate nearest neighbor search (i.e.
virtual bool SingleMode () const =0
Get whether single-tree search is being used.
virtual bool & SingleMode ()=0
Modify whether single-tree search is being used.
virtual size_t SingleSampleLimit () const =0
Get the single sample limit.
virtual size_t & SingleSampleLimit ()=0
Modify the single sample limit.
virtual double Tau () const =0
Get the value of tau.
virtual double & Tau ()=0
Modify the value of tau.
virtual void Train (arma::mat &&referenceSet, const size_t leafSize)=0
Train the RASearch model with the given parameters.
Detailed Description
RAWrapperBase is a base wrapper class for holding all RASearch types supported by RAModel.
All RASearch type wrappers inherit from this class, allowing a simple interface via inheritance for all the different types we want to support.
Definition at line 32 of file ra_model.hpp.
Constructor & Destructor Documentation
RAWrapperBase()
 RAWrapperBase () [inline]
Create the RAWrapperBase object.
The base class does not hold anything, so this constructor does nothing.
Definition at line 37 of file ra_model.hpp.
References RAWrapperBase::Clone().
~RAWrapperBase()
virtual ~ RAWrapperBase () [inline], [virtual]
Destruct the RAWrapperBase (nothing to do).
Definition at line 44 of file ra_model.hpp.
References RAWrapperBase::Alpha(), RAWrapperBase::Dataset(), RAWrapperBase::FirstLeafExact(), RAWrapperBase::Naive(), RAWrapperBase::SampleAtLeaves(), RAWrapperBase::Search(), RAWrapperBase::SingleMode(), RAWrapperBase::SingleSampleLimit(), RAWrapperBase::Tau(), and RAWrapperBase::Train().
Member Function Documentation
Alpha() [1/2]
virtual double Alpha () const [pure virtual]
Get the value of alpha.
Implemented in RAWrapper< TreeType > .
Referenced by RAModel::Alpha(), and RAWrapperBase::~RAWrapperBase().
Alpha() [2/2]
virtual double& Alpha () [pure virtual]
Modify the value of alpha.
Implemented in RAWrapper< TreeType > .
Clone()
virtual RAWrapperBase* Clone () const [pure virtual]
Create a new RAWrapperBase that is the same as this one.
This function will properly handle polymorphism.
Implemented in LeafSizeRAWrapper< TreeType > , and RAWrapper< TreeType > .
Referenced by RAWrapperBase::RAWrapperBase().
Dataset()
virtual const arma::mat& Dataset () const [pure virtual]
Return a reference to the dataset.
Implemented in RAWrapper< TreeType > .
Referenced by RAModel::Dataset(), and RAWrapperBase::~RAWrapperBase().
FirstLeafExact() [1/2]
virtual bool FirstLeafExact () const [pure virtual]
Get whether to do exact search at the first leaf.
Implemented in RAWrapper< TreeType > .
Referenced by RAModel::FirstLeafExact(), and RAWrapperBase::~RAWrapperBase().
FirstLeafExact() [2/2]
virtual bool& FirstLeafExact () [pure virtual]
Modify whether to do exact search at the first leaf.
Implemented in RAWrapper< TreeType > .
Naive() [1/2]
virtual bool Naive () const [pure virtual]
Get whether naive search is being used.
Implemented in RAWrapper< TreeType > .
Referenced by RAModel::Naive(), and RAWrapperBase::~RAWrapperBase().
Naive() [2/2]
virtual bool& Naive () [pure virtual]
Modify whether naive search is being used.
Implemented in RAWrapper< TreeType > .
SampleAtLeaves() [1/2]
virtual bool SampleAtLeaves () const [pure virtual]
Get whether to do sampling at leaves.
Implemented in RAWrapper< TreeType > .
Referenced by RAModel::SampleAtLeaves(), and RAWrapperBase::~RAWrapperBase().
SampleAtLeaves() [2/2]
virtual bool& SampleAtLeaves () [pure virtual]
Modify whether to do sampling at leaves.
Implemented in RAWrapper< TreeType > .
Search() [1/2]
virtual void Search (arma::mat && querySet, const size_t k, arma::Mat< size_t > & neighbors, arma::mat & distances, const size_t leafSize) [pure virtual]
Perform bichromatic rank-approximate nearest neighbor search (i.e.
search with a separate query set).
Implemented in LeafSizeRAWrapper< TreeType > , and RAWrapper< TreeType > .
Referenced by LeafSizeRAWrapper< TreeType >::Clone(), RAWrapper< TreeType >::Naive(), RAModel::RandomBasis(), and RAWrapperBase::~RAWrapperBase().
Search() [2/2]
virtual void Search (const size_t k, arma::Mat< size_t > & neighbors, arma::mat & distances) [pure virtual]
Perform monochromatic rank-approximate nearest neighbor search (i.e.
a search with the reference set as the query set).
Implemented in RAWrapper< TreeType > .
SingleMode() [1/2]
virtual bool SingleMode () const [pure virtual]
Get whether single-tree search is being used.
Implemented in RAWrapper< TreeType > .
Referenced by RAModel::SingleMode(), and RAWrapperBase::~RAWrapperBase().
SingleMode() [2/2]
virtual bool& SingleMode () [pure virtual]
Modify whether single-tree search is being used.
Implemented in RAWrapper< TreeType > .
SingleSampleLimit() [1/2]
virtual size_t SingleSampleLimit () const [pure virtual]
Get the single sample limit.
Implemented in RAWrapper< TreeType > .
Referenced by RAModel::SingleSampleLimit(), and RAWrapperBase::~RAWrapperBase().
SingleSampleLimit() [2/2]
virtual size_t& SingleSampleLimit () [pure virtual]
Modify the single sample limit.
Implemented in RAWrapper< TreeType > .
Tau() [1/2]
virtual double Tau () const [pure virtual]
Get the value of tau.
Implemented in RAWrapper< TreeType > .
Referenced by RAModel::Tau(), and RAWrapperBase::~RAWrapperBase().
Tau() [2/2]
virtual double& Tau () [pure virtual]
Modify the value of tau.
Implemented in RAWrapper< TreeType > .
Train()
virtual void Train (arma::mat && referenceSet, const size_t leafSize) [pure virtual]
Train the RASearch model with the given parameters.
Implemented in LeafSizeRAWrapper< TreeType > , and RAWrapper< TreeType > .
Referenced by LeafSizeRAWrapper< TreeType >::Clone(), RAWrapper< TreeType >::Naive(), and RAWrapperBase::~RAWrapperBase().
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/methods/rann/ ra_model.hpp