KDECleanRules< TreeType > Class Template Reference
A dual-tree traversal Rules class for cleaning used trees before performing kernel density estimation.
Public Types
typedef tree::TraversalInfo< TreeType > TraversalInfoType
Public Member Functions
 KDECleanRules ()
Construct KDECleanRules.
double BaseCase (const size_t, const size_t)
Base Case.
double Rescore (const size_t, TreeType &, const double oldScore) const
SingleTree Rescore.
double Rescore (TreeType &, TreeType &, const double oldScore) const
Dual-Tree Rescore.
double Score (const size_t, TreeType &referenceNode)
SingleTree Score.
double Score (TreeType &queryNode, TreeType &referenceNode)
Dual-Tree Score.
const TraversalInfoType & TraversalInfo () const
Get traversal information.
 TraversalInfoType & TraversalInfo ()
Modify traversal information.
Detailed Description
template<typename TreeType>
class mlpack::kde::KDECleanRules< TreeType >
A dual-tree traversal Rules class for cleaning used trees before performing kernel density estimation.
Definition at line 189 of file kde_rules.hpp.
Member Typedef Documentation
TraversalInfoType
typedef tree::TraversalInfo<TreeType> TraversalInfoType
Definition at line 214 of file kde_rules.hpp.
Constructor & Destructor Documentation
KDECleanRules()
 KDECleanRules () [inline]
Construct KDECleanRules.
Definition at line 193 of file kde_rules.hpp.
References KDERules< MetricType, KernelType, TreeType >::BaseCase(), and KDERules< MetricType, KernelType, TreeType >::Score().
Member Function Documentation
BaseCase()
double BaseCase (const size_t , const size_t)
Base Case.
Rescore() [1/2]
double Rescore (const size_t , TreeType & , const double oldScore) const [inline]
SingleTree Rescore.
Definition at line 202 of file kde_rules.hpp.
References KDERules< MetricType, KernelType, TreeType >::Score().
Rescore() [2/2]
double Rescore (TreeType & , TreeType & , const double oldScore) const [inline]
Dual-Tree Rescore.
Definition at line 210 of file kde_rules.hpp.
Score() [1/2]
double Score (const size_t , TreeType & referenceNode)
SingleTree Score.
Score() [2/2]
double Score (TreeType & queryNode, TreeType & referenceNode)
Dual-Tree Score.
TraversalInfo() [1/2]
const TraversalInfoType& TraversalInfo () const [inline]
Get traversal information.
Definition at line 217 of file kde_rules.hpp.
TraversalInfo() [2/2]
 TraversalInfoType& TraversalInfo () [inline]
Modify traversal information.
Definition at line 220 of file kde_rules.hpp.
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/methods/kde/ kde_rules.hpp