NguyenWidrowInitialization Class Reference
This class is used to initialize the weight matrix with the Nguyen-Widrow method.
Public Member Functions
 NguyenWidrowInitialization (const double lowerBound=-0.5, const double upperBound=0.5)
Initialize the random initialization rule with the given lower bound and upper bound.
template<typename eT >
void Initialize (arma::Mat< eT > &W, const size_t rows, const size_t cols)
Initialize the elements of the specified weight matrix with the Nguyen-Widrow method.
template<typename eT >
void Initialize (arma::Mat< eT > &W)
Initialize the elements of the specified weight matrix with the Nguyen-Widrow method.
template<typename eT >
void Initialize (arma::Cube< eT > &W, const size_t rows, const size_t cols, const size_t slices)
Initialize the elements of the specified weight 3rd order tensor with the Nguyen-Widrow method.
template<typename eT >
void Initialize (arma::Cube< eT > &W)
Initialize the elements of the specified weight 3rd order tensor with the Nguyen-Widrow method.
Detailed Description
This class is used to initialize the weight matrix with the Nguyen-Widrow method.
The method is defined by
 \gamma &\le& w_i \le \gamma \\ \beta &=& 0.7H^{\frac{1}{I}} \\ n &=& \sqrt{\sum_{i=0}{I}w_{i}^{2}} \\ w_i &=& \frac{\beta w_i}{n} 
Where H is the number of neurons in the outgoing layer, I represents the number of neurons in the ingoing layer and gamma defines the random interval that is used to initialize the weights with a random value in a specific range.
Definition at line 53 of file nguyen_widrow_init.hpp.
Constructor & Destructor Documentation
NguyenWidrowInitialization()
 NguyenWidrowInitialization (const double lowerBound = -0.5, const double upperBound = 0.5) [inline]
Initialize the random initialization rule with the given lower bound and upper bound.
Parameters
lowerBound The number used as lower bound.
upperBound The number used as upper bound.
Definition at line 63 of file nguyen_widrow_init.hpp.
Member Function Documentation
Initialize() [1/4]
void Initialize (arma::Mat< eT > & W, const size_t rows, const size_t cols) [inline]
Initialize the elements of the specified weight matrix with the Nguyen-Widrow method.
Parameters
W Weight matrix to initialize.
rows Number of rows.
cols Number of columns.
Definition at line 76 of file nguyen_widrow_init.hpp.
References RandomInitialization::Initialize().
Referenced by NguyenWidrowInitialization::Initialize().
Initialize() [2/4]
void Initialize (arma::Mat< eT > & W) [inline]
Initialize the elements of the specified weight matrix with the Nguyen-Widrow method.
Parameters
W Weight matrix to initialize.
Definition at line 92 of file nguyen_widrow_init.hpp.
References RandomInitialization::Initialize().
Initialize() [3/4]
void Initialize (arma::Cube< eT > & W, const size_t rows, const size_t cols, const size_t slices) [inline]
Initialize the elements of the specified weight 3rd order tensor with the Nguyen-Widrow method.
Parameters
W Weight matrix to initialize.
rows Number of rows.
cols Number of columns.
slices Number of slices.
Definition at line 111 of file nguyen_widrow_init.hpp.
References NguyenWidrowInitialization::Initialize().
Initialize() [4/4]
void Initialize (arma::Cube< eT > & W) [inline]
Initialize the elements of the specified weight 3rd order tensor with the Nguyen-Widrow method.
Parameters
W Weight matrix to initialize.
Definition at line 130 of file nguyen_widrow_init.hpp.
References NguyenWidrowInitialization::Initialize().
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/methods/ann/init_rules/ nguyen_widrow_init.hpp