KathirvalavakumarSubavathiInitialization Class Reference
This class is used to initialize the weight matrix with the method proposed by T.
Public Member Functions
template<typename eT >
 KathirvalavakumarSubavathiInitialization (const arma::Mat< eT > &data, const double s)
Initialize the random initialization rule with the given values.
template<typename eT >
void Initialize (arma::Cube< eT > &W)
Initialize the elements of the specified weight 3rd order tensor with the Kathirvalavakumar-Subavathi method.
template<typename eT >
void Initialize (arma::Cube< eT > &W, const size_t rows, const size_t cols, const size_t slices)
Initialize the elements of the specified weight 3rd order tensor with the Kathirvalavakumar-Subavathi method.
template<typename eT >
void Initialize (arma::Mat< eT > &W)
Initialize the elements of the specified weight matrix with the Kathirvalavakumar-Subavathi method.
template<typename eT >
void Initialize (arma::Mat< eT > &W, const size_t rows, const size_t cols)
Initialize the elements of the specified weight matrix with the Kathirvalavakumar-Subavathi method.
Detailed Description
This class is used to initialize the weight matrix with the method proposed by T.
Kathirvalavakumar and S. Subavathi. The method is based on sensitivity analysis using using cauchy’s inequality. The method is defined by
 \overline{s} &=& f^{-1}(\overline{t}) \\ \Theta^{1}_{p} &\le& \overline{s} \sqrt{\frac{3}{I \sum_{i = 1}^{I} (x_{ip}^2)}} \\ \Theta^1 &=& min(\Theta_{p}^{1}); p=1,2,..,P \\ -\Theta^{1} \le w_{i}^{1} &\le& \Theta^{1} 
where I is the number of inputs including the bias, p refers the pattern considered in training, f is the transfer function and ={s} is the active region in which the derivative of the activation function is greater than 4% of the maximum derivatives.
Definition at line 60 of file kathirvalavakumar_subavathi_init.hpp.
Constructor & Destructor Documentation
KathirvalavakumarSubavathiInitialization()
 KathirvalavakumarSubavathiInitialization (const arma::Mat< eT > & data, const double s) [inline]
Initialize the random initialization rule with the given values.
Parameters
data The input patterns.
s Parameter that defines the active region.
Definition at line 70 of file kathirvalavakumar_subavathi_init.hpp.
Member Function Documentation
Initialize() [1/4]
void Initialize (arma::Cube< eT > & W) [inline]
Initialize the elements of the specified weight 3rd order tensor with the Kathirvalavakumar-Subavathi method.
Parameters
W Weight matrix to initialize.
Definition at line 137 of file kathirvalavakumar_subavathi_init.hpp.
References Log::Fatal, and KathirvalavakumarSubavathiInitialization::Initialize().
Initialize() [2/4]
void Initialize (arma::Cube< eT > & W, const size_t rows, const size_t cols, const size_t slices) [inline]
Initialize the elements of the specified weight 3rd order tensor with the Kathirvalavakumar-Subavathi method.
Parameters
W Weight matrix to initialize.
rows Number of rows.
cols Number of columns.
slices Number of slices
Definition at line 118 of file kathirvalavakumar_subavathi_init.hpp.
References KathirvalavakumarSubavathiInitialization::Initialize().
Initialize() [3/4]
void Initialize (arma::Mat< eT > & W) [inline]
Initialize the elements of the specified weight matrix with the Kathirvalavakumar-Subavathi method.
Parameters
W Weight matrix to initialize.
Definition at line 100 of file kathirvalavakumar_subavathi_init.hpp.
References RandomInitialization::Initialize().
Initialize() [4/4]
void Initialize (arma::Mat< eT > & W, const size_t rows, const size_t cols) [inline]
Initialize the elements of the specified weight matrix with the Kathirvalavakumar-Subavathi method.
Parameters
W Weight matrix to initialize.
rows Number of rows.
cols Number of columns.
Definition at line 85 of file kathirvalavakumar_subavathi_init.hpp.
References RandomInitialization::Initialize().
Referenced by KathirvalavakumarSubavathiInitialization::Initialize().
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/methods/ann/init_rules/ kathirvalavakumar_subavathi_init.hpp