ContinuousMountainCar Class Reference
Implementation of Continuous Mountain Car task.
Classes
struct Action
Implementation of action of Continuous Mountain Car.
class State
Implementation of state of Continuous Mountain Car.
Public Member Functions
 ContinuousMountainCar (const double positionMin=-1.2, const double positionMax=0.6, const double positionGoal=0.45, const double velocityMin=-0.07, const double velocityMax=0.07, const double duration=0.0015, const double doneReward=100, const size_t maxSteps=0)
Construct a Continuous Mountain Car instance using the given constant.
 State InitialSample ()
Initial position is randomly generated within [-0.6, -0.4].
bool IsTerminal (const State &state) const
Whether given state is a terminal state.
size_t & MaxSteps ()
Set the maximum number of steps allowed.
size_t MaxSteps () const
Get the maximum number of steps allowed.
double Sample (const State &state, const Action &action)
Dynamics of Continuous Mountain Car.
double Sample (const State &state, const Action &action, State &nextState)
Dynamics of Continuous Mountain Car.
size_t StepsPerformed () const
Get the number of steps performed.
Detailed Description
Implementation of Continuous Mountain Car task.
Definition at line 29 of file continuous_mountain_car.hpp.
Constructor & Destructor Documentation
ContinuousMountainCar()
 ContinuousMountainCar (const double positionMin = -1.2, const double positionMax = 0.6, const double positionGoal = 0.45, const double velocityMin = -0.07, const double velocityMax = 0.07, const double duration = 0.0015, const double doneReward = 100, const size_t maxSteps = 0) [inline]
Construct a Continuous Mountain Car instance using the given constant.
Parameters
positionMin Minimum legal position.
positionMax Maximum legal position.
positionGoal Final target position.
velocityMin Minimum legal velocity.
velocityMax Maximum legal velocity.
duration Time Duration for which force is applied on the car.
doneReward Reward recieved by the agent on success.
maxSteps The number of steps after which the episode terminates. If the value is 0, there is no limit.
Definition at line 105 of file continuous_mountain_car.hpp.
Member Function Documentation
InitialSample()
 State InitialSample () [inline]
Initial position is randomly generated within [-0.6, -0.4].
Initial velocity is 0.
Returns
Initial state for each episode.
Definition at line 185 of file continuous_mountain_car.hpp.
References ContinuousMountainCar::State::Position(), mlpack::math::Random(), and ContinuousMountainCar::State::Velocity().
IsTerminal()
bool IsTerminal (const State & state) const [inline]
Whether given state is a terminal state.
Parameters
state desired state.
Returns
true if state is a terminal state, otherwise false.
Definition at line 200 of file continuous_mountain_car.hpp.
References Log::Info, and ContinuousMountainCar::State::Position().
Referenced by ContinuousMountainCar::Sample().
MaxSteps() [1/2]
size_t& MaxSteps () [inline]
Set the maximum number of steps allowed.
Definition at line 222 of file continuous_mountain_car.hpp.
MaxSteps() [2/2]
size_t MaxSteps () const [inline]
Get the maximum number of steps allowed.
Definition at line 220 of file continuous_mountain_car.hpp.
Sample() [1/2]
double Sample (const State & state, const Action & action) [inline]
Dynamics of Continuous Mountain Car.
Get reward based on current state and current action.
Parameters
state The current state.
action The current action.
Returns
reward, it's always -1.0.
Definition at line 173 of file continuous_mountain_car.hpp.
References ContinuousMountainCar::Sample().
Sample() [2/2]
double Sample (const State & state, const Action & action, State & nextState) [inline]
Dynamics of Continuous Mountain Car.
Get reward and next state based on current state and current action.
Parameters
state The current state.
action The current action.
nextState The next state.
Definition at line 132 of file continuous_mountain_car.hpp.
References ContinuousMountainCar::Action::action, mlpack::math::ClampRange(), ContinuousMountainCar::IsTerminal(), ContinuousMountainCar::State::Position(), and ContinuousMountainCar::State::Velocity().
Referenced by ContinuousMountainCar::Sample().
StepsPerformed()
size_t StepsPerformed () const [inline]
Get the number of steps performed.
Definition at line 217 of file continuous_mountain_car.hpp.
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/methods/reinforcement_learning/environment/ continuous_mountain_car.hpp