GlorotInitializationType< Uniform > Class Template Reference
This class is used to initialize the weight matrix with the Glorot Initialization method.
Public Member Functions
 GlorotInitializationType ()
Initialize the Glorot initialization object.
template<typename eT >
void Initialize (arma::Cube< eT > &W)
Initialize the elements of the specified weight 3rd order tensor with glorot initialization method.
template<typename eT >
void Initialize (arma::Cube< eT > &W, const size_t rows, const size_t cols, const size_t slices)
Initialize the elements of the specified weight 3rd order tensor with glorot initialization method.
template<typename eT >
void Initialize (arma::Mat< eT > &W)
Initialize the elements weight matrix with glorot initialization method.
void Initialize (arma::Mat< eT > &W)
void Initialize (arma::Mat< eT > &W)
template<typename eT >
void Initialize (arma::Mat< eT > &W, const size_t rows, const size_t cols)
Initialize the elements weight matrix with glorot initialization method.
void Initialize (arma::Mat< eT > &W, const size_t rows, const size_t cols)
void Initialize (arma::Mat< eT > &W, const size_t rows, const size_t cols)
Detailed Description
template<bool Uniform = true>
class mlpack::ann::GlorotInitializationType< Uniform >
This class is used to initialize the weight matrix with the Glorot Initialization method.
The method is defined by
 \mathrm{Var}[w_i] &=& \frac{2}{n_i + n_{i+1}} \\ w_i \sim \mathrm{U}[-\frac{\sqrt{6}}{\sqrt{n_i + n_{i+1}}}, \frac{\sqrt{6}}{\sqrt{n_i + n_{i+1}}}] 
where $ n_{i+1} $ is the number of neurons in the outgoing layer, $ n_i $ represents the number of neurons in the ingoing layer. Here Normal Distribution may also be used if needed
For more information, see the following paper.
@inproceedings {pmlr-v9-glorot10a,
 title = {Understanding the difficulty of training
              deep feedforward neural networks},
 author = {Xavier Glorot and Yoshua Bengio},
 booktitle = {Proceedings of the Thirteenth International Conference
              on Artificial Intelligence and Statistics},
 year = {2010}
}
Definition at line 55 of file glorot_init.hpp.
Constructor & Destructor Documentation
GlorotInitializationType()
 GlorotInitializationType () [inline]
Initialize the Glorot initialization object.
Definition at line 61 of file glorot_init.hpp.
Member Function Documentation
Initialize() [1/8]
void Initialize (arma::Cube< eT > & W) [inline]
Initialize the elements of the specified weight 3rd order tensor with glorot initialization method.
Parameters
W Weight matrix to initialize.
Definition at line 181 of file glorot_init.hpp.
References Log::Fatal.
Initialize() [2/8]
void Initialize (arma::Cube< eT > & W, const size_t rows, const size_t cols, const size_t slices) [inline]
Initialize the elements of the specified weight 3rd order tensor with glorot initialization method.
Parameters
W Weight matrix to initialize.
rows Number of rows.
cols Number of columns.
slices Number of slices.
Definition at line 167 of file glorot_init.hpp.
Initialize() [3/8]
void Initialize (arma::Mat< eT > & W)
Initialize the elements weight matrix with glorot initialization method.
Parameters
W Weight matrix to initialize.
Initialize() [4/8]
void Initialize (arma::Mat< eT > & W) [inline]
Definition at line 127 of file glorot_init.hpp.
References Log::Fatal, and GaussianInitialization::Initialize().
Initialize() [5/8]
void Initialize (arma::Mat< eT > & W) [inline]
Definition at line 154 of file glorot_init.hpp.
References Log::Fatal, and RandomInitialization::Initialize().
Initialize() [6/8]
void Initialize (arma::Mat< eT > & W, const size_t rows, const size_t cols)
Initialize the elements weight matrix with glorot initialization method.
Parameters
W Weight matrix to initialize.
rows Number of rows.
cols Number of columns.
Initialize() [7/8]
void Initialize (arma::Mat< eT > & W, const size_t rows, const size_t cols) [inline]
Definition at line 113 of file glorot_init.hpp.
References GaussianInitialization::Initialize().
Initialize() [8/8]
void Initialize (arma::Mat< eT > & W, const size_t rows, const size_t cols) [inline]
Definition at line 139 of file glorot_init.hpp.
References RandomInitialization::Initialize().
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/methods/ann/init_rules/ glorot_init.hpp