CFWrapperBase Class Reference
The CFWrapperBase class provides a unified interface that can be used by the CFModel class to interact with all different CF types at runtime.
Public Member Functions
 CFWrapperBase ()
Create the object. The base class has nothing to hold.
virtual ~CFWrapperBase ()
Delete the object.
virtual CFWrapperBase * Clone () const =0
Make a copy of the object.
virtual void GetRecommendations (const NeighborSearchTypes nsType, const InterpolationTypes interpolationType, const size_t numRecs, arma::Mat< size_t > &recommendations)=0
Compute recommendations for all users.
virtual void GetRecommendations (const NeighborSearchTypes nsType, const InterpolationTypes interpolationType, const size_t numRecs, arma::Mat< size_t > &recommendations, const arma::Col< size_t > &users)=0
Compute recommendations.
virtual void Predict (const NeighborSearchTypes nsType, const InterpolationTypes interpolationType, const arma::Mat< size_t > &combinations, arma::vec &predictions)=0
Compute predictions for users.
Detailed Description
The CFWrapperBase class provides a unified interface that can be used by the CFModel class to interact with all different CF types at runtime.
All CF wrapper types inherit from this base class.
Definition at line 49 of file cf_model.hpp.
Constructor & Destructor Documentation
CFWrapperBase()
 CFWrapperBase () [inline]
Create the object. The base class has nothing to hold.
Definition at line 53 of file cf_model.hpp.
References CFWrapperBase::Clone().
~CFWrapperBase()
virtual ~ CFWrapperBase () [inline], [virtual]
Delete the object.
Definition at line 59 of file cf_model.hpp.
References CFWrapperBase::GetRecommendations(), and CFWrapperBase::Predict().
Member Function Documentation
Clone()
virtual CFWrapperBase* Clone () const [pure virtual]
Make a copy of the object.
Implemented in CFWrapper< DecompositionPolicy, NormalizationPolicy > .
Referenced by CFWrapperBase::CFWrapperBase().
GetRecommendations() [1/2]
virtual void GetRecommendations (const NeighborSearchTypes nsType, const InterpolationTypes interpolationType, const size_t numRecs, arma::Mat< size_t > & recommendations) [pure virtual]
Compute recommendations for all users.
Implemented in CFWrapper< DecompositionPolicy, NormalizationPolicy > .
Referenced by CFWrapper< DecompositionPolicy, NormalizationPolicy >::CF(), CFModel::NormalizationType(), and CFWrapperBase::~CFWrapperBase().
GetRecommendations() [2/2]
virtual void GetRecommendations (const NeighborSearchTypes nsType, const InterpolationTypes interpolationType, const size_t numRecs, arma::Mat< size_t > & recommendations, const arma::Col< size_t > & users) [pure virtual]
Compute recommendations.
Implemented in CFWrapper< DecompositionPolicy, NormalizationPolicy > .
Predict()
virtual void Predict (const NeighborSearchTypes nsType, const InterpolationTypes interpolationType, const arma::Mat< size_t > & combinations, arma::vec & predictions) [pure virtual]
Compute predictions for users.
Implemented in CFWrapper< DecompositionPolicy, NormalizationPolicy > .
Referenced by CFWrapper< DecompositionPolicy, NormalizationPolicy >::CF(), CFModel::NormalizationType(), and CFWrapperBase::~CFWrapperBase().
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/methods/cf/ cf_model.hpp