AdaBoost< WeakLearnerType, MatType > Class Template Reference
The AdaBoost class.
Public Member Functions
 AdaBoost (const MatType &data, const arma::Row< size_t > &labels, const size_t numClasses, const WeakLearnerType &other, const size_t iterations=100, const double tolerance=1e-6)
Constructor.
 AdaBoost (const double tolerance=1e-6)
Create the AdaBoost object without training.
double Alpha (const size_t i) const
Get the weights for the given weak learner.
double & Alpha (const size_t i)
Modify the weight for the given weak learner (be careful!).
void Classify (const MatType &test, arma::Row< size_t > &predictedLabels, arma::mat &probabilities)
Classify the given test points.
void Classify (const MatType &test, arma::Row< size_t > &predictedLabels)
Classify the given test points.
size_t NumClasses () const
Get the number of classes this model is trained on.
template<typename Archive >
void serialize (Archive &ar, const uint32_t)
Serialize the AdaBoost model.
double Tolerance () const
Get the tolerance for stopping the optimization during training.
double & Tolerance ()
Modify the tolerance for stopping the optimization during training.
double Train (const MatType &data, const arma::Row< size_t > &labels, const size_t numClasses, const WeakLearnerType &learner, const size_t iterations=100, const double tolerance=1e-6)
Train AdaBoost on the given dataset.
const WeakLearnerType & WeakLearner (const size_t i) const
Get the given weak learner.
WeakLearnerType & WeakLearner (const size_t i)
Modify the given weak learner (be careful!).
size_t WeakLearners () const
Get the number of weak learners in the model.
Detailed Description
template<typename WeakLearnerType = mlpack::perceptron::Perceptron<>, typename MatType = arma::mat>
class mlpack::adaboost::AdaBoost< WeakLearnerType, MatType >
The AdaBoost class.
AdaBoost is a boosting algorithm, meaning that it combines an ensemble of weak learners to produce a strong learner. For more information on AdaBoost, see the following paper:
@article{schapire1999improved,
  author = {Schapire, Robert E. and Singer, Yoram},
  title = {Improved Boosting Algorithms Using Confidence-rated Predictions},
  journal = {Machine Learning},
  volume = {37},
  number = {3},
  month = dec,
  year = {1999},
  issn = {0885-6125},
  pages = {297--336},
}
This class is general, and can be used with any type of weak learner, so long as the learner implements the following functions:
// A boosting constructor, which learns using the training parameters of the
// given other WeakLearner, but uses the given instance weights for training.
WeakLearner(WeakLearner& other,
            const MatType& data,
            const arma::Row<size_t>& labels,
            const arma::rowvec& weights);
// Given the test points, classify them and output predictions into
// predictedLabels.
void Classify(const MatType& data, arma::Row<size_t>& predictedLabels);
For more information on and examples of weak learners, see perceptron::Perceptron<> and tree::ID3DecisionStump.
Template Parameters
MatType Data matrix type (i.e. arma::mat or arma::sp_mat).
WeakLearnerType Type of weak learner to use.
Definition at line 81 of file adaboost.hpp.
Constructor & Destructor Documentation
AdaBoost() [1/2]
 AdaBoost (const MatType & data, const arma::Row< size_t > & labels, const size_t numClasses, const WeakLearnerType & other, const size_t iterations = 100, const double tolerance = 1e-6)
Constructor.
This runs the AdaBoost.MH algorithm to provide a trained boosting model. This constructor takes an already-initialized weak learner; all other weak learners will learn with the same parameters as the given weak learner.
Parameters
data Input data.
labels Corresponding labels.
numClasses The number of classes.
iterations Number of boosting rounds.
tolerance The tolerance for change in values of rt.
other Weak learner that has already been initialized.
AdaBoost() [2/2]
 AdaBoost (const double tolerance = 1e-6)
Create the AdaBoost object without training.
Be sure to call Train() before calling Classify()!
Member Function Documentation
Alpha() [1/2]
double Alpha (const size_t i) const [inline]
Get the weights for the given weak learner.
Definition at line 122 of file adaboost.hpp.
Alpha() [2/2]
double& Alpha (const size_t i) [inline]
Modify the weight for the given weak learner (be careful!).
Definition at line 124 of file adaboost.hpp.
Classify() [1/2]
void Classify (const MatType & test, arma::Row< size_t > & predictedLabels, arma::mat & probabilities)
Classify the given test points.
Parameters
test Testing data.
predictedLabels Vector in which the predicted labels of the test set will be stored.
probabilities matrix to store the predicted class probabilities for each point in the test set.
Referenced by AdaBoost< mlpack::tree::DecisionTree >::WeakLearner().
Classify() [2/2]
void Classify (const MatType & test, arma::Row< size_t > & predictedLabels)
Classify the given test points.
Parameters
test Testing data.
predictedLabels Vector in which the predicted labels of the test set will be stored.
NumClasses()
size_t NumClasses () const [inline]
Get the number of classes this model is trained on.
Definition at line 116 of file adaboost.hpp.
serialize()
void serialize (Archive & ar, const uint32_t)
Serialize the AdaBoost model.
Referenced by AdaBoost< mlpack::tree::DecisionTree >::WeakLearner().
Tolerance() [1/2]
double Tolerance () const [inline]
Get the tolerance for stopping the optimization during training.
Definition at line 111 of file adaboost.hpp.
Tolerance() [2/2]
double& Tolerance () [inline]
Modify the tolerance for stopping the optimization during training.
Definition at line 113 of file adaboost.hpp.
Train()
double Train (const MatType & data, const arma::Row< size_t > & labels, const size_t numClasses, const WeakLearnerType & learner, const size_t iterations = 100, const double tolerance = 1e-6)
Train AdaBoost on the given dataset.
This method takes an initialized WeakLearnerType; the parameters for this weak learner will be used to train each of the weak learners during AdaBoost training. Note that this will completely overwrite any model that has already been trained with this object.
Parameters
data Dataset to train on.
labels Labels for each point in the dataset.
numClasses The number of classes.
learner Learner to use for training.
iterations Number of boosting rounds.
tolerance The tolerance for change in values of rt.
Returns
The upper bound for training error.
Referenced by AdaBoost< mlpack::tree::DecisionTree >::WeakLearner().
WeakLearner() [1/2]
const WeakLearnerType& WeakLearner (const size_t i) const [inline]
Get the given weak learner.
Definition at line 127 of file adaboost.hpp.
WeakLearner() [2/2]
WeakLearnerType& WeakLearner (const size_t i) [inline]
Modify the given weak learner (be careful!).
Definition at line 129 of file adaboost.hpp.
WeakLearners()
size_t WeakLearners () const [inline]
Get the number of weak learners in the model.
Definition at line 119 of file adaboost.hpp.
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/methods/adaboost/ adaboost.hpp