Sequential< InputDataType, OutputDataType, Residual, CustomLayers > Class Template Reference
Implementation of the Sequential class.
Public Member Functions
 Sequential (const bool model=true)
Create the Sequential object using the specified parameters.
 Sequential (const bool model, const bool ownsLayers)
Create the Sequential object using the specified parameters.
 Sequential (const Sequential &layer)
Copy constructor.
 ~Sequential ()
Destroy the Sequential object.
template<class LayerType , class... Args>
void Add (Args... args)
void Add (LayerTypes< CustomLayers... > layer)
template<typename eT >
void Backward (const arma::Mat< eT > &, const arma::Mat< eT > &gy, arma::Mat< eT > &g)
Ordinary feed backward pass of a neural network, using 3rd-order tensors as input, calculating the function f(x) by propagating x backwards through f.
arma::mat const & Delta () const
Get the delta.
arma::mat & Delta ()
Modify the delta.
template<typename eT >
void Forward (const arma::Mat< eT > &input, arma::Mat< eT > &output)
Ordinary feed forward pass of a neural network, evaluating the function f(x) by propagating the activity forward through f.
template<typename eT >
void Gradient (const arma::Mat< eT > &input, const arma::Mat< eT > &error, arma::Mat< eT > &)
arma::mat const & Gradient () const
Get the gradient.
arma::mat & Gradient ()
Modify the gradient.
arma::mat const & InputParameter () const
Get the input parameter.
arma::mat & InputParameter ()
Modify the input parameter.
size_t InputShape () const
std::vector< LayerTypes< CustomLayers... > > & Model ()
Return the model modules.
 Sequential & operator= (const Sequential &layer)
Copy assignment operator.
arma::mat const & OutputParameter () const
Get the output parameter.
arma::mat & OutputParameter ()
Modify the output parameter.
const arma::mat & Parameters () const
Return the initial point for the optimization.
arma::mat & Parameters ()
Modify the initial point for the optimization.
template<typename Archive >
void serialize (Archive &ar, const uint32_t)
Serialize the layer.
Detailed Description
template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat, bool Residual = false, typename... CustomLayers>
class mlpack::ann::Sequential< InputDataType, OutputDataType, Residual, CustomLayers >
Implementation of the Sequential class.
The sequential class works as a feed-forward fully connected network container which plugs various layers together.
This class can also be used as a container for a residual block. In that case, the sizes of the input and output matrices of this class should be equal. A typedef has been added for use as a Residual<> class.
For more information, refer the following paper.
@article{He15,
  author = {Kaiming He, Xiangyu Zhang, Shaoqing Ren, Jian Sun},
  title = {Deep Residual Learning for Image Recognition},
  year = {2015},
  url = {https://arxiv.org/abs/1512.03385},
  eprint = {1512.03385},
}
Note: If this class is used as the first layer of a network, it should be preceded by IdentityLayer<>.
Note: This class should at least have two layers for a call to its Gradient() function.
Template Parameters
InputDataType Type of the input data (arma::colvec, arma::mat, arma::sp_mat or arma::cube).
OutputDataType Type of the output data (arma::colvec, arma::mat, arma::sp_mat or arma::cube).
Residual If true, use the object as a Residual block.
Definition at line 141 of file layer_types.hpp.
Constructor & Destructor Documentation
Sequential() [1/3]
 Sequential (const bool model = true)
Create the Sequential object using the specified parameters.
Parameters
model Expose the all network modules.
Sequential() [2/3]
 Sequential (const bool model, const bool ownsLayers)
Create the Sequential object using the specified parameters.
Parameters
model Expose all the network modules.
ownsLayers If true, then this module will delete its layers when deallocated.
Sequential() [3/3]
 Sequential (const Sequential< InputDataType, OutputDataType, Residual, CustomLayers > & layer)
Copy constructor.
~Sequential()
~ Sequential ()
Destroy the Sequential object.
Member Function Documentation
Add() [1/2]
void Add (Args... args) [inline]
Definition at line 143 of file sequential.hpp.
Referenced by DuelingDQN< OutputLayerType, InitType, CompleteNetworkType, FeatureNetworkType, AdvantageNetworkType, ValueNetworkType >::DuelingDQN().
Add() [2/2]
void Add (LayerTypes< CustomLayers... > layer) [inline]
Definition at line 150 of file sequential.hpp.
Backward()
void Backward (const arma::Mat< eT > & , const arma::Mat< eT > & gy, arma::Mat< eT > & g)
Ordinary feed backward pass of a neural network, using 3rd-order tensors as input, calculating the function f(x) by propagating x backwards through f.
Using the results from the feed forward pass.
Parameters
* (input) The propagated input activation.
gy The backpropagated error.
g The calculated gradient.
Delta() [1/2]
arma::mat const& Delta () const [inline]
Get the delta.
Definition at line 179 of file sequential.hpp.
Delta() [2/2]
arma::mat& Delta () [inline]
Modify the delta.
Definition at line 181 of file sequential.hpp.
Forward()
void Forward (const arma::Mat< eT > & input, arma::Mat< eT > & output)
Ordinary feed forward pass of a neural network, evaluating the function f(x) by propagating the activity forward through f.
Parameters
input Input data used for evaluating the specified function.
output Resulting output activation.
Gradient() [1/3]
void Gradient (const arma::Mat< eT > & input, const arma::Mat< eT > & error, arma::Mat< eT > &)
Gradient() [2/3]
arma::mat const& Gradient () const [inline]
Get the gradient.
Definition at line 184 of file sequential.hpp.
Gradient() [3/3]
arma::mat& Gradient () [inline]
Modify the gradient.
Definition at line 186 of file sequential.hpp.
References Sequential< InputDataType, OutputDataType, Residual, CustomLayers >::InputShape(), and Sequential< InputDataType, OutputDataType, Residual, CustomLayers >::serialize().
InputParameter() [1/2]
arma::mat const& InputParameter () const [inline]
Get the input parameter.
Definition at line 169 of file sequential.hpp.
InputParameter() [2/2]
arma::mat& InputParameter () [inline]
Modify the input parameter.
Definition at line 171 of file sequential.hpp.
InputShape()
size_t InputShape () const
Referenced by Sequential< InputDataType, OutputDataType, Residual, CustomLayers >::Gradient().
Model()
std::vector< LayerTypes<CustomLayers...> >& Model () [inline]
Return the model modules.
Definition at line 153 of file sequential.hpp.
operator=()
 Sequential& operator= (const Sequential< InputDataType, OutputDataType, Residual, CustomLayers > & layer)
Copy assignment operator.
OutputParameter() [1/2]
arma::mat const& OutputParameter () const [inline]
Get the output parameter.
Definition at line 174 of file sequential.hpp.
OutputParameter() [2/2]
arma::mat& OutputParameter () [inline]
Modify the output parameter.
Definition at line 176 of file sequential.hpp.
Parameters() [1/2]
const arma::mat& Parameters () const [inline]
Return the initial point for the optimization.
Definition at line 164 of file sequential.hpp.
Parameters() [2/2]
arma::mat& Parameters () [inline]
Modify the initial point for the optimization.
Definition at line 166 of file sequential.hpp.
serialize()
void serialize (Archive & ar, const uint32_t)
Serialize the layer.
Referenced by Sequential< InputDataType, OutputDataType, Residual, CustomLayers >::Gradient().
The documentation for this class was generated from the following files:
/home/aakash/mlpack/src/mlpack/methods/ann/layer/ layer_types.hpp
/home/aakash/mlpack/src/mlpack/methods/ann/layer/ sequential.hpp