TrainingConfig Class Reference
Public Member Functions
 TrainingConfig ()
 TrainingConfig (size_t numWorkers, size_t updateInterval, size_t targetNetworkSyncInterval, size_t stepLimit, size_t explorationSteps, double stepSize, double discount, double gradientLimit, bool doubleQLearning, bool noisyQLearning, bool isCategorical, size_t atomSize, double vMin, double vMax, double rho)
size_t AtomSize () const
Get the number of atoms.
size_t & AtomSize ()
Modify the number of atoms.
double Discount () const
Get the discount rate for future reward.
double & Discount ()
Modify the discount rate for future reward.
bool DoubleQLearning () const
Get the indicator of double q-learning.
bool & DoubleQLearning ()
Modify the indicator of double q-learning.
size_t ExplorationSteps () const
Get the exploration steps.
size_t & ExplorationSteps ()
Modify the exploration steps.
double GradientLimit () const
Get the limit of update gradient.
double & GradientLimit ()
Modify the limit of update gradient.
bool IsCategorical () const
Get the indicator of categorical q-learning.
bool & IsCategorical ()
Modify the indicator of categorical q-learning.
bool NoisyQLearning () const
Get the indicator of noisy q-learning.
bool & NoisyQLearning ()
Modify the indicator of double q-learning.
size_t NumWorkers () const
Get the amount of workers.
size_t & NumWorkers ()
Modify the amount of workers.
double Rho () const
Get the rho value for sac.
double & Rho ()
Modify the rho value for sac.
size_t StepLimit () const
Get the maximum steps of each episode.
size_t & StepLimit ()
Modify the maximum steps of each episode.
double StepSize () const
Get the step size of the optimizer.
double & StepSize ()
Modify the step size of the optimizer.
size_t TargetNetworkSyncInterval () const
Get the interval for syncing target network.
size_t & TargetNetworkSyncInterval ()
Modify the interval for syncing target network.
size_t UpdateInterval () const
Get the update interval.
size_t & UpdateInterval ()
Modify the update interval.
double VMax () const
Get the maximum value for support.
double & VMax ()
Modify the maximum value for support.
double VMin () const
Get the minimum value for support.
double & VMin ()
Modify the minimum value for support.
Detailed Description
Definition at line 19 of file training_config.hpp.
Constructor & Destructor Documentation
TrainingConfig() [1/2]
 TrainingConfig () [inline]
Definition at line 22 of file training_config.hpp.
TrainingConfig() [2/2]
 TrainingConfig (size_t numWorkers, size_t updateInterval, size_t targetNetworkSyncInterval, size_t stepLimit, size_t explorationSteps, double stepSize, double discount, double gradientLimit, bool doubleQLearning, bool noisyQLearning, bool isCategorical, size_t atomSize, double vMin, double vMax, double rho) [inline]
Definition at line 40 of file training_config.hpp.
Member Function Documentation
AtomSize() [1/2]
size_t AtomSize () const [inline]
Get the number of atoms.
Definition at line 133 of file training_config.hpp.
AtomSize() [2/2]
size_t& AtomSize () [inline]
Modify the number of atoms.
Definition at line 135 of file training_config.hpp.
Discount() [1/2]
double Discount () const [inline]
Get the discount rate for future reward.
Definition at line 108 of file training_config.hpp.
Referenced by NStepQLearningWorker< EnvironmentType, NetworkType, UpdaterType, PolicyType >::Step(), OneStepQLearningWorker< EnvironmentType, NetworkType, UpdaterType, PolicyType >::Step(), and OneStepSarsaWorker< EnvironmentType, NetworkType, UpdaterType, PolicyType >::Step().
Discount() [2/2]
double& Discount () [inline]
Modify the discount rate for future reward.
Definition at line 110 of file training_config.hpp.
DoubleQLearning() [1/2]
bool DoubleQLearning () const [inline]
Get the indicator of double q-learning.
Definition at line 118 of file training_config.hpp.
DoubleQLearning() [2/2]
bool& DoubleQLearning () [inline]
Modify the indicator of double q-learning.
Definition at line 120 of file training_config.hpp.
ExplorationSteps() [1/2]
size_t ExplorationSteps () const [inline]
Get the exploration steps.
Definition at line 98 of file training_config.hpp.
ExplorationSteps() [2/2]
size_t& ExplorationSteps () [inline]
Modify the exploration steps.
Definition at line 100 of file training_config.hpp.
GradientLimit() [1/2]
double GradientLimit () const [inline]
Get the limit of update gradient.
Definition at line 113 of file training_config.hpp.
Referenced by NStepQLearningWorker< EnvironmentType, NetworkType, UpdaterType, PolicyType >::Step(), OneStepQLearningWorker< EnvironmentType, NetworkType, UpdaterType, PolicyType >::Step(), and OneStepSarsaWorker< EnvironmentType, NetworkType, UpdaterType, PolicyType >::Step().
GradientLimit() [2/2]
double& GradientLimit () [inline]
Modify the limit of update gradient.
Definition at line 115 of file training_config.hpp.
IsCategorical() [1/2]
bool IsCategorical () const [inline]
Get the indicator of categorical q-learning.
Definition at line 128 of file training_config.hpp.
IsCategorical() [2/2]
bool& IsCategorical () [inline]
Modify the indicator of categorical q-learning.
Definition at line 130 of file training_config.hpp.
NoisyQLearning() [1/2]
bool NoisyQLearning () const [inline]
Get the indicator of noisy q-learning.
Definition at line 123 of file training_config.hpp.
NoisyQLearning() [2/2]
bool& NoisyQLearning () [inline]
Modify the indicator of double q-learning.
Definition at line 125 of file training_config.hpp.
NumWorkers() [1/2]
size_t NumWorkers () const [inline]
Get the amount of workers.
Definition at line 74 of file training_config.hpp.
NumWorkers() [2/2]
size_t& NumWorkers () [inline]
Modify the amount of workers.
Definition at line 76 of file training_config.hpp.
Rho() [1/2]
double Rho () const [inline]
Get the rho value for sac.
Definition at line 148 of file training_config.hpp.
Rho() [2/2]
double& Rho () [inline]
Modify the rho value for sac.
Definition at line 150 of file training_config.hpp.
StepLimit() [1/2]
size_t StepLimit () const [inline]
Get the maximum steps of each episode.
Definition at line 90 of file training_config.hpp.
Referenced by NStepQLearningWorker< EnvironmentType, NetworkType, UpdaterType, PolicyType >::Step(), OneStepQLearningWorker< EnvironmentType, NetworkType, UpdaterType, PolicyType >::Step(), and OneStepSarsaWorker< EnvironmentType, NetworkType, UpdaterType, PolicyType >::Step().
StepLimit() [2/2]
size_t& StepLimit () [inline]
Modify the maximum steps of each episode.
Setting it to 0 means no limit.
Definition at line 95 of file training_config.hpp.
StepSize() [1/2]
double StepSize () const [inline]
Get the step size of the optimizer.
Definition at line 103 of file training_config.hpp.
Referenced by NStepQLearningWorker< EnvironmentType, NetworkType, UpdaterType, PolicyType >::Step(), OneStepQLearningWorker< EnvironmentType, NetworkType, UpdaterType, PolicyType >::Step(), and OneStepSarsaWorker< EnvironmentType, NetworkType, UpdaterType, PolicyType >::Step().
StepSize() [2/2]
double& StepSize () [inline]
Modify the step size of the optimizer.
Definition at line 105 of file training_config.hpp.
TargetNetworkSyncInterval() [1/2]
size_t TargetNetworkSyncInterval () const [inline]
Get the interval for syncing target network.
Definition at line 84 of file training_config.hpp.
Referenced by NStepQLearningWorker< EnvironmentType, NetworkType, UpdaterType, PolicyType >::Step(), OneStepQLearningWorker< EnvironmentType, NetworkType, UpdaterType, PolicyType >::Step(), and OneStepSarsaWorker< EnvironmentType, NetworkType, UpdaterType, PolicyType >::Step().
TargetNetworkSyncInterval() [2/2]
size_t& TargetNetworkSyncInterval () [inline]
Modify the interval for syncing target network.
Definition at line 87 of file training_config.hpp.
UpdateInterval() [1/2]
size_t UpdateInterval () const [inline]
Get the update interval.
Definition at line 79 of file training_config.hpp.
Referenced by NStepQLearningWorker< EnvironmentType, NetworkType, UpdaterType, PolicyType >::Step(), OneStepQLearningWorker< EnvironmentType, NetworkType, UpdaterType, PolicyType >::Step(), and OneStepSarsaWorker< EnvironmentType, NetworkType, UpdaterType, PolicyType >::Step().
UpdateInterval() [2/2]
size_t& UpdateInterval () [inline]
Modify the update interval.
Definition at line 81 of file training_config.hpp.
VMax() [1/2]
double VMax () const [inline]
Get the maximum value for support.
Definition at line 143 of file training_config.hpp.
VMax() [2/2]
double& VMax () [inline]
Modify the maximum value for support.
Definition at line 145 of file training_config.hpp.
VMin() [1/2]
double VMin () const [inline]
Get the minimum value for support.
Definition at line 138 of file training_config.hpp.
VMin() [2/2]
double& VMin () [inline]
Modify the minimum value for support.
Definition at line 140 of file training_config.hpp.
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/methods/reinforcement_learning/ training_config.hpp