MDOption< T > Class Template Reference
The Markdown option class.
Public Member Functions
 MDOption (const T defaultValue, const std::string &identifier, const std::string &description, const std::string &alias, const std::string &cppName, const bool required=false, const bool input=true, const bool noTranspose=false, const std::string &bindingName=``)
Construct an MDOption object.
Detailed Description
template<typename T>
class mlpack::bindings::markdown::MDOption< T >
The Markdown option class.
Definition at line 33 of file md_option.hpp.
Constructor & Destructor Documentation
MDOption()
 MDOption (const T defaultValue, const std::string & identifier, const std::string & description, const std::string & alias, const std::string & cppName, const bool required = false, const bool input = true, const bool noTranspose = false, const std::string & bindingName = ``) [inline]
Construct an MDOption object.
When constructed, it will register itself with CLI. The testName parameter is not used and added for compatibility reasons.
Definition at line 41 of file md_option.hpp.
References IO::Add(), ParamData::alias, IO::ClearSettings(), ParamData::cppType, ParamData::desc, IO::functionMap, IO::GetSingleton(), ParamData::input, ParamData::loaded, ParamData::name, ParamData::noTranspose, ParamData::persistent, ParamData::required, IO::RestoreSettings(), IO::StoreSettings(), ParamData::tname, TYPENAME, ParamData::value, and ParamData::wasPassed.
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/bindings/markdown/ md_option.hpp