OrthogonalInitialization Class Reference
This class is used to initialize the weight matrix with the orthogonal matrix initialization.
Public Member Functions
 OrthogonalInitialization (const double gain=1.0)
Initialize the orthogonal matrix initialization rule with the given gain.
template<typename eT >
void Initialize (arma::Cube< eT > &W)
Initialize the elements of the specified weight 3rd order tensor with the orthogonal matrix initialization method.
template<typename eT >
void Initialize (arma::Cube< eT > &W, const size_t rows, const size_t cols, const size_t slices)
Initialize the elements of the specified weight 3rd order tensor with the orthogonal matrix initialization method.
template<typename eT >
void Initialize (arma::Mat< eT > &W)
Initialize the elements of the specified weight matrix with the orthogonal matrix initialization method.
template<typename eT >
void Initialize (arma::Mat< eT > &W, const size_t rows, const size_t cols)
Initialize the elements of the specified weight matrix with the orthogonal matrix initialization method.
Detailed Description
This class is used to initialize the weight matrix with the orthogonal matrix initialization.
Definition at line 24 of file orthogonal_init.hpp.
Constructor & Destructor Documentation
OrthogonalInitialization()
 OrthogonalInitialization (const double gain = 1.0) [inline]
Initialize the orthogonal matrix initialization rule with the given gain.
Parameters
gain The gain value.
Definition at line 32 of file orthogonal_init.hpp.
Member Function Documentation
Initialize() [1/4]
void Initialize (arma::Cube< eT > & W) [inline]
Initialize the elements of the specified weight 3rd order tensor with the orthogonal matrix initialization method.
Parameters
W Weight matrix to initialize.
Definition at line 97 of file orthogonal_init.hpp.
References Log::Fatal, and OrthogonalInitialization::Initialize().
Initialize() [2/4]
void Initialize (arma::Cube< eT > & W, const size_t rows, const size_t cols, const size_t slices) [inline]
Initialize the elements of the specified weight 3rd order tensor with the orthogonal matrix initialization method.
Parameters
W Weight matrix to initialize.
rows Number of rows.
cols Number of columns.
slices Number of slices.
Definition at line 78 of file orthogonal_init.hpp.
References OrthogonalInitialization::Initialize().
Initialize() [3/4]
void Initialize (arma::Mat< eT > & W) [inline]
Initialize the elements of the specified weight matrix with the orthogonal matrix initialization method.
Parameters
W Weight matrix to initialize.
Definition at line 59 of file orthogonal_init.hpp.
Initialize() [4/4]
void Initialize (arma::Mat< eT > & W, const size_t rows, const size_t cols) [inline]
Initialize the elements of the specified weight matrix with the orthogonal matrix initialization method.
Parameters
W Weight matrix to initialize.
rows Number of rows.
cols Number of columns.
Definition at line 43 of file orthogonal_init.hpp.
Referenced by OrthogonalInitialization::Initialize().
The documentation for this class was generated from the following file:
/home/aakash/mlpack/src/mlpack/methods/ann/init_rules/ orthogonal_init.hpp