mlpack::bindings::cli Namespace Reference
Classes
class CLIOption
A static object whose constructor registers a parameter with the IO class.
struct ParameterType
Utility struct to return the type that CLI11 should accept for a given input type.
struct ParameterType< arma::Col< eT > >
For vector types, CLI11 will accept a std::string, not an arma::Col<eT> (since it is not clear how to specify a vector on the command-line).
struct ParameterType< arma::Mat< eT > >
For matrix types, CLI11 will accept a std::string, not an arma::mat (since it is not clear how to specify a matrix on the command-line).
struct ParameterType< arma::Row< eT > >
For row vector types, CLI11 will accept a std::string, not an arma::Row<eT> (since it is not clear how to specify a vector on the command-line).
struct ParameterType< std::tuple< mlpack::data::DatasetMapper< PolicyType, std::string >, arma::Mat< eT > > >
For matrix+dataset info types, we should accept a std::string.
struct ParameterTypeDeducer
struct ParameterTypeDeducer< true, T >
Functions
template<typename T >
void AddToCLI11 (const std::string &cliName, util::ParamData &param, CLI::App &app, const typename boost::disable_if< std::is_same< T, bool >>::type *=0, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::disable_if< data::HasSerialize< T >>::type *=0, const typename boost::disable_if< std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>>::type *=0)
Add an option to CLI11.
template<typename T >
void AddToCLI11 (const std::string &cliName, util::ParamData &param, CLI::App &app, const typename boost::disable_if< std::is_same< T, bool >>::type *=0, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::disable_if< data::HasSerialize< T >>::type *=0, const typename boost::enable_if< std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>>::type *=0)
Add a tuple option to CLI11.
template<typename T >
void AddToCLI11 (const std::string &cliName, util::ParamData &param, CLI::App &app, const typename boost::disable_if< std::is_same< T, bool >>::type *=0, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::enable_if< data::HasSerialize< T >>::type *=0, const typename boost::disable_if< std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>>::type *=0)
Add a serializable option to CLI11.
template<typename T >
void AddToCLI11 (const std::string &cliName, util::ParamData &param, CLI::App &app, const typename boost::disable_if< std::is_same< T, bool >>::type *=0, const typename boost::enable_if< arma::is_arma_type< T >>::type *=0, const typename boost::disable_if< std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>>::type *=0)
Add an arma matrix to CLI11.
template<typename T >
void AddToCLI11 (const std::string &cliName, util::ParamData &param, CLI::App &app, const typename boost::enable_if< std::is_same< T, bool >>::type *=0, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::disable_if< data::HasSerialize< T >>::type *=0, const typename boost::disable_if< std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>>::type *=0)
Add a boolean option to CLI11.
template<typename T >
void AddToCLI11 (util::ParamData &param, const void *, void *output)
Add an option to CLI11.
template<typename T >
void DefaultParam (util::ParamData &data, const void *, void *output)
Return the default value of an option.
template<typename T >
std::string DefaultParamImpl (util::ParamData &data, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::disable_if< util::IsStdVector< T >>::type *=0, const typename boost::disable_if< data::HasSerialize< T >>::type *=0, const typename boost::disable_if< std::is_same< T, std::string >>::type *=0, const typename boost::disable_if< std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>>::type *=0)
Return the default value of an option.
template<typename T >
std::string DefaultParamImpl (util::ParamData &data, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::enable_if< data::HasSerialize< T >>::type *=0)
Return the default value of a model option (this returns the default filename, or '' if the default is no file).
template<typename T >
std::string DefaultParamImpl (util::ParamData &data, const typename boost::enable_if< std::is_same< T, std::string >>::type *=0)
Return the default value of a string option.
template<typename T >
std::string DefaultParamImpl (util::ParamData &data, const typename boost::enable_if< util::IsStdVector< T >>::type *=0)
Return the default value of a vector option.
template<typename T >
std::string DefaultParamImpl (util::ParamData &data, const typename boost::enable_if_c< arma::is_arma_type< T >::value||std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>::value >::type *=0)
Return the default value of a matrix option, a tuple option, a serializable option, or a string option (this returns the default filename, or '' if the default is no file).
template<typename T >
void DeleteAllocatedMemory (util::ParamData &d, const void *, void *)
template<typename T >
void DeleteAllocatedMemoryImpl (util::ParamData &, const typename boost::disable_if< data::HasSerialize< T >>::type *=0, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0)
template<typename T >
void DeleteAllocatedMemoryImpl (util::ParamData &, const typename boost::enable_if< arma::is_arma_type< T >>::type *=0)
template<typename T >
void DeleteAllocatedMemoryImpl (util::ParamData &d, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::enable_if< data::HasSerialize< T >>::type *=0)
void EndProgram ()
Handle command-line program termination.
template<typename T >
void * GetAllocatedMemory (util::ParamData &, const typename boost::disable_if< data::HasSerialize< T >>::type *=0, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0)
template<typename T >
void * GetAllocatedMemory (util::ParamData &, const typename boost::enable_if< arma::is_arma_type< T >>::type *=0)
template<typename T >
void * GetAllocatedMemory (util::ParamData &d, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::enable_if< data::HasSerialize< T >>::type *=0)
template<typename T >
void GetAllocatedMemory (util::ParamData &d, const void *, void *output)
std::string GetBindingName (const std::string &bindingName)
Given the name of a binding, print its command-line name (this returns `mlpack_<bindingName>`.
template<typename T >
T & GetParam (util::ParamData &d, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::disable_if< data::HasSerialize< T >>::type *=0, const typename boost::disable_if< std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>>::type *=0)
This overload is called when nothing special needs to happen to the name of the parameter.
template<typename T >
T *& GetParam (util::ParamData &d, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::enable_if< data::HasSerialize< T >>::type *=0)
Return a serializable object.
template<typename T >
T & GetParam (util::ParamData &d, const typename boost::enable_if< arma::is_arma_type< T >>::type *=0)
Return a matrix parameter.
template<typename T >
T & GetParam (util::ParamData &d, const typename boost::enable_if< std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>>::type *=0)
Return a matrix/dataset info parameter.
template<typename T >
void GetParam (util::ParamData &d, const void *, void *output)
Return a parameter casted to the given type.
template<typename T >
std::string GetPrintableParam (util::ParamData &data, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::disable_if< util::IsStdVector< T >>::type *=0, const typename boost::disable_if< data::HasSerialize< T >>::type *=0, const typename boost::disable_if< std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>>::type *=0)
Print an option.
template<typename T >
std::string GetPrintableParam (util::ParamData &data, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::enable_if< data::HasSerialize< T >>::type *=0)
Print a model option (this just prints the filename).
template<typename T >
std::string GetPrintableParam (util::ParamData &data, const typename std::enable_if< arma::is_arma_type< T >::value||std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>::value >::type *=0)
Print a matrix/tuple option (this just prints the filename).
template<typename T >
std::string GetPrintableParam (util::ParamData &data, const typename std::enable_if< util::IsStdVector< T >::value >::type *=0)
Print a vector option, with spaces between it.
template<typename T >
void GetPrintableParam (util::ParamData &data, const void *, void *output)
Print an option into a std::string.
template<typename T >
void GetPrintableParamName (util::ParamData &d, const void *, void *output)
Get the parameter's name as seen by the user.
template<typename T >
std::string GetPrintableParamName (util::ParamData &data, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::disable_if< data::HasSerialize< T >>::type *=0, const typename boost::disable_if< std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>>::type *=0)
Get the parameter name for a type that has no special handling.
template<typename T >
std::string GetPrintableParamName (util::ParamData &data, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::enable_if< data::HasSerialize< T >>::type *=0)
Get the parameter name for a serializable model type (where the user has to pass the file that holds the matrix).
template<typename T >
std::string GetPrintableParamName (util::ParamData &data, const typename boost::enable_if< arma::is_arma_type< T >>::type *=0)
Get the parameter name for a matrix type (where the user has to pass the file that holds the matrix).
template<typename T >
std::string GetPrintableParamName (util::ParamData &data, const typename boost::enable_if< std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>>::type *=0)
Get the parameter name for a mapped matrix type (where the user has to pass the file that holds the matrix).
template<typename T >
void GetPrintableParamValue (util::ParamData &d, const void *input, void *output)
Get the parameter's name as seen by the user.
template<typename T >
std::string GetPrintableParamValue (util::ParamData &data, const std::string &value, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::disable_if< data::HasSerialize< T >>::type *=0, const typename boost::disable_if< std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>>::type *=0)
Get the parameter name for a type that has no special handling.
template<typename T >
std::string GetPrintableParamValue (util::ParamData &data, const std::string &value, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::enable_if< data::HasSerialize< T >>::type *=0)
Get the parameter name for a serializable model type (where the user has to pass the file that holds the matrix).
template<typename T >
std::string GetPrintableParamValue (util::ParamData &data, const std::string &value, const typename boost::enable_if< arma::is_arma_type< T >>::type *=0)
Get the parameter name for a matrix type (where the user has to pass the file that holds the matrix).
template<typename T >
std::string GetPrintableParamValue (util::ParamData &data, const std::string &value, const typename boost::enable_if< std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>>::type *=0)
Get the parameter name for a mapped matrix type (where the user has to pass the file that holds the matrix).
template<typename T >
std::string GetPrintableType (util::ParamData &data, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::disable_if< util::IsStdVector< T >>::type *=0, const typename boost::disable_if< data::HasSerialize< T >>::type *=0, const typename boost::disable_if< std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>>::type *=0)
Return a string representing the command-line type of an option.
template<typename T >
std::string GetPrintableType (util::ParamData &data, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::enable_if< data::HasSerialize< T >>::type *=0)
Return a string representing the command-line type of a model.
template<typename T >
std::string GetPrintableType (util::ParamData &data, const typename std::enable_if< arma::is_arma_type< T >::value >::type *=0)
Return a string representing the command-line type of a matrix option.
template<typename T >
std::string GetPrintableType (util::ParamData &data, const typename std::enable_if< std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>::value >::type *=0)
Return a string representing the command-line type of a matrix tuple option.
template<typename T >
std::string GetPrintableType (util::ParamData &data, const typename std::enable_if< util::IsStdVector< T >::value >::type *=0)
Return a string representing the command-line type of a vector.
template<typename T >
void GetPrintableType (util::ParamData &data, const void *, void *output)
Print the command-line type of an option into a string.
template<typename T >
T & GetRawParam (util::ParamData &d, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::disable_if< data::HasSerialize< T >>::type *=0, const typename boost::disable_if< std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>>::type *=0)
This overload is called when nothing special needs to happen to the name of the parameter.
template<typename T >
T *& GetRawParam (util::ParamData &d, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::enable_if< data::HasSerialize< T >>::type *=0)
Return the name of a model parameter.
template<typename T >
T & GetRawParam (util::ParamData &d, const typename boost::enable_if_c< arma::is_arma_type< T >::value||std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>::value >::type *=0)
Return a matrix parameter.
template<typename T >
void GetRawParam (util::ParamData &d, const void *, void *output)
Return a parameter casted to the given type.
template<typename T >
bool IgnoreCheck (const T &)
Return whether or not a runtime check on parameters should be ignored.
template<typename T >
void InPlaceCopy (util::ParamData &d, const void *input, void *)
Make the given ParamData be an in-place copy of the input.
template<typename T >
void InPlaceCopyInternal (util::ParamData &, util::ParamData &, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::disable_if< data::HasSerialize< T >>::type *=0, const typename boost::disable_if< std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>>::type *=0)
This overload is called when nothing special needs to happen to make something an in-place copy.
template<typename T >
void InPlaceCopyInternal (util::ParamData &d, util::ParamData &input, const typename std::enable_if< arma::is_arma_type< T >::value||std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>::value >::type *=0)
Modify the filename for any type that needs to be loaded from disk to match the filename of the input parameter, for a matrix/DatasetInfo parameter.
template<typename T >
void InPlaceCopyInternal (util::ParamData &d, util::ParamData &input, const typename std::enable_if< data::HasSerialize< T >::value >::type *=0)
Modify the filename for any type that needs to be loaded from disk to match the filename of the input parameter.
template<typename T >
std::string MapParameterName (const std::string &identifier, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::disable_if< data::HasSerialize< T >>::type *=0, const typename boost::disable_if< std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>>::type *=0)
If needed, map the parameter name to the name that is used by CLI11.
template<typename T >
std::string MapParameterName (const std::string &identifier, const typename boost::enable_if_c< arma::is_arma_type< T >::value||std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>::value|| data::HasSerialize< T >::value >::type *=0)
Map the parameter name to the name that is used by CLI11.
template<typename T >
void MapParameterName (util::ParamData &d, const void *, void *output)
Map the parameter name to the name seen by CLI.
template<typename T >
void OutputParam (util::ParamData &data, const void *, void *)
Output an option.
template<typename T >
void OutputParamImpl (util::ParamData &data, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::disable_if< util::IsStdVector< T >>::type *=0, const typename boost::disable_if< data::HasSerialize< T >>::type *=0, const typename boost::disable_if< std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>>::type *=0)
Output an option (print to stdout).
template<typename T >
void OutputParamImpl (util::ParamData &data, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::enable_if< data::HasSerialize< T >>::type *=0)
Output a serializable class option (this saves it to the given file).
template<typename T >
void OutputParamImpl (util::ParamData &data, const typename boost::enable_if< arma::is_arma_type< T >>::type *=0)
Output a matrix option (this saves it to the given file).
template<typename T >
void OutputParamImpl (util::ParamData &data, const typename boost::enable_if< std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>>::type *=0)
Output a mapped dataset.
template<typename T >
void OutputParamImpl (util::ParamData &data, const typename boost::enable_if< util::IsStdVector< T >>::type *=0)
Output a vector option (print to stdout).
 PARAM_FLAG (`help`, `Default help info.`, `h`)
 PARAM_FLAG (`verbose`, `Display informational messages and the full list of ` `parameters and timers at the end of execution.`, `v`)
 PARAM_FLAG (`version`, `Display the version of mlpack.`, `V`)
 PARAM_STRING_IN (`info`, `Print help on a specific option.`, ``, ``)
std::string ParamString (const std::string &paramName)
Print what a user would type to invoke the given option name.
void ParseCommandLine (int argc, char **argv)
Parse the command line, setting all of the options inside of the CLI object to their appropriate given values.
std::string PrintDataset (const std::string &dataset)
Print a dataset type parameter (add .csv and return).
std::string PrintDefault (const std::string &paramName)
Given a parameter name, print its corresponding default value.
void PrintHelp (const std::string &param=``)
Print the help for the given parameter.
std::string PrintImport (const std::string &bindingName)
Print any imports for CLI (there are none, so this returns an empty string).
std::string PrintInputOptionInfo ()
Print any special information about input options.
std::string PrintModel (const std::string &model)
Print a model type parameter (add .bin and return).
std::string PrintOutputOptionInfo ()
Print any special information about output options.
std::string PrintType (util::ParamData &param)
Print the type of a parameter that a user would specify from the command-line.
template<typename T >
std::string PrintTypeDoc (util::ParamData &data, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::disable_if< util::IsStdVector< T >>::type *=0, const typename boost::disable_if< data::HasSerialize< T >>::type *=0, const typename boost::disable_if< std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>>::type *=0)
Return a string representing the command-line type of an option.
template<typename T >
std::string PrintTypeDoc (util::ParamData &data, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::enable_if< data::HasSerialize< T >>::type *=0)
Return a string representing the command-line type of a model.
template<typename T >
std::string PrintTypeDoc (util::ParamData &data, const typename std::enable_if< arma::is_arma_type< T >::value >::type *=0)
Return a string representing the command-line type of a matrix option.
template<typename T >
std::string PrintTypeDoc (util::ParamData &data, const typename std::enable_if< std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>::value >::type *=0)
Return a string representing the command-line type of a matrix tuple option.
template<typename T >
std::string PrintTypeDoc (util::ParamData &data, const typename std::enable_if< util::IsStdVector< T >::value >::type *=0)
Return a string representing the command-line type of a vector.
template<typename T >
void PrintTypeDoc (util::ParamData &data, const void *, void *output)
Print the command-line type of an option into a string.
std::string PrintTypeDocs ()
Print documentation for each of the types.
template<typename T >
std::string PrintValue (const T &value, bool quotes)
Given a parameter type, print the corresponding value.
std::string ProcessOptions ()
Base case for recursion.
template<typename T , typename... Args>
std::string ProcessOptions (const std::string &paramName, const T &value, Args... args)
Print an option for a command-line argument.
std::string ProgramCall (const std::string &programName)
Given a program name, print a program call invocation assuming that all options are specified.
template<typename... Args>
std::string ProgramCall (const std::string &programName, Args... args)
Given a program name and arguments for it, print what its invocation would be.
template<typename T >
void SetParam (util::ParamData &d, const boost::any &, const typename boost::enable_if< std::is_same< T, bool >>::type *=0)
This overload is called to set a boolean.
template<typename T >
void SetParam (util::ParamData &d, const boost::any &value, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::disable_if< data::HasSerialize< T >>::type *=0, const typename boost::disable_if< std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>>::type *=0, const typename boost::disable_if< std::is_same< T, bool >>::type *=0)
This overload is called when nothing special needs to happen to the name of the parameter.
template<typename T >
void SetParam (util::ParamData &d, const boost::any &value, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::enable_if< data::HasSerialize< T >>::type *=0)
Set a serializable object.
template<typename T >
void SetParam (util::ParamData &d, const boost::any &value, const typename std::enable_if< arma::is_arma_type< T >::value||std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>::value >::type *=0)
Set a matrix parameter, a matrix/dataset info parameter.
template<typename T >
void SetParam (util::ParamData &d, const void *input, void *)
Return a parameter casted to the given type.
template<typename T >
void StringTypeParam (util::ParamData &, const void *, void *output)
Return a string containing the type of a parameter.
template<> void StringTypeParam< bool > (util::ParamData &, const void *, void *output)
Return `bool`.
template<> void StringTypeParam< double > (util::ParamData &, const void *, void *output)
Return `double`.
template<> void StringTypeParam< int > (util::ParamData &, const void *, void *output)
Return `int`.
template<> void StringTypeParam< std::string > (util::ParamData &, const void *, void *output)
Return `string`.
template<> void StringTypeParam< std::tuple< mlpack::data::DatasetInfo, arma::mat > > (util::ParamData &, const void *, void *output)
Return `string`;.
template<typename T >
std::string StringTypeParamImpl (const typename boost::disable_if< util::IsStdVector< T >>::type *=0, const typename boost::disable_if< data::HasSerialize< T >>::type *=0)
Return a string containing the type of the parameter.
template<typename T >
std::string StringTypeParamImpl (const typename boost::enable_if< data::HasSerialize< T >>::type *=0)
Return a string containing the type of the parameter,.
template<typename T >
std::string StringTypeParamImpl (const typename boost::enable_if< util::IsStdVector< T >>::type *=0)
Return a string containing the type of the parameter, for vector options.
Function Documentation
AddToCLI11() [1/6]
void mlpack::bindings::cli::AddToCLI11 (const std::string & cliName, util::ParamData & param, CLI::App & app, const typename boost::disable_if< std::is_same< T, bool >>::type * = 0, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::disable_if< data::HasSerialize< T >>::type * = 0, const typename boost::disable_if< std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>>::type * = 0)
Add an option to CLI11.
Parameters
cliName The name of the option to add to CLI11.
param an object of util::ParamData.
app a CLI11 object to add parameter to.
Definition at line 127 of file add_to_cli11.hpp.
References ParamData::desc, ParamData::value, and ParamData::wasPassed.
AddToCLI11() [2/6]
void mlpack::bindings::cli::AddToCLI11 (const std::string & cliName, util::ParamData & param, CLI::App & app, const typename boost::disable_if< std::is_same< T, bool >>::type * = 0, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::disable_if< data::HasSerialize< T >>::type * = 0, const typename boost::enable_if< std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>>::type * = 0)
Add a tuple option to CLI11.
Parameters
cliName The name of the option to add to CLI11.
param an object of util::ParamData.
app A CLI11 object to add parameter to.
Definition at line 33 of file add_to_cli11.hpp.
References ParamData::desc, ParamData::value, and ParamData::wasPassed.
AddToCLI11() [3/6]
void mlpack::bindings::cli::AddToCLI11 (const std::string & cliName, util::ParamData & param, CLI::App & app, const typename boost::disable_if< std::is_same< T, bool >>::type * = 0, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::enable_if< data::HasSerialize< T >>::type * = 0, const typename boost::disable_if< std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>>::type * = 0)
Add a serializable option to CLI11.
Parameters
cliName The name of the option to add to CLI11.
param an object of util::ParamData.
app a CLI11 object to add parameter to.
Definition at line 65 of file add_to_cli11.hpp.
References ParamData::desc, ParamData::value, and ParamData::wasPassed.
AddToCLI11() [4/6]
void mlpack::bindings::cli::AddToCLI11 (const std::string & cliName, util::ParamData & param, CLI::App & app, const typename boost::disable_if< std::is_same< T, bool >>::type * = 0, const typename boost::enable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::disable_if< std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>>::type * = 0)
Add an arma matrix to CLI11.
Parameters
cliName The name of the option to add to CLI11.
param an object of util::ParamData.
app a CLI11 object to add parameter to.
Definition at line 97 of file add_to_cli11.hpp.
References ParamData::desc, ParamData::value, and ParamData::wasPassed.
AddToCLI11() [5/6]
void mlpack::bindings::cli::AddToCLI11 (const std::string & cliName, util::ParamData & param, CLI::App & app, const typename boost::enable_if< std::is_same< T, bool >>::type * = 0, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::disable_if< data::HasSerialize< T >>::type * = 0, const typename boost::disable_if< std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>>::type * = 0)
Add a boolean option to CLI11.
Parameters
cliName The name of the option to add to CLI11.
param an object of util::ParamData.
app a CLI11 object to add parameter to.
Definition at line 157 of file add_to_cli11.hpp.
References ParamData::desc.
AddToCLI11() [6/6]
void mlpack::bindings::cli::AddToCLI11 (util::ParamData & param, const void * , void * output)
Add an option to CLI11.
This is the function meant to be used in the CLI function map.
Parameters
param Parameter data.
* (input) Unused void pointer.
output Void pointer to options_description object.
Definition at line 188 of file add_to_cli11.hpp.
References ParamData::alias, and ParamData::name.
DefaultParam()
void mlpack::bindings::cli::DefaultParam (util::ParamData & data, const void * , void * output)
Return the default value of an option.
This is the function that will be placed into the CLI functionMap.
Definition at line 80 of file default_param.hpp.
DefaultParamImpl() [1/5]
std::string mlpack::bindings::cli::DefaultParamImpl (util::ParamData & data, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::disable_if< util::IsStdVector< T >>::type * = 0, const typename boost::disable_if< data::HasSerialize< T >>::type * = 0, const typename boost::disable_if< std::is_same< T, std::string >>::type * = 0, const typename boost::disable_if< std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>>::type * = 0)
Return the default value of an option.
This is for regular types.
DefaultParamImpl() [2/5]
std::string mlpack::bindings::cli::DefaultParamImpl (util::ParamData & data, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::enable_if< data::HasSerialize< T >>::type * = 0)
Return the default value of a model option (this returns the default filename, or '' if the default is no file).
DefaultParamImpl() [3/5]
std::string mlpack::bindings::cli::DefaultParamImpl (util::ParamData & data, const typename boost::enable_if< std::is_same< T, std::string >>::type * = 0)
Return the default value of a string option.
DefaultParamImpl() [4/5]
std::string mlpack::bindings::cli::DefaultParamImpl (util::ParamData & data, const typename boost::enable_if< util::IsStdVector< T >>::type * = 0)
Return the default value of a vector option.
DefaultParamImpl() [5/5]
std::string mlpack::bindings::cli::DefaultParamImpl (util::ParamData & data, const typename boost::enable_if_c< arma::is_arma_type< T >::value||std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>::value >::type * = 0)
Return the default value of a matrix option, a tuple option, a serializable option, or a string option (this returns the default filename, or '' if the default is no file).
DeleteAllocatedMemory()
void mlpack::bindings::cli::DeleteAllocatedMemory (util::ParamData & d, const void * , void *)
Definition at line 50 of file delete_allocated_memory.hpp.
DeleteAllocatedMemoryImpl() [1/3]
void mlpack::bindings::cli::DeleteAllocatedMemoryImpl (util::ParamData & , const typename boost::disable_if< data::HasSerialize< T >>::type * = 0, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0)
Definition at line 22 of file delete_allocated_memory.hpp.
DeleteAllocatedMemoryImpl() [2/3]
void mlpack::bindings::cli::DeleteAllocatedMemoryImpl (util::ParamData & , const typename boost::enable_if< arma::is_arma_type< T >>::type * = 0)
Definition at line 31 of file delete_allocated_memory.hpp.
DeleteAllocatedMemoryImpl() [3/3]
void mlpack::bindings::cli::DeleteAllocatedMemoryImpl (util::ParamData & d, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::enable_if< data::HasSerialize< T >>::type * = 0)
Definition at line 39 of file delete_allocated_memory.hpp.
References ParamData::value.
EndProgram()
void mlpack::bindings::cli::EndProgram () [inline]
Handle command-line program termination.
If --help or --info was passed, we won't make it here, so we don't have to write any contingencies for that.
Definition at line 26 of file end_program.hpp.
References IO::functionMap, Timers::GetAllTimers(), IO::GetSingleton(), IO::HasParam(), Log::Info, ParamData::input, IO::Parameters(), Timers::PrintTimer(), Timers::StopAllTimers(), IO::timer, and ParamData::tname.
GetAllocatedMemory() [1/4]
void* mlpack::bindings::cli::GetAllocatedMemory (util::ParamData & , const typename boost::disable_if< data::HasSerialize< T >>::type * = 0, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0)
Definition at line 23 of file get_allocated_memory.hpp.
GetAllocatedMemory() [2/4]
void* mlpack::bindings::cli::GetAllocatedMemory (util::ParamData & , const typename boost::enable_if< arma::is_arma_type< T >>::type * = 0)
Definition at line 32 of file get_allocated_memory.hpp.
GetAllocatedMemory() [3/4]
void* mlpack::bindings::cli::GetAllocatedMemory (util::ParamData & d, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::enable_if< data::HasSerialize< T >>::type * = 0)
Definition at line 40 of file get_allocated_memory.hpp.
References ParamData::value.
GetAllocatedMemory() [4/4]
void mlpack::bindings::cli::GetAllocatedMemory (util::ParamData & d, const void * , void * output)
Definition at line 52 of file get_allocated_memory.hpp.
GetBindingName()
std::string mlpack::bindings::cli::GetBindingName (const std::string & bindingName) [inline]
Given the name of a binding, print its command-line name (this returns `mlpack_<bindingName>`.
GetParam() [1/5]
T& mlpack::bindings::cli::GetParam (util::ParamData & d, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::disable_if< data::HasSerialize< T >>::type * = 0, const typename boost::disable_if< std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>>::type * = 0)
This overload is called when nothing special needs to happen to the name of the parameter.
Parameters
d ParamData object to get parameter value from.
Definition at line 29 of file get_param.hpp.
References ParamData::value.
GetParam() [2/5]
T*& mlpack::bindings::cli::GetParam (util::ParamData & d, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::enable_if< data::HasSerialize< T >>::type * = 0)
Return a serializable object.
Parameters
d ParamData object to get parameter value from.
Definition at line 111 of file get_param.hpp.
References ParamData::input, mlpack::data::Load(), ParamData::loaded, and ParamData::value.
GetParam() [3/5]
T& mlpack::bindings::cli::GetParam (util::ParamData & d, const typename boost::enable_if< arma::is_arma_type< T >>::type * = 0)
Return a matrix parameter.
Parameters
d ParamData object to get parameter value from.
Definition at line 46 of file get_param.hpp.
References ParamData::input, mlpack::data::Load(), ParamData::loaded, ParamData::noTranspose, and ParamData::value.
GetParam() [4/5]
T& mlpack::bindings::cli::GetParam (util::ParamData & d, const typename boost::enable_if< std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>>::type * = 0)
Return a matrix/dataset info parameter.
Parameters
d ParamData object to get parameter value from.
Definition at line 81 of file get_param.hpp.
References ParamData::input, mlpack::data::Load(), ParamData::loaded, ParamData::noTranspose, and ParamData::value.
GetParam() [5/5]
void mlpack::bindings::cli::GetParam (util::ParamData & d, const void * , void * output)
Return a parameter casted to the given type.
Type checking does not happen here!
Parameters
d Parameter information.
* (input) Unused parameter.
output Place to store pointer to value.
Definition at line 140 of file get_param.hpp.
GetPrintableParam() [1/5]
std::string mlpack::bindings::cli::GetPrintableParam (util::ParamData & data, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::disable_if< util::IsStdVector< T >>::type * = 0, const typename boost::disable_if< data::HasSerialize< T >>::type * = 0, const typename boost::disable_if< std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>>::type * = 0)
Print an option.
GetPrintableParam() [2/5]
std::string mlpack::bindings::cli::GetPrintableParam (util::ParamData & data, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::enable_if< data::HasSerialize< T >>::type * = 0)
Print a model option (this just prints the filename).
GetPrintableParam() [3/5]
std::string mlpack::bindings::cli::GetPrintableParam (util::ParamData & data, const typename std::enable_if< arma::is_arma_type< T >::value||std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>::value >::type * = 0)
Print a matrix/tuple option (this just prints the filename).
GetPrintableParam() [4/5]
std::string mlpack::bindings::cli::GetPrintableParam (util::ParamData & data, const typename std::enable_if< util::IsStdVector< T >::value >::type * = 0)
Print a vector option, with spaces between it.
GetPrintableParam() [5/5]
void mlpack::bindings::cli::GetPrintableParam (util::ParamData & data, const void * , void * output)
Print an option into a std::string.
This should print a short, one-line representation of the object. The string will be stored in the output pointer.
Definition at line 69 of file get_printable_param.hpp.
GetPrintableParamName() [1/5]
void mlpack::bindings::cli::GetPrintableParamName (util::ParamData & d, const void * , void * output)
Get the parameter's name as seen by the user.
Definition at line 67 of file get_printable_param_name.hpp.
GetPrintableParamName() [2/5]
std::string mlpack::bindings::cli::GetPrintableParamName (util::ParamData & data, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::disable_if< data::HasSerialize< T >>::type * = 0, const typename boost::disable_if< std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>>::type * = 0)
Get the parameter name for a type that has no special handling.
GetPrintableParamName() [3/5]
std::string mlpack::bindings::cli::GetPrintableParamName (util::ParamData & data, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::enable_if< data::HasSerialize< T >>::type * = 0)
Get the parameter name for a serializable model type (where the user has to pass the file that holds the matrix).
GetPrintableParamName() [4/5]
std::string mlpack::bindings::cli::GetPrintableParamName (util::ParamData & data, const typename boost::enable_if< arma::is_arma_type< T >>::type * = 0)
Get the parameter name for a matrix type (where the user has to pass the file that holds the matrix).
GetPrintableParamName() [5/5]
std::string mlpack::bindings::cli::GetPrintableParamName (util::ParamData & data, const typename boost::enable_if< std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>>::type * = 0)
Get the parameter name for a mapped matrix type (where the user has to pass the file that holds the matrix).
GetPrintableParamValue() [1/5]
void mlpack::bindings::cli::GetPrintableParamValue (util::ParamData & d, const void * input, void * output)
Get the parameter's name as seen by the user.
Definition at line 71 of file get_printable_param_value.hpp.
GetPrintableParamValue() [2/5]
std::string mlpack::bindings::cli::GetPrintableParamValue (util::ParamData & data, const std::string & value, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::disable_if< data::HasSerialize< T >>::type * = 0, const typename boost::disable_if< std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>>::type * = 0)
Get the parameter name for a type that has no special handling.
GetPrintableParamValue() [3/5]
std::string mlpack::bindings::cli::GetPrintableParamValue (util::ParamData & data, const std::string & value, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::enable_if< data::HasSerialize< T >>::type * = 0)
Get the parameter name for a serializable model type (where the user has to pass the file that holds the matrix).
GetPrintableParamValue() [4/5]
std::string mlpack::bindings::cli::GetPrintableParamValue (util::ParamData & data, const std::string & value, const typename boost::enable_if< arma::is_arma_type< T >>::type * = 0)
Get the parameter name for a matrix type (where the user has to pass the file that holds the matrix).
GetPrintableParamValue() [5/5]
std::string mlpack::bindings::cli::GetPrintableParamValue (util::ParamData & data, const std::string & value, const typename boost::enable_if< std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>>::type * = 0)
Get the parameter name for a mapped matrix type (where the user has to pass the file that holds the matrix).
GetPrintableType() [1/6]
std::string mlpack::bindings::cli::GetPrintableType (util::ParamData & data, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::disable_if< util::IsStdVector< T >>::type * = 0, const typename boost::disable_if< data::HasSerialize< T >>::type * = 0, const typename boost::disable_if< std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>>::type * = 0)
Return a string representing the command-line type of an option.
GetPrintableType() [2/6]
std::string mlpack::bindings::cli::GetPrintableType (util::ParamData & data, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::enable_if< data::HasSerialize< T >>::type * = 0)
Return a string representing the command-line type of a model.
GetPrintableType() [3/6]
std::string mlpack::bindings::cli::GetPrintableType (util::ParamData & data, const typename std::enable_if< arma::is_arma_type< T >::value >::type * = 0)
Return a string representing the command-line type of a matrix option.
GetPrintableType() [4/6]
std::string mlpack::bindings::cli::GetPrintableType (util::ParamData & data, const typename std::enable_if< std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>::value >::type * = 0)
Return a string representing the command-line type of a matrix tuple option.
GetPrintableType() [5/6]
std::string mlpack::bindings::cli::GetPrintableType (util::ParamData & data, const typename std::enable_if< util::IsStdVector< T >::value >::type * = 0)
Return a string representing the command-line type of a vector.
GetPrintableType() [6/6]
void mlpack::bindings::cli::GetPrintableType (util::ParamData & data, const void * , void * output)
Print the command-line type of an option into a string.
Definition at line 70 of file get_printable_type.hpp.
GetRawParam() [1/4]
T& mlpack::bindings::cli::GetRawParam (util::ParamData & d, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::disable_if< data::HasSerialize< T >>::type * = 0, const typename boost::disable_if< std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>>::type * = 0)
This overload is called when nothing special needs to happen to the name of the parameter.
Definition at line 28 of file get_raw_param.hpp.
References ParamData::value.
GetRawParam() [2/4]
T*& mlpack::bindings::cli::GetRawParam (util::ParamData & d, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::enable_if< data::HasSerialize< T >>::type * = 0)
Return the name of a model parameter.
Definition at line 60 of file get_raw_param.hpp.
References ParamData::value.
GetRawParam() [3/4]
T& mlpack::bindings::cli::GetRawParam (util::ParamData & d, const typename boost::enable_if_c< arma::is_arma_type< T >::value||std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>::value >::type * = 0)
Return a matrix parameter.
Definition at line 43 of file get_raw_param.hpp.
References ParamData::value.
GetRawParam() [4/4]
void mlpack::bindings::cli::GetRawParam (util::ParamData & d, const void * , void * output)
Return a parameter casted to the given type.
Type checking does not happen here!
Parameters
d Parameter information.
* (input) Unused parameter.
output Place to store pointer to value.
Definition at line 80 of file get_raw_param.hpp.
IgnoreCheck()
bool mlpack::bindings::cli::IgnoreCheck (const T &) [inline]
Return whether or not a runtime check on parameters should be ignored.
We don't ignore any runtime checks for CLI bindings, so this always returns false.
Definition at line 117 of file print_doc_functions.hpp.
InPlaceCopy()
void mlpack::bindings::cli::InPlaceCopy (util::ParamData & d, const void * input, void *)
Make the given ParamData be an in-place copy of the input.
Parameters
d Parameter information.
input Input ParamData we would like be the source of the in-place copy.
* (output) Unused parameter.
Definition at line 100 of file in_place_copy.hpp.
InPlaceCopyInternal() [1/3]
void mlpack::bindings::cli::InPlaceCopyInternal (util::ParamData & , util::ParamData & , const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::disable_if< data::HasSerialize< T >>::type * = 0, const typename boost::disable_if< std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>>::type * = 0)
This overload is called when nothing special needs to happen to make something an in-place copy.
Parameters
* (d) ParamData object to get parameter value from. (Unused.)
* (input) ParamData object that represents the option we are making a copy of. (Unused.)
Definition at line 31 of file in_place_copy.hpp.
InPlaceCopyInternal() [2/3]
void mlpack::bindings::cli::InPlaceCopyInternal (util::ParamData & d, util::ParamData & input, const typename std::enable_if< arma::is_arma_type< T >::value||std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>::value >::type * = 0)
Modify the filename for any type that needs to be loaded from disk to match the filename of the input parameter, for a matrix/DatasetInfo parameter.
Parameters
d ParamData object we want to make into an in-place copy.
input ParamData object whose filename we should copy.
Definition at line 50 of file in_place_copy.hpp.
References ParamData::value.
InPlaceCopyInternal() [3/3]
void mlpack::bindings::cli::InPlaceCopyInternal (util::ParamData & d, util::ParamData & input, const typename std::enable_if< data::HasSerialize< T >::value >::type * = 0)
Modify the filename for any type that needs to be loaded from disk to match the filename of the input parameter.
For serializable objects.
Parameters
d ParamData object we want to make into an in-place copy.
input ParamData object whose filename we should copy.
Definition at line 76 of file in_place_copy.hpp.
References ParamData::value.
MapParameterName() [1/3]
std::string mlpack::bindings::cli::MapParameterName (const std::string & identifier, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::disable_if< data::HasSerialize< T >>::type * = 0, const typename boost::disable_if< std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>>::type * = 0)
If needed, map the parameter name to the name that is used by CLI11.
This overload simply returns the same name, so it is used for primitive types.
Definition at line 28 of file map_parameter_name.hpp.
Referenced by CLIOption< N >::CLIOption().
MapParameterName() [2/3]
std::string mlpack::bindings::cli::MapParameterName (const std::string & identifier, const typename boost::enable_if_c< arma::is_arma_type< T >::value||std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>::value|| data::HasSerialize< T >::value >::type * = 0)
Map the parameter name to the name that is used by CLI11.
This overload addresses matrices and models, where the parameter name has `_file` appended to it (since a filename will be provided).
Definition at line 44 of file map_parameter_name.hpp.
MapParameterName() [3/3]
void mlpack::bindings::cli::MapParameterName (util::ParamData & d, const void * , void * output)
Map the parameter name to the name seen by CLI.
Parameters
d Parameter data.
* (input) Unused parameter.
output Pointer to std::string that will hold the mapped name.
Definition at line 63 of file map_parameter_name.hpp.
References ParamData::name.
OutputParam()
void mlpack::bindings::cli::OutputParam (util::ParamData & data, const void * , void *)
Output an option.
This is the function that will be called by the IO module.
Definition at line 74 of file output_param.hpp.
OutputParamImpl() [1/5]
void mlpack::bindings::cli::OutputParamImpl (util::ParamData & data, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::disable_if< util::IsStdVector< T >>::type * = 0, const typename boost::disable_if< data::HasSerialize< T >>::type * = 0, const typename boost::disable_if< std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>>::type * = 0)
Output an option (print to stdout).
OutputParamImpl() [2/5]
void mlpack::bindings::cli::OutputParamImpl (util::ParamData & data, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::enable_if< data::HasSerialize< T >>::type * = 0)
Output a serializable class option (this saves it to the given file).
OutputParamImpl() [3/5]
void mlpack::bindings::cli::OutputParamImpl (util::ParamData & data, const typename boost::enable_if< arma::is_arma_type< T >>::type * = 0)
Output a matrix option (this saves it to the given file).
OutputParamImpl() [4/5]
void mlpack::bindings::cli::OutputParamImpl (util::ParamData & data, const typename boost::enable_if< std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>>::type * = 0)
Output a mapped dataset.
OutputParamImpl() [5/5]
void mlpack::bindings::cli::OutputParamImpl (util::ParamData & data, const typename boost::enable_if< util::IsStdVector< T >>::type * = 0)
Output a vector option (print to stdout).
PARAM_FLAG() [1/3]
mlpack::bindings::cli::PARAM_FLAG (`help` , `Default help info.` , `h`)
PARAM_FLAG() [2/3]
mlpack::bindings::cli::PARAM_FLAG (`verbose` , `Display informational messages and the full list of ` `parameters and timers at the end of execution.` , `v`)
PARAM_FLAG() [3/3]
mlpack::bindings::cli::PARAM_FLAG (`version` , `Display the version of mlpack.` , `V`)
PARAM_STRING_IN()
mlpack::bindings::cli::PARAM_STRING_IN (`info` , `Print help on a specific option.` , `` , ``)
ParamString()
std::string mlpack::bindings::cli::ParamString (const std::string & paramName) [inline]
Print what a user would type to invoke the given option name.
Note that the name must exist in the CLI module. (Note that because of the way BINDING_LONG_DESC() and BINDING_EXAMPLE() is structured, this doesn't mean that all of the PARAM_*() declarataions need to come before BINDING_LONG_DESC() and BINDING_EXAMPLE() declaration.)
ParseCommandLine()
void mlpack::bindings::cli::ParseCommandLine (int argc, char ** argv)
Parse the command line, setting all of the options inside of the CLI object to their appropriate given values.
Definition at line 36 of file parse_command_line.hpp.
References Log::Debug, IO::didParse, Log::Fatal, IO::functionMap, IO::GetSingleton(), mlpack::util::GetVersion(), IO::HasParam(), PrefixedOutStream::ignoreInput, Log::Info, IO::Parameters(), PrintHelp(), IO::ProgramName(), ParamData::required, and ParamData::tname.
PrintDataset()
std::string mlpack::bindings::cli::PrintDataset (const std::string & dataset) [inline]
Print a dataset type parameter (add .csv and return).
PrintDefault()
std::string mlpack::bindings::cli::PrintDefault (const std::string & paramName) [inline]
Given a parameter name, print its corresponding default value.
PrintHelp()
void mlpack::bindings::cli::PrintHelp (const std::string & param = ``)
Print the help for the given parameter.
If no parameter is specified, then help will be printed for all parameters.
Parameters
param Parameter name to print help for.
Referenced by ParseCommandLine().
PrintImport()
std::string mlpack::bindings::cli::PrintImport (const std::string & bindingName) [inline]
Print any imports for CLI (there are none, so this returns an empty string).
PrintInputOptionInfo()
std::string mlpack::bindings::cli::PrintInputOptionInfo () [inline]
Print any special information about input options.
PrintModel()
std::string mlpack::bindings::cli::PrintModel (const std::string & model) [inline]
Print a model type parameter (add .bin and return).
PrintOutputOptionInfo()
std::string mlpack::bindings::cli::PrintOutputOptionInfo () [inline]
Print any special information about output options.
PrintType()
std::string mlpack::bindings::cli::PrintType (util::ParamData & param) [inline]
Print the type of a parameter that a user would specify from the command-line.
PrintTypeDoc() [1/6]
std::string mlpack::bindings::cli::PrintTypeDoc (util::ParamData & data, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::disable_if< util::IsStdVector< T >>::type * = 0, const typename boost::disable_if< data::HasSerialize< T >>::type * = 0, const typename boost::disable_if< std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>>::type * = 0)
Return a string representing the command-line type of an option.
PrintTypeDoc() [2/6]
std::string mlpack::bindings::cli::PrintTypeDoc (util::ParamData & data, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::enable_if< data::HasSerialize< T >>::type * = 0)
Return a string representing the command-line type of a model.
PrintTypeDoc() [3/6]
std::string mlpack::bindings::cli::PrintTypeDoc (util::ParamData & data, const typename std::enable_if< arma::is_arma_type< T >::value >::type * = 0)
Return a string representing the command-line type of a matrix option.
PrintTypeDoc() [4/6]
std::string mlpack::bindings::cli::PrintTypeDoc (util::ParamData & data, const typename std::enable_if< std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>::value >::type * = 0)
Return a string representing the command-line type of a matrix tuple option.
PrintTypeDoc() [5/6]
std::string mlpack::bindings::cli::PrintTypeDoc (util::ParamData & data, const typename std::enable_if< util::IsStdVector< T >::value >::type * = 0)
Return a string representing the command-line type of a vector.
PrintTypeDoc() [6/6]
void mlpack::bindings::cli::PrintTypeDoc (util::ParamData & data, const void * , void * output)
Print the command-line type of an option into a string.
Definition at line 72 of file print_type_doc.hpp.
PrintTypeDocs()
std::string mlpack::bindings::cli::PrintTypeDocs () [inline]
Print documentation for each of the types.
PrintValue()
std::string mlpack::bindings::cli::PrintValue (const T & value, bool quotes) [inline]
Given a parameter type, print the corresponding value.
ProcessOptions() [1/2]
std::string mlpack::bindings::cli::ProcessOptions () [inline]
Base case for recursion.
ProcessOptions() [2/2]
std::string mlpack::bindings::cli::ProcessOptions (const std::string & paramName, const T & value, Args... args)
Print an option for a command-line argument.
ProgramCall() [1/2]
std::string mlpack::bindings::cli::ProgramCall (const std::string & programName) [inline]
Given a program name, print a program call invocation assuming that all options are specified.
ProgramCall() [2/2]
std::string mlpack::bindings::cli::ProgramCall (const std::string & programName, Args... args)
Given a program name and arguments for it, print what its invocation would be.
SetParam() [1/5]
void mlpack::bindings::cli::SetParam (util::ParamData & d, const boost::any & , const typename boost::enable_if< std::is_same< T, bool >>::type * = 0)
This overload is called to set a boolean.
Definition at line 44 of file set_param.hpp.
References ParamData::value, and ParamData::wasPassed.
SetParam() [2/5]
void mlpack::bindings::cli::SetParam (util::ParamData & d, const boost::any & value, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::disable_if< data::HasSerialize< T >>::type * = 0, const typename boost::disable_if< std::is_same< T, std::tuple< mlpack::data::DatasetInfo, arma::mat >>>::type * = 0, const typename boost::disable_if< std::is_same< T, bool >>::type * = 0)
This overload is called when nothing special needs to happen to the name of the parameter.
Definition at line 27 of file set_param.hpp.
References ParamData::value.
SetParam() [3/5]
void mlpack::bindings::cli::SetParam (util::ParamData & d, const boost::any & value, const typename boost::disable_if< arma::is_arma_type< T >>::type * = 0, const typename boost::enable_if< data::HasSerialize< T >>::type * = 0)
Set a serializable object.
This sets the filename referring to the parameter.
Definition at line 76 of file set_param.hpp.
References ParamData::value.
SetParam() [4/5]
void mlpack::bindings::cli::SetParam (util::ParamData & d, const boost::any & value, const typename std::enable_if< arma::is_arma_type< T >::value||std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>::value >::type * = 0)
Set a matrix parameter, a matrix/dataset info parameter.
These set the filename referring to the parameter.
Definition at line 58 of file set_param.hpp.
References ParamData::value.
SetParam() [5/5]
void mlpack::bindings::cli::SetParam (util::ParamData & d, const void * input, void *)
Return a parameter casted to the given type.
Type checking does not happen here!
Parameters
d Parameter information.
input Unused parameter.
* (output) Place to store pointer to value.
Definition at line 97 of file set_param.hpp.
StringTypeParam()
void mlpack::bindings::cli::StringTypeParam (util::ParamData & , const void * , void * output)
Return a string containing the type of a parameter.
This overload is used if we don't have a primitive type.
Definition at line 51 of file string_type_param.hpp.
StringTypeParam< bool >()
void mlpack::bindings::cli::StringTypeParam< bool > (util::ParamData & , const void * , void * output) [inline]
Return `bool`.
StringTypeParam< double >()
void mlpack::bindings::cli::StringTypeParam< double > (util::ParamData & , const void * , void * output) [inline]
Return `double`.
StringTypeParam< int >()
void mlpack::bindings::cli::StringTypeParam< int > (util::ParamData & , const void * , void * output) [inline]
Return `int`.
StringTypeParam< std::string >()
void mlpack::bindings::cli::StringTypeParam< std::string > (util::ParamData & , const void * , void * output) [inline]
Return `string`.
StringTypeParam< std::tuple< mlpack::data::DatasetInfo, arma::mat > >()
void mlpack::bindings::cli::StringTypeParam< std::tuple< mlpack::data::DatasetInfo, arma::mat > > (util::ParamData & , const void * , void * output) [inline]
Return `string`;.
StringTypeParamImpl() [1/3]
std::string mlpack::bindings::cli::StringTypeParamImpl (const typename boost::disable_if< util::IsStdVector< T >>::type * = 0, const typename boost::disable_if< data::HasSerialize< T >>::type * = 0)
Return a string containing the type of the parameter.
StringTypeParamImpl() [2/3]
std::string mlpack::bindings::cli::StringTypeParamImpl (const typename boost::enable_if< data::HasSerialize< T >>::type * = 0)
Return a string containing the type of the parameter,.
StringTypeParamImpl() [3/3]
std::string mlpack::bindings::cli::StringTypeParamImpl (const typename boost::enable_if< util::IsStdVector< T >>::type * = 0)
Return a string containing the type of the parameter, for vector options.