mlpack Namespace Reference
Linear algebra utility functions, generally performed on matrices or vectors.
Namespaces
  adaboost
  amf
Alternating Matrix Factorization.
  ann
Artificial Neural Network.
  bound
  cf
Collaborative filtering.
  cv
  data
Functions to load and save matrices and models.
  dbscan
  det
Density Estimation Trees.
  distribution
Probability distributions.
  emst
Euclidean Minimum Spanning Trees.
  fastmks
Fast max-kernel search.
  gmm
Gaussian Mixture Models.
  hmm
Hidden Markov Models.
  hpt
  kde
Kernel Density Estimation.
  kernel
Kernel functions.
  kmeans
K-Means clustering.
  kpca
  lcc
  lmnn
Large Margin Nearest Neighbor.
  math
Miscellaneous math routines.
  matrix_completion
  meanshift
Mean shift clustering.
  metric
  mvu
  naive_bayes
The Naive Bayes Classifier.
  nca
Neighborhood Components Analysis.
  neighbor
  nn
  pca
  perceptron
  radical
  range
Range-search routines.
  regression
Regression methods.
  rl
  sfinae
  sparse_coding
  svd
  svm
  tree
Trees and tree-building procedures.
  util
Classes
class Backtrace
Provides a backtrace.
class IO
Parses the command line for parameters and holds user-specified parameters.
class Timer
The timer class provides a way for mlpack methods to be timed.
class Timers
Functions
void CheckMatrices (const arma::mat &x, const arma::mat &xmlX, const arma::mat &jsonX, const arma::mat &binaryX)
void CheckMatrices (const arma::Mat< size_t > &x, const arma::Mat< size_t > &xmlX, const arma::Mat< size_t > &jsonX, const arma::Mat< size_t > &binaryX)
void CheckMatrices (const arma::cube &x, const arma::cube &xmlX, const arma::cube &jsonX, const arma::cube &binaryX)
template<typename T , typename IArchiveType , typename OArchiveType >
void SerializeObject (T &t, T &newT)
template<typename T >
void SerializeObjectAll (T &t, T &xmlT, T &jsonT, T &binaryT)
template<typename T , typename IArchiveType , typename OArchiveType >
void SerializePointerObject (T *t, T *&newT)
template<typename T >
void SerializePointerObjectAll (T *t, T *&xmlT, T *&jsonT, T *&binaryT)
template<typename CubeType >
void TestAllArmadilloSerialization (arma::Cube< CubeType > &x)
template<typename MatType >
void TestAllArmadilloSerialization (MatType &x)
template<typename CubeType , typename IArchiveType , typename OArchiveType >
void TestArmadilloSerialization (arma::Cube< CubeType > &x)
template<typename MatType , typename IArchiveType , typename OArchiveType >
void TestArmadilloSerialization (MatType &x)
Detailed Description
Linear algebra utility functions, generally performed on matrices or vectors.
This class is used to update the weightVectors matrix according to the simple update rule as discussed by Rosenblatt:
if a vector x has been incorrectly classified by a weight w, then w = w - x and w'= w'+ x
where w' is the weight vector which correctly classifies x.
Function Documentation
CheckMatrices() [1/3]
void mlpack::CheckMatrices (const arma::mat & x, const arma::mat & xmlX, const arma::mat & jsonX, const arma::mat & binaryX)
Referenced by SerializePointerObjectAll().
CheckMatrices() [2/3]
void mlpack::CheckMatrices (const arma::Mat< size_t > & x, const arma::Mat< size_t > & xmlX, const arma::Mat< size_t > & jsonX, const arma::Mat< size_t > & binaryX)
CheckMatrices() [3/3]
void mlpack::CheckMatrices (const arma::cube & x, const arma::cube & xmlX, const arma::cube & jsonX, const arma::cube & binaryX)
SerializeObject()
void mlpack::SerializeObject (T & t, T & newT)
Definition at line 145 of file serialization.hpp.
References mlpack::data::binary, and FilterFileName().
Referenced by SerializeObjectAll().
SerializeObjectAll()
void mlpack::SerializeObjectAll (T & t, T & xmlT, T & jsonT, T & binaryT)
Definition at line 172 of file serialization.hpp.
References SerializeObject().
SerializePointerObject()
void mlpack::SerializePointerObject (T * t, T *& newT)
Definition at line 184 of file serialization.hpp.
References mlpack::data::binary, CEREAL_POINTER, and FilterFileName().
Referenced by SerializePointerObjectAll().
SerializePointerObjectAll()
void mlpack::SerializePointerObjectAll (T * t, T *& xmlT, T *& jsonT, T *& binaryT)
Definition at line 206 of file serialization.hpp.
References CheckMatrices(), and SerializePointerObject().
TestAllArmadilloSerialization() [1/2]
void mlpack::TestAllArmadilloSerialization (arma::Cube< CubeType > & x)
Definition at line 78 of file serialization.hpp.
References TestArmadilloSerialization().
TestAllArmadilloSerialization() [2/2]
void mlpack::TestAllArmadilloSerialization (MatType & x)
Definition at line 132 of file serialization.hpp.
References TestArmadilloSerialization().
TestArmadilloSerialization() [1/2]
void mlpack::TestArmadilloSerialization (arma::Cube< CubeType > & x)
Definition at line 26 of file serialization.hpp.
References mlpack::data::binary, and FilterFileName().
Referenced by TestAllArmadilloSerialization().
TestArmadilloSerialization() [2/2]
void mlpack::TestArmadilloSerialization (MatType & x)
Definition at line 92 of file serialization.hpp.
References mlpack::data::binary, and FilterFileName().