load_visitor< T > Struct Template Reference
Static Public Member Functions
template<typename Archive , typename VariantType >
static void load (Archive &ar, VariantType &variant)
template<typename Archive , typename VariantType >
static void load_impl (Archive &ar, VariantType &value, std::false_type)
template<typename Archive , typename VariantType >
static void load_impl (Archive &ar, VariantType &variant, std::true_type)
Detailed Description
template<typename T>
struct cereal::load_visitor< T >
Definition at line 68 of file pointer_variant_wrapper.hpp.
Member Function Documentation
load()
static void load (Archive & ar, VariantType & variant) [inline], [static]
Definition at line 89 of file pointer_variant_wrapper.hpp.
References load_visitor< T >::load_impl().
load_impl() [1/2]
static void load_impl (Archive & ar, VariantType & value, std::false_type) [inline], [static]
Definition at line 80 of file pointer_variant_wrapper.hpp.
References cereal::make_pointer_variant().
load_impl() [2/2]
static void load_impl (Archive & ar, VariantType & variant, std::true_type) [inline], [static]
Definition at line 71 of file pointer_variant_wrapper.hpp.
References CEREAL_POINTER.
Referenced by load_visitor< T >::load().
The documentation for this struct was generated from the following file:
/home/aakash/mlpack/src/mlpack/core/cereal/ pointer_variant_wrapper.hpp