InitHMMModel Struct Reference
Static Public Member Functions
template<typename HMMType >
static void Apply (HMMType &hmm, vector< mat > *trainSeq)
static void Create (HMM< DiagonalGMM > &hmm, vector< mat > &trainSeq, size_t states, double tolerance=1e-05)
Helper function to create Diagonal GMM HMM.
static void Create (HMM< DiscreteDistribution > &hmm, vector< mat > &trainSeq, size_t states, double tolerance=1e-05)
Helper function to create discrete HMM.
static void Create (HMM< GaussianDistribution > &hmm, vector< mat > &trainSeq, size_t states, double tolerance=1e-05)
static void Create (HMM< GMM > &hmm, vector< mat > &trainSeq, size_t states, double tolerance=1e-05)
static void RandomInitialize (vector< DiagonalGMM > &e)
Helper function for diagonal GMM emission distributions.
static void RandomInitialize (vector< DiscreteDistribution > &e)
Helper function for discrete emission distributions.
static void RandomInitialize (vector< GaussianDistribution > &e)
static void RandomInitialize (vector< GMM > &e)
Detailed Description
Definition at line 21 of file hmm_test_utils.hpp.
Member Function Documentation
Apply()
static void Apply (HMMType & hmm, vector< mat > * trainSeq) [inline], [static]
Definition at line 24 of file hmm_test_utils.hpp.
References Create(), and RandomInitialize().
Create() [1/4]
static void Create (HMM< DiagonalGMM > & hmm, vector< mat > & trainSeq, size_t states, double tolerance = 1e-05) [inline], [static]
Helper function to create Diagonal GMM HMM.
Definition at line 109 of file hmm_test_utils.hpp.
Create() [2/4]
static void Create (HMM< DiscreteDistribution > & hmm, vector< mat > & trainSeq, size_t states, double tolerance = 1e-05) [inline], [static]
Helper function to create discrete HMM.
Definition at line 37 of file hmm_test_utils.hpp.
Referenced by Apply().
Create() [3/4]
static void Create (HMM< GaussianDistribution > & hmm, vector< mat > & trainSeq, size_t states, double tolerance = 1e-05) [inline], [static]
Definition at line 58 of file hmm_test_utils.hpp.
Create() [4/4]
static void Create (HMM< GMM > & hmm, vector< mat > & trainSeq, size_t states, double tolerance = 1e-05) [inline], [static]
Definition at line 82 of file hmm_test_utils.hpp.
RandomInitialize() [1/4]
static void RandomInitialize (vector< DiagonalGMM > & e) [inline], [static]
Helper function for diagonal GMM emission distributions.
Definition at line 180 of file hmm_test_utils.hpp.
RandomInitialize() [2/4]
static void RandomInitialize (vector< DiscreteDistribution > & e) [inline], [static]
Helper function for discrete emission distributions.
Definition at line 136 of file hmm_test_utils.hpp.
Referenced by Apply().
RandomInitialize() [3/4]
static void RandomInitialize (vector< GaussianDistribution > & e) [inline], [static]
Definition at line 145 of file hmm_test_utils.hpp.
RandomInitialize() [4/4]
static void RandomInitialize (vector< GMM > & e) [inline], [static]
Definition at line 157 of file hmm_test_utils.hpp.
The documentation for this struct was generated from the following file:
/home/aakash/mlpack/src/mlpack/tests/main_tests/ hmm_test_utils.hpp