/home/aakash/mlpack/src/mlpack/tests/test_catch_tools.hpp File Reference
Macros
#define REQUIRE_RELATIVE_ERR(L, R, E) REQUIRE(std::abs((R) - (L)) <= (E) * std::abs(R))
Functions
template<typename FieldType , typename = std::enable_if_t< arma::is_arma_type<typename FieldType::object_type>::value>>
void CheckFields (const FieldType &a, const FieldType &b)
void CheckMatrices (const arma::cube &a, const arma::cube &b, double tolerance=1e-5)
void CheckMatrices (const arma::mat &a, const arma::mat &b, double tolerance=1e-5)
void CheckMatrices (const arma::Mat< size_t > &a, const arma::Mat< size_t > &b)
void CheckMatricesNotEqual (const arma::cube &a, const arma::cube &b, double tolerance=1e-5)
void CheckMatricesNotEqual (const arma::mat &a, const arma::mat &b, double tolerance=1e-5)
void CheckMatricesNotEqual (const arma::Mat< size_t > &a, const arma::Mat< size_t > &b)
std::string FilterFileName (const std::string &inputString)
Detailed Description
Author
Ryan Curtin
This file includes some useful macros for tests.
mlpack is free software; you may redistribute it and/or modify it under the terms of the 3-clause BSD license. You should have received a copy of the 3-clause BSD license along with mlpack. If not, see http://www.opensource.org/licenses/BSD-3-Clause for more information.
Macro Definition Documentation
REQUIRE_RELATIVE_ERR
#define REQUIRE_RELATIVE_ERR(L, R, E) REQUIRE(std::abs((R) - (L)) <= (E) * std::abs(R))
Definition at line 22 of file test_catch_tools.hpp.
Function Documentation
CheckFields()
void CheckFields (const FieldType & a, const FieldType & b) [inline]
Definition at line 57 of file test_catch_tools.hpp.
References CheckMatrices().
CheckMatrices() [1/3]
void CheckMatrices (const arma::cube & a, const arma::cube & b, double tolerance = 1e-5) [inline]
Definition at line 68 of file test_catch_tools.hpp.
CheckMatrices() [2/3]
void CheckMatrices (const arma::mat & a, const arma::mat & b, double tolerance = 1e-5) [inline]
Definition at line 26 of file test_catch_tools.hpp.
Referenced by CheckFields().
CheckMatrices() [3/3]
void CheckMatrices (const arma::Mat< size_t > & a, const arma::Mat< size_t > & b) [inline]
Definition at line 43 of file test_catch_tools.hpp.
CheckMatricesNotEqual() [1/3]
void CheckMatricesNotEqual (const arma::cube & a, const arma::cube & b, double tolerance = 1e-5) [inline]
Definition at line 143 of file test_catch_tools.hpp.
CheckMatricesNotEqual() [2/3]
void CheckMatricesNotEqual (const arma::mat & a, const arma::mat & b, double tolerance = 1e-5) [inline]
Definition at line 86 of file test_catch_tools.hpp.
CheckMatricesNotEqual() [3/3]
void CheckMatricesNotEqual (const arma::Mat< size_t > & a, const arma::Mat< size_t > & b) [inline]
Definition at line 118 of file test_catch_tools.hpp.
FilterFileName()
std::string FilterFileName (const std::string & inputString) [inline]
Definition at line 176 of file test_catch_tools.hpp.
Referenced by mlpack::SerializeObject(), mlpack::SerializePointerObject(), and mlpack::TestArmadilloSerialization().