/net/hc292/nadeem/fastlib/u/nadeem/parallel-em/parallel_em: /net/hc292/nadeem/fastlib/u/nadeem/parallel-em/Makefile /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/u/nadeem/parallel-em/parallel_em
	@echo '... Making /net/hc292/nadeem/fastlib/u/nadeem/parallel-em/parallel_em'
	@rm -f /net/hc292/nadeem/fastlib/u/nadeem/parallel-em/parallel_em
	@ln -s -f /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/u/nadeem/parallel-em/parallel_em /net/hc292/nadeem/fastlib/u/nadeem/parallel-em/parallel_em
	@echo '*** Created 1 symlinks in /net/hc292/nadeem/fastlib/u/nadeem/parallel-em/.'
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/u/nadeem/parallel-em/parallel_em: /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libmath_math.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libbase_base.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libfile_file.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libcol_col.a /net/hc292/nadeem/fastlib/bin_keep/x86_64_Linux_COMMON_mpi_COMMON/libblaspack.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libfx_fx.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libu_nadeem_parallel-em_parallel_em__auto.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libdata_data.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libla_la.a
	@echo '... Making bin/x86_64_Linux_check_mpi_/u/nadeem/parallel-em/parallel_em'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/u/nadeem/parallel-em
	@mpiCC -o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/u/nadeem/parallel-em/parallel_em -O2 -g -DDEBUG  /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libu_nadeem_parallel-em_parallel_em__auto.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libmath_math.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libdata_data.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libfile_file.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libfx_fx.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libla_la.a /net/hc292/nadeem/fastlib/bin_keep/x86_64_Linux_COMMON_mpi_COMMON/libblaspack.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libcol_col.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libbase_base.a -lm -lpthread -lg2c
pseudo_4: /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libmath_math.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libbase_base.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libfile_file.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libcol_col.a /net/hc292/nadeem/fastlib/bin_keep/x86_64_Linux_COMMON_mpi_COMMON/libblaspack.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libfx_fx.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libu_nadeem_parallel-em_parallel_em__auto.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libdata_data.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libla_la.a
	@echo '*** Done with /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libmath_math.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libbase_base.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libfile_file.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libcol_col.a /net/hc292/nadeem/fastlib/bin_keep/x86_64_Linux_COMMON_mpi_COMMON/libblaspack.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libfx_fx.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libu_nadeem_parallel-em_parallel_em__auto.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libdata_data.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libla_la.a'
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libu_nadeem_parallel-em_parallel_em__auto.a: /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/u_nadeem_parallel-em_fl_kmeans.o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/u_nadeem_parallel-em_fl_par_em.o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/u_nadeem_parallel-em_fl_data_io.o
	@echo '... Making bin/x86_64_Linux_check_mpi_/libu_nadeem_parallel-em_parallel_em__auto.a'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_
	@ar r /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libu_nadeem_parallel-em_parallel_em__auto.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/u_nadeem_parallel-em_fl_par_em.o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/u_nadeem_parallel-em_fl_data_io.o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/u_nadeem_parallel-em_fl_kmeans.o
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/u_nadeem_parallel-em_fl_kmeans.o: /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libfastlib_fastlib.h /net/hc292/nadeem/fastlib/u/nadeem/parallel-em/fl_par_em.h /net/hc292/nadeem/fastlib/u/nadeem/parallel-em/fl_data_io.h /net/hc292/nadeem/fastlib/u/nadeem/parallel-em/fl_kmeans.h /net/hc292/nadeem/fastlib/u/nadeem/parallel-em/fl_kmeans.cc
	@echo '... Making bin/x86_64_Linux_check_mpi_/obj/u_nadeem_parallel-em_fl_kmeans.o'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj
	@cd /net/hc292/nadeem/fastlib/u/nadeem/parallel-em && mpiCC -fno-exceptions -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_ -I/net/hc292/nadeem/fastlib -O2 -g -DDEBUG   -c fl_kmeans.cc -o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/u_nadeem_parallel-em_fl_kmeans.o
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/u_nadeem_parallel-em_fl_data_io.o: /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libfastlib_fastlib.h /net/hc292/nadeem/fastlib/u/nadeem/parallel-em/fl_par_em.h /net/hc292/nadeem/fastlib/u/nadeem/parallel-em/fl_data_io.cc /net/hc292/nadeem/fastlib/u/nadeem/parallel-em/fl_data_io.h /net/hc292/nadeem/fastlib/u/nadeem/parallel-em/fl_kmeans.h
	@echo '... Making bin/x86_64_Linux_check_mpi_/obj/u_nadeem_parallel-em_fl_data_io.o'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj
	@cd /net/hc292/nadeem/fastlib/u/nadeem/parallel-em && mpiCC -fno-exceptions -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_ -I/net/hc292/nadeem/fastlib -O2 -g -DDEBUG   -c fl_data_io.cc -o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/u_nadeem_parallel-em_fl_data_io.o
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/u_nadeem_parallel-em_fl_par_em.o: /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libfastlib_fastlib.h /net/hc292/nadeem/fastlib/u/nadeem/parallel-em/fl_par_em.h /net/hc292/nadeem/fastlib/u/nadeem/parallel-em/fl_par_em.cc /net/hc292/nadeem/fastlib/u/nadeem/parallel-em/fl_data_io.h /net/hc292/nadeem/fastlib/u/nadeem/parallel-em/fl_kmeans.h
	@echo '... Making bin/x86_64_Linux_check_mpi_/obj/u_nadeem_parallel-em_fl_par_em.o'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj
	@cd /net/hc292/nadeem/fastlib/u/nadeem/parallel-em && mpiCC -fno-exceptions -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_ -I/net/hc292/nadeem/fastlib -O2 -g -DDEBUG   -c fl_par_em.cc -o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/u_nadeem_parallel-em_fl_par_em.o
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libfastlib_fastlib.h: /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libmath_math.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libla_la.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libfx_fx.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libdata_data.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libbase_base.h /net/hc292/nadeem/fastlib/fastlib/fastlib.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libfile_file.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libcol_col.h
	@echo '... Making bin/x86_64_Linux_COMMON_mpi_COMMON/libfastlib_fastlib.h'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON
	@touch /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libfastlib_fastlib.h
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libmath_math.h: /net/hc292/nadeem/fastlib/math/kernel.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libbase_base.h /net/hc292/nadeem/fastlib/math/geometry.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libcol_col.h /net/hc292/nadeem/fastlib/math/math.h /net/hc292/nadeem/fastlib/math/discrete.h
	@echo '... Making bin/x86_64_Linux_COMMON_mpi_COMMON/libmath_math.h'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON
	@touch /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libmath_math.h
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libdata_data.h: /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libfile_file.h /net/hc292/nadeem/fastlib/data/dataset.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libbase_base.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libla_la.h /net/hc292/nadeem/fastlib/data/crossvalidation.h
	@echo '... Making bin/x86_64_Linux_COMMON_mpi_COMMON/libdata_data.h'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON
	@touch /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libdata_data.h
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libfx_fx.h: /net/hc292/nadeem/fastlib/fx/datastore.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libbase_base.h /net/hc292/nadeem/fastlib/fx/timer.h /net/hc292/nadeem/fastlib/fx/fx.h
	@echo '... Making bin/x86_64_Linux_COMMON_mpi_COMMON/libfx_fx.h'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON
	@touch /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libfx_fx.h
pseudo_20: /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libmath_math.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libbase_base.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libfile_file.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libcol_col.a /net/hc292/nadeem/fastlib/bin_keep/x86_64_Linux_COMMON_mpi_COMMON/libblaspack.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libfx_fx.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libdata_data.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libla_la.a
	@echo '*** Done with /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libmath_math.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libbase_base.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libfile_file.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libcol_col.a /net/hc292/nadeem/fastlib/bin_keep/x86_64_Linux_COMMON_mpi_COMMON/libblaspack.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libfx_fx.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libdata_data.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libla_la.a'
pseudo_22: /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libcol_col.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libbase_base.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libmath_math.a
	@echo '*** Done with /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libcol_col.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libbase_base.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libmath_math.a'
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libmath_math.a: /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/math_geometry.o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/math_discrete.o
	@echo '... Making bin/x86_64_Linux_check_mpi_/libmath_math.a'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_
	@ar r /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libmath_math.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/math_discrete.o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/math_geometry.o
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/math_geometry.o: /net/hc292/nadeem/fastlib/math/geometry.cc /net/hc292/nadeem/fastlib/math/kernel.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libbase_base.h /net/hc292/nadeem/fastlib/math/geometry.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libcol_col.h /net/hc292/nadeem/fastlib/math/math.h /net/hc292/nadeem/fastlib/math/discrete.h
	@echo '... Making bin/x86_64_Linux_check_mpi_/obj/math_geometry.o'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj
	@cd /net/hc292/nadeem/fastlib/math && mpiCC -fno-exceptions -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_ -I/net/hc292/nadeem/fastlib -O2 -g -DDEBUG   -c geometry.cc -o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/math_geometry.o
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/math_discrete.o: /net/hc292/nadeem/fastlib/math/kernel.h /net/hc292/nadeem/fastlib/math/discrete.cc /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libbase_base.h /net/hc292/nadeem/fastlib/math/geometry.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libcol_col.h /net/hc292/nadeem/fastlib/math/math.h /net/hc292/nadeem/fastlib/math/discrete.h
	@echo '... Making bin/x86_64_Linux_check_mpi_/obj/math_discrete.o'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj
	@cd /net/hc292/nadeem/fastlib/math && mpiCC -fno-exceptions -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_ -I/net/hc292/nadeem/fastlib -O2 -g -DDEBUG   -c discrete.cc -o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/math_discrete.o
pseudo_32: /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libbase_base.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libfile_file.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libcol_col.a /net/hc292/nadeem/fastlib/bin_keep/x86_64_Linux_COMMON_mpi_COMMON/libblaspack.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libdata_data.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libla_la.a
	@echo '*** Done with /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libbase_base.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libfile_file.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libcol_col.a /net/hc292/nadeem/fastlib/bin_keep/x86_64_Linux_COMMON_mpi_COMMON/libblaspack.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libdata_data.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libla_la.a'
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libdata_data.a: /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/data_dataset.o
	@echo '... Making bin/x86_64_Linux_check_mpi_/libdata_data.a'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_
	@ar r /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libdata_data.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/data_dataset.o
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/data_dataset.o: /net/hc292/nadeem/fastlib/data/crossvalidation.h /net/hc292/nadeem/fastlib/data/dataset.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libla_la.h /net/hc292/nadeem/fastlib/data/dataset.cc /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libbase_base.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libfile_file.h
	@echo '... Making bin/x86_64_Linux_check_mpi_/obj/data_dataset.o'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj
	@cd /net/hc292/nadeem/fastlib/data && mpiCC -fno-exceptions -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_ -I/net/hc292/nadeem/fastlib -O2 -g -DDEBUG   -c dataset.cc -o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/data_dataset.o
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libla_la.h: /net/hc292/nadeem/fastlib/la/clapack.h /net/hc292/nadeem/fastlib/la/matrix.h /net/hc292/nadeem/fastlib/la/blas.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libbase_base.h /net/hc292/nadeem/fastlib/la/uselapack.h /net/hc292/nadeem/fastlib/la/la.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libcol_col.h
	@echo '... Making bin/x86_64_Linux_COMMON_mpi_COMMON/libla_la.h'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON
	@touch /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libla_la.h
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libfile_file.h: /net/hc292/nadeem/fastlib/file/textfile.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libbase_base.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libcol_col.h /net/hc292/nadeem/fastlib/file/serialize.h
	@echo '... Making bin/x86_64_Linux_COMMON_mpi_COMMON/libfile_file.h'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON
	@touch /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libfile_file.h
pseudo_40: /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libcol_col.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libbase_base.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libfile_file.a
	@echo '*** Done with /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libcol_col.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libbase_base.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libfile_file.a'
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libfile_file.a: /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/file_textfile.o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/file_serialize.o
	@echo '... Making bin/x86_64_Linux_check_mpi_/libfile_file.a'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_
	@ar r /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libfile_file.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/file_textfile.o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/file_serialize.o
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/file_serialize.o: /net/hc292/nadeem/fastlib/file/textfile.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libbase_base.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libcol_col.h /net/hc292/nadeem/fastlib/file/serialize.cc /net/hc292/nadeem/fastlib/file/serialize.h
	@echo '... Making bin/x86_64_Linux_check_mpi_/obj/file_serialize.o'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj
	@cd /net/hc292/nadeem/fastlib/file && mpiCC -fno-exceptions -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_ -I/net/hc292/nadeem/fastlib -O2 -g -DDEBUG   -c serialize.cc -o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/file_serialize.o
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/file_textfile.o: /net/hc292/nadeem/fastlib/file/textfile.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libbase_base.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libcol_col.h /net/hc292/nadeem/fastlib/file/serialize.h /net/hc292/nadeem/fastlib/file/textfile.cc
	@echo '... Making bin/x86_64_Linux_check_mpi_/obj/file_textfile.o'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj
	@cd /net/hc292/nadeem/fastlib/file && mpiCC -fno-exceptions -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_ -I/net/hc292/nadeem/fastlib -O2 -g -DDEBUG   -c textfile.cc -o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/file_textfile.o
pseudo_48: /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libfx_fx.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libbase_base.a
	@echo '*** Done with /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libfx_fx.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libbase_base.a'
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libfx_fx.a: /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/fx_timer.o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/fx_fx.o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/fx_datastore.o
	@echo '... Making bin/x86_64_Linux_check_mpi_/libfx_fx.a'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_
	@ar r /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libfx_fx.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/fx_datastore.o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/fx_timer.o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/fx_fx.o
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/fx_fx.o: /net/hc292/nadeem/fastlib/fx/datastore.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libbase_base.h /net/hc292/nadeem/fastlib/fx/timer.h /net/hc292/nadeem/fastlib/fx/fx.c /net/hc292/nadeem/fastlib/fx/fx.h
	@echo '... Making bin/x86_64_Linux_check_mpi_/obj/fx_fx.o'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj
	@cd /net/hc292/nadeem/fastlib/fx && mpicc -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_ -I/net/hc292/nadeem/fastlib -O2 -g -DDEBUG   -c fx.c -o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/fx_fx.o
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/fx_timer.o: /net/hc292/nadeem/fastlib/fx/datastore.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libbase_base.h /net/hc292/nadeem/fastlib/fx/timer.h /net/hc292/nadeem/fastlib/fx/timer.c /net/hc292/nadeem/fastlib/fx/fx.h
	@echo '... Making bin/x86_64_Linux_check_mpi_/obj/fx_timer.o'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj
	@cd /net/hc292/nadeem/fastlib/fx && mpicc -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_ -I/net/hc292/nadeem/fastlib -O2 -g -DDEBUG   -c timer.c -o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/fx_timer.o
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/fx_datastore.o: /net/hc292/nadeem/fastlib/fx/datastore.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libbase_base.h /net/hc292/nadeem/fastlib/fx/timer.h /net/hc292/nadeem/fastlib/fx/datastore.c /net/hc292/nadeem/fastlib/fx/fx.h
	@echo '... Making bin/x86_64_Linux_check_mpi_/obj/fx_datastore.o'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj
	@cd /net/hc292/nadeem/fastlib/fx && mpicc -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_ -I/net/hc292/nadeem/fastlib -O2 -g -DDEBUG   -c datastore.c -o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/fx_datastore.o
pseudo_59: /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libcol_col.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libbase_base.a /net/hc292/nadeem/fastlib/bin_keep/x86_64_Linux_COMMON_mpi_COMMON/libblaspack.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libla_la.a
	@echo '*** Done with /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libcol_col.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libbase_base.a /net/hc292/nadeem/fastlib/bin_keep/x86_64_Linux_COMMON_mpi_COMMON/libblaspack.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libla_la.a'
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libla_la.a: /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/la_uselapack.o
	@echo '... Making bin/x86_64_Linux_check_mpi_/libla_la.a'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_
	@ar r /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libla_la.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/la_uselapack.o
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/la_uselapack.o: /net/hc292/nadeem/fastlib/la/clapack.h /net/hc292/nadeem/fastlib/la/matrix.h /net/hc292/nadeem/fastlib/la/blas.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libbase_base.h /net/hc292/nadeem/fastlib/la/uselapack.cc /net/hc292/nadeem/fastlib/la/uselapack.h /net/hc292/nadeem/fastlib/la/la.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libcol_col.h
	@echo '... Making bin/x86_64_Linux_check_mpi_/obj/la_uselapack.o'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj
	@cd /net/hc292/nadeem/fastlib/la && mpiCC -fno-exceptions -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_ -I/net/hc292/nadeem/fastlib -O2 -g -DDEBUG   -c uselapack.cc -o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/la_uselapack.o
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libcol_col.h: /net/hc292/nadeem/fastlib/col/fastalloc.h /net/hc292/nadeem/fastlib/col/string.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libbase_base.h /net/hc292/nadeem/fastlib/col/heap.h /net/hc292/nadeem/fastlib/col/arraylist.h
	@echo '... Making bin/x86_64_Linux_COMMON_mpi_COMMON/libcol_col.h'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON
	@touch /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libcol_col.h
/net/hc292/nadeem/fastlib/bin_keep/x86_64_Linux_COMMON_mpi_COMMON/libblaspack.a: /net/hc292/nadeem/fastlib/la/blaspack.tgz
	@echo '... Making /net/hc292/nadeem/fastlib/bin_keep/x86_64_Linux_COMMON_mpi_COMMON/libblaspack.a'
	@mkdir -p /net/hc292/nadeem/fastlib/bin_keep/x86_64_Linux_COMMON_mpi_COMMON
	@echo '... Extracting FORTRAN files...'
	@mkdir -p /net/hc292/nadeem/fastlib/bin_keep/x86_64_Linux_COMMON_mpi_COMMON/libblaspack_workspace
	@cd /net/hc292/nadeem/fastlib/bin_keep/x86_64_Linux_COMMON_mpi_COMMON/libblaspack_workspace && tar -xzf /net/hc292/nadeem/fastlib/la/blaspack.tgz
	@echo '*** Compiling LAPACK with BLAS reference implementation.'
	@echo '... Our compilation differs slightly from regular LAPACK/BLAS:'
	@echo '... NOTE 1: We omit complex-number routines (halves compile time).'
	@echo '... NOTE 2: We require case sensitivity for LAPACK/BLAS string parameters.'
	@echo '... This may take several minutes (about 800 FORTRAN files).'
	@cd /net/hc292/nadeem/fastlib/bin_keep/x86_64_Linux_COMMON_mpi_COMMON/libblaspack_workspace && mpif77 -O2 -c src/*.f
	@echo '... Almost done with LAPACK/BLAS...'
	@cd /net/hc292/nadeem/fastlib/bin_keep/x86_64_Linux_COMMON_mpi_COMMON/libblaspack_workspace && mpif77 -O0 -c src/dlamch.f src/slamch.f
	@cd /net/hc292/nadeem/fastlib/bin_keep/x86_64_Linux_COMMON_mpi_COMMON/libblaspack_workspace && ar r /net/hc292/nadeem/fastlib/bin_keep/x86_64_Linux_COMMON_mpi_COMMON/libblaspack.a *.o
	@echo '... Created archive, cleaning up.'
	@rm -rf /net/hc292/nadeem/fastlib/bin_keep/x86_64_Linux_COMMON_mpi_COMMON/libblaspack_workspace
	@echo '*** Done with LAPACK and BLAS!'
/net/hc292/nadeem/fastlib/la/blaspack.tgz: 
	@echo '... Making /net/hc292/nadeem/fastlib/la/blaspack.tgz'
	@echo 'Downloading the file using curl...'
	@cd /net/hc292/nadeem/fastlib/la && curl -L -o blaspack.tgz "http://www.cc.gatech.edu/~garryb/fastlib/blaspack.tgz"
pseudo_71: /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libcol_col.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libbase_base.a
	@echo '*** Done with /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libcol_col.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libbase_base.a'
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libcol_col.a: /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/col_col.o
	@echo '... Making bin/x86_64_Linux_check_mpi_/libcol_col.a'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_
	@ar r /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libcol_col.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/col_col.o
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/col_col.o: /net/hc292/nadeem/fastlib/col/fastalloc.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libbase_base.h /net/hc292/nadeem/fastlib/col/arraylist.h /net/hc292/nadeem/fastlib/col/string.h /net/hc292/nadeem/fastlib/col/col.cc /net/hc292/nadeem/fastlib/col/heap.h
	@echo '... Making bin/x86_64_Linux_check_mpi_/obj/col_col.o'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj
	@cd /net/hc292/nadeem/fastlib/col && mpiCC -fno-exceptions -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_ -I/net/hc292/nadeem/fastlib -O2 -g -DDEBUG   -c col.cc -o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/col_col.o
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libbase_base.h: /net/hc292/nadeem/fastlib/base/compiler_impl.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/base/basic_types.h /net/hc292/nadeem/fastlib/base/common.h /net/hc292/nadeem/fastlib/base/cc.h /net/hc292/nadeem/fastlib/base/debug.h /net/hc292/nadeem/fastlib/base/compiler.h /net/hc292/nadeem/fastlib/base/scale.h /net/hc292/nadeem/fastlib/base/ccmem.h /net/hc292/nadeem/fastlib/base/fortran.h /net/hc292/nadeem/fastlib/base/otrav.h /net/hc292/nadeem/fastlib/base/test.h
	@echo '... Making bin/x86_64_Linux_COMMON_mpi_COMMON/libbase_base.h'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON
	@touch /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/libbase_base.h
pseudo_80: /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libbase_base.a
	@echo '*** Done with /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libbase_base.a'
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libbase_base.a: /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/base_cc.o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/base_otrav.o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/base_common.o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/base_ccmem.o
	@echo '... Making bin/x86_64_Linux_check_mpi_/libbase_base.a'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_
	@ar r /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/libbase_base.a /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/base_common.o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/base_cc.o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/base_ccmem.o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/base_otrav.o
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/base_otrav.o: /net/hc292/nadeem/fastlib/base/otrav.cc /net/hc292/nadeem/fastlib/base/compiler_impl.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/base/basic_types.h /net/hc292/nadeem/fastlib/base/common.h /net/hc292/nadeem/fastlib/base/cc.h /net/hc292/nadeem/fastlib/base/debug.h /net/hc292/nadeem/fastlib/base/compiler.h /net/hc292/nadeem/fastlib/base/scale.h /net/hc292/nadeem/fastlib/base/ccmem.h /net/hc292/nadeem/fastlib/base/fortran.h /net/hc292/nadeem/fastlib/base/otrav.h /net/hc292/nadeem/fastlib/base/test.h
	@echo '... Making bin/x86_64_Linux_check_mpi_/obj/base_otrav.o'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj
	@cd /net/hc292/nadeem/fastlib/base && mpiCC -fno-exceptions -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_ -I/net/hc292/nadeem/fastlib -O2 -g -DDEBUG   -c otrav.cc -o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/base_otrav.o
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/base_ccmem.o: /net/hc292/nadeem/fastlib/base/compiler_impl.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/base/basic_types.h /net/hc292/nadeem/fastlib/base/common.h /net/hc292/nadeem/fastlib/base/cc.h /net/hc292/nadeem/fastlib/base/debug.h /net/hc292/nadeem/fastlib/base/compiler.h /net/hc292/nadeem/fastlib/base/scale.h /net/hc292/nadeem/fastlib/base/ccmem.h /net/hc292/nadeem/fastlib/base/ccmem.cc /net/hc292/nadeem/fastlib/base/fortran.h /net/hc292/nadeem/fastlib/base/otrav.h /net/hc292/nadeem/fastlib/base/test.h
	@echo '... Making bin/x86_64_Linux_check_mpi_/obj/base_ccmem.o'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj
	@cd /net/hc292/nadeem/fastlib/base && mpiCC -fno-exceptions -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_ -I/net/hc292/nadeem/fastlib -O2 -g -DDEBUG   -c ccmem.cc -o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/base_ccmem.o
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/base_cc.o: /net/hc292/nadeem/fastlib/base/compiler_impl.h /net/hc292/nadeem/fastlib/base/cc.cc /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/base/basic_types.h /net/hc292/nadeem/fastlib/base/common.h /net/hc292/nadeem/fastlib/base/cc.h /net/hc292/nadeem/fastlib/base/debug.h /net/hc292/nadeem/fastlib/base/compiler.h /net/hc292/nadeem/fastlib/base/scale.h /net/hc292/nadeem/fastlib/base/ccmem.h /net/hc292/nadeem/fastlib/base/fortran.h /net/hc292/nadeem/fastlib/base/otrav.h /net/hc292/nadeem/fastlib/base/test.h
	@echo '... Making bin/x86_64_Linux_check_mpi_/obj/base_cc.o'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj
	@cd /net/hc292/nadeem/fastlib/base && mpiCC -fno-exceptions -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_ -I/net/hc292/nadeem/fastlib -O2 -g -DDEBUG   -c cc.cc -o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/base_cc.o
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/base_common.o: /net/hc292/nadeem/fastlib/base/compiler_impl.h /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/base/basic_types.h /net/hc292/nadeem/fastlib/base/common.h /net/hc292/nadeem/fastlib/base/cc.h /net/hc292/nadeem/fastlib/base/common.c /net/hc292/nadeem/fastlib/base/debug.h /net/hc292/nadeem/fastlib/base/compiler.h /net/hc292/nadeem/fastlib/base/scale.h /net/hc292/nadeem/fastlib/base/ccmem.h /net/hc292/nadeem/fastlib/base/fortran.h /net/hc292/nadeem/fastlib/base/otrav.h /net/hc292/nadeem/fastlib/base/test.h
	@echo '... Making bin/x86_64_Linux_check_mpi_/obj/base_common.o'
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj
	@cd /net/hc292/nadeem/fastlib/base && mpicc -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON -I/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_ -I/net/hc292/nadeem/fastlib -O2 -g -DDEBUG   -c common.c -o /net/hc292/nadeem/fastlib/bin/x86_64_Linux_check_mpi_/obj/base_common.o
/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/base/basic_types.h: /net/hc292/nadeem/fastlib/script/config.py /net/hc292/nadeem/fastlib/base/config/template_types.c
	@echo '... Making bin/x86_64_Linux_COMMON_mpi_COMMON/base/basic_types.h'
	@/net/hc292/nadeem/fastlib/script/config.py --genfiles_dir=/net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON --source_dir=/net/hc292/nadeem/fastlib
	@mkdir -p /net/hc292/nadeem/fastlib/bin/x86_64_Linux_COMMON_mpi_COMMON/base
clean:
	@echo 'Removing the bin/ directory.'
	rm -rf /net/hc292/nadeem/fastlib/bin/*
