.TH "src/mlpack/core/optimizers/sgd/update_policies Directory Reference" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack/core/optimizers/sgd/update_policies Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmomentum_update\&.hpp\fP"
.br
.ti -1c
.RI "file \fBvanilla_update\&.hpp\fP"
.br
.in -1c
