.TH "src/mlpack/methods/det Directory Reference" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack/methods/det Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdt_utils\&.hpp\fP"
.br
.ti -1c
.RI "file \fBdtree\&.hpp\fP"
.br
.in -1c
