.TH "src/mlpack/methods/gmm Directory Reference" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack/methods/gmm Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdiagonal_constraint\&.hpp\fP"
.br
.ti -1c
.RI "file \fBeigenvalue_ratio_constraint\&.hpp\fP"
.br
.ti -1c
.RI "file \fBem_fit\&.hpp\fP"
.br
.ti -1c
.RI "file \fBgmm\&.hpp\fP"
.br
.ti -1c
.RI "file \fBno_constraint\&.hpp\fP"
.br
.ti -1c
.RI "file \fBpositive_definite_constraint\&.hpp\fP"
.br
.in -1c
