.TH "src/mlpack/methods/amf/init_rules Directory Reference" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack/methods/amf/init_rules Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaverage_init\&.hpp\fP"
.br
.ti -1c
.RI "file \fBgiven_init\&.hpp\fP"
.br
.ti -1c
.RI "file \fBrandom_acol_init\&.hpp\fP"
.br
.ti -1c
.RI "file \fBrandom_init\&.hpp\fP"
.br
.in -1c
