.TH "src/mlpack/methods/neighbor_search/sort_policies Directory Reference" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack/methods/neighbor_search/sort_policies Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBfurthest_neighbor_sort\&.hpp\fP"
.br
.ti -1c
.RI "file \fBnearest_neighbor_sort\&.hpp\fP"
.br
.in -1c
