.TH "src/mlpack/methods/kernel_pca/kernel_rules Directory Reference" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack/methods/kernel_pca/kernel_rules Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBnaive_method\&.hpp\fP"
.br
.ti -1c
.RI "file \fBnystroem_method\&.hpp\fP"
.br
.in -1c
