.TH "doc/tutorials/amf/amf.txt" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doc/tutorials/amf/amf.txt \- Tutorial for how to use the AMF class\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Tutorial for how to use the AMF class\&. 


.PP
\fBAuthor:\fP
.RS 4
Sumedh Ghaisas 
.RE
.PP

.PP
Definition in file \fBamf\&.txt\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
