.TH "src/mlpack/core/tree/ballbound.hpp" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack/core/tree/ballbound.hpp \- Bounds that are useful for binary space partitioning trees\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmlpack::bound::BallBound< MetricType, VecType >\fP"
.br
.RI "\fIBall bound encloses a set of points at a specific distance (radius) from a specific point (center)\&. \fP"
.ti -1c
.RI "struct \fBmlpack::bound::BoundTraits< BallBound< MetricType, VecType > >\fP"
.br
.RI "\fIA specialization of \fBBoundTraits\fP for this bound type\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmlpack\fP"
.br
.RI "\fILinear algebra utility functions, generally performed on matrices or vectors\&. \fP"
.ti -1c
.RI " \fBmlpack::bound\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Bounds that are useful for binary space partitioning trees\&. 

Interface to a ball bound that works in arbitrary metric spaces\&.
.PP
mlpack is free software; you may redistribute it and/or modify it under the terms of the 3-clause BSD license\&. You should have received a copy of the 3-clause BSD license along with mlpack\&. If not, see http://www.opensource.org/licenses/BSD-3-Clause for more information\&. 
.PP
Definition in file \fBballbound\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
