.TH "src/mlpack/core/tree/binary_space_tree/breadth_first_dual_tree_traverser.hpp" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack/core/tree/binary_space_tree/breadth_first_dual_tree_traverser.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::BreadthFirstDualTreeTraverser< RuleType >\fP"
.br
.ti -1c
.RI "struct \fBmlpack::tree::QueueFrame< TreeType, TraversalInfoType >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmlpack\fP"
.br
.RI "\fILinear algebra utility functions, generally performed on matrices or vectors\&. \fP"
.ti -1c
.RI " \fBmlpack::tree\fP"
.br
.RI "\fITrees and tree-building procedures\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Ryan Curtin
.RE
.PP
Defines the BreadthFirstDualTreeTraverser for the BinarySpaceTree tree type\&. This is a nested class of BinarySpaceTree which traverses two trees in a breadth-first manner with a given set of rules which indicate the branches which can be pruned and the order in which to recurse\&.
.PP
mlpack is free software; you may redistribute it and/or modify it under the terms of the 3-clause BSD license\&. You should have received a copy of the 3-clause BSD license along with mlpack\&. If not, see http://www.opensource.org/licenses/BSD-3-Clause for more information\&. 
.PP
Definition in file \fBbreadth_first_dual_tree_traverser\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
