.TH "src/mlpack/methods/decision_tree/decision_tree.hpp" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack/methods/decision_tree/decision_tree.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmlpack::tree::DecisionTree< FitnessFunction, NumericSplitType, CategoricalSplitType, ElemType, NoRecursion >\fP"
.br
.RI "\fIThis class implements a generic decision tree learner\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmlpack\fP"
.br
.RI "\fILinear algebra utility functions, generally performed on matrices or vectors\&. \fP"
.ti -1c
.RI " \fBmlpack::tree\fP"
.br
.RI "\fITrees and tree-building procedures\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "template<typename FitnessFunction  = GiniGain, template< typename > class NumericSplitType = BestBinaryNumericSplit, template< typename > class CategoricalSplitType = AllCategoricalSplit, typename ElemType  = double> using \fBmlpack::tree::DecisionStump\fP = DecisionTree< FitnessFunction, NumericSplitType, CategoricalSplitType, ElemType, false >"
.br
.RI "\fIConvenience typedef for decision stumps (single level decision trees)\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Ryan Curtin
.RE
.PP
A generic decision tree learner\&. Its behavior can be controlled via template arguments\&. 
.PP
Definition in file \fBdecision_tree\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
