.TH "src/mlpack/core/util/deprecated.hpp" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack/core/util/deprecated.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBmlpack_deprecated\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marcos Pividori\&.
.RE
.PP
Definition of the mlpack_deprecated macro\&.
.PP
mlpack is free software; you may redistribute it and/or modify it under the terms of the 3-clause BSD license\&. You should have received a copy of the 3-clause BSD license along with mlpack\&. If not, see http://www.opensource.org/licenses/BSD-3-Clause for more information\&. 
.PP
Definition in file \fBdeprecated\&.hpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define mlpack_deprecated"

.PP
Definition at line 22 of file deprecated\&.hpp\&.
.PP
Referenced by mlpack::regression::LogisticRegression< MatType >::Lambda()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
