.TH "doc/tutorials/det/det.txt" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doc/tutorials/det/det.txt \- Tutorial for how to perform density estimation with Density Estimation Trees (DET)\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "f f \fB$V\fP (t)\\f $is the volume of the node\\f $t\\f $and\\f $\\tilde"
.br
.ti -1c
.RI "see subsection cli_alt_reg_tut Alternate DET \fBregularization\fP The usual regularized error f $R_ \fBalpha\fP (t)\\f $of a node\\f $t\\f $is given by"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "f is the \fBset\fP of leaves in the subtree rooted at f $t f For the purposes of density \fBestimation\fP"
.br
.ti -1c
.RI "this option is not available in DET right \fBnow\fP"
.br
.ti -1c
.RI "f is the \fBset\fP of leaves in the subtree rooted at f $t f For the purposes of density there is a different form of \fBregularization\fP"
.br
.ti -1c
.RI "f is the \fBset\fP of leaves in the subtree rooted at f $t f For the purposes of density there is a different form of we penalize the sum of the inverse of the volumes of the leaves With this very small volume nodes are discouraged unless the data actually warrants it \fBThus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tutorial for how to perform density estimation with Density Estimation Trees (DET)\&. 


.PP
\fBAuthor:\fP
.RS 4
Parikshit Ram 
.RE
.PP

.PP
Definition in file \fBdet\&.txt\fP\&.
.SH "Function Documentation"
.PP 
.SS "f f $V (t)"

.PP
Definition at line 351 of file det\&.txt\&.
.SS "see subsection cli_alt_reg_tut Alternate DET \fBregularization\fP The usual regularized error f $R_ alpha (t)"

.PP
Definition at line 344 of file det\&.txt\&.
.SH "Variable Documentation"
.PP 
.SS "f is the \fBset\fP of leaves in the subtree rooted at f $t f For the purposes of density estimation"

.PP
Definition at line 354 of file det\&.txt\&.
.SS "this option is not available in DET right now"

.PP
Definition at line 341 of file det\&.txt\&.
.SS "f is the \fBset\fP of leaves in the subtree rooted at f $t f For the purposes of density there is a different form of we penalize the sum of the inverse of the volumes of the leaves With this regularization"

.PP
Definition at line 354 of file det\&.txt\&.
.SS "f is the \fBset\fP of leaves in the subtree rooted at f $t f For the purposes of density there is a different form of we penalize the sum of the inverse of the volumes of the leaves With this very small volume nodes are discouraged unless the data actually warrants it Thus"

.PP
Definition at line 354 of file det\&.txt\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
