.TH "src/mlpack/methods/det/dt_utils.hpp" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack/methods/det/dt_utils.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmlpack\fP"
.br
.RI "\fILinear algebra utility functions, generally performed on matrices or vectors\&. \fP"
.ti -1c
.RI " \fBmlpack::det\fP"
.br
.RI "\fIDensity Estimation Trees\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename MatType , typename TagType > void \fBmlpack::det::PrintLeafMembership\fP (DTree< MatType, TagType > *dtree, const MatType &data, const arma::Mat< size_t > &labels, const size_t numClasses, const \fBstd::string\fP leafClassMembershipFile='')"
.br
.RI "\fIPrint the membership of leaves of a density estimation tree given the labels and number of classes\&. \fP"
.ti -1c
.RI "template<typename MatType , typename TagType > void \fBmlpack::det::PrintVariableImportance\fP (const DTree< MatType, TagType > *dtree, const \fBstd::string\fP viFile='')"
.br
.RI "\fIPrint the variable importance of each dimension of a density estimation tree\&. \fP"
.ti -1c
.RI "template<typename MatType , typename TagType > DTree< MatType, TagType > * \fBmlpack::det::Trainer\fP (MatType &dataset, const size_t folds, const bool useVolumeReg=false, const size_t maxLeafSize=10, const size_t minLeafSize=5, const \fBstd::string\fP unprunedTreeOutput='')"
.br
.RI "\fITrain the optimal decision tree using cross-validation with the given number of folds\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Parikshit Ram (pram@cc.gatech.edu)
.RE
.PP
This file implements functions to perform different tasks with the Density Tree class\&.
.PP
mlpack is free software; you may redistribute it and/or modify it under the terms of the 3-clause BSD license\&. You should have received a copy of the 3-clause BSD license along with mlpack\&. If not, see http://www.opensource.org/licenses/BSD-3-Clause for more information\&. 
.PP
Definition in file \fBdt_utils\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
