.TH "src/mlpack/core/util/gitversion.hpp" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack/core/util/gitversion.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "return mlpack \fBgit\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "return mlpack git"

.PP
Definition at line 1 of file gitversion\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
