.TH "src/mlpack/methods/hoeffding_trees/hoeffding_numeric_split.hpp" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack/methods/hoeffding_trees/hoeffding_numeric_split.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmlpack::tree::HoeffdingNumericSplit< FitnessFunction, ObservationType >\fP"
.br
.RI "\fIThe \fBHoeffdingNumericSplit\fP class implements the numeric feature splitting strategy alluded to by Domingos and Hulten in the following paper: \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmlpack\fP"
.br
.RI "\fILinear algebra utility functions, generally performed on matrices or vectors\&. \fP"
.ti -1c
.RI " \fBmlpack::tree\fP"
.br
.RI "\fITrees and tree-building procedures\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "template<typename FitnessFunction > using \fBmlpack::tree::HoeffdingDoubleNumericSplit\fP = HoeffdingNumericSplit< FitnessFunction, double >"
.br
.RI "\fIConvenience typedef\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Ryan Curtin
.RE
.PP
A numeric feature split for Hoeffding trees\&. This is a very simple implementation based on a minor note in the paper 'Mining High-Speed Data
Streams' by Pedro Domingos and Geoff Hulten\&.
.PP
mlpack is free software; you may redistribute it and/or modify it under the terms of the 3-clause BSD license\&. You should have received a copy of the 3-clause BSD license along with mlpack\&. If not, see http://www.opensource.org/licenses/BSD-3-Clause for more information\&. 
.PP
Definition in file \fBhoeffding_numeric_split\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
