.TH "src/mlpack/core/tree/space_split/hyperplane.hpp" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack/core/tree/space_split/hyperplane.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmlpack::tree::HyperplaneBase< BoundT, ProjVectorT >\fP"
.br
.RI "\fI\fBHyperplaneBase\fP defines a splitting hyperplane based on a projection vector and projection value\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmlpack\fP"
.br
.RI "\fILinear algebra utility functions, generally performed on matrices or vectors\&. \fP"
.ti -1c
.RI " \fBmlpack::tree\fP"
.br
.RI "\fITrees and tree-building procedures\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "template<typename MetricType > using \fBmlpack::tree::AxisOrthogonalHyperplane\fP = HyperplaneBase< bound::HRectBound< MetricType >, AxisParallelProjVector >"
.br
.RI "\fIAxisOrthogonalHyperplane represents a hyperplane orthogonal to an axis\&. \fP"
.ti -1c
.RI "template<typename MetricType > using \fBmlpack::tree::Hyperplane\fP = HyperplaneBase< bound::BallBound< MetricType >, ProjVector >"
.br
.RI "\fIHyperplane represents a general hyperplane (not necessarily axis-orthogonal)\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marcos Pividori
.RE
.PP
Definition of Hyperplane and AxisOrthogonalHyperplane\&.
.PP
mlpack is free software; you may redistribute it and/or modify it under the terms of the 3-clause BSD license\&. You should have received a copy of the 3-clause BSD license along with mlpack\&. If not, see http://www.opensource.org/licenses/BSD-3-Clause for more information\&. 
.PP
Definition in file \fBhyperplane\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
