.TH "doc/tutorials/linear_regression/linear_regression.txt" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doc/tutorials/linear_regression/linear_regression.txt \- Tutorial for how to use the LinearRegression class\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Tutorial for how to use the LinearRegression class\&. 


.PP
\fBAuthor:\fP
.RS 4
James Cline 
.RE
.PP

.PP
Definition in file \fBlinear_regression\&.txt\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
