.TH "mlpack::matrix_completion" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::matrix_completion \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMatrixCompletion\fP"
.br
.RI "\fIThis class implements the popular nuclear norm minimization heuristic for matrix completion problems\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
