.TH "mlpack::bound::BoundTraits< HRectBound< MetricType, ElemType > >" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::bound::BoundTraits< HRectBound< MetricType, ElemType > > \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBHasTightBounds\fP = true"
.br
.RI "\fIThese bounds are always tight for each dimension\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename MetricType, typename ElemType>
.br
struct mlpack::bound::BoundTraits< HRectBound< MetricType, ElemType > >"

.PP
Definition at line 234 of file hrectbound\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename MetricType , typename ElemType > const bool \fBmlpack::bound::BoundTraits\fP< \fBHRectBound\fP< MetricType, ElemType > >::HasTightBounds = true\fC [static]\fP"

.PP
These bounds are always tight for each dimension\&. 
.PP
Definition at line 237 of file hrectbound\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
