.TH "mlpack::nca" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::nca \- Neighborhood Components Analysis\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNCA\fP"
.br
.RI "\fIAn implementation of Neighborhood Components Analysis, both a linear dimensionality reduction technique and a distance learning technique\&. \fP"
.ti -1c
.RI "class \fBSoftmaxErrorFunction\fP"
.br
.RI "\fIThe 'softmax' stochastic neighbor assignment probability function\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Neighborhood Components Analysis\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
