.TH "mlpack::neighbor::ReferenceSetVisitor" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::neighbor::ReferenceSetVisitor \- \fBReferenceSetVisitor\fP exposes the referenceSet of the given NSType\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits static_visitor< const arma::mat & >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename NSType > const arma::mat & \fBoperator()\fP (\fBNSType\fP *ns) const "
.br
.RI "\fIReturn the reference set\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBReferenceSetVisitor\fP exposes the referenceSet of the given NSType\&. 
.PP
Definition at line 236 of file ns_model\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename NSType > const arma::mat& mlpack::neighbor::ReferenceSetVisitor::operator() (\fBNSType\fP * ns) const"

.PP
Return the reference set\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
