.TH "mlpack::regression" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::regression \- Regression methods\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLARS\fP"
.br
.RI "\fIAn implementation of \fBLARS\fP, a stage-wise homotopy-based algorithm for l1-regularized linear regression (LASSO) and l1+l2 regularized linear regression (Elastic Net)\&. \fP"
.ti -1c
.RI "class \fBLinearRegression\fP"
.br
.RI "\fIA simple linear regression algorithm using ordinary least squares\&. \fP"
.ti -1c
.RI "class \fBLogisticRegression\fP"
.br
.RI "\fIThe \fBLogisticRegression\fP class implements an L2-regularized logistic regression model, and supports training with multiple optimizers and classification\&. \fP"
.ti -1c
.RI "class \fBLogisticRegressionFunction\fP"
.br
.RI "\fIThe log-likelihood function for the logistic regression objective function\&. \fP"
.ti -1c
.RI "class \fBSoftmaxRegression\fP"
.br
.RI "\fISoftmax Regression is a classifier which can be used for classification when the data available can take two or more class values\&. \fP"
.ti -1c
.RI "class \fBSoftmaxRegressionFunction\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Regression methods\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
