.TH "mlpack::ann::DeltaVisitor" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::ann::DeltaVisitor \- \fBDeltaVisitor\fP exposes the delta parameter of the given module\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits static_visitor< arma::mat & >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename LayerType > arma::mat & \fBoperator()\fP (LayerType *layer) const "
.br
.RI "\fIReturn the delta parameter\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBDeltaVisitor\fP exposes the delta parameter of the given module\&. 
.PP
Definition at line 27 of file delta_visitor\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename LayerType > arma::mat& mlpack::ann::DeltaVisitor::operator() (LayerType * layer) const"

.PP
Return the delta parameter\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
