.TH "mlpack::range::DeleteVisitor" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::range::DeleteVisitor \- \fBDeleteVisitor\fP deletes the given RSType instance\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits static_visitor< void >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename RSType > void \fBoperator()\fP (\fBRSType\fP *rs) const "
.br
.RI "\fIDelete the RSType object\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBDeleteVisitor\fP deletes the given RSType instance\&. 
.PP
Definition at line 182 of file rs_model\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename RSType > void mlpack::range::DeleteVisitor::operator() (\fBRSType\fP * rs) const"

.PP
Delete the RSType object\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
