.TH "mlpack::data::FirstArrayShim< T >" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::data::FirstArrayShim< T > \- A first shim for arrays\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFirstArrayShim\fP (T *\fBt\fP, const size_t \fBlen\fP, const \fBstd::string\fP &\fBname\fP)"
.br
.RI "\fIConstruct the first shim with the given objects, length, and name\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const size_t \fBlen\fP"
.br
.ti -1c
.RI "const \fBstd::string\fP & \fBname\fP"
.br
.ti -1c
.RI "T * \fBt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct mlpack::data::FirstArrayShim< T >"
A first shim for arrays\&. 

This shim's purpose is to be caught by our overloads of operator<<, operator&, and operator>>, which then creates a second shim\&. 
.PP
Definition at line 63 of file serialization_shim\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBmlpack::data::FirstArrayShim\fP< T >::\fBFirstArrayShim\fP (T * t, const size_t len, const \fBstd::string\fP & name)\fC [inline]\fP"

.PP
Construct the first shim with the given objects, length, and name\&. 
.PP
Definition at line 264 of file serialization_shim\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T> const size_t \fBmlpack::data::FirstArrayShim\fP< T >::len"

.PP
Definition at line 268 of file serialization_shim\&.hpp\&.
.PP
Referenced by mlpack::data::operator&(), and mlpack::data::operator>>()\&.
.SS "template<typename T> const \fBstd::string\fP& \fBmlpack::data::FirstArrayShim\fP< T >::name"

.PP
Definition at line 269 of file serialization_shim\&.hpp\&.
.PP
Referenced by mlpack::data::operator&(), and mlpack::data::operator>>()\&.
.SS "template<typename T> T* \fBmlpack::data::FirstArrayShim\fP< T >::t"

.PP
Definition at line 267 of file serialization_shim\&.hpp\&.
.PP
Referenced by mlpack::data::operator&(), and mlpack::data::operator>>()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
