.TH "mlpack::optimization::test::WoodFunction" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::optimization::test::WoodFunction \- The Wood function, defined by f(x) = f1(x) + f2(x) + f3(x) + f4(x) + f5(x) + f6(x) f1(x) = 100 (x2 - x1^2)^2 f2(x) = (1 - x1)^2 f3(x) = 90 (x4 - x3^2)^2 f4(x) = (1 - x3)^2 f5(x) = 10 (x2 + x4 - 2)^2 f6(x) = (1 / 10) (x2 - x4)^2 x_0 = [-3, -1, -3, -1]\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWoodFunction\fP ()"
.br
.ti -1c
.RI "double \fBEvaluate\fP (const arma::mat &coordinates)"
.br
.ti -1c
.RI "const arma::mat & \fBGetInitialPoint\fP () const "
.br
.ti -1c
.RI "void \fBGradient\fP (const arma::mat &coordinates, arma::mat &gradient)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "arma::mat \fBinitialPoint\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The Wood function, defined by f(x) = f1(x) + f2(x) + f3(x) + f4(x) + f5(x) + f6(x) f1(x) = 100 (x2 - x1^2)^2 f2(x) = (1 - x1)^2 f3(x) = 90 (x4 - x3^2)^2 f4(x) = (1 - x3)^2 f5(x) = 10 (x2 + x4 - 2)^2 f6(x) = (1 / 10) (x2 - x4)^2 x_0 = [-3, -1, -3, -1]\&. 

This should optimize to f(x) = 0, at x = [1, 1, 1, 1]\&.
.PP
'A comparative study of nonlinear programming codes\&.' A\&.R\&. Colville\&. 1968\&. Rep\&. 320-2949, IBM N\&.Y\&. Scientific Center\&. 
.PP
Definition at line 83 of file test_functions\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mlpack::optimization::test::WoodFunction::WoodFunction ()"

.SH "Member Function Documentation"
.PP 
.SS "double mlpack::optimization::test::WoodFunction::Evaluate (const arma::mat & coordinates)"

.SS "const arma::mat& mlpack::optimization::test::WoodFunction::GetInitialPoint () const"

.SS "void mlpack::optimization::test::WoodFunction::Gradient (const arma::mat & coordinates, arma::mat & gradient)"

.SH "Member Data Documentation"
.PP 
.SS "arma::mat mlpack::optimization::test::WoodFunction::initialPoint\fC [private]\fP"

.PP
Definition at line 94 of file test_functions\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
