.TH "mlpack::neighbor::BiSearchVisitor< SortPolicy >" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::neighbor::BiSearchVisitor< SortPolicy > \- \fBBiSearchVisitor\fP executes a bichromatic neighbor search on the given NSType\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits static_visitor< void >\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "template<template< typename TreeMetricType, typename TreeStatType, typename TreeMatType > class TreeType> using \fBNSTypeT\fP = \fBNSType\fP< SortPolicy, TreeType >"
.br
.RI "\fIAlias template necessary for visual c++ compiler\&. \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBiSearchVisitor\fP (const arma::mat &\fBquerySet\fP, const size_t \fBk\fP, arma::Mat< size_t > &\fBneighbors\fP, arma::mat &\fBdistances\fP, const size_t \fBleafSize\fP, const double \fBtau\fP, const double \fBrho\fP)"
.br
.RI "\fIConstruct the \fBBiSearchVisitor\fP\&. \fP"
.ti -1c
.RI "template<template< typename TreeMetricType, typename TreeStatType, typename TreeMatType > class TreeType> void \fBoperator()\fP (\fBNSTypeT\fP< TreeType > *ns) const "
.br
.RI "\fIDefault Bichromatic neighbor search on the given NSType instance\&. \fP"
.ti -1c
.RI "void \fBoperator()\fP (\fBNSTypeT\fP< \fBtree::KDTree\fP > *ns) const "
.br
.RI "\fIBichromatic neighbor search on the given NSType specialized for KDTrees\&. \fP"
.ti -1c
.RI "void \fBoperator()\fP (\fBNSTypeT\fP< \fBtree::BallTree\fP > *ns) const "
.br
.RI "\fIBichromatic neighbor search on the given NSType specialized for BallTrees\&. \fP"
.ti -1c
.RI "void \fBoperator()\fP (\fBSpillKNN\fP *ns) const "
.br
.RI "\fIBichromatic neighbor search specialized for SPTrees\&. \fP"
.ti -1c
.RI "void \fBoperator()\fP (\fBNSTypeT\fP< \fBtree::Octree\fP > *ns) const "
.br
.RI "\fIBichromatic neighbor search specialized for octrees\&. \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "template<typename NSType > void \fBSearchLeaf\fP (\fBNSType\fP *ns) const "
.br
.RI "\fIBichromatic neighbor search on the given NSType considering the leafSize\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "arma::mat & \fBdistances\fP"
.br
.RI "\fIThe result matrix for distances\&. \fP"
.ti -1c
.RI "const size_t \fBk\fP"
.br
.RI "\fIThe number of neighbors to search for\&. \fP"
.ti -1c
.RI "const size_t \fBleafSize\fP"
.br
.RI "\fIThe number of points in a leaf (for BinarySpaceTrees)\&. \fP"
.ti -1c
.RI "arma::Mat< size_t > & \fBneighbors\fP"
.br
.RI "\fIThe result matrix for neighbors\&. \fP"
.ti -1c
.RI "const arma::mat & \fBquerySet\fP"
.br
.RI "\fIThe query set for the bichromatic search\&. \fP"
.ti -1c
.RI "const double \fBrho\fP"
.br
.RI "\fIBalance threshold (for spill trees)\&. \fP"
.ti -1c
.RI "const double \fBtau\fP"
.br
.RI "\fIOverlapping size (for spill trees)\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename SortPolicy>
.br
class mlpack::neighbor::BiSearchVisitor< SortPolicy >"
\fBBiSearchVisitor\fP executes a bichromatic neighbor search on the given NSType\&. 

We use template specialization to differentiate those tree types that accept leafSize as a parameter\&. In these cases, before doing neighbor search, a query tree with proper leafSize is built from the querySet\&. 
.PP
Definition at line 98 of file ns_model\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename SortPolicy > template<template< typename TreeMetricType, typename TreeStatType, typename TreeMatType > class TreeType> using \fBmlpack::neighbor::BiSearchVisitor\fP< SortPolicy >::\fBNSTypeT\fP =  \fBNSType\fP<SortPolicy, TreeType>"

.PP
Alias template necessary for visual c++ compiler\&. 
.PP
Definition at line 125 of file ns_model\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename SortPolicy > \fBmlpack::neighbor::BiSearchVisitor\fP< SortPolicy >::\fBBiSearchVisitor\fP (const arma::mat & querySet, const size_t k, arma::Mat< size_t > & neighbors, arma::mat & distances, const size_t leafSize, const double tau, const double rho)"

.PP
Construct the \fBBiSearchVisitor\fP\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename SortPolicy > template<template< typename TreeMetricType, typename TreeStatType, typename TreeMatType > class TreeType> void \fBmlpack::neighbor::BiSearchVisitor\fP< SortPolicy >::operator() (\fBNSTypeT\fP< TreeType > * ns) const"

.PP
Default Bichromatic neighbor search on the given NSType instance\&. 
.SS "template<typename SortPolicy > void \fBmlpack::neighbor::BiSearchVisitor\fP< SortPolicy >::operator() (\fBNSTypeT\fP< \fBtree::KDTree\fP > * ns) const"

.PP
Bichromatic neighbor search on the given NSType specialized for KDTrees\&. 
.SS "template<typename SortPolicy > void \fBmlpack::neighbor::BiSearchVisitor\fP< SortPolicy >::operator() (\fBNSTypeT\fP< \fBtree::BallTree\fP > * ns) const"

.PP
Bichromatic neighbor search on the given NSType specialized for BallTrees\&. 
.SS "template<typename SortPolicy > void \fBmlpack::neighbor::BiSearchVisitor\fP< SortPolicy >::operator() (\fBSpillKNN\fP * ns) const"

.PP
Bichromatic neighbor search specialized for SPTrees\&. 
.SS "template<typename SortPolicy > void \fBmlpack::neighbor::BiSearchVisitor\fP< SortPolicy >::operator() (\fBNSTypeT\fP< \fBtree::Octree\fP > * ns) const"

.PP
Bichromatic neighbor search specialized for octrees\&. 
.SS "template<typename SortPolicy > template<typename NSType > void \fBmlpack::neighbor::BiSearchVisitor\fP< SortPolicy >::SearchLeaf (\fBNSType\fP * ns) const\fC [private]\fP"

.PP
Bichromatic neighbor search on the given NSType considering the leafSize\&. 
.SH "Member Data Documentation"
.PP 
.SS "template<typename SortPolicy > arma::mat& \fBmlpack::neighbor::BiSearchVisitor\fP< SortPolicy >::distances\fC [private]\fP"

.PP
The result matrix for distances\&. 
.PP
Definition at line 108 of file ns_model\&.hpp\&.
.SS "template<typename SortPolicy > const size_t \fBmlpack::neighbor::BiSearchVisitor\fP< SortPolicy >::k\fC [private]\fP"

.PP
The number of neighbors to search for\&. 
.PP
Definition at line 104 of file ns_model\&.hpp\&.
.SS "template<typename SortPolicy > const size_t \fBmlpack::neighbor::BiSearchVisitor\fP< SortPolicy >::leafSize\fC [private]\fP"

.PP
The number of points in a leaf (for BinarySpaceTrees)\&. 
.PP
Definition at line 110 of file ns_model\&.hpp\&.
.SS "template<typename SortPolicy > arma::Mat<size_t>& \fBmlpack::neighbor::BiSearchVisitor\fP< SortPolicy >::neighbors\fC [private]\fP"

.PP
The result matrix for neighbors\&. 
.PP
Definition at line 106 of file ns_model\&.hpp\&.
.SS "template<typename SortPolicy > const arma::mat& \fBmlpack::neighbor::BiSearchVisitor\fP< SortPolicy >::querySet\fC [private]\fP"

.PP
The query set for the bichromatic search\&. 
.PP
Definition at line 102 of file ns_model\&.hpp\&.
.SS "template<typename SortPolicy > const double \fBmlpack::neighbor::BiSearchVisitor\fP< SortPolicy >::rho\fC [private]\fP"

.PP
Balance threshold (for spill trees)\&. 
.PP
Definition at line 114 of file ns_model\&.hpp\&.
.SS "template<typename SortPolicy > const double \fBmlpack::neighbor::BiSearchVisitor\fP< SortPolicy >::tau\fC [private]\fP"

.PP
Overlapping size (for spill trees)\&. 
.PP
Definition at line 112 of file ns_model\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
