.TH "mlpack::range::SingleModeVisitor" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::range::SingleModeVisitor \- \fBSingleModeVisitor\fP exposes the SingleMode() method of the given RSType\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits static_visitor< bool & >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename RSType > bool & \fBoperator()\fP (\fBRSType\fP *rs) const "
.br
.RI "\fIGet a reference to the singleMode parameter of the given RangeSeach object\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBSingleModeVisitor\fP exposes the SingleMode() method of the given RSType\&. 
.PP
Definition at line 214 of file rs_model\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename RSType > bool& mlpack::range::SingleModeVisitor::operator() (\fBRSType\fP * rs) const"

.PP
Get a reference to the singleMode parameter of the given RangeSeach object\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
