.TH "mlpack::pca::PCAType< DecompositionPolicy >" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::pca::PCAType< DecompositionPolicy > \- This class implements principal components analysis (PCA)\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPCAType\fP (const bool \fBscaleData\fP=false, const DecompositionPolicy &\fBdecomposition\fP=DecompositionPolicy())"
.br
.RI "\fICreate the PCA object, specifying if the data should be scaled in each dimension by standard deviation when PCA is performed\&. \fP"
.ti -1c
.RI "void \fBApply\fP (const arma::mat &data, arma::mat &transformedData, arma::vec &eigVal, arma::mat &eigvec)"
.br
.RI "\fIApply Principal Component Analysis to the provided data set\&. \fP"
.ti -1c
.RI "void \fBApply\fP (const arma::mat &data, arma::mat &transformedData, arma::vec &eigVal)"
.br
.RI "\fIApply Principal Component Analysis to the provided data set\&. \fP"
.ti -1c
.RI "double \fBApply\fP (arma::mat &data, const size_t newDimension)"
.br
.RI "\fIUse PCA for dimensionality reduction on the given dataset\&. \fP"
.ti -1c
.RI "double \fBApply\fP (arma::mat &data, const int newDimension)"
.br
.RI "\fIThis overload is here to make sure int gets casted right to size_t\&. \fP"
.ti -1c
.RI "double \fBApply\fP (arma::mat &data, const double varRetained)"
.br
.RI "\fIUse PCA for dimensionality reduction on the given dataset\&. \fP"
.ti -1c
.RI "bool \fBScaleData\fP () const "
.br
.RI "\fIGet whether or not this PCA object will scale (by standard deviation) the data when PCA is performed\&. \fP"
.ti -1c
.RI "bool & \fBScaleData\fP ()"
.br
.RI "\fIModify whether or not this PCA object will scale (by standard deviation) the data when PCA is performed\&. \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBScaleData\fP (arma::mat &centeredData)"
.br
.RI "\fIScaling the data is when we reduce the variance of each dimension to 1\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "DecompositionPolicy \fBdecomposition\fP"
.br
.RI "\fIDecomposition method used to perform principal components analysis\&. \fP"
.ti -1c
.RI "bool \fBscaleData\fP"
.br
.RI "\fIWhether or not the data will be scaled by standard deviation when PCA is performed\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename DecompositionPolicy = ExactSVDPolicy>
.br
class mlpack::pca::PCAType< DecompositionPolicy >"
This class implements principal components analysis (PCA)\&. 

This is a common, widely-used technique that is often used for either dimensionality reduction or transforming data into a better basis\&. Further information on PCA can be found in almost any statistics or machine learning textbook, and all over the internet\&. Note this class will be changed to have the name PCA in mlpack 3\&.0\&.0 
.PP
Definition at line 34 of file pca\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename DecompositionPolicy  = ExactSVDPolicy> \fBmlpack::pca::PCAType\fP< DecompositionPolicy >::\fBPCAType\fP (const bool scaleData = \fCfalse\fP, const DecompositionPolicy & decomposition = \fCDecompositionPolicy()\fP)"

.PP
Create the PCA object, specifying if the data should be scaled in each dimension by standard deviation when PCA is performed\&. 
.PP
\fBParameters:\fP
.RS 4
\fIscaleData\fP Whether or not to scale the data\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<typename DecompositionPolicy  = ExactSVDPolicy> void \fBmlpack::pca::PCAType\fP< DecompositionPolicy >::Apply (const arma::mat & data, arma::mat & transformedData, arma::vec & eigVal, arma::mat & eigvec)"

.PP
Apply Principal Component Analysis to the provided data set\&. It is safe to pass the same matrix reference for both data and transformedData\&.
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP Data matrix\&. 
.br
\fItransformedData\fP Matrix to put results of PCA into\&. 
.br
\fIeigval\fP Vector to put eigenvalues into\&. 
.br
\fIeigvec\fP Matrix to put eigenvectors (loadings) into\&. 
.RE
.PP

.PP
Referenced by mlpack::pca::PCAType< DecompositionPolicy >::Apply()\&.
.SS "template<typename DecompositionPolicy  = ExactSVDPolicy> void \fBmlpack::pca::PCAType\fP< DecompositionPolicy >::Apply (const arma::mat & data, arma::mat & transformedData, arma::vec & eigVal)"

.PP
Apply Principal Component Analysis to the provided data set\&. It is safe to pass the same matrix reference for both data and transformedData\&.
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP Data matrix\&. 
.br
\fItransformedData\fP Matrix to store results of PCA in\&. 
.br
\fIeigVal\fP Vector to put eigenvalues into\&. 
.RE
.PP

.SS "template<typename DecompositionPolicy  = ExactSVDPolicy> double \fBmlpack::pca::PCAType\fP< DecompositionPolicy >::Apply (arma::mat & data, const size_t newDimension)"

.PP
Use PCA for dimensionality reduction on the given dataset\&. This will save the newDimension largest principal components of the data and remove the rest\&. The parameter returned is the amount of variance of the data that is retained; this is a value between 0 and 1\&. For instance, a value of 0\&.9 indicates that 90% of the variance present in the data was retained\&.
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP Data matrix\&. 
.br
\fInewDimension\fP New dimension of the data\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Amount of the variance of the data retained (between 0 and 1)\&. 
.RE
.PP

.SS "template<typename DecompositionPolicy  = ExactSVDPolicy> double \fBmlpack::pca::PCAType\fP< DecompositionPolicy >::Apply (arma::mat & data, const int newDimension)\fC [inline]\fP"

.PP
This overload is here to make sure int gets casted right to size_t\&. 
.PP
Definition at line 86 of file pca\&.hpp\&.
.PP
References mlpack::pca::PCAType< DecompositionPolicy >::Apply()\&.
.SS "template<typename DecompositionPolicy  = ExactSVDPolicy> double \fBmlpack::pca::PCAType\fP< DecompositionPolicy >::Apply (arma::mat & data, const double varRetained)"

.PP
Use PCA for dimensionality reduction on the given dataset\&. This will save as many dimensions as necessary to retain at least the given amount of variance (specified by parameter varRetained)\&. The amount should be between 0 and 1; if the amount is 0, then only 1 dimension will be retained\&. If the amount is 1, then all dimensions will be retained\&.
.PP
The method returns the actual amount of variance retained, which will always be greater than or equal to the varRetained parameter\&.
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP Data matrix\&. 
.br
\fIvarRetained\fP Lower bound on amount of variance to retain; should be between 0 and 1\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Actual amount of variance retained (between 0 and 1)\&. 
.RE
.PP

.SS "template<typename DecompositionPolicy  = ExactSVDPolicy> bool \fBmlpack::pca::PCAType\fP< DecompositionPolicy >::ScaleData () const\fC [inline]\fP"

.PP
Get whether or not this PCA object will scale (by standard deviation) the data when PCA is performed\&. 
.PP
Definition at line 110 of file pca\&.hpp\&.
.PP
References mlpack::pca::PCAType< DecompositionPolicy >::scaleData\&.
.SS "template<typename DecompositionPolicy  = ExactSVDPolicy> bool& \fBmlpack::pca::PCAType\fP< DecompositionPolicy >::ScaleData ()\fC [inline]\fP"

.PP
Modify whether or not this PCA object will scale (by standard deviation) the data when PCA is performed\&. 
.PP
Definition at line 113 of file pca\&.hpp\&.
.PP
References mlpack::pca::PCAType< DecompositionPolicy >::scaleData\&.
.SS "template<typename DecompositionPolicy  = ExactSVDPolicy> void \fBmlpack::pca::PCAType\fP< DecompositionPolicy >::ScaleData (arma::mat & centeredData)\fC [inline]\fP, \fC [private]\fP"

.PP
Scaling the data is when we reduce the variance of each dimension to 1\&. 
.PP
Definition at line 117 of file pca\&.hpp\&.
.PP
References mlpack::pca::PCAType< DecompositionPolicy >::scaleData\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename DecompositionPolicy  = ExactSVDPolicy> DecompositionPolicy \fBmlpack::pca::PCAType\fP< DecompositionPolicy >::decomposition\fC [private]\fP"

.PP
Decomposition method used to perform principal components analysis\&. 
.PP
Definition at line 141 of file pca\&.hpp\&.
.SS "template<typename DecompositionPolicy  = ExactSVDPolicy> bool \fBmlpack::pca::PCAType\fP< DecompositionPolicy >::scaleData\fC [private]\fP"

.PP
Whether or not the data will be scaled by standard deviation when PCA is performed\&. 
.PP
Definition at line 138 of file pca\&.hpp\&.
.PP
Referenced by mlpack::pca::PCAType< DecompositionPolicy >::ScaleData()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
