.TH "mlpack::perceptron::ZeroInitialization" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::perceptron::ZeroInitialization \- This class is used to initialize the matrix weightVectors to zero\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBZeroInitialization\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBInitialize\fP (arma::mat &weights, arma::vec &biases, const size_t numFeatures, const size_t numClasses)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is used to initialize the matrix weightVectors to zero\&. 
.PP
Definition at line 23 of file zero_init\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mlpack::perceptron::ZeroInitialization::ZeroInitialization ()\fC [inline]\fP"

.PP
Definition at line 26 of file zero_init\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static void mlpack::perceptron::ZeroInitialization::Initialize (arma::mat & weights, arma::vec & biases, const size_t numFeatures, const size_t numClasses)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 28 of file zero_init\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
