.TH "mlpack::neighbor::LSHSearch< SortPolicy >::CandidateCmp" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::neighbor::LSHSearch< SortPolicy >::CandidateCmp \- Compare two candidates based on the distance\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBCandidate\fP &c1, const \fBCandidate\fP &c2)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename SortPolicy = NearestNeighborSort>
.br
struct mlpack::neighbor::LSHSearch< SortPolicy >::CandidateCmp"
Compare two candidates based on the distance\&. 
.PP
Definition at line 463 of file lsh_search\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename SortPolicy  = NearestNeighborSort> bool \fBmlpack::neighbor::LSHSearch\fP< SortPolicy >::CandidateCmp::operator() (const \fBCandidate\fP & c1, const \fBCandidate\fP & c2)\fC [inline]\fP"

.PP
Definition at line 464 of file lsh_search\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
