.TH "mlpack::bound::meta::IsLMetric< MetricType >" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::bound::meta::IsLMetric< MetricType > \- Utility struct where Value is true if and only if the argument is of type LMetric\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBValue\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename MetricType>
.br
struct mlpack::bound::meta::IsLMetric< MetricType >"
Utility struct where Value is true if and only if the argument is of type LMetric\&. 


.PP
Definition at line 30 of file hrectbound\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename MetricType > const bool \fBmlpack::bound::meta::IsLMetric\fP< MetricType >::Value = false\fC [static]\fP"

.PP
Definition at line 32 of file hrectbound\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
