.TH "mlpack::ann::SoftsignFunction" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::ann::SoftsignFunction \- The softsign function, defined by\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static double \fBDeriv\fP (const double y)"
.br
.RI "\fIComputes the first derivative of the softsign function\&. \fP"
.ti -1c
.RI "template<typename InputVecType , typename OutputVecType > static void \fBDeriv\fP (const InputVecType &y, OutputVecType &x)"
.br
.RI "\fIComputes the first derivatives of the softsign function\&. \fP"
.ti -1c
.RI "static double \fBFn\fP (const double x)"
.br
.RI "\fIComputes the softsign function\&. \fP"
.ti -1c
.RI "template<typename InputVecType , typename OutputVecType > static void \fBFn\fP (const InputVecType &x, OutputVecType &y)"
.br
.RI "\fIComputes the softsign function\&. \fP"
.ti -1c
.RI "static double \fBInv\fP (const double y)"
.br
.RI "\fIComputes the inverse of the softsign function\&. \fP"
.ti -1c
.RI "template<typename InputVecType , typename OutputVecType > static void \fBInv\fP (const InputVecType &y, OutputVecType &x)"
.br
.RI "\fIComputes the inverse of the softsign function\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The softsign function, defined by\&. 

\begin{eqnarray*} f(x) &=& \frac{x}{1 + |x|} \\ f'(x) &=& (1 - |x|)^2 \\ f(x) &=& \left\{ \begin{array}{lr} -\frac{y}{y-1} & : x > 0 \\ \frac{x}{1 + x} & : x \le 0 \end{array} \right. \end{eqnarray*} 
.PP
Definition at line 47 of file softsign_function\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static double mlpack::ann::SoftsignFunction::Deriv (const double y)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the first derivative of the softsign function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIy\fP Input data\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
f'(x) 
.RE
.PP

.PP
Definition at line 84 of file softsign_function\&.hpp\&.
.SS "template<typename InputVecType , typename OutputVecType > static void mlpack::ann::SoftsignFunction::Deriv (const InputVecType & y, OutputVecType & x)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the first derivatives of the softsign function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIy\fP Input activations\&. 
.br
\fIx\fP The resulting derivatives\&. 
.RE
.PP

.PP
Definition at line 96 of file softsign_function\&.hpp\&.
.SS "static double mlpack::ann::SoftsignFunction::Fn (const double x)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the softsign function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Input data\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
f(x)\&. 
.RE
.PP

.PP
Definition at line 56 of file softsign_function\&.hpp\&.
.PP
Referenced by Fn()\&.
.SS "template<typename InputVecType , typename OutputVecType > static void mlpack::ann::SoftsignFunction::Fn (const InputVecType & x, OutputVecType & y)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the softsign function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Input data\&. 
.br
\fIy\fP The resulting output activation\&. 
.RE
.PP

.PP
Definition at line 70 of file softsign_function\&.hpp\&.
.PP
References Fn()\&.
.SS "static double mlpack::ann::SoftsignFunction::Inv (const double y)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the inverse of the softsign function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIy\fP Input data\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
f^{-1}(y) 
.RE
.PP

.PP
Definition at line 107 of file softsign_function\&.hpp\&.
.PP
Referenced by Inv()\&.
.SS "template<typename InputVecType , typename OutputVecType > static void mlpack::ann::SoftsignFunction::Inv (const InputVecType & y, OutputVecType & x)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the inverse of the softsign function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIy\fP Input data\&. 
.br
\fIx\fP The resulting inverse of the input data\&. 
.RE
.PP

.PP
Definition at line 122 of file softsign_function\&.hpp\&.
.PP
References Inv()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
