.TH "mlpack::adaboost::AdaBoostModel" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::adaboost::AdaBoostModel \- The model to save to disk\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBWeakLearnerTypes\fP { \fBDECISION_STUMP\fP, \fBPERCEPTRON\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAdaBoostModel\fP ()"
.br
.RI "\fICreate an empty \fBAdaBoost\fP model\&. \fP"
.ti -1c
.RI "\fBAdaBoostModel\fP (const arma::Col< size_t > &\fBmappings\fP, const size_t \fBweakLearnerType\fP)"
.br
.RI "\fICreate the \fBAdaBoost\fP model with the given mappings and type\&. \fP"
.ti -1c
.RI "\fBAdaBoostModel\fP (const \fBAdaBoostModel\fP &other)"
.br
.RI "\fICopy constructor\&. \fP"
.ti -1c
.RI "\fBAdaBoostModel\fP (\fBAdaBoostModel\fP &&other)"
.br
.RI "\fIMove constructor\&. \fP"
.ti -1c
.RI "\fB~AdaBoostModel\fP ()"
.br
.RI "\fIClean up memory\&. \fP"
.ti -1c
.RI "void \fBClassify\fP (const arma::mat &testData, arma::Row< size_t > &predictions)"
.br
.RI "\fIClassify test points\&. \fP"
.ti -1c
.RI "size_t \fBDimensionality\fP () const "
.br
.RI "\fIGet the dimensionality of the model\&. \fP"
.ti -1c
.RI "size_t & \fBDimensionality\fP ()"
.br
.RI "\fIModify the dimensionality of the model\&. \fP"
.ti -1c
.RI "const arma::Col< size_t > & \fBMappings\fP () const "
.br
.RI "\fIGet the mappings\&. \fP"
.ti -1c
.RI "arma::Col< size_t > & \fBMappings\fP ()"
.br
.RI "\fIModify the mappings\&. \fP"
.ti -1c
.RI "\fBAdaBoostModel\fP & \fBoperator=\fP (const \fBAdaBoostModel\fP &other)"
.br
.RI "\fICopy assignment operator\&. \fP"
.ti -1c
.RI "template<typename Archive > void \fBSerialize\fP (Archive &ar, const unsigned int)"
.br
.RI "\fISerialize the model\&. \fP"
.ti -1c
.RI "void \fBTrain\fP (const arma::mat &data, const arma::Row< size_t > &labels, const size_t iterations, const double tolerance)"
.br
.RI "\fITrain the model\&. \fP"
.ti -1c
.RI "size_t \fBWeakLearnerType\fP () const "
.br
.RI "\fIGet the weak learner type\&. \fP"
.ti -1c
.RI "size_t & \fBWeakLearnerType\fP ()"
.br
.RI "\fIModify the weak learner type\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "size_t \fBdimensionality\fP"
.br
.RI "\fINumber of dimensions in training data\&. \fP"
.ti -1c
.RI "\fBAdaBoost\fP< \fBdecision_stump::DecisionStump\fP<> > * \fBdsBoost\fP"
.br
.RI "\fINon-NULL if using decision stumps\&. \fP"
.ti -1c
.RI "arma::Col< size_t > \fBmappings\fP"
.br
.RI "\fIThe mappings for the labels\&. \fP"
.ti -1c
.RI "\fBAdaBoost\fP< \fBperceptron::Perceptron\fP<> > * \fBpBoost\fP"
.br
.RI "\fINon-NULL if using perceptrons\&. \fP"
.ti -1c
.RI "size_t \fBweakLearnerType\fP"
.br
.RI "\fIThe type of weak learner\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The model to save to disk\&. 
.PP
Definition at line 19 of file adaboost_model\&.hpp\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBmlpack::adaboost::AdaBoostModel::WeakLearnerTypes\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDECISION_STUMP \fP\fP
.TP
\fB\fIPERCEPTRON \fP\fP
.PP
Definition at line 22 of file adaboost_model\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mlpack::adaboost::AdaBoostModel::AdaBoostModel ()"

.PP
Create an empty \fBAdaBoost\fP model\&. 
.SS "mlpack::adaboost::AdaBoostModel::AdaBoostModel (const arma::Col< size_t > & mappings, const size_t weakLearnerType)"

.PP
Create the \fBAdaBoost\fP model with the given mappings and type\&. 
.SS "mlpack::adaboost::AdaBoostModel::AdaBoostModel (const \fBAdaBoostModel\fP & other)"

.PP
Copy constructor\&. 
.SS "mlpack::adaboost::AdaBoostModel::AdaBoostModel (\fBAdaBoostModel\fP && other)"

.PP
Move constructor\&. 
.SS "mlpack::adaboost::AdaBoostModel::~AdaBoostModel ()"

.PP
Clean up memory\&. 
.SH "Member Function Documentation"
.PP 
.SS "void mlpack::adaboost::AdaBoostModel::Classify (const arma::mat & testData, arma::Row< size_t > & predictions)"

.PP
Classify test points\&. 
.PP
Referenced by Dimensionality()\&.
.SS "size_t mlpack::adaboost::AdaBoostModel::Dimensionality () const\fC [inline]\fP"

.PP
Get the dimensionality of the model\&. 
.PP
Definition at line 71 of file adaboost_model\&.hpp\&.
.PP
References dimensionality\&.
.SS "size_t& mlpack::adaboost::AdaBoostModel::Dimensionality ()\fC [inline]\fP"

.PP
Modify the dimensionality of the model\&. 
.PP
Definition at line 73 of file adaboost_model\&.hpp\&.
.PP
References Classify(), dimensionality, and Train()\&.
.SS "const arma::Col<size_t>& mlpack::adaboost::AdaBoostModel::Mappings () const\fC [inline]\fP"

.PP
Get the mappings\&. 
.PP
Definition at line 61 of file adaboost_model\&.hpp\&.
.PP
References mappings\&.
.SS "arma::Col<size_t>& mlpack::adaboost::AdaBoostModel::Mappings ()\fC [inline]\fP"

.PP
Modify the mappings\&. 
.PP
Definition at line 63 of file adaboost_model\&.hpp\&.
.PP
References mappings\&.
.SS "\fBAdaBoostModel\fP& mlpack::adaboost::AdaBoostModel::operator= (const \fBAdaBoostModel\fP & other)"

.PP
Copy assignment operator\&. 
.SS "template<typename Archive > void mlpack::adaboost::AdaBoostModel::Serialize (Archive & ar, const unsigned int)\fC [inline]\fP"

.PP
Serialize the model\&. 
.PP
Definition at line 86 of file adaboost_model\&.hpp\&.
.PP
References mlpack::data::CreateNVP(), dsBoost, and pBoost\&.
.SS "void mlpack::adaboost::AdaBoostModel::Train (const arma::mat & data, const arma::Row< size_t > & labels, const size_t iterations, const double tolerance)"

.PP
Train the model\&. 
.PP
Referenced by Dimensionality()\&.
.SS "size_t mlpack::adaboost::AdaBoostModel::WeakLearnerType () const\fC [inline]\fP"

.PP
Get the weak learner type\&. 
.PP
Definition at line 66 of file adaboost_model\&.hpp\&.
.PP
References weakLearnerType\&.
.SS "size_t& mlpack::adaboost::AdaBoostModel::WeakLearnerType ()\fC [inline]\fP"

.PP
Modify the weak learner type\&. 
.PP
Definition at line 68 of file adaboost_model\&.hpp\&.
.PP
References weakLearnerType\&.
.SH "Member Data Documentation"
.PP 
.SS "size_t mlpack::adaboost::AdaBoostModel::dimensionality\fC [private]\fP"

.PP
Number of dimensions in training data\&. 
.PP
Definition at line 38 of file adaboost_model\&.hpp\&.
.PP
Referenced by Dimensionality()\&.
.SS "\fBAdaBoost\fP<\fBdecision_stump::DecisionStump\fP<> >* mlpack::adaboost::AdaBoostModel::dsBoost\fC [private]\fP"

.PP
Non-NULL if using decision stumps\&. 
.PP
Definition at line 34 of file adaboost_model\&.hpp\&.
.PP
Referenced by Serialize()\&.
.SS "arma::Col<size_t> mlpack::adaboost::AdaBoostModel::mappings\fC [private]\fP"

.PP
The mappings for the labels\&. 
.PP
Definition at line 30 of file adaboost_model\&.hpp\&.
.PP
Referenced by Mappings()\&.
.SS "\fBAdaBoost\fP<\fBperceptron::Perceptron\fP<> >* mlpack::adaboost::AdaBoostModel::pBoost\fC [private]\fP"

.PP
Non-NULL if using perceptrons\&. 
.PP
Definition at line 36 of file adaboost_model\&.hpp\&.
.PP
Referenced by Serialize()\&.
.SS "size_t mlpack::adaboost::AdaBoostModel::weakLearnerType\fC [private]\fP"

.PP
The type of weak learner\&. 
.PP
Definition at line 32 of file adaboost_model\&.hpp\&.
.PP
Referenced by WeakLearnerType()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
