.TH "mlpack::tree::QueueFrame< TreeType, TraversalInfoType >" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::tree::QueueFrame< TreeType, TraversalInfoType > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBqueryDepth\fP"
.br
.ti -1c
.RI "TreeType * \fBqueryNode\fP"
.br
.ti -1c
.RI "TreeType * \fBreferenceNode\fP"
.br
.ti -1c
.RI "double \fBscore\fP"
.br
.ti -1c
.RI "TraversalInfoType \fBtraversalInfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename TreeType, typename TraversalInfoType>
.br
struct mlpack::tree::QueueFrame< TreeType, TraversalInfoType >"

.PP
Definition at line 27 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename TreeType , typename TraversalInfoType > size_t \fBmlpack::tree::QueueFrame\fP< TreeType, TraversalInfoType >::queryDepth"

.PP
Definition at line 31 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "template<typename TreeType , typename TraversalInfoType > TreeType* \fBmlpack::tree::QueueFrame\fP< TreeType, TraversalInfoType >::queryNode"

.PP
Definition at line 29 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "template<typename TreeType , typename TraversalInfoType > TreeType* \fBmlpack::tree::QueueFrame\fP< TreeType, TraversalInfoType >::referenceNode"

.PP
Definition at line 30 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "template<typename TreeType , typename TraversalInfoType > double \fBmlpack::tree::QueueFrame\fP< TreeType, TraversalInfoType >::score"

.PP
Definition at line 32 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "template<typename TreeType , typename TraversalInfoType > TraversalInfoType \fBmlpack::tree::QueueFrame\fP< TreeType, TraversalInfoType >::traversalInfo"

.PP
Definition at line 33 of file breadth_first_dual_tree_traverser\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
