.TH "mlpack::tree::IsSpillTree< TreeType >" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::tree::IsSpillTree< TreeType > \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBvalue\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename TreeType>
.br
struct mlpack::tree::IsSpillTree< TreeType >"

.PP
Definition at line 21 of file is_spill_tree\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename TreeType > const bool \fBmlpack::tree::IsSpillTree\fP< TreeType >::value = false\fC [static]\fP"

.PP
Definition at line 23 of file is_spill_tree\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
