.TH "mlpack::naive_bayes" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::naive_bayes \- The Naive Bayes Classifier\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNaiveBayesClassifier\fP"
.br
.RI "\fIThe simple Naive Bayes classifier\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The Naive Bayes Classifier\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
