.TH "mlpack::tree::TreeTraits< BinarySpaceTree< MetricType, StatisticType, MatType, bound::CellBound, SplitType > >" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::tree::TreeTraits< BinarySpaceTree< MetricType, StatisticType, MatType, bound::CellBound, SplitType > > \- This is a specialization of the TreeType class to the UBTree tree type\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBBinaryTree\fP = true"
.br
.ti -1c
.RI "static const bool \fBFirstPointIsCentroid\fP = false"
.br
.ti -1c
.RI "static const bool \fBHasDuplicatedPoints\fP = false"
.br
.ti -1c
.RI "static const bool \fBHasOverlappingChildren\fP = true"
.br
.ti -1c
.RI "static const bool \fBHasSelfChildren\fP = false"
.br
.ti -1c
.RI "static const bool \fBRearrangesDataset\fP = true"
.br
.ti -1c
.RI "static const bool \fBUniqueNumDescendants\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename MetricType, typename StatisticType, typename MatType, template< typename SplitBoundType, typename SplitMatType > class SplitType>
.br
class mlpack::tree::TreeTraits< BinarySpaceTree< MetricType, StatisticType, MatType, bound::CellBound, SplitType > >"
This is a specialization of the TreeType class to the UBTree tree type\&. 

The only difference with general \fBBinarySpaceTree\fP is that UBTree can have overlapping children\&. See \fBmlpack/core/tree/tree_traits\&.hpp\fP for more information\&. 
.PP
Definition at line 235 of file traits\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename MetricType , typename StatisticType , typename MatType , template< typename SplitBoundType, typename SplitMatType > class SplitType> const bool \fBmlpack::tree::TreeTraits\fP< \fBBinarySpaceTree\fP< MetricType, StatisticType, MatType, \fBbound::CellBound\fP, SplitType > >::BinaryTree = true\fC [static]\fP"

.PP
Definition at line 244 of file traits\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType , typename MatType , template< typename SplitBoundType, typename SplitMatType > class SplitType> const bool \fBmlpack::tree::TreeTraits\fP< \fBBinarySpaceTree\fP< MetricType, StatisticType, MatType, \fBbound::CellBound\fP, SplitType > >::FirstPointIsCentroid = false\fC [static]\fP"

.PP
Definition at line 241 of file traits\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType , typename MatType , template< typename SplitBoundType, typename SplitMatType > class SplitType> const bool \fBmlpack::tree::TreeTraits\fP< \fBBinarySpaceTree\fP< MetricType, StatisticType, MatType, \fBbound::CellBound\fP, SplitType > >::HasDuplicatedPoints = false\fC [static]\fP"

.PP
Definition at line 240 of file traits\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType , typename MatType , template< typename SplitBoundType, typename SplitMatType > class SplitType> const bool \fBmlpack::tree::TreeTraits\fP< \fBBinarySpaceTree\fP< MetricType, StatisticType, MatType, \fBbound::CellBound\fP, SplitType > >::HasOverlappingChildren = true\fC [static]\fP"

.PP
Definition at line 239 of file traits\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType , typename MatType , template< typename SplitBoundType, typename SplitMatType > class SplitType> const bool \fBmlpack::tree::TreeTraits\fP< \fBBinarySpaceTree\fP< MetricType, StatisticType, MatType, \fBbound::CellBound\fP, SplitType > >::HasSelfChildren = false\fC [static]\fP"

.PP
Definition at line 242 of file traits\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType , typename MatType , template< typename SplitBoundType, typename SplitMatType > class SplitType> const bool \fBmlpack::tree::TreeTraits\fP< \fBBinarySpaceTree\fP< MetricType, StatisticType, MatType, \fBbound::CellBound\fP, SplitType > >::RearrangesDataset = true\fC [static]\fP"

.PP
Definition at line 243 of file traits\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType , typename MatType , template< typename SplitBoundType, typename SplitMatType > class SplitType> const bool \fBmlpack::tree::TreeTraits\fP< \fBBinarySpaceTree\fP< MetricType, StatisticType, MatType, \fBbound::CellBound\fP, SplitType > >::UniqueNumDescendants = true\fC [static]\fP"

.PP
Definition at line 245 of file traits\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
