.TH "mlpack::bound::BoundTraits< BallBound< MetricType, VecType > >" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::bound::BoundTraits< BallBound< MetricType, VecType > > \- A specialization of \fBBoundTraits\fP for this bound type\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBHasTightBounds\fP = false"
.br
.RI "\fIThese bounds are potentially loose in some dimensions\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename MetricType, typename VecType>
.br
struct mlpack::bound::BoundTraits< BallBound< MetricType, VecType > >"
A specialization of \fBBoundTraits\fP for this bound type\&. 
.PP
Definition at line 196 of file ballbound\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename MetricType , typename VecType > const bool \fBmlpack::bound::BoundTraits\fP< \fBBallBound\fP< MetricType, VecType > >::HasTightBounds = false\fC [static]\fP"

.PP
These bounds are potentially loose in some dimensions\&. 
.PP
Definition at line 199 of file ballbound\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
