.TH "mlpack::tree::CompareCosineNode" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::tree::CompareCosineNode \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBCosineTree\fP *a, const \fBCosineTree\fP *b) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 246 of file cosine_tree\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool mlpack::tree::CompareCosineNode::operator() (const \fBCosineTree\fP * a, const \fBCosineTree\fP * b) const\fC [inline]\fP"

.PP
Definition at line 251 of file cosine_tree\&.hpp\&.
.PP
References mlpack::tree::CosineTree::L2Error()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
