.TH "mlpack::ann::BackwardVisitor" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::ann::BackwardVisitor \- \fBBackwardVisitor\fP executes the Backward() function given the input, error and delta parameter\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits static_visitor< void >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBackwardVisitor\fP (arma::mat &&\fBinput\fP, arma::mat &&\fBerror\fP, arma::mat &&\fBdelta\fP)"
.br
.RI "\fIExecute the Backward() function given the input, error and delta parameter\&. \fP"
.ti -1c
.RI "template<typename LayerType > void \fBoperator()\fP (LayerType *layer) const "
.br
.RI "\fIExecute the Backward() function\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "arma::mat && \fBdelta\fP"
.br
.RI "\fIThe delta parameter\&. \fP"
.ti -1c
.RI "arma::mat && \fBerror\fP"
.br
.RI "\fIThe error parameter\&. \fP"
.ti -1c
.RI "arma::mat && \fBinput\fP"
.br
.RI "\fIThe input parameter set\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBBackwardVisitor\fP executes the Backward() function given the input, error and delta parameter\&. 
.PP
Definition at line 28 of file backward_visitor\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mlpack::ann::BackwardVisitor::BackwardVisitor (arma::mat && input, arma::mat && error, arma::mat && delta)"

.PP
Execute the Backward() function given the input, error and delta parameter\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename LayerType > void mlpack::ann::BackwardVisitor::operator() (LayerType * layer) const"

.PP
Execute the Backward() function\&. 
.SH "Member Data Documentation"
.PP 
.SS "arma::mat&& mlpack::ann::BackwardVisitor::delta\fC [private]\fP"

.PP
The delta parameter\&. 
.PP
Definition at line 47 of file backward_visitor\&.hpp\&.
.SS "arma::mat&& mlpack::ann::BackwardVisitor::error\fC [private]\fP"

.PP
The error parameter\&. 
.PP
Definition at line 44 of file backward_visitor\&.hpp\&.
.SS "arma::mat&& mlpack::ann::BackwardVisitor::input\fC [private]\fP"

.PP
The input parameter set\&. 
.PP
Definition at line 41 of file backward_visitor\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
