.TH "mlpack::cf" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::cf \- Collaborative filtering\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCF\fP"
.br
.RI "\fIThis class implements Collaborative Filtering (\fBCF\fP)\&. \fP"
.ti -1c
.RI "class \fBDummyClass\fP"
.br
.RI "\fIThis class acts as a dummy class for passing as template parameter\&. \fP"
.ti -1c
.RI "struct \fBFactorizerTraits\fP"
.br
.RI "\fITemplate class for factorizer traits\&. \fP"
.ti -1c
.RI "class \fBFactorizerTraits< mlpack::svd::RegularizedSVD<> >\fP"
.br
.RI "\fIFactorizer traits of Regularized SVD\&. \fP"
.ti -1c
.RI "class \fBSVDWrapper\fP"
.br
.RI "\fIThis class acts as the wrapper for all SVD factorizers which are incompatible with \fBCF\fP module\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBSVDWrapper\fP< \fBDummyClass\fP > \fBArmaSVDFactorizer\fP"
.br
.RI "\fIadd simple typedefs \fP"
.in -1c
.SH "Detailed Description"
.PP 
Collaborative filtering\&. 


.SH "Typedef Documentation"
.PP 
.SS "typedef \fBSVDWrapper\fP<\fBDummyClass\fP> \fBmlpack::cf::ArmaSVDFactorizer\fP"

.PP
add simple typedefs 
.PP
Definition at line 83 of file svd_wrapper\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
