.TH "mlpack::svd::RandomizedSVD" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::svd::RandomizedSVD \- Randomized SVD is a matrix factorization that is based on randomized matrix approximation techniques, developed in in 'Finding structure with randomness:
Probabilistic algorithms for constructing approximate matrix decompositions'\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRandomizedSVD\fP (const arma::mat &data, arma::mat &u, arma::vec &s, arma::mat &v, const size_t \fBiteratedPower\fP=0, const size_t \fBmaxIterations\fP=2, const size_t rank=0, const double \fBeps\fP=1e\-7)"
.br
.RI "\fICreate object for the randomized SVD method\&. \fP"
.ti -1c
.RI "\fBRandomizedSVD\fP (const size_t \fBiteratedPower\fP=0, const size_t \fBmaxIterations\fP=2, const double \fBeps\fP=1e\-7)"
.br
.RI "\fICreate object for the randomized SVD method\&. \fP"
.ti -1c
.RI "void \fBApply\fP (const arma::mat &data, arma::mat &u, arma::vec &s, arma::mat &v, const size_t rank)"
.br
.RI "\fIApply Principal Component Analysis to the provided data set using the randomized SVD\&. \fP"
.ti -1c
.RI "double \fBEpsilon\fP () const "
.br
.RI "\fIGet the value used for decomposition stability\&. \fP"
.ti -1c
.RI "double & \fBEpsilon\fP ()"
.br
.RI "\fIModify the value used for decomposition stability\&. \fP"
.ti -1c
.RI "size_t \fBIteratedPower\fP () const "
.br
.RI "\fIGet the size of the normalized power iterations\&. \fP"
.ti -1c
.RI "size_t & \fBIteratedPower\fP ()"
.br
.RI "\fIModify the size of the normalized power iterations\&. \fP"
.ti -1c
.RI "size_t \fBMaxIterations\fP () const "
.br
.RI "\fIGet the number of iterations for the power method\&. \fP"
.ti -1c
.RI "size_t & \fBMaxIterations\fP ()"
.br
.RI "\fIModify the number of iterations for the power method\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBeps\fP"
.br
.RI "\fIThe value used for numerical stability\&. \fP"
.ti -1c
.RI "size_t \fBiteratedPower\fP"
.br
.RI "\fILocally stored size of the normalized power iterations\&. \fP"
.ti -1c
.RI "size_t \fBmaxIterations\fP"
.br
.RI "\fILocally stored number of iterations for the power method\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Randomized SVD is a matrix factorization that is based on randomized matrix approximation techniques, developed in in 'Finding structure with randomness:
Probabilistic algorithms for constructing approximate matrix decompositions'\&. 

For more information, see the following\&.
.PP
.PP
.nf
@article{Halko2011,
  author  = {Halko, N\&. and Martinsson, P\&. G\&. and Tropp, J\&. A\&.},
  title   = {Finding Structure with Randomness: Probabilistic Algorithms for
             Constructing Approximate Matrix Decompositions},
  journal = {SIAM Rev\&.},
  volume  = {53},
  year    = {2011},
}
.fi
.PP
.PP
.PP
.nf
@article{Szlam2014,
  author  = {Arthur Szlam Yuval Kluger and Mark Tygert},
  title   = {An implementation of a randomized algorithm for principal
             component analysis},
  journal = {CoRR},
  volume  = {abs/1412\&.3510},
  year    = {2014},
}
.fi
.PP
.PP
An example of how to use the interface is shown below:
.PP
.PP
.nf
arma::mat data; // Rating data in the form of coordinate list\&.

const size_t rank = 20; // Rank used for the decomposition\&.

// Make a RandomizedSVD object\&.
RandomizedSVD rSVD();

arma::mat u, s, v;

// Use the Apply() method to get a factorization\&.
rSVD\&.Apply(data, u, s, v, rank);
.fi
.PP
 
.PP
Definition at line 66 of file randomized_svd\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mlpack::svd::RandomizedSVD::RandomizedSVD (const arma::mat & data, arma::mat & u, arma::vec & s, arma::mat & v, const size_t iteratedPower = \fC0\fP, const size_t maxIterations = \fC2\fP, const size_t rank = \fC0\fP, const double eps = \fC1e\-7\fP)"

.PP
Create object for the randomized SVD method\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP Data matrix\&. 
.br
\fIu\fP First unitary matrix\&. 
.br
\fIv\fP Second unitary matrix\&. 
.br
\fIsigma\fP Diagonal matrix of singular values\&. 
.br
\fIiteratedPower\fP Size of the normalized power iterations (Default: rank + 2)\&. 
.br
\fImaxIterations\fP Number of iterations for the power method (Default: 2)\&. 
.br
\fIrank\fP Rank of the approximation (Default: number of rows\&.) 
.br
\fIeps\fP The eps coefficient to avoid division by zero (numerical stability)\&. 
.RE
.PP

.SS "mlpack::svd::RandomizedSVD::RandomizedSVD (const size_t iteratedPower = \fC0\fP, const size_t maxIterations = \fC2\fP, const double eps = \fC1e\-7\fP)"

.PP
Create object for the randomized SVD method\&. 
.PP
\fBParameters:\fP
.RS 4
\fIiteratedPower\fP Size of the normalized power iterations (Default: rank + 2)\&. 
.br
\fImaxIterations\fP Number of iterations for the power method (Default: 2)\&. 
.br
\fIeps\fP The eps coefficient to avoid division by zero (numerical stability)\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void mlpack::svd::RandomizedSVD::Apply (const arma::mat & data, arma::mat & u, arma::vec & s, arma::mat & v, const size_t rank)"

.PP
Apply Principal Component Analysis to the provided data set using the randomized SVD\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP Data matrix\&. 
.br
\fIu\fP First unitary matrix\&. 
.br
\fIv\fP Second unitary matrix\&. 
.br
\fIsigma\fP Diagonal matrix of singular values\&. 
.br
\fIrank\fP Rank of the approximation\&. 
.RE
.PP

.PP
Referenced by mlpack::pca::RandomizedSVDPolicy::Apply()\&.
.SS "double mlpack::svd::RandomizedSVD::Epsilon () const\fC [inline]\fP"

.PP
Get the value used for decomposition stability\&. 
.PP
Definition at line 134 of file randomized_svd\&.hpp\&.
.PP
References eps\&.
.SS "double& mlpack::svd::RandomizedSVD::Epsilon ()\fC [inline]\fP"

.PP
Modify the value used for decomposition stability\&. 
.PP
Definition at line 136 of file randomized_svd\&.hpp\&.
.PP
References eps\&.
.SS "size_t mlpack::svd::RandomizedSVD::IteratedPower () const\fC [inline]\fP"

.PP
Get the size of the normalized power iterations\&. 
.PP
Definition at line 124 of file randomized_svd\&.hpp\&.
.PP
References iteratedPower\&.
.SS "size_t& mlpack::svd::RandomizedSVD::IteratedPower ()\fC [inline]\fP"

.PP
Modify the size of the normalized power iterations\&. 
.PP
Definition at line 126 of file randomized_svd\&.hpp\&.
.PP
References iteratedPower\&.
.SS "size_t mlpack::svd::RandomizedSVD::MaxIterations () const\fC [inline]\fP"

.PP
Get the number of iterations for the power method\&. 
.PP
Definition at line 129 of file randomized_svd\&.hpp\&.
.PP
References maxIterations\&.
.SS "size_t& mlpack::svd::RandomizedSVD::MaxIterations ()\fC [inline]\fP"

.PP
Modify the number of iterations for the power method\&. 
.PP
Definition at line 131 of file randomized_svd\&.hpp\&.
.PP
References maxIterations\&.
.SH "Member Data Documentation"
.PP 
.SS "double mlpack::svd::RandomizedSVD::eps\fC [private]\fP"

.PP
The value used for numerical stability\&. 
.PP
Definition at line 146 of file randomized_svd\&.hpp\&.
.PP
Referenced by Epsilon()\&.
.SS "size_t mlpack::svd::RandomizedSVD::iteratedPower\fC [private]\fP"

.PP
Locally stored size of the normalized power iterations\&. 
.PP
Definition at line 140 of file randomized_svd\&.hpp\&.
.PP
Referenced by IteratedPower()\&.
.SS "size_t mlpack::svd::RandomizedSVD::maxIterations\fC [private]\fP"

.PP
Locally stored number of iterations for the power method\&. 
.PP
Definition at line 143 of file randomized_svd\&.hpp\&.
.PP
Referenced by MaxIterations()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
