.TH "mlpack::ann::IdentityFunction" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::ann::IdentityFunction \- The identity function, defined by\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static double \fBDeriv\fP (const double)"
.br
.RI "\fIComputes the first derivative of the identity function\&. \fP"
.ti -1c
.RI "template<typename InputVecType , typename OutputVecType > static void \fBDeriv\fP (const InputVecType &y, OutputVecType &x)"
.br
.RI "\fIComputes the first derivatives of the identity function\&. \fP"
.ti -1c
.RI "template<typename eT > static void \fBDeriv\fP (const arma::Cube< eT > &y, arma::Cube< eT > &x)"
.br
.RI "\fIComputes the first derivatives of the identity function using a 3rd order tensor as input\&. \fP"
.ti -1c
.RI "static double \fBFn\fP (const double x)"
.br
.RI "\fIComputes the identity function\&. \fP"
.ti -1c
.RI "template<typename InputVecType , typename OutputVecType > static void \fBFn\fP (const InputVecType &x, OutputVecType &y)"
.br
.RI "\fIComputes the identity function\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The identity function, defined by\&. 

\begin{eqnarray*} f(x) &=& x \\ f'(x) &=& 1 \end{eqnarray*} 
.PP
Definition at line 28 of file identity_function\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static double mlpack::ann::IdentityFunction::Deriv (const double)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the first derivative of the identity function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Input data\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
f'(x) 
.RE
.PP

.PP
Definition at line 60 of file identity_function\&.hpp\&.
.SS "template<typename InputVecType , typename OutputVecType > static void mlpack::ann::IdentityFunction::Deriv (const InputVecType & y, OutputVecType & x)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the first derivatives of the identity function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIy\fP Input activations\&. 
.br
\fIx\fP The resulting derivatives\&. 
.RE
.PP

.PP
Definition at line 72 of file identity_function\&.hpp\&.
.SS "template<typename eT > static void mlpack::ann::IdentityFunction::Deriv (const arma::Cube< eT > & y, arma::Cube< eT > & x)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the first derivatives of the identity function using a 3rd order tensor as input\&. 
.PP
\fBParameters:\fP
.RS 4
\fIy\fP Input activations\&. 
.br
\fIx\fP The resulting derivatives\&. 
.RE
.PP

.PP
Definition at line 85 of file identity_function\&.hpp\&.
.SS "static double mlpack::ann::IdentityFunction::Fn (const double x)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the identity function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Input data\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
f(x)\&. 
.RE
.PP

.PP
Definition at line 37 of file identity_function\&.hpp\&.
.SS "template<typename InputVecType , typename OutputVecType > static void mlpack::ann::IdentityFunction::Fn (const InputVecType & x, OutputVecType & y)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the identity function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Input data\&. 
.br
\fIy\fP The resulting output activation\&. 
.RE
.PP

.PP
Definition at line 49 of file identity_function\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
