.TH "mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::BreadthFirstDualTreeTraverser< RuleType >" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::BreadthFirstDualTreeTraverser< RuleType > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBQueueFrame\fP< \fBBinarySpaceTree\fP, typename RuleType::TraversalInfoType > \fBQueueFrameType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBreadthFirstDualTreeTraverser\fP (RuleType &\fBrule\fP)"
.br
.RI "\fIInstantiate the dual-tree traverser with the given rule set\&. \fP"
.ti -1c
.RI "size_t \fBNumBaseCases\fP () const "
.br
.RI "\fIGet the number of times a base case was calculated\&. \fP"
.ti -1c
.RI "size_t & \fBNumBaseCases\fP ()"
.br
.RI "\fIModify the number of times a base case was calculated\&. \fP"
.ti -1c
.RI "size_t \fBNumPrunes\fP () const "
.br
.RI "\fIGet the number of prunes\&. \fP"
.ti -1c
.RI "size_t & \fBNumPrunes\fP ()"
.br
.RI "\fIModify the number of prunes\&. \fP"
.ti -1c
.RI "size_t \fBNumScores\fP () const "
.br
.RI "\fIGet the number of times a node combination was scored\&. \fP"
.ti -1c
.RI "size_t & \fBNumScores\fP ()"
.br
.RI "\fIModify the number of times a node combination was scored\&. \fP"
.ti -1c
.RI "size_t \fBNumVisited\fP () const "
.br
.RI "\fIGet the number of visited combinations\&. \fP"
.ti -1c
.RI "size_t & \fBNumVisited\fP ()"
.br
.RI "\fIModify the number of visited combinations\&. \fP"
.ti -1c
.RI "void \fBTraverse\fP (\fBBinarySpaceTree\fP &queryNode, \fBBinarySpaceTree\fP &referenceNode)"
.br
.RI "\fITraverse the two trees\&. \fP"
.ti -1c
.RI "void \fBTraverse\fP (\fBBinarySpaceTree\fP &queryNode, std::priority_queue< \fBQueueFrameType\fP > &referenceQueue)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "size_t \fBnumBaseCases\fP"
.br
.RI "\fIThe number of times a base case was calculated\&. \fP"
.ti -1c
.RI "size_t \fBnumPrunes\fP"
.br
.RI "\fIThe number of prunes\&. \fP"
.ti -1c
.RI "size_t \fBnumScores\fP"
.br
.RI "\fIThe number of times a node combination was scored\&. \fP"
.ti -1c
.RI "size_t \fBnumVisited\fP"
.br
.RI "\fIThe number of node combinations that have been visited during traversal\&. \fP"
.ti -1c
.RI "RuleType & \fBrule\fP"
.br
.RI "\fIReference to the rules with which the trees will be traversed\&. \fP"
.ti -1c
.RI "RuleType::TraversalInfoType \fBtraversalInfo\fP"
.br
.RI "\fITraversal information, held in the class so that it isn't continually being reallocated\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename MetricType, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename\&.\&.\&. > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit>
.br
template<typename RuleType>
.br
class mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::BreadthFirstDualTreeTraverser< RuleType >"

.PP
Definition at line 103 of file binary_space_tree\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename BoundMetricType, typename\&.\&.\&. > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename RuleType > typedef \fBQueueFrame\fP<\fBBinarySpaceTree\fP, typename RuleType::TraversalInfoType> \fBmlpack::tree::BinarySpaceTree\fP< MetricType, StatisticType, MatType, BoundType, SplitType >::\fBBreadthFirstDualTreeTraverser\fP< RuleType >::\fBQueueFrameType\fP"

.PP
Definition at line 53 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename BoundMetricType, typename\&.\&.\&. > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename RuleType > \fBmlpack::tree::BinarySpaceTree\fP< MetricType, StatisticType, MatType, BoundType, SplitType >::\fBBreadthFirstDualTreeTraverser\fP< RuleType >::\fBBreadthFirstDualTreeTraverser\fP (RuleType & rule)"

.PP
Instantiate the dual-tree traverser with the given rule set\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename BoundMetricType, typename\&.\&.\&. > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename RuleType > size_t \fBmlpack::tree::BinarySpaceTree\fP< MetricType, StatisticType, MatType, BoundType, SplitType >::\fBBreadthFirstDualTreeTraverser\fP< RuleType >::NumBaseCases () const\fC [inline]\fP"

.PP
Get the number of times a base case was calculated\&. 
.PP
Definition at line 83 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename BoundMetricType, typename\&.\&.\&. > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename RuleType > size_t& \fBmlpack::tree::BinarySpaceTree\fP< MetricType, StatisticType, MatType, BoundType, SplitType >::\fBBreadthFirstDualTreeTraverser\fP< RuleType >::NumBaseCases ()\fC [inline]\fP"

.PP
Modify the number of times a base case was calculated\&. 
.PP
Definition at line 85 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename BoundMetricType, typename\&.\&.\&. > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename RuleType > size_t \fBmlpack::tree::BinarySpaceTree\fP< MetricType, StatisticType, MatType, BoundType, SplitType >::\fBBreadthFirstDualTreeTraverser\fP< RuleType >::NumPrunes () const\fC [inline]\fP"

.PP
Get the number of prunes\&. 
.PP
Definition at line 68 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename BoundMetricType, typename\&.\&.\&. > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename RuleType > size_t& \fBmlpack::tree::BinarySpaceTree\fP< MetricType, StatisticType, MatType, BoundType, SplitType >::\fBBreadthFirstDualTreeTraverser\fP< RuleType >::NumPrunes ()\fC [inline]\fP"

.PP
Modify the number of prunes\&. 
.PP
Definition at line 70 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename BoundMetricType, typename\&.\&.\&. > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename RuleType > size_t \fBmlpack::tree::BinarySpaceTree\fP< MetricType, StatisticType, MatType, BoundType, SplitType >::\fBBreadthFirstDualTreeTraverser\fP< RuleType >::NumScores () const\fC [inline]\fP"

.PP
Get the number of times a node combination was scored\&. 
.PP
Definition at line 78 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename BoundMetricType, typename\&.\&.\&. > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename RuleType > size_t& \fBmlpack::tree::BinarySpaceTree\fP< MetricType, StatisticType, MatType, BoundType, SplitType >::\fBBreadthFirstDualTreeTraverser\fP< RuleType >::NumScores ()\fC [inline]\fP"

.PP
Modify the number of times a node combination was scored\&. 
.PP
Definition at line 80 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename BoundMetricType, typename\&.\&.\&. > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename RuleType > size_t \fBmlpack::tree::BinarySpaceTree\fP< MetricType, StatisticType, MatType, BoundType, SplitType >::\fBBreadthFirstDualTreeTraverser\fP< RuleType >::NumVisited () const\fC [inline]\fP"

.PP
Get the number of visited combinations\&. 
.PP
Definition at line 73 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename BoundMetricType, typename\&.\&.\&. > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename RuleType > size_t& \fBmlpack::tree::BinarySpaceTree\fP< MetricType, StatisticType, MatType, BoundType, SplitType >::\fBBreadthFirstDualTreeTraverser\fP< RuleType >::NumVisited ()\fC [inline]\fP"

.PP
Modify the number of visited combinations\&. 
.PP
Definition at line 75 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename BoundMetricType, typename\&.\&.\&. > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename RuleType > void \fBmlpack::tree::BinarySpaceTree\fP< MetricType, StatisticType, MatType, BoundType, SplitType >::\fBBreadthFirstDualTreeTraverser\fP< RuleType >::Traverse (\fBBinarySpaceTree\fP & queryNode, \fBBinarySpaceTree\fP & referenceNode)"

.PP
Traverse the two trees\&. This does not reset the number of prunes\&.
.PP
\fBParameters:\fP
.RS 4
\fIqueryNode\fP The query node to be traversed\&. 
.br
\fIreferenceNode\fP The reference node to be traversed\&. 
.br
\fIscore\fP The score of the current node combination\&. 
.RE
.PP

.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename BoundMetricType, typename\&.\&.\&. > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename RuleType > void \fBmlpack::tree::BinarySpaceTree\fP< MetricType, StatisticType, MatType, BoundType, SplitType >::\fBBreadthFirstDualTreeTraverser\fP< RuleType >::Traverse (\fBBinarySpaceTree\fP & queryNode, std::priority_queue< \fBQueueFrameType\fP > & referenceQueue)"

.SH "Member Data Documentation"
.PP 
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename BoundMetricType, typename\&.\&.\&. > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename RuleType > size_t \fBmlpack::tree::BinarySpaceTree\fP< MetricType, StatisticType, MatType, BoundType, SplitType >::\fBBreadthFirstDualTreeTraverser\fP< RuleType >::numBaseCases\fC [private]\fP"

.PP
The number of times a base case was calculated\&. 
.PP
Definition at line 101 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename BoundMetricType, typename\&.\&.\&. > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename RuleType > size_t \fBmlpack::tree::BinarySpaceTree\fP< MetricType, StatisticType, MatType, BoundType, SplitType >::\fBBreadthFirstDualTreeTraverser\fP< RuleType >::numPrunes\fC [private]\fP"

.PP
The number of prunes\&. 
.PP
Definition at line 92 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename BoundMetricType, typename\&.\&.\&. > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename RuleType > size_t \fBmlpack::tree::BinarySpaceTree\fP< MetricType, StatisticType, MatType, BoundType, SplitType >::\fBBreadthFirstDualTreeTraverser\fP< RuleType >::numScores\fC [private]\fP"

.PP
The number of times a node combination was scored\&. 
.PP
Definition at line 98 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename BoundMetricType, typename\&.\&.\&. > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename RuleType > size_t \fBmlpack::tree::BinarySpaceTree\fP< MetricType, StatisticType, MatType, BoundType, SplitType >::\fBBreadthFirstDualTreeTraverser\fP< RuleType >::numVisited\fC [private]\fP"

.PP
The number of node combinations that have been visited during traversal\&. 
.PP
Definition at line 95 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename BoundMetricType, typename\&.\&.\&. > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename RuleType > RuleType& \fBmlpack::tree::BinarySpaceTree\fP< MetricType, StatisticType, MatType, BoundType, SplitType >::\fBBreadthFirstDualTreeTraverser\fP< RuleType >::rule\fC [private]\fP"

.PP
Reference to the rules with which the trees will be traversed\&. 
.PP
Definition at line 89 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename BoundMetricType, typename\&.\&.\&. > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename RuleType > RuleType::TraversalInfoType \fBmlpack::tree::BinarySpaceTree\fP< MetricType, StatisticType, MatType, BoundType, SplitType >::\fBBreadthFirstDualTreeTraverser\fP< RuleType >::traversalInfo\fC [private]\fP"

.PP
Traversal information, held in the class so that it isn't continually being reallocated\&. 
.PP
Definition at line 105 of file breadth_first_dual_tree_traverser\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
