.TH "mlpack::ann::MeanPoolingRule" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::ann::MeanPoolingRule \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename MatType > double \fBPooling\fP (const MatType &input)"
.br
.ti -1c
.RI "template<typename MatType > void \fBUnpooling\fP (const MatType &input, const double value, MatType &output)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file glimpse\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename MatType > double mlpack::ann::MeanPoolingRule::Pooling (const MatType & input)\fC [inline]\fP"

.PP
Definition at line 46 of file glimpse\&.hpp\&.
.SS "template<typename MatType > void mlpack::ann::MeanPoolingRule::Unpooling (const MatType & input, const double value, MatType & output)\fC [inline]\fP"

.PP
Definition at line 59 of file glimpse\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
