.TH "mlpack::ann::DeleteVisitor" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::ann::DeleteVisitor \- \fBDeleteVisitor\fP executes the destructor of the instantiated object\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits static_visitor< void >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename LayerType > void \fBoperator()\fP (LayerType *layer) const "
.br
.RI "\fIExecute the destructor\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBDeleteVisitor\fP executes the destructor of the instantiated object\&. 
.PP
Definition at line 27 of file delete_visitor\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename LayerType > void mlpack::ann::DeleteVisitor::operator() (LayerType * layer) const"

.PP
Execute the destructor\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
