.TH "mlpack::meanshift" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::meanshift \- Mean shift clustering\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMeanShift\fP"
.br
.RI "\fIThis class implements mean shift clustering\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Mean shift clustering\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
