.TH "mlpack::neighbor::NSModelName< NearestNeighborSort >" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::neighbor::NSModelName< NearestNeighborSort > \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const \fBstd::string\fP \fBName\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
struct mlpack::neighbor::NSModelName< NearestNeighborSort >"

.PP
Definition at line 51 of file ns_model\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static const \fBstd::string\fP \fBmlpack::neighbor::NSModelName\fP< \fBNearestNeighborSort\fP >::Name ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 53 of file ns_model\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
