.TH "mlpack::cf::CF::CandidateCmp" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::cf::CF::CandidateCmp \- Compare two candidates based on the value\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBCandidate\fP &c1, const \fBCandidate\fP &c2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Compare two candidates based on the value\&. 
.PP
Definition at line 269 of file cf\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool mlpack::cf::CF::CandidateCmp::operator() (const \fBCandidate\fP & c1, const \fBCandidate\fP & c2)\fC [inline]\fP"

.PP
Definition at line 270 of file cf\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
