.TH "mlpack::bound::meta::IsLMetric< metric::LMetric< Power, TakeRoot > >" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::bound::meta::IsLMetric< metric::LMetric< Power, TakeRoot > > \- Specialization for \fBIsLMetric\fP when the argument is of type LMetric\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBValue\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<int Power, bool TakeRoot>
.br
struct mlpack::bound::meta::IsLMetric< metric::LMetric< Power, TakeRoot > >"
Specialization for \fBIsLMetric\fP when the argument is of type LMetric\&. 
.PP
Definition at line 37 of file hrectbound\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<int Power, bool TakeRoot> const bool \fBmlpack::bound::meta::IsLMetric\fP< \fBmetric::LMetric\fP< Power, TakeRoot > >::Value = true\fC [static]\fP"

.PP
Definition at line 39 of file hrectbound\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
