.TH "mlpack::util::ParameterType< arma::Mat< eT > >" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::util::ParameterType< arma::Mat< eT > > \- For matrix types, boost::program_options will accept a std::string, not an arma::mat (since it is not clear how to specify a matrix on the command-line)\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBstd::string\fP \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename eT>
.br
struct mlpack::util::ParameterType< arma::Mat< eT > >"
For matrix types, boost::program_options will accept a std::string, not an arma::mat (since it is not clear how to specify a matrix on the command-line)\&. 
.PP
Definition at line 63 of file param_data\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename eT > typedef \fBstd::string\fP \fBmlpack::util::ParameterType\fP< arma::Mat< eT > >::\fBtype\fP"

.PP
Definition at line 65 of file param_data\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
