.TH "mlpack::range::ReferenceSetVisitor" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::range::ReferenceSetVisitor \- \fBReferenceSetVisitor\fP exposes the referenceSet of the given RSType\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits static_visitor< const arma::mat & >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename RSType > const arma::mat & \fBoperator()\fP (\fBRSType\fP *rs) const "
.br
.RI "\fIReturn the reference set\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBReferenceSetVisitor\fP exposes the referenceSet of the given RSType\&. 
.PP
Definition at line 171 of file rs_model\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename RSType > const arma::mat& mlpack::range::ReferenceSetVisitor::operator() (\fBRSType\fP * rs) const"

.PP
Return the reference set\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
