.TH "mlpack::tree::RPTreeMaxSplit< BoundType, MatType >::SplitInfo" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::tree::RPTreeMaxSplit< BoundType, MatType >::SplitInfo \- An information about the partition\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "arma::Col< \fBElemType\fP > \fBdirection\fP"
.br
.RI "\fIThe normal vector to the hyperplane that splits the node\&. \fP"
.ti -1c
.RI "\fBElemType\fP \fBsplitVal\fP"
.br
.RI "\fIThe value according to which the node is being split\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename BoundType, typename MatType = arma::mat>
.br
struct mlpack::tree::RPTreeMaxSplit< BoundType, MatType >::SplitInfo"
An information about the partition\&. 
.PP
Definition at line 38 of file rp_tree_max_split\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename BoundType , typename MatType  = arma::mat> arma::Col<\fBElemType\fP> \fBmlpack::tree::RPTreeMaxSplit\fP< BoundType, MatType >::SplitInfo::direction"

.PP
The normal vector to the hyperplane that splits the node\&. 
.PP
Definition at line 41 of file rp_tree_max_split\&.hpp\&.
.PP
Referenced by mlpack::tree::RPTreeMaxSplit< BoundType, MatType >::AssignToLeftNode()\&.
.SS "template<typename BoundType , typename MatType  = arma::mat> \fBElemType\fP \fBmlpack::tree::RPTreeMaxSplit\fP< BoundType, MatType >::SplitInfo::splitVal"

.PP
The value according to which the node is being split\&. 
.PP
Definition at line 43 of file rp_tree_max_split\&.hpp\&.
.PP
Referenced by mlpack::tree::RPTreeMaxSplit< BoundType, MatType >::AssignToLeftNode()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
