.TH "mlpack::tree::SpillTree< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::SpillDualTreeTraverser< MetricType, StatisticType, MatType, HyperplaneType, SplitType >" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::tree::SpillTree< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::SpillDualTreeTraverser< MetricType, StatisticType, MatType, HyperplaneType, SplitType > \- A generic dual-tree traverser for hybrid spill trees; see \fBspill_dual_tree_traverser\&.hpp\fP for implementation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpillDualTreeTraverser\fP (RuleType &\fBrule\fP)"
.br
.RI "\fIInstantiate the dual-tree traverser with the given rule set\&. \fP"
.ti -1c
.RI "size_t \fBNumBaseCases\fP () const "
.br
.RI "\fIGet the number of times a base case was calculated\&. \fP"
.ti -1c
.RI "size_t & \fBNumBaseCases\fP ()"
.br
.RI "\fIModify the number of times a base case was calculated\&. \fP"
.ti -1c
.RI "size_t \fBNumPrunes\fP () const "
.br
.RI "\fIGet the number of prunes\&. \fP"
.ti -1c
.RI "size_t & \fBNumPrunes\fP ()"
.br
.RI "\fIModify the number of prunes\&. \fP"
.ti -1c
.RI "size_t \fBNumScores\fP () const "
.br
.RI "\fIGet the number of times a node combination was scored\&. \fP"
.ti -1c
.RI "size_t & \fBNumScores\fP ()"
.br
.RI "\fIModify the number of times a node combination was scored\&. \fP"
.ti -1c
.RI "size_t \fBNumVisited\fP () const "
.br
.RI "\fIGet the number of visited combinations\&. \fP"
.ti -1c
.RI "size_t & \fBNumVisited\fP ()"
.br
.RI "\fIModify the number of visited combinations\&. \fP"
.ti -1c
.RI "void \fBTraverse\fP (\fBSpillTree\fP &queryNode, \fBSpillTree\fP &referenceNode)"
.br
.RI "\fITraverse the two trees\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "size_t \fBnumBaseCases\fP"
.br
.RI "\fIThe number of times a base case was calculated\&. \fP"
.ti -1c
.RI "size_t \fBnumPrunes\fP"
.br
.RI "\fIThe number of prunes\&. \fP"
.ti -1c
.RI "size_t \fBnumScores\fP"
.br
.RI "\fIThe number of times a node combination was scored\&. \fP"
.ti -1c
.RI "size_t \fBnumVisited\fP"
.br
.RI "\fIThe number of node combinations that have been visited during traversal\&. \fP"
.ti -1c
.RI "RuleType & \fBrule\fP"
.br
.RI "\fIReference to the rules with which the trees will be traversed\&. \fP"
.ti -1c
.RI "RuleType::TraversalInfoType \fBtraversalInfo\fP"
.br
.RI "\fITraversal information, held in the class so that it isn't continually being reallocated\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename MetricType, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename HyperplaneMetricType > class HyperplaneType = AxisOrthogonalHyperplane, template< typename SplitMetricType, typename SplitMatType > class SplitType = MidpointSpaceSplit>
.br
template<typename MetricType, typename StatisticType, typename MatType, template< typename HyperplaneMetricType > class HyperplaneType, template< typename SplitMetricType, typename SplitMatType > class SplitType>
.br
class mlpack::tree::SpillTree< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::SpillDualTreeTraverser< MetricType, StatisticType, MatType, HyperplaneType, SplitType >"
A generic dual-tree traverser for hybrid spill trees; see \fBspill_dual_tree_traverser\&.hpp\fP for implementation\&. 

The Defeatist template parameter determines if the traverser must do defeatist search on overlapping nodes\&. 
.PP
Definition at line 35 of file spill_dual_tree_traverser\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename HyperplaneMetricType > class HyperplaneType = AxisOrthogonalHyperplane, template< typename SplitMetricType, typename SplitMatType > class SplitType = MidpointSpaceSplit> template<typename MetricType , typename StatisticType , typename MatType , template< typename HyperplaneMetricType > class HyperplaneType, template< typename SplitMetricType, typename SplitMatType > class SplitType> \fBmlpack::tree::SpillTree\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::\fBSpillDualTreeTraverser\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::\fBSpillDualTreeTraverser\fP (RuleType & rule)"

.PP
Instantiate the dual-tree traverser with the given rule set\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename HyperplaneMetricType > class HyperplaneType = AxisOrthogonalHyperplane, template< typename SplitMetricType, typename SplitMatType > class SplitType = MidpointSpaceSplit> template<typename MetricType , typename StatisticType , typename MatType , template< typename HyperplaneMetricType > class HyperplaneType, template< typename SplitMetricType, typename SplitMatType > class SplitType> size_t \fBmlpack::tree::SpillTree\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::\fBSpillDualTreeTraverser\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::NumBaseCases () const\fC [inline]\fP"

.PP
Get the number of times a base case was calculated\&. 
.PP
Definition at line 70 of file spill_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename HyperplaneMetricType > class HyperplaneType = AxisOrthogonalHyperplane, template< typename SplitMetricType, typename SplitMatType > class SplitType = MidpointSpaceSplit> template<typename MetricType , typename StatisticType , typename MatType , template< typename HyperplaneMetricType > class HyperplaneType, template< typename SplitMetricType, typename SplitMatType > class SplitType> size_t& \fBmlpack::tree::SpillTree\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::\fBSpillDualTreeTraverser\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::NumBaseCases ()\fC [inline]\fP"

.PP
Modify the number of times a base case was calculated\&. 
.PP
Definition at line 72 of file spill_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename HyperplaneMetricType > class HyperplaneType = AxisOrthogonalHyperplane, template< typename SplitMetricType, typename SplitMatType > class SplitType = MidpointSpaceSplit> template<typename MetricType , typename StatisticType , typename MatType , template< typename HyperplaneMetricType > class HyperplaneType, template< typename SplitMetricType, typename SplitMatType > class SplitType> size_t \fBmlpack::tree::SpillTree\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::\fBSpillDualTreeTraverser\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::NumPrunes () const\fC [inline]\fP"

.PP
Get the number of prunes\&. 
.PP
Definition at line 55 of file spill_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename HyperplaneMetricType > class HyperplaneType = AxisOrthogonalHyperplane, template< typename SplitMetricType, typename SplitMatType > class SplitType = MidpointSpaceSplit> template<typename MetricType , typename StatisticType , typename MatType , template< typename HyperplaneMetricType > class HyperplaneType, template< typename SplitMetricType, typename SplitMatType > class SplitType> size_t& \fBmlpack::tree::SpillTree\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::\fBSpillDualTreeTraverser\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::NumPrunes ()\fC [inline]\fP"

.PP
Modify the number of prunes\&. 
.PP
Definition at line 57 of file spill_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename HyperplaneMetricType > class HyperplaneType = AxisOrthogonalHyperplane, template< typename SplitMetricType, typename SplitMatType > class SplitType = MidpointSpaceSplit> template<typename MetricType , typename StatisticType , typename MatType , template< typename HyperplaneMetricType > class HyperplaneType, template< typename SplitMetricType, typename SplitMatType > class SplitType> size_t \fBmlpack::tree::SpillTree\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::\fBSpillDualTreeTraverser\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::NumScores () const\fC [inline]\fP"

.PP
Get the number of times a node combination was scored\&. 
.PP
Definition at line 65 of file spill_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename HyperplaneMetricType > class HyperplaneType = AxisOrthogonalHyperplane, template< typename SplitMetricType, typename SplitMatType > class SplitType = MidpointSpaceSplit> template<typename MetricType , typename StatisticType , typename MatType , template< typename HyperplaneMetricType > class HyperplaneType, template< typename SplitMetricType, typename SplitMatType > class SplitType> size_t& \fBmlpack::tree::SpillTree\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::\fBSpillDualTreeTraverser\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::NumScores ()\fC [inline]\fP"

.PP
Modify the number of times a node combination was scored\&. 
.PP
Definition at line 67 of file spill_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename HyperplaneMetricType > class HyperplaneType = AxisOrthogonalHyperplane, template< typename SplitMetricType, typename SplitMatType > class SplitType = MidpointSpaceSplit> template<typename MetricType , typename StatisticType , typename MatType , template< typename HyperplaneMetricType > class HyperplaneType, template< typename SplitMetricType, typename SplitMatType > class SplitType> size_t \fBmlpack::tree::SpillTree\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::\fBSpillDualTreeTraverser\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::NumVisited () const\fC [inline]\fP"

.PP
Get the number of visited combinations\&. 
.PP
Definition at line 60 of file spill_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename HyperplaneMetricType > class HyperplaneType = AxisOrthogonalHyperplane, template< typename SplitMetricType, typename SplitMatType > class SplitType = MidpointSpaceSplit> template<typename MetricType , typename StatisticType , typename MatType , template< typename HyperplaneMetricType > class HyperplaneType, template< typename SplitMetricType, typename SplitMatType > class SplitType> size_t& \fBmlpack::tree::SpillTree\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::\fBSpillDualTreeTraverser\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::NumVisited ()\fC [inline]\fP"

.PP
Modify the number of visited combinations\&. 
.PP
Definition at line 62 of file spill_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename HyperplaneMetricType > class HyperplaneType = AxisOrthogonalHyperplane, template< typename SplitMetricType, typename SplitMatType > class SplitType = MidpointSpaceSplit> template<typename MetricType , typename StatisticType , typename MatType , template< typename HyperplaneMetricType > class HyperplaneType, template< typename SplitMetricType, typename SplitMatType > class SplitType> void \fBmlpack::tree::SpillTree\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::\fBSpillDualTreeTraverser\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::Traverse (\fBSpillTree\fP & queryNode, \fBSpillTree\fP & referenceNode)"

.PP
Traverse the two trees\&. This does not reset the number of prunes\&.
.PP
\fBParameters:\fP
.RS 4
\fIqueryNode\fP The query node to be traversed\&. 
.br
\fIreferenceNode\fP The reference node to be traversed\&. 
.br
\fIscore\fP The score of the current node combination\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename HyperplaneMetricType > class HyperplaneType = AxisOrthogonalHyperplane, template< typename SplitMetricType, typename SplitMatType > class SplitType = MidpointSpaceSplit> template<typename MetricType , typename StatisticType , typename MatType , template< typename HyperplaneMetricType > class HyperplaneType, template< typename SplitMetricType, typename SplitMatType > class SplitType> size_t \fBmlpack::tree::SpillTree\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::\fBSpillDualTreeTraverser\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::numBaseCases\fC [private]\fP"

.PP
The number of times a base case was calculated\&. 
.PP
Definition at line 88 of file spill_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename HyperplaneMetricType > class HyperplaneType = AxisOrthogonalHyperplane, template< typename SplitMetricType, typename SplitMatType > class SplitType = MidpointSpaceSplit> template<typename MetricType , typename StatisticType , typename MatType , template< typename HyperplaneMetricType > class HyperplaneType, template< typename SplitMetricType, typename SplitMatType > class SplitType> size_t \fBmlpack::tree::SpillTree\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::\fBSpillDualTreeTraverser\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::numPrunes\fC [private]\fP"

.PP
The number of prunes\&. 
.PP
Definition at line 79 of file spill_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename HyperplaneMetricType > class HyperplaneType = AxisOrthogonalHyperplane, template< typename SplitMetricType, typename SplitMatType > class SplitType = MidpointSpaceSplit> template<typename MetricType , typename StatisticType , typename MatType , template< typename HyperplaneMetricType > class HyperplaneType, template< typename SplitMetricType, typename SplitMatType > class SplitType> size_t \fBmlpack::tree::SpillTree\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::\fBSpillDualTreeTraverser\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::numScores\fC [private]\fP"

.PP
The number of times a node combination was scored\&. 
.PP
Definition at line 85 of file spill_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename HyperplaneMetricType > class HyperplaneType = AxisOrthogonalHyperplane, template< typename SplitMetricType, typename SplitMatType > class SplitType = MidpointSpaceSplit> template<typename MetricType , typename StatisticType , typename MatType , template< typename HyperplaneMetricType > class HyperplaneType, template< typename SplitMetricType, typename SplitMatType > class SplitType> size_t \fBmlpack::tree::SpillTree\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::\fBSpillDualTreeTraverser\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::numVisited\fC [private]\fP"

.PP
The number of node combinations that have been visited during traversal\&. 
.PP
Definition at line 82 of file spill_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename HyperplaneMetricType > class HyperplaneType = AxisOrthogonalHyperplane, template< typename SplitMetricType, typename SplitMatType > class SplitType = MidpointSpaceSplit> template<typename MetricType , typename StatisticType , typename MatType , template< typename HyperplaneMetricType > class HyperplaneType, template< typename SplitMetricType, typename SplitMatType > class SplitType> RuleType& \fBmlpack::tree::SpillTree\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::\fBSpillDualTreeTraverser\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::rule\fC [private]\fP"

.PP
Reference to the rules with which the trees will be traversed\&. 
.PP
Definition at line 76 of file spill_dual_tree_traverser\&.hpp\&.
.SS "template<typename MetricType , typename StatisticType  = EmptyStatistic, typename MatType  = arma::mat, template< typename HyperplaneMetricType > class HyperplaneType = AxisOrthogonalHyperplane, template< typename SplitMetricType, typename SplitMatType > class SplitType = MidpointSpaceSplit> template<typename MetricType , typename StatisticType , typename MatType , template< typename HyperplaneMetricType > class HyperplaneType, template< typename SplitMetricType, typename SplitMatType > class SplitType> RuleType::TraversalInfoType \fBmlpack::tree::SpillTree\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::\fBSpillDualTreeTraverser\fP< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::traversalInfo\fC [private]\fP"

.PP
Traversal information, held in the class so that it isn't continually being reallocated\&. 
.PP
Definition at line 92 of file spill_dual_tree_traverser\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
