.TH "mlpack::tree::MidpointSplit< BoundType, MatType >::SplitInfo" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::tree::MidpointSplit< BoundType, MatType >::SplitInfo \- A struct that contains an information about the split\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBsplitDimension\fP"
.br
.RI "\fIThe dimension to split the node on\&. \fP"
.ti -1c
.RI "double \fBsplitVal\fP"
.br
.RI "\fIThe split in dimension splitDimension is based on this value\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename BoundType, typename MatType = arma::mat>
.br
struct mlpack::tree::MidpointSplit< BoundType, MatType >::SplitInfo"
A struct that contains an information about the split\&. 
.PP
Definition at line 34 of file midpoint_split\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename BoundType , typename MatType  = arma::mat> size_t \fBmlpack::tree::MidpointSplit\fP< BoundType, MatType >::SplitInfo::splitDimension"

.PP
The dimension to split the node on\&. 
.PP
Definition at line 37 of file midpoint_split\&.hpp\&.
.PP
Referenced by mlpack::tree::MidpointSplit< BoundType, MatType >::AssignToLeftNode()\&.
.SS "template<typename BoundType , typename MatType  = arma::mat> double \fBmlpack::tree::MidpointSplit\fP< BoundType, MatType >::SplitInfo::splitVal"

.PP
The split in dimension splitDimension is based on this value\&. 
.PP
Definition at line 39 of file midpoint_split\&.hpp\&.
.PP
Referenced by mlpack::tree::MidpointSplit< BoundType, MatType >::AssignToLeftNode()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
