.TH "mlpack::range::TrainVisitor" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::range::TrainVisitor \- \fBTrainVisitor\fP sets the reference set to a new reference set on the given RSType\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits static_visitor< void >\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "template<template< typename TreeMetricType, typename TreeStatType, typename TreeMatType > class TreeType> using \fBRSTypeT\fP = \fBRSType\fP< TreeType >"
.br
.RI "\fIAlias template necessary for visual c++ compiler\&. \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTrainVisitor\fP (arma::mat &&\fBreferenceSet\fP, const size_t \fBleafSize\fP)"
.br
.RI "\fIConstruct the \fBTrainVisitor\fP object with the given reference set, leafSize\&. \fP"
.ti -1c
.RI "template<template< typename TreeMetricType, typename TreeStatType, typename TreeMatType > class TreeType> void \fBoperator()\fP (\fBRSTypeT\fP< TreeType > *rs) const "
.br
.RI "\fIDefault Train on the given RSType instance\&. \fP"
.ti -1c
.RI "void \fBoperator()\fP (\fBRSTypeT\fP< \fBtree::KDTree\fP > *rs) const "
.br
.RI "\fITrain on the given RSType specialized for KDTrees\&. \fP"
.ti -1c
.RI "void \fBoperator()\fP (\fBRSTypeT\fP< \fBtree::BallTree\fP > *rs) const "
.br
.RI "\fITrain on the given RSType specialized for BallTrees\&. \fP"
.ti -1c
.RI "void \fBoperator()\fP (\fBRSTypeT\fP< \fBtree::Octree\fP > *rs) const "
.br
.RI "\fITrain specialized for octrees\&. \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "template<typename RSType > void \fBTrainLeaf\fP (\fBRSType\fP *rs) const "
.br
.RI "\fITrain on the given RsType considering the leafSize\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "size_t \fBleafSize\fP"
.br
.RI "\fIThe leaf size, used only by BinarySpaceTree\&. \fP"
.ti -1c
.RI "arma::mat && \fBreferenceSet\fP"
.br
.RI "\fIThe reference set to use for training\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBTrainVisitor\fP sets the reference set to a new reference set on the given RSType\&. 

We use template specialization to differentiate those tree types that accept leafSize as a parameter\&. In these cases, a reference tree with proper leafSize is built from the referenceSet\&. 
.PP
Definition at line 130 of file rs_model\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<template< typename TreeMetricType, typename TreeStatType, typename TreeMatType > class TreeType> using \fBmlpack::range::TrainVisitor::RSTypeT\fP =  \fBRSType\fP<TreeType>"

.PP
Alias template necessary for visual c++ compiler\&. 
.PP
Definition at line 146 of file rs_model\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mlpack::range::TrainVisitor::TrainVisitor (arma::mat && referenceSet, const size_t leafSize)"

.PP
Construct the \fBTrainVisitor\fP object with the given reference set, leafSize\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<template< typename TreeMetricType, typename TreeStatType, typename TreeMatType > class TreeType> void mlpack::range::TrainVisitor::operator() (\fBRSTypeT\fP< TreeType > * rs) const"

.PP
Default Train on the given RSType instance\&. 
.SS "void mlpack::range::TrainVisitor::operator() (\fBRSTypeT\fP< \fBtree::KDTree\fP > * rs) const"

.PP
Train on the given RSType specialized for KDTrees\&. 
.SS "void mlpack::range::TrainVisitor::operator() (\fBRSTypeT\fP< \fBtree::BallTree\fP > * rs) const"

.PP
Train on the given RSType specialized for BallTrees\&. 
.SS "void mlpack::range::TrainVisitor::operator() (\fBRSTypeT\fP< \fBtree::Octree\fP > * rs) const"

.PP
Train specialized for octrees\&. 
.SS "template<typename RSType > void mlpack::range::TrainVisitor::TrainLeaf (\fBRSType\fP * rs) const\fC [private]\fP"

.PP
Train on the given RsType considering the leafSize\&. 
.SH "Member Data Documentation"
.PP 
.SS "size_t mlpack::range::TrainVisitor::leafSize\fC [private]\fP"

.PP
The leaf size, used only by BinarySpaceTree\&. 
.PP
Definition at line 136 of file rs_model\&.hpp\&.
.SS "arma::mat&& mlpack::range::TrainVisitor::referenceSet\fC [private]\fP"

.PP
The reference set to use for training\&. 
.PP
Definition at line 134 of file rs_model\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
