.TH "mlpack::ann::GradientZeroVisitor" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::ann::GradientZeroVisitor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits static_visitor< void >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGradientZeroVisitor\fP ()"
.br
.RI "\fISet the gradient to zero for the given module\&. \fP"
.ti -1c
.RI "template<typename LayerType > void \fBoperator()\fP (LayerType *layer) const "
.br
.RI "\fISet the gradient to zero\&. \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > std::enable_if< HasGradientCheck< T, arma::mat &(T::*)()>::value, void >::type \fBLayerGradients\fP (T *layer, arma::mat &input) const "
.br
.RI "\fISet the gradient to zero if the module implements the Gradient() function\&. \fP"
.ti -1c
.RI "template<typename T , typename P > std::enable_if< !HasGradientCheck< T, P &(T::*)()>::value, void >::type \fBLayerGradients\fP (T *layer, P &input) const "
.br
.RI "\fIDo not set the gradient to zero if the module doesn't implement the Gradient() function\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file gradient_zero_visitor\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mlpack::ann::GradientZeroVisitor::GradientZeroVisitor ()"

.PP
Set the gradient to zero for the given module\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > std::enable_if< HasGradientCheck<T, arma::mat&(T::*)()>::value, void>::type mlpack::ann::GradientZeroVisitor::LayerGradients (T * layer, arma::mat & input) const\fC [private]\fP"

.PP
Set the gradient to zero if the module implements the Gradient() function\&. 
.SS "template<typename T , typename P > std::enable_if< !HasGradientCheck<T, P&(T::*)()>::value, void>::type mlpack::ann::GradientZeroVisitor::LayerGradients (T * layer, P & input) const\fC [private]\fP"

.PP
Do not set the gradient to zero if the module doesn't implement the Gradient() function\&. 
.SS "template<typename LayerType > void mlpack::ann::GradientZeroVisitor::operator() (LayerType * layer) const"

.PP
Set the gradient to zero\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
