.TH "mlpack::data::CustomImputation< T >" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::data::CustomImputation< T > \- A simple custom imputation class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCustomImputation\fP (T \fBcustomValue\fP)"
.br
.ti -1c
.RI "void \fBImpute\fP (arma::Mat< T > &input, const T &mappedValue, const size_t dimension, const bool columnMajor=true)"
.br
.RI "\fIImpute function searches through the input looking for mappedValue and replaces it with the user-defined custom value of the given dimension\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "T \fBcustomValue\fP"
.br
.RI "\fIA user-defined value that the user wants to replace missing values with\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class mlpack::data::CustomImputation< T >"
A simple custom imputation class\&. 


.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP Type of armadillo matrix 
.RE
.PP

.PP
Definition at line 24 of file custom_imputation\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBmlpack::data::CustomImputation\fP< T >::\fBCustomImputation\fP (T customValue)\fC [inline]\fP"

.PP
Definition at line 27 of file custom_imputation\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > void \fBmlpack::data::CustomImputation\fP< T >::Impute (arma::Mat< T > & input, const T & mappedValue, const size_t dimension, const bool columnMajor = \fCtrue\fP)\fC [inline]\fP"

.PP
Impute function searches through the input looking for mappedValue and replaces it with the user-defined custom value of the given dimension\&. The result is overwritten to the input, not creating any copy\&. Custom value must be set when initializing the \fBCustomImputation\fP object\&.
.PP
\fBParameters:\fP
.RS 4
\fIinput\fP Matrix that contains mappedValue\&. 
.br
\fImappedValue\fP Value that the user wants to get rid of\&. 
.br
\fIdimension\fP Index of the dimension of the mappedValue\&. 
.br
\fIcolumnMajor\fP State of whether the input matrix is columnMajor or not\&. 
.RE
.PP

.PP
Definition at line 44 of file custom_imputation\&.hpp\&.
.PP
References mlpack::data::CustomImputation< T >::customValue\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T > T \fBmlpack::data::CustomImputation\fP< T >::customValue\fC [private]\fP"

.PP
A user-defined value that the user wants to replace missing values with\&. 
.PP
Definition at line 76 of file custom_imputation\&.hpp\&.
.PP
Referenced by mlpack::data::CustomImputation< T >::Impute()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
