.TH "mlpack::pca::QUICSVDPolicy" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::pca::QUICSVDPolicy \- Implementation of the QUIC-SVD policy\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQUICSVDPolicy\fP (const double \fBepsilon\fP=0\&.03, const double \fBdelta\fP=0\&.1)"
.br
.RI "\fIUse QUIC-SVD method to perform the principal components analysis (PCA)\&. \fP"
.ti -1c
.RI "void \fBApply\fP (const arma::mat &data, const arma::mat &centeredData, arma::mat &transformedData, arma::vec &eigVal, arma::mat &eigvec, const size_t)"
.br
.RI "\fIApply Principal Component Analysis to the provided data set using the QUIC-SVD method\&. \fP"
.ti -1c
.RI "double \fBDelta\fP () const "
.br
.RI "\fIGet the cumulative probability for Monte Carlo error lower bound\&. \fP"
.ti -1c
.RI "double & \fBDelta\fP ()"
.br
.RI "\fIModify the cumulative probability for Monte Carlo error lower bound\&. \fP"
.ti -1c
.RI "double \fBEpsilon\fP () const "
.br
.RI "\fIGet the error tolerance fraction for calculated subspace\&. \fP"
.ti -1c
.RI "double & \fBEpsilon\fP ()"
.br
.RI "\fIModify the error tolerance fraction for calculated subspace\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBdelta\fP"
.br
.RI "\fICumulative probability for Monte Carlo error lower bound\&. \fP"
.ti -1c
.RI "double \fBepsilon\fP"
.br
.RI "\fIError tolerance fraction for calculated subspace\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Implementation of the QUIC-SVD policy\&. 
.PP
Definition at line 26 of file quic_svd_method\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mlpack::pca::QUICSVDPolicy::QUICSVDPolicy (const double epsilon = \fC0\&.03\fP, const double delta = \fC0\&.1\fP)\fC [inline]\fP"

.PP
Use QUIC-SVD method to perform the principal components analysis (PCA)\&. 
.PP
\fBParameters:\fP
.RS 4
\fIepsilon\fP Error tolerance fraction for calculated subspace\&. 
.br
\fIdelta\fP Cumulative probability for Monte Carlo error lower bound\&. 
.RE
.PP

.PP
Definition at line 36 of file quic_svd_method\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void mlpack::pca::QUICSVDPolicy::Apply (const arma::mat & data, const arma::mat & centeredData, arma::mat & transformedData, arma::vec & eigVal, arma::mat & eigvec, const size_t)\fC [inline]\fP"

.PP
Apply Principal Component Analysis to the provided data set using the QUIC-SVD method\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP Data matrix\&. 
.br
\fIcenteredData\fP Centered data matrix\&. 
.br
\fItransformedData\fP Matrix to put results of PCA into\&. 
.br
\fIeigVal\fP Vector to put eigenvalues into\&. 
.br
\fIeigvec\fP Matrix to put eigenvectors (loadings) into\&. 
.br
\fIrank\fP Rank of the decomposition\&. 
.RE
.PP

.PP
Definition at line 54 of file quic_svd_method\&.hpp\&.
.PP
References delta, and epsilon\&.
.SS "double mlpack::pca::QUICSVDPolicy::Delta () const\fC [inline]\fP"

.PP
Get the cumulative probability for Monte Carlo error lower bound\&. 
.PP
Definition at line 82 of file quic_svd_method\&.hpp\&.
.PP
References delta\&.
.SS "double& mlpack::pca::QUICSVDPolicy::Delta ()\fC [inline]\fP"

.PP
Modify the cumulative probability for Monte Carlo error lower bound\&. 
.PP
Definition at line 84 of file quic_svd_method\&.hpp\&.
.PP
References delta\&.
.SS "double mlpack::pca::QUICSVDPolicy::Epsilon () const\fC [inline]\fP"

.PP
Get the error tolerance fraction for calculated subspace\&. 
.PP
Definition at line 77 of file quic_svd_method\&.hpp\&.
.PP
References epsilon\&.
.SS "double& mlpack::pca::QUICSVDPolicy::Epsilon ()\fC [inline]\fP"

.PP
Modify the error tolerance fraction for calculated subspace\&. 
.PP
Definition at line 79 of file quic_svd_method\&.hpp\&.
.PP
References epsilon\&.
.SH "Member Data Documentation"
.PP 
.SS "double mlpack::pca::QUICSVDPolicy::delta\fC [private]\fP"

.PP
Cumulative probability for Monte Carlo error lower bound\&. 
.PP
Definition at line 91 of file quic_svd_method\&.hpp\&.
.PP
Referenced by Apply(), and Delta()\&.
.SS "double mlpack::pca::QUICSVDPolicy::epsilon\fC [private]\fP"

.PP
Error tolerance fraction for calculated subspace\&. 
.PP
Definition at line 88 of file quic_svd_method\&.hpp\&.
.PP
Referenced by Apply(), and Epsilon()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
