.TH "mlpack::neighbor::SearchModeVisitor" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::neighbor::SearchModeVisitor \- \fBSearchModeVisitor\fP exposes the SearchMode() method of the given NSType\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits static_visitor< NeighborSearchMode & >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename NSType > \fBNeighborSearchMode\fP & \fBoperator()\fP (\fBNSType\fP *ns) const "
.br
.RI "\fIReturn the search mode\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBSearchModeVisitor\fP exposes the SearchMode() method of the given NSType\&. 
.PP
Definition at line 214 of file ns_model\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename NSType > \fBNeighborSearchMode\fP& mlpack::neighbor::SearchModeVisitor::operator() (\fBNSType\fP * ns) const"

.PP
Return the search mode\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
