.TH "mlpack::tree::MinimalCoverageSweep< SplitPolicy >::SweepCost< TreeType >" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::tree::MinimalCoverageSweep< SplitPolicy >::SweepCost< TreeType > \- A struct that provides the type of the sweep cost\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef TreeType::ElemType \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename SplitPolicy>
.br
template<typename TreeType>
.br
struct mlpack::tree::MinimalCoverageSweep< SplitPolicy >::SweepCost< TreeType >"
A struct that provides the type of the sweep cost\&. 
.PP
Definition at line 35 of file minimal_coverage_sweep\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename SplitPolicy > template<typename TreeType > typedef TreeType::ElemType \fBmlpack::tree::MinimalCoverageSweep\fP< SplitPolicy >::\fBSweepCost\fP< TreeType >::\fBtype\fP"

.PP
Definition at line 37 of file minimal_coverage_sweep\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
