.TH "mlpack::ann::SoftplusFunction" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::ann::SoftplusFunction \- The softplus function, defined by\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static double \fBDeriv\fP (const double y)"
.br
.RI "\fIComputes the first derivative of the softplus function\&. \fP"
.ti -1c
.RI "template<typename InputVecType , typename OutputVecType > static void \fBDeriv\fP (const InputVecType &y, OutputVecType &x)"
.br
.RI "\fIComputes the first derivatives of the softplus function\&. \fP"
.ti -1c
.RI "static double \fBFn\fP (const double x)"
.br
.RI "\fIComputes the softplus function\&. \fP"
.ti -1c
.RI "template<typename InputVecType , typename OutputVecType > static void \fBFn\fP (const InputVecType &x, OutputVecType &y)"
.br
.RI "\fIComputes the softplus function\&. \fP"
.ti -1c
.RI "static double \fBInv\fP (const double y)"
.br
.RI "\fIComputes the inverse of the softplus function\&. \fP"
.ti -1c
.RI "template<typename InputVecType , typename OutputVecType > static void \fBInv\fP (const InputVecType &y, OutputVecType &x)"
.br
.RI "\fIComputes the inverse of the softplus function\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The softplus function, defined by\&. 

\begin{eqnarray*} f(x) &=& \ln(1 + e^{x}) \\ f'(x) &=& \frac{1}{1 + e^{-x}} \\ f^{-1}(y) &=& \ln(e^{y} - 1) \end{eqnarray*} 
.PP
Definition at line 43 of file softplus_function\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static double mlpack::ann::SoftplusFunction::Deriv (const double y)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the first derivative of the softplus function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIy\fP Input data\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
f'(x) 
.RE
.PP

.PP
Definition at line 81 of file softplus_function\&.hpp\&.
.SS "template<typename InputVecType , typename OutputVecType > static void mlpack::ann::SoftplusFunction::Deriv (const InputVecType & y, OutputVecType & x)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the first derivatives of the softplus function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIy\fP Input activations\&. 
.br
\fIx\fP The resulting derivatives\&. 
.RE
.PP

.PP
Definition at line 93 of file softplus_function\&.hpp\&.
.SS "static double mlpack::ann::SoftplusFunction::Fn (const double x)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the softplus function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Input data\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
f(x)\&. 
.RE
.PP

.PP
Definition at line 53 of file softplus_function\&.hpp\&.
.PP
Referenced by Fn()\&.
.SS "template<typename InputVecType , typename OutputVecType > static void mlpack::ann::SoftplusFunction::Fn (const InputVecType & x, OutputVecType & y)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the softplus function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Input data\&. 
.br
\fIy\fP The resulting output activation\&. 
.RE
.PP

.PP
Definition at line 67 of file softplus_function\&.hpp\&.
.PP
References Fn()\&.
.SS "static double mlpack::ann::SoftplusFunction::Inv (const double y)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the inverse of the softplus function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIy\fP Input data\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
f^{-1}(y) 
.RE
.PP

.PP
Definition at line 104 of file softplus_function\&.hpp\&.
.PP
Referenced by Inv()\&.
.SS "template<typename InputVecType , typename OutputVecType > static void mlpack::ann::SoftplusFunction::Inv (const InputVecType & y, OutputVecType & x)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the inverse of the softplus function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIy\fP Input data\&. 
.br
\fIx\fP The resulting inverse of the input data\&. 
.RE
.PP

.PP
Definition at line 116 of file softplus_function\&.hpp\&.
.PP
References Inv()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
