.TH "mlpack::util::CLIDeleter" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::util::CLIDeleter \- Extremely simple class whose only job is to delete the existing \fBCLI\fP object at the end of execution\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCLIDeleter\fP ()"
.br
.ti -1c
.RI "\fB~CLIDeleter\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Extremely simple class whose only job is to delete the existing \fBCLI\fP object at the end of execution\&. 

This is meant to allow the user to avoid typing '\fBCLI::Destroy()\fP' at the end of their program\&. The file also defines a static \fBCLIDeleter\fP class, which will be initialized at the beginning of the program and deleted at the end\&. The destructor destroys the \fBCLI\fP singleton\&. 
.PP
Definition at line 25 of file cli_deleter\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mlpack::util::CLIDeleter::CLIDeleter ()"

.SS "mlpack::util::CLIDeleter::~CLIDeleter ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
