.TH "mlpack::kmeans::HamerlyKMeans< MetricType, MatType >" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::kmeans::HamerlyKMeans< MetricType, MatType > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHamerlyKMeans\fP (const MatType &\fBdataset\fP, MetricType &\fBmetric\fP)"
.br
.RI "\fIConstruct the \fBHamerlyKMeans\fP object, which must store several sets of bounds\&. \fP"
.ti -1c
.RI "size_t \fBDistanceCalculations\fP () const "
.br
.ti -1c
.RI "double \fBIterate\fP (const arma::mat &centroids, arma::mat &newCentroids, arma::Col< size_t > &counts)"
.br
.RI "\fIRun a single iteration of Hamerly's algorithm, updating the given centroids into the newCentroids matrix\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "arma::Col< size_t > \fBassignments\fP"
.br
.RI "\fIAssignments for each point\&. \fP"
.ti -1c
.RI "const MatType & \fBdataset\fP"
.br
.RI "\fIThe dataset\&. \fP"
.ti -1c
.RI "size_t \fBdistanceCalculations\fP"
.br
.RI "\fITrack distance calculations\&. \fP"
.ti -1c
.RI "arma::vec \fBlowerBounds\fP"
.br
.RI "\fILower bounds for each point\&. \fP"
.ti -1c
.RI "MetricType & \fBmetric\fP"
.br
.RI "\fIThe instantiated metric\&. \fP"
.ti -1c
.RI "arma::vec \fBminClusterDistances\fP"
.br
.RI "\fIMinimum cluster distances from each cluster\&. \fP"
.ti -1c
.RI "arma::vec \fBupperBounds\fP"
.br
.RI "\fIUpper bounds for each point\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename MetricType, typename MatType>
.br
class mlpack::kmeans::HamerlyKMeans< MetricType, MatType >"

.PP
Definition at line 19 of file hamerly_kmeans\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename MetricType , typename MatType > \fBmlpack::kmeans::HamerlyKMeans\fP< MetricType, MatType >::\fBHamerlyKMeans\fP (const MatType & dataset, MetricType & metric)"

.PP
Construct the \fBHamerlyKMeans\fP object, which must store several sets of bounds\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename MetricType , typename MatType > size_t \fBmlpack::kmeans::HamerlyKMeans\fP< MetricType, MatType >::DistanceCalculations () const\fC [inline]\fP"

.PP
Definition at line 40 of file hamerly_kmeans\&.hpp\&.
.PP
References mlpack::kmeans::HamerlyKMeans< MetricType, MatType >::distanceCalculations\&.
.SS "template<typename MetricType , typename MatType > double \fBmlpack::kmeans::HamerlyKMeans\fP< MetricType, MatType >::Iterate (const arma::mat & centroids, arma::mat & newCentroids, arma::Col< size_t > & counts)"

.PP
Run a single iteration of Hamerly's algorithm, updating the given centroids into the newCentroids matrix\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcentroids\fP Current cluster centroids\&. 
.br
\fInewCentroids\fP New cluster centroids\&. 
.br
\fIcounts\fP Current counts, to be overwritten with new counts\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "template<typename MetricType , typename MatType > arma::Col<size_t> \fBmlpack::kmeans::HamerlyKMeans\fP< MetricType, MatType >::assignments\fC [private]\fP"

.PP
Assignments for each point\&. 
.PP
Definition at line 56 of file hamerly_kmeans\&.hpp\&.
.SS "template<typename MetricType , typename MatType > const MatType& \fBmlpack::kmeans::HamerlyKMeans\fP< MetricType, MatType >::dataset\fC [private]\fP"

.PP
The dataset\&. 
.PP
Definition at line 44 of file hamerly_kmeans\&.hpp\&.
.SS "template<typename MetricType , typename MatType > size_t \fBmlpack::kmeans::HamerlyKMeans\fP< MetricType, MatType >::distanceCalculations\fC [private]\fP"

.PP
Track distance calculations\&. 
.PP
Definition at line 59 of file hamerly_kmeans\&.hpp\&.
.PP
Referenced by mlpack::kmeans::HamerlyKMeans< MetricType, MatType >::DistanceCalculations()\&.
.SS "template<typename MetricType , typename MatType > arma::vec \fBmlpack::kmeans::HamerlyKMeans\fP< MetricType, MatType >::lowerBounds\fC [private]\fP"

.PP
Lower bounds for each point\&. 
.PP
Definition at line 54 of file hamerly_kmeans\&.hpp\&.
.SS "template<typename MetricType , typename MatType > MetricType& \fBmlpack::kmeans::HamerlyKMeans\fP< MetricType, MatType >::metric\fC [private]\fP"

.PP
The instantiated metric\&. 
.PP
Definition at line 46 of file hamerly_kmeans\&.hpp\&.
.SS "template<typename MetricType , typename MatType > arma::vec \fBmlpack::kmeans::HamerlyKMeans\fP< MetricType, MatType >::minClusterDistances\fC [private]\fP"

.PP
Minimum cluster distances from each cluster\&. 
.PP
Definition at line 49 of file hamerly_kmeans\&.hpp\&.
.SS "template<typename MetricType , typename MatType > arma::vec \fBmlpack::kmeans::HamerlyKMeans\fP< MetricType, MatType >::upperBounds\fC [private]\fP"

.PP
Upper bounds for each point\&. 
.PP
Definition at line 52 of file hamerly_kmeans\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
