.TH "mlpack::tree::MinimalSplitsNumberSweep< SplitPolicy >::SweepCost< typename >" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::tree::MinimalSplitsNumberSweep< SplitPolicy >::SweepCost< typename > \- A struct that provides the type of the sweep cost\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef size_t \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename SplitPolicy>
.br
template<typename>
.br
struct mlpack::tree::MinimalSplitsNumberSweep< SplitPolicy >::SweepCost< typename >"
A struct that provides the type of the sweep cost\&. 
.PP
Definition at line 36 of file minimal_splits_number_sweep\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename SplitPolicy > template<typename > typedef size_t \fBmlpack::tree::MinimalSplitsNumberSweep\fP< SplitPolicy >::\fBSweepCost\fP< typename >::\fBtype\fP"

.PP
Definition at line 38 of file minimal_splits_number_sweep\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
