.TH "mlpack::cf::FactorizerTraits< FactorizerType >" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::cf::FactorizerTraits< FactorizerType > \- Template class for factorizer traits\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBUsesCoordinateList\fP = false"
.br
.RI "\fIIf true, then the passed data matrix is used for factorizer\&.Apply()\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename FactorizerType>
.br
struct mlpack::cf::FactorizerTraits< FactorizerType >"
Template class for factorizer traits\&. 

This stores the default values for the variables to be assumed for a given factorizer\&. If any of the factorizers needs to have a different value for the traits, a template specialization has be wriiten for that factorizer\&. An example can be found in the module for Regularized SVD\&. 
.PP
Definition at line 39 of file cf\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename FactorizerType > const bool \fBmlpack::cf::FactorizerTraits\fP< FactorizerType >::UsesCoordinateList = false\fC [static]\fP"

.PP
If true, then the passed data matrix is used for factorizer\&.Apply()\&. Otherwise, it is modified into a form suitable for factorization\&. 
.PP
Definition at line 45 of file cf\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
