.TH "mlpack::optimization::LRSDP< SDPType >" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::optimization::LRSDP< SDPType > \- \fBLRSDP\fP is the implementation of Monteiro and Burer's formulation of low-rank semidefinite programs (LR-SDP)\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLRSDP\fP (const size_t numSparseConstraints, const size_t numDenseConstraints, const arma::mat &initialPoint)"
.br
.RI "\fICreate an \fBLRSDP\fP to be optimized\&. \fP"
.ti -1c
.RI "\fBLRSDP\fP (const SDPType &sdp, const arma::mat &initialPoint)"
.br
.RI "\fICreate an \fBLRSDP\fP object with the given \fBSDP\fP problem to be solved, and the given initial point\&. \fP"
.ti -1c
.RI "const \fBAugLagrangian\fP< \fBLRSDPFunction\fP< SDPType > > & \fBAugLag\fP () const "
.br
.RI "\fIReturn the augmented Lagrangian object\&. \fP"
.ti -1c
.RI "\fBAugLagrangian\fP< \fBLRSDPFunction\fP< SDPType > > & \fBAugLag\fP ()"
.br
.RI "\fIModify the augmented Lagrangian object\&. \fP"
.ti -1c
.RI "const \fBLRSDPFunction\fP< SDPType > & \fBFunction\fP () const "
.br
.RI "\fIReturn the function to be optimized\&. \fP"
.ti -1c
.RI "\fBLRSDPFunction\fP< SDPType > & \fBFunction\fP ()"
.br
.RI "\fIModify the function to be optimized\&. \fP"
.ti -1c
.RI "double \fBOptimize\fP (arma::mat &coordinates)"
.br
.RI "\fIOptimize the \fBLRSDP\fP and return the final objective value\&. \fP"
.ti -1c
.RI "const SDPType & \fBSDP\fP () const "
.br
.RI "\fIReturn the \fBSDP\fP that will be solved\&. \fP"
.ti -1c
.RI "SDPType & \fBSDP\fP ()"
.br
.RI "\fIModify the \fBSDP\fP that will be solved\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBAugLagrangian\fP< \fBLRSDPFunction\fP< SDPType > > \fBaugLag\fP"
.br
.RI "\fIThe \fBAugLagrangian\fP object which will be used for optimization\&. \fP"
.ti -1c
.RI "\fBLRSDPFunction\fP< SDPType > \fBfunction\fP"
.br
.RI "\fIFunction to optimize, which the \fBAugLagrangian\fP object holds\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename SDPType>
.br
class mlpack::optimization::LRSDP< SDPType >"
\fBLRSDP\fP is the implementation of Monteiro and Burer's formulation of low-rank semidefinite programs (LR-SDP)\&. 

This solver uses the augmented Lagrangian optimizer to solve low-rank semidefinite programs\&. 
.PP
Definition at line 30 of file lrsdp\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename SDPType> \fBmlpack::optimization::LRSDP\fP< SDPType >::\fBLRSDP\fP (const size_t numSparseConstraints, const size_t numDenseConstraints, const arma::mat & initialPoint)"

.PP
Create an \fBLRSDP\fP to be optimized\&. The solution will end up being a matrix of size (rows) x (rank)\&. To construct each constraint and the objective function, use the function \fBSDP()\fP in order to access the SDPType object associated with this optimizer\&.
.PP
\fBParameters:\fP
.RS 4
\fInumConstraints\fP Number of constraints in the problem\&. 
.br
\fIinitialPoint\fP Initial point of the optimization\&. 
.RE
.PP

.SS "template<typename SDPType> \fBmlpack::optimization::LRSDP\fP< SDPType >::\fBLRSDP\fP (const SDPType & sdp, const arma::mat & initialPoint)"

.PP
Create an \fBLRSDP\fP object with the given \fBSDP\fP problem to be solved, and the given initial point\&. Note that the \fBSDP\fP may be modified later by calling \fBSDP()\fP to access the object\&.
.PP
\fBParameters:\fP
.RS 4
\fIsdp\fP \fBSDP\fP to be solved\&. 
.br
\fIinitialPoint\fP Initial point of the optimization\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<typename SDPType> const \fBAugLagrangian\fP<\fBLRSDPFunction\fP<SDPType> >& \fBmlpack::optimization::LRSDP\fP< SDPType >::AugLag () const\fC [inline]\fP"

.PP
Return the augmented Lagrangian object\&. 
.PP
Definition at line 76 of file lrsdp\&.hpp\&.
.SS "template<typename SDPType> \fBAugLagrangian\fP<\fBLRSDPFunction\fP<SDPType> >& \fBmlpack::optimization::LRSDP\fP< SDPType >::AugLag ()\fC [inline]\fP"

.PP
Modify the augmented Lagrangian object\&. 
.PP
Definition at line 78 of file lrsdp\&.hpp\&.
.SS "template<typename SDPType> const \fBLRSDPFunction\fP<SDPType>& \fBmlpack::optimization::LRSDP\fP< SDPType >::Function () const\fC [inline]\fP"

.PP
Return the function to be optimized\&. 
.PP
Definition at line 71 of file lrsdp\&.hpp\&.
.SS "template<typename SDPType> \fBLRSDPFunction\fP<SDPType>& \fBmlpack::optimization::LRSDP\fP< SDPType >::Function ()\fC [inline]\fP"

.PP
Modify the function to be optimized\&. 
.PP
Definition at line 73 of file lrsdp\&.hpp\&.
.SS "template<typename SDPType> double \fBmlpack::optimization::LRSDP\fP< SDPType >::Optimize (arma::mat & coordinates)"

.PP
Optimize the \fBLRSDP\fP and return the final objective value\&. The given coordinates will be modified to contain the final solution\&.
.PP
\fBParameters:\fP
.RS 4
\fIcoordinates\fP Starting coordinates for the optimization\&. 
.RE
.PP

.SS "template<typename SDPType> const SDPType& \fBmlpack::optimization::LRSDP\fP< SDPType >::\fBSDP\fP () const\fC [inline]\fP"

.PP
Return the \fBSDP\fP that will be solved\&. 
.PP
Definition at line 66 of file lrsdp\&.hpp\&.
.SS "template<typename SDPType> SDPType& \fBmlpack::optimization::LRSDP\fP< SDPType >::\fBSDP\fP ()\fC [inline]\fP"

.PP
Modify the \fBSDP\fP that will be solved\&. 
.PP
Definition at line 68 of file lrsdp\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename SDPType> \fBAugLagrangian\fP<\fBLRSDPFunction\fP<SDPType> > \fBmlpack::optimization::LRSDP\fP< SDPType >::augLag\fC [private]\fP"

.PP
The \fBAugLagrangian\fP object which will be used for optimization\&. 
.PP
Definition at line 85 of file lrsdp\&.hpp\&.
.PP
Referenced by mlpack::optimization::LRSDP< optimization::SDP< arma::sp_mat > >::AugLag()\&.
.SS "template<typename SDPType> \fBLRSDPFunction\fP<SDPType> \fBmlpack::optimization::LRSDP\fP< SDPType >::function\fC [private]\fP"

.PP
Function to optimize, which the \fBAugLagrangian\fP object holds\&. 
.PP
Definition at line 82 of file lrsdp\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
