.TH "mlpack::tree::DiscreteHilbertValue< TreeElemType >" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::tree::DiscreteHilbertValue< TreeElemType > \- The \fBDiscreteHilbertValue\fP class stores Hilbert values for all of the points in a \fBRectangleTree\fP node, and calculates Hilbert values for new points\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename TreeElemType>
.br
class mlpack::tree::DiscreteHilbertValue< TreeElemType >"
The \fBDiscreteHilbertValue\fP class stores Hilbert values for all of the points in a \fBRectangleTree\fP node, and calculates Hilbert values for new points\&. 

This implementation calculates the full discrete Hilbert value; for a d-dimensional vector filled with elements of size E, each Hilbert value will take dE space\&. 
.PP
Definition at line 29 of file discrete_hilbert_value\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
