.TH "mlpack::ann::Dropout< InputDataType, OutputDataType >" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::ann::Dropout< InputDataType, OutputDataType > \- The dropout layer is a regularizer that randomly with probability ratio sets input values to zero and scales the remaining elements by factor 1 / (1 - ratio)\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDropout\fP (const double \fBratio\fP=0\&.5, const bool \fBrescale\fP=true)"
.br
.RI "\fICreate the \fBDropout\fP object using the specified ratio and rescale parameter\&. \fP"
.ti -1c
.RI "template<typename eT > void \fBBackward\fP (const arma::Mat< eT > &&, arma::Mat< eT > &&gy, arma::Mat< eT > &&g)"
.br
.RI "\fIOrdinary feed backward pass of the dropout layer\&. \fP"
.ti -1c
.RI "OutputDataType const & \fBDelta\fP () const "
.br
.RI "\fIGet the detla\&. \fP"
.ti -1c
.RI "OutputDataType & \fBDelta\fP ()"
.br
.RI "\fIModify the delta\&. \fP"
.ti -1c
.RI "bool \fBDeterministic\fP () const "
.br
.RI "\fIThe value of the deterministic parameter\&. \fP"
.ti -1c
.RI "bool & \fBDeterministic\fP ()"
.br
.RI "\fIModify the value of the deterministic parameter\&. \fP"
.ti -1c
.RI "template<typename eT > void \fBForward\fP (const arma::Mat< eT > &&input, arma::Mat< eT > &&output)"
.br
.RI "\fIOrdinary feed forward pass of the dropout layer\&. \fP"
.ti -1c
.RI "InputDataType const & \fBInputParameter\fP () const "
.br
.RI "\fIGet the input parameter\&. \fP"
.ti -1c
.RI "InputDataType & \fBInputParameter\fP ()"
.br
.RI "\fIModify the input parameter\&. \fP"
.ti -1c
.RI "OutputDataType const & \fBOutputParameter\fP () const "
.br
.RI "\fIGet the output parameter\&. \fP"
.ti -1c
.RI "OutputDataType & \fBOutputParameter\fP ()"
.br
.RI "\fIModify the output parameter\&. \fP"
.ti -1c
.RI "double \fBRatio\fP () const "
.br
.RI "\fIThe probability of setting a value to zero\&. \fP"
.ti -1c
.RI "void \fBRatio\fP (const double r)"
.br
.RI "\fIModify the probability of setting a value to zero\&. \fP"
.ti -1c
.RI "bool \fBRescale\fP () const "
.br
.RI "\fIThe value of the rescale parameter\&. \fP"
.ti -1c
.RI "bool & \fBRescale\fP ()"
.br
.RI "\fIModify the value of the rescale parameter\&. \fP"
.ti -1c
.RI "template<typename Archive > void \fBSerialize\fP (Archive &ar, const unsigned int)"
.br
.RI "\fISerialize the layer\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "OutputDataType \fBdelta\fP"
.br
.RI "\fILocally-stored delta object\&. \fP"
.ti -1c
.RI "bool \fBdeterministic\fP"
.br
.RI "\fIIf true dropout and scaling is disabled, see notes above\&. \fP"
.ti -1c
.RI "InputDataType \fBinputParameter\fP"
.br
.RI "\fILocally-stored input parameter object\&. \fP"
.ti -1c
.RI "OutputDataType \fBmask\fP"
.br
.RI "\fILocally-stored mast object\&. \fP"
.ti -1c
.RI "OutputDataType \fBoutputParameter\fP"
.br
.RI "\fILocally-stored output parameter object\&. \fP"
.ti -1c
.RI "double \fBratio\fP"
.br
.RI "\fIThe probability of setting a value to zero\&. \fP"
.ti -1c
.RI "bool \fBrescale\fP"
.br
.RI "\fIIf true the input is rescaled when deterministic is False\&. \fP"
.ti -1c
.RI "double \fBscale\fP"
.br
.RI "\fIThe scale fraction\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat>
.br
class mlpack::ann::Dropout< InputDataType, OutputDataType >"
The dropout layer is a regularizer that randomly with probability ratio sets input values to zero and scales the remaining elements by factor 1 / (1 - ratio)\&. 

If rescale is true the input is scaled with 1 / (1-p) when deterministic is false\&. In the deterministic mode (during testing), the layer just scales the output\&.
.PP
Note: During training you should set deterministic to false and during testing you should set deterministic to true\&.
.PP
For more information, see the following\&.
.PP
.PP
.nf
@article{Hinton2012,
  author  = {Geoffrey E\&. Hinton, Nitish Srivastava, Alex Krizhevsky,
             Ilya Sutskever, Ruslan Salakhutdinov},
  title   = {Improving neural networks by preventing co-adaptation of feature
             detectors},
  journal = {CoRR},
  volume  = {abs/1207\&.0580},
  year    = {2012},
}
.fi
.PP
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIInputDataType\fP Type of the input data (arma::colvec, arma::mat, arma::sp_mat or arma::cube)\&. 
.br
\fIOutputDataType\fP Type of the output data (arma::colvec, arma::mat, arma::sp_mat or arma::cube)\&. 
.RE
.PP

.PP
Definition at line 54 of file dropout\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename InputDataType  = arma::mat, typename OutputDataType  = arma::mat> \fBmlpack::ann::Dropout\fP< InputDataType, OutputDataType >::\fBDropout\fP (const double ratio = \fC0\&.5\fP, const bool rescale = \fCtrue\fP)"

.PP
Create the \fBDropout\fP object using the specified ratio and rescale parameter\&. 
.PP
\fBParameters:\fP
.RS 4
\fIratio\fP The probability of setting a value to zero\&. 
.br
\fIrescale\fP If true the input is rescaled when deterministic is False\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<typename InputDataType  = arma::mat, typename OutputDataType  = arma::mat> template<typename eT > void \fBmlpack::ann::Dropout\fP< InputDataType, OutputDataType >::Backward (const arma::Mat< eT > &&, arma::Mat< eT > && gy, arma::Mat< eT > && g)"

.PP
Ordinary feed backward pass of the dropout layer\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinput\fP The propagated input activation\&. 
.br
\fIgy\fP The backpropagated error\&. 
.br
\fIg\fP The calculated gradient\&. 
.RE
.PP

.SS "template<typename InputDataType  = arma::mat, typename OutputDataType  = arma::mat> OutputDataType const& \fBmlpack::ann::Dropout\fP< InputDataType, OutputDataType >::Delta () const\fC [inline]\fP"

.PP
Get the detla\&. 
.PP
Definition at line 98 of file dropout\&.hpp\&.
.PP
References mlpack::ann::Dropout< InputDataType, OutputDataType >::delta\&.
.SS "template<typename InputDataType  = arma::mat, typename OutputDataType  = arma::mat> OutputDataType& \fBmlpack::ann::Dropout\fP< InputDataType, OutputDataType >::Delta ()\fC [inline]\fP"

.PP
Modify the delta\&. 
.PP
Definition at line 100 of file dropout\&.hpp\&.
.PP
References mlpack::ann::Dropout< InputDataType, OutputDataType >::delta\&.
.SS "template<typename InputDataType  = arma::mat, typename OutputDataType  = arma::mat> bool \fBmlpack::ann::Dropout\fP< InputDataType, OutputDataType >::Deterministic () const\fC [inline]\fP"

.PP
The value of the deterministic parameter\&. 
.PP
Definition at line 103 of file dropout\&.hpp\&.
.PP
References mlpack::ann::Dropout< InputDataType, OutputDataType >::deterministic\&.
.SS "template<typename InputDataType  = arma::mat, typename OutputDataType  = arma::mat> bool& \fBmlpack::ann::Dropout\fP< InputDataType, OutputDataType >::Deterministic ()\fC [inline]\fP"

.PP
Modify the value of the deterministic parameter\&. 
.PP
Definition at line 105 of file dropout\&.hpp\&.
.PP
References mlpack::ann::Dropout< InputDataType, OutputDataType >::deterministic\&.
.SS "template<typename InputDataType  = arma::mat, typename OutputDataType  = arma::mat> template<typename eT > void \fBmlpack::ann::Dropout\fP< InputDataType, OutputDataType >::Forward (const arma::Mat< eT > && input, arma::Mat< eT > && output)"

.PP
Ordinary feed forward pass of the dropout layer\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinput\fP Input data used for evaluating the specified function\&. 
.br
\fIoutput\fP Resulting output activation\&. 
.RE
.PP

.SS "template<typename InputDataType  = arma::mat, typename OutputDataType  = arma::mat> InputDataType const& \fBmlpack::ann::Dropout\fP< InputDataType, OutputDataType >::InputParameter () const\fC [inline]\fP"

.PP
Get the input parameter\&. 
.PP
Definition at line 88 of file dropout\&.hpp\&.
.PP
References mlpack::ann::Dropout< InputDataType, OutputDataType >::inputParameter\&.
.SS "template<typename InputDataType  = arma::mat, typename OutputDataType  = arma::mat> InputDataType& \fBmlpack::ann::Dropout\fP< InputDataType, OutputDataType >::InputParameter ()\fC [inline]\fP"

.PP
Modify the input parameter\&. 
.PP
Definition at line 90 of file dropout\&.hpp\&.
.PP
References mlpack::ann::Dropout< InputDataType, OutputDataType >::inputParameter\&.
.SS "template<typename InputDataType  = arma::mat, typename OutputDataType  = arma::mat> OutputDataType const& \fBmlpack::ann::Dropout\fP< InputDataType, OutputDataType >::OutputParameter () const\fC [inline]\fP"

.PP
Get the output parameter\&. 
.PP
Definition at line 93 of file dropout\&.hpp\&.
.PP
References mlpack::ann::Dropout< InputDataType, OutputDataType >::outputParameter\&.
.SS "template<typename InputDataType  = arma::mat, typename OutputDataType  = arma::mat> OutputDataType& \fBmlpack::ann::Dropout\fP< InputDataType, OutputDataType >::OutputParameter ()\fC [inline]\fP"

.PP
Modify the output parameter\&. 
.PP
Definition at line 95 of file dropout\&.hpp\&.
.PP
References mlpack::ann::Dropout< InputDataType, OutputDataType >::outputParameter\&.
.SS "template<typename InputDataType  = arma::mat, typename OutputDataType  = arma::mat> double \fBmlpack::ann::Dropout\fP< InputDataType, OutputDataType >::Ratio () const\fC [inline]\fP"

.PP
The probability of setting a value to zero\&. 
.PP
Definition at line 108 of file dropout\&.hpp\&.
.PP
References mlpack::ann::Dropout< InputDataType, OutputDataType >::ratio\&.
.SS "template<typename InputDataType  = arma::mat, typename OutputDataType  = arma::mat> void \fBmlpack::ann::Dropout\fP< InputDataType, OutputDataType >::Ratio (const double r)\fC [inline]\fP"

.PP
Modify the probability of setting a value to zero\&. 
.PP
Definition at line 111 of file dropout\&.hpp\&.
.PP
References mlpack::ann::Dropout< InputDataType, OutputDataType >::ratio, and mlpack::ann::Dropout< InputDataType, OutputDataType >::scale\&.
.SS "template<typename InputDataType  = arma::mat, typename OutputDataType  = arma::mat> bool \fBmlpack::ann::Dropout\fP< InputDataType, OutputDataType >::Rescale () const\fC [inline]\fP"

.PP
The value of the rescale parameter\&. 
.PP
Definition at line 118 of file dropout\&.hpp\&.
.PP
References mlpack::ann::Dropout< InputDataType, OutputDataType >::rescale\&.
.SS "template<typename InputDataType  = arma::mat, typename OutputDataType  = arma::mat> bool& \fBmlpack::ann::Dropout\fP< InputDataType, OutputDataType >::Rescale ()\fC [inline]\fP"

.PP
Modify the value of the rescale parameter\&. 
.PP
Definition at line 120 of file dropout\&.hpp\&.
.PP
References mlpack::ann::Dropout< InputDataType, OutputDataType >::rescale, and mlpack::ann::Dropout< InputDataType, OutputDataType >::Serialize()\&.
.SS "template<typename InputDataType  = arma::mat, typename OutputDataType  = arma::mat> template<typename Archive > void \fBmlpack::ann::Dropout\fP< InputDataType, OutputDataType >::Serialize (Archive & ar, const unsigned int)"

.PP
Serialize the layer\&. 
.PP
Referenced by mlpack::ann::Dropout< InputDataType, OutputDataType >::Rescale()\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename InputDataType  = arma::mat, typename OutputDataType  = arma::mat> OutputDataType \fBmlpack::ann::Dropout\fP< InputDataType, OutputDataType >::delta\fC [private]\fP"

.PP
Locally-stored delta object\&. 
.PP
Definition at line 130 of file dropout\&.hpp\&.
.PP
Referenced by mlpack::ann::Dropout< InputDataType, OutputDataType >::Delta()\&.
.SS "template<typename InputDataType  = arma::mat, typename OutputDataType  = arma::mat> bool \fBmlpack::ann::Dropout\fP< InputDataType, OutputDataType >::deterministic\fC [private]\fP"

.PP
If true dropout and scaling is disabled, see notes above\&. 
.PP
Definition at line 148 of file dropout\&.hpp\&.
.PP
Referenced by mlpack::ann::Dropout< InputDataType, OutputDataType >::Deterministic()\&.
.SS "template<typename InputDataType  = arma::mat, typename OutputDataType  = arma::mat> InputDataType \fBmlpack::ann::Dropout\fP< InputDataType, OutputDataType >::inputParameter\fC [private]\fP"

.PP
Locally-stored input parameter object\&. 
.PP
Definition at line 133 of file dropout\&.hpp\&.
.PP
Referenced by mlpack::ann::Dropout< InputDataType, OutputDataType >::InputParameter()\&.
.SS "template<typename InputDataType  = arma::mat, typename OutputDataType  = arma::mat> OutputDataType \fBmlpack::ann::Dropout\fP< InputDataType, OutputDataType >::mask\fC [private]\fP"

.PP
Locally-stored mast object\&. 
.PP
Definition at line 139 of file dropout\&.hpp\&.
.SS "template<typename InputDataType  = arma::mat, typename OutputDataType  = arma::mat> OutputDataType \fBmlpack::ann::Dropout\fP< InputDataType, OutputDataType >::outputParameter\fC [private]\fP"

.PP
Locally-stored output parameter object\&. 
.PP
Definition at line 136 of file dropout\&.hpp\&.
.PP
Referenced by mlpack::ann::Dropout< InputDataType, OutputDataType >::OutputParameter()\&.
.SS "template<typename InputDataType  = arma::mat, typename OutputDataType  = arma::mat> double \fBmlpack::ann::Dropout\fP< InputDataType, OutputDataType >::ratio\fC [private]\fP"

.PP
The probability of setting a value to zero\&. 
.PP
Definition at line 142 of file dropout\&.hpp\&.
.PP
Referenced by mlpack::ann::Dropout< InputDataType, OutputDataType >::Ratio()\&.
.SS "template<typename InputDataType  = arma::mat, typename OutputDataType  = arma::mat> bool \fBmlpack::ann::Dropout\fP< InputDataType, OutputDataType >::rescale\fC [private]\fP"

.PP
If true the input is rescaled when deterministic is False\&. 
.PP
Definition at line 151 of file dropout\&.hpp\&.
.PP
Referenced by mlpack::ann::Dropout< InputDataType, OutputDataType >::Rescale()\&.
.SS "template<typename InputDataType  = arma::mat, typename OutputDataType  = arma::mat> double \fBmlpack::ann::Dropout\fP< InputDataType, OutputDataType >::scale\fC [private]\fP"

.PP
The scale fraction\&. 
.PP
Definition at line 145 of file dropout\&.hpp\&.
.PP
Referenced by mlpack::ann::Dropout< InputDataType, OutputDataType >::Ratio()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
