.TH "mlpack::kernel::KernelTraits< GaussianKernel >" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::kernel::KernelTraits< GaussianKernel > \- Kernel traits for the Gaussian kernel\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBIsNormalized\fP = true"
.br
.RI "\fIThe Gaussian kernel is normalized: K(x, x) = 1 for all x\&. \fP"
.ti -1c
.RI "static const bool \fBUsesSquaredDistance\fP = true"
.br
.RI "\fIThe Gaussian kernel includes a squared distance\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
class mlpack::kernel::KernelTraits< GaussianKernel >"
Kernel traits for the Gaussian kernel\&. 
.PP
Definition at line 167 of file gaussian_kernel\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "const bool \fBmlpack::kernel::KernelTraits\fP< \fBGaussianKernel\fP >::IsNormalized = true\fC [static]\fP"

.PP
The Gaussian kernel is normalized: K(x, x) = 1 for all x\&. 
.PP
Definition at line 171 of file gaussian_kernel\&.hpp\&.
.SS "const bool \fBmlpack::kernel::KernelTraits\fP< \fBGaussianKernel\fP >::UsesSquaredDistance = true\fC [static]\fP"

.PP
The Gaussian kernel includes a squared distance\&. 
.PP
Definition at line 173 of file gaussian_kernel\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
