.TH "mlpack::sparse_coding::NothingInitializer" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::sparse_coding::NothingInitializer \- A DictionaryInitializer for \fBSparseCoding\fP which does not initialize anything; it is useful for when the dictionary is already known and will be set with \fBSparseCoding::Dictionary()\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBInitialize\fP (const arma::mat &, const size_t, arma::mat &)"
.br
.RI "\fIThis function does not initialize the dictionary\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A DictionaryInitializer for \fBSparseCoding\fP which does not initialize anything; it is useful for when the dictionary is already known and will be set with \fBSparseCoding::Dictionary()\fP\&. 
.PP
Definition at line 27 of file nothing_initializer\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static void mlpack::sparse_coding::NothingInitializer::Initialize (const arma::mat &, const size_t, arma::mat &)\fC [inline]\fP, \fC [static]\fP"

.PP
This function does not initialize the dictionary\&. This will cause problems for \fBSparseCoding\fP if the dictionary is not set manually before running the method\&. 
.PP
Definition at line 35 of file nothing_initializer\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
