.TH "src/mlpack/methods/ann/layer/multiply_constant.hpp" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack/methods/ann/layer/multiply_constant.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmlpack::ann::MultiplyConstant< InputDataType, OutputDataType >\fP"
.br
.RI "\fIImplementation of the multiply constant layer\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmlpack\fP"
.br
.RI "\fILinear algebra utility functions, generally performed on matrices or vectors\&. \fP"
.ti -1c
.RI " \fBmlpack::ann\fP"
.br
.RI "\fIArtificial Neural Network\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Marcus Edel
.RE
.PP
Definition of the MultiplyConstantLayer class, which multiplies the input by a (non-learnable) constant\&. 
.PP
Definition in file \fBmultiply_constant\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
