.TH "src/mlpack/prereqs.hpp" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack/prereqs.hpp \- The core includes that mlpack expects; standard C++ includes and Armadillo\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBstd\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_USE_MATH_DEFINES\fP"
.br
.ti -1c
.RI "#define \fBBOOST_MPL_CFG_NO_PREPROCESSED_HEADERS\fP"
.br
.ti -1c
.RI "#define \fBBOOST_MPL_LIMIT_LIST_SIZE\fP   40"
.br
.ti -1c
.RI "#define \fBBOOST_PFTO\fP"
.br
.ti -1c
.RI "#define \fBforce_inline\fP"
.br
.ti -1c
.RI "#define \fBM_PI\fP   3\&.141592653589793238462643383279"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "template<bool B, class T  = void> using \fBstd::enable_if_t\fP = typename enable_if< B, T >::type"
.br
.in -1c
.SH "Detailed Description"
.PP 
The core includes that mlpack expects; standard C++ includes and Armadillo\&. 

mlpack is free software; you may redistribute it and/or modify it under the terms of the 3-clause BSD license\&. You should have received a copy of the 3-clause BSD license along with mlpack\&. If not, see http://www.opensource.org/licenses/BSD-3-Clause for more information\&. 
.PP
Definition in file \fBprereqs\&.hpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define _USE_MATH_DEFINES"

.PP
Definition at line 15 of file prereqs\&.hpp\&.
.SS "#define BOOST_MPL_CFG_NO_PREPROCESSED_HEADERS"

.PP
Definition at line 68 of file prereqs\&.hpp\&.
.SS "#define BOOST_MPL_LIMIT_LIST_SIZE   40"

.PP
Definition at line 69 of file prereqs\&.hpp\&.
.SS "#define BOOST_PFTO"

.PP
Definition at line 84 of file prereqs\&.hpp\&.
.SS "#define force_inline"

.PP
Definition at line 44 of file prereqs\&.hpp\&.
.SS "#define M_PI   3\&.141592653589793238462643383279"

.PP
Definition at line 40 of file prereqs\&.hpp\&.
.PP
Referenced by mlpack::kernel::SphericalKernel::Normalizer(), and mlpack::kernel::GaussianKernel::Normalizer()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
