.TH "src/mlpack/methods/rann/ra_search.hpp" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack/methods/rann/ra_search.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmlpack::neighbor::RAModel< SortPolicy >\fP"
.br
.RI "\fIThe \fBRAModel\fP class provides an abstraction for the \fBRASearch\fP class, abstracting away the TreeType parameter and allowing it to be specified at runtime in this class\&. \fP"
.ti -1c
.RI "class \fBmlpack::neighbor::RASearch< SortPolicy, MetricType, MatType, TreeType >\fP"
.br
.RI "\fIThe \fBRASearch\fP class: This class provides a generic manner to perform rank-approximate search via random-sampling\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmlpack\fP"
.br
.RI "\fILinear algebra utility functions, generally performed on matrices or vectors\&. \fP"
.ti -1c
.RI " \fBmlpack::neighbor\fP"
.br
.RI "\fINeighbor-search routines\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Parikshit Ram
.RE
.PP
Defines the RASearch class, which performs an abstract rank-approximate nearest/farthest neighbor query on two datasets\&.
.PP
The details of this method can be found in the following paper:
.PP
{ram2009rank, title={{Rank-Approximate Nearest Neighbor Search: Retaining Meaning and Speed in High Dimensions}}, author={{Ram, P\&. and Lee, D\&. and Ouyang, H\&. and Gray, A\&. G\&.}}, booktitle={{Advances of Neural Information Processing Systems}}, year={2009} }
.PP
mlpack is free software; you may redistribute it and/or modify it under the terms of the 3-clause BSD license\&. You should have received a copy of the 3-clause BSD license along with mlpack\&. If not, see http://www.opensource.org/licenses/BSD-3-Clause for more information\&. 
.PP
Definition in file \fBra_search\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
