.TH "src/mlpack/core/math/random.hpp" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack/core/math/random.hpp \- Miscellaneous math random-related routines\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmlpack\fP"
.br
.RI "\fILinear algebra utility functions, generally performed on matrices or vectors\&. \fP"
.ti -1c
.RI " \fBmlpack::math\fP"
.br
.RI "\fIMiscellaneous math routines\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmlpack::math::ObtainDistinctSamples\fP (const size_t loInclusive, const size_t hiExclusive, const size_t maxNumSamples, arma::uvec &distinctSamples)"
.br
.RI "\fIObtains no more than maxNumSamples distinct samples\&. \fP"
.ti -1c
.RI "int \fBmlpack::math::RandInt\fP (const int hiExclusive)"
.br
.RI "\fIGenerates a uniform random integer\&. \fP"
.ti -1c
.RI "int \fBmlpack::math::RandInt\fP (const int lo, const int hiExclusive)"
.br
.RI "\fIGenerates a uniform random integer\&. \fP"
.ti -1c
.RI "double \fBmlpack::math::RandNormal\fP ()"
.br
.RI "\fIGenerates a normally distributed random number with mean 0 and variance 1\&. \fP"
.ti -1c
.RI "double \fBmlpack::math::RandNormal\fP (const double mean, const double variance)"
.br
.RI "\fIGenerates a normally distributed random number with specified mean and variance\&. \fP"
.ti -1c
.RI "double \fBmlpack::math::Random\fP ()"
.br
.RI "\fIGenerates a uniform random number between 0 and 1\&. \fP"
.ti -1c
.RI "double \fBmlpack::math::Random\fP (const double lo, const double hi)"
.br
.RI "\fIGenerates a uniform random number in the specified range\&. \fP"
.ti -1c
.RI "void \fBmlpack::math::RandomSeed\fP (const size_t seed)"
.br
.RI "\fISet the random seed used by the random functions (\fBRandom()\fP and \fBRandInt()\fP)\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "MLPACK_EXPORT std::mt19937 \fBmlpack::math::randGen\fP"
.br
.RI "\fIMLPACK_EXPORT is required for global variables; it exports the symbols correctly on Windows\&. \fP"
.ti -1c
.RI "MLPACK_EXPORT std::normal_distribution \fBmlpack::math::randNormalDist\fP"
.br
.ti -1c
.RI "MLPACK_EXPORT std::uniform_real_distribution \fBmlpack::math::randUniformDist\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Miscellaneous math random-related routines\&. 

mlpack is free software; you may redistribute it and/or modify it under the terms of the 3-clause BSD license\&. You should have received a copy of the 3-clause BSD license along with mlpack\&. If not, see http://www.opensource.org/licenses/BSD-3-Clause for more information\&. 
.PP
Definition in file \fBrandom\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
