.TH "src/mlpack/methods/cf/svd_wrapper.hpp" 3 "Sat Mar 25 2017" "Version master" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mlpack/methods/cf/svd_wrapper.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmlpack::cf::DummyClass\fP"
.br
.RI "\fIThis class acts as a dummy class for passing as template parameter\&. \fP"
.ti -1c
.RI "class \fBmlpack::cf::SVDWrapper< Factorizer >\fP"
.br
.RI "\fIThis class acts as the wrapper for all SVD factorizers which are incompatible with \fBCF\fP module\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmlpack\fP"
.br
.RI "\fILinear algebra utility functions, generally performed on matrices or vectors\&. \fP"
.ti -1c
.RI " \fBmlpack::cf\fP"
.br
.RI "\fICollaborative filtering\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef SVDWrapper< DummyClass > \fBmlpack::cf::ArmaSVDFactorizer\fP"
.br
.RI "\fIadd simple typedefs \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Sumedh Ghaisas
.RE
.PP
Wrapper class for SVD factorizers used for Collaborative Filtering\&.
.PP
mlpack is free software; you may redistribute it and/or modify it under the terms of the 3-clause BSD license\&. You should have received a copy of the 3-clause BSD license along with mlpack\&. If not, see http://www.opensource.org/licenses/BSD-3-Clause for more information\&. 
.PP
Definition in file \fBsvd_wrapper\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
