# Makefile for dirlib ~/g/kde

here		= kde

includes	= allnn.h cp_args.h cp_string.h cp_platform.h cp_utils.h

sources		= allnn.c kde.c cp_args.c cp_string.c cp_utils.c

private_sources = 

siblings	= dyvballs dset extra utils nbody_headers mrkd

#t:=fastdebug
include .g/Make.common
