// The style checker build will check the style of all the code in the
// repository.
pipeline
{
  // Run inside of the custom Docker image for style checking.
  agent
  {
    docker { image 'ubuntu:22.04' }
  }

  stages
  {
    // Get tools that we need.
    stage('Set up environment')
    {
      steps
      {
        sh '''
          apt-get update
          apt-get install -y python3 python3-venv git
        '''
      }
    }

    // First we have to check out the jenkins-conf repository, which contains
    // the scripts that we will use for checking the style.
    stage('Check out jenkins-conf repository')
    {
      steps
      {
        sh '''
          git clone https://github.com/mlpack/jenkins-conf
        '''
      }
    }

    // Now we can run those scripts.
    stage('Check code style')
    {
      steps
      {
        sh '''
          mkdir -p reports
          ./jenkins-conf/linter/lint.sh \
              --root . \
              --reports reports/cpplint.junit.xml \
              --dir ./src/mlpack

          # Print the results.
          cat reports/cpplint.junit.xml
        '''
      }
    }
  }
}
