src/mlpack/bindings/matlab/allkfn/CMakeLists.txt File Reference
Functions
add_library (allkfn_mex SHARED allkfn.cpp) target_link_libraries(allkfn_mex mlpack $
install (TARGETS allkfn_mex LIBRARY DESTINATION`${MATLAB_TOOLBOX_DIR}/mlpack/`) install(FILES allkfn.m DESTINATION`$
Function Documentation
add_library (allkfn_mex SHARED allkfn. cpp)
Definition at line 4 of file CMakeLists.txt.
References file().
Referenced by add_subdirectory().
install (TARGETS allkfn_mex LIBRARY DESTINATION`${MATLAB_TOOLBOX_DIR}/mlpack/`)
Definition at line 13 of file CMakeLists.txt.
Referenced by file(), and macro().