src/mlpack/bindings/matlab/CMakeLists.txt File Reference
Functions
the MATLAB version can probably be deleted (always save a copy in case this is wrong!).` `\nFor more information on this confusing issue
find_package (MatlabMex REQUIRED) if(UNIX) execute_process(COMMAND`$
test cpp RESULT_VARIABLE MEX_RESULT_TRASH OUTPUT_VARIABLE MEX_OUTPUT ERROR_VARIABLE MEX_ERROR_TRASH string (REGEX MATCH`Warning: You are using`MEX_WARNING`${MEX_OUTPUT}`) if(MEX_WARNING) string(REGEX REPLACE`.*using [a-zA-Z]* version \`([0-9.]*)[^\`]*\`.*``\\1`OTHER_COMPILER_VERSION`$
string (REGEX REPLACE`.*currently supported with MEX is \`([0-9.]*)[^\`]*\`.*``\\1`MEX_COMPILER_VERSION`${MEX_OUTPUT}`) set(NEED_TO_WARN 1) if(MEX_COMPILER_VERSION AND OTHER_COMPILER_VERSION) if(NOT(`$
Variables
the MATLAB version can probably be see n http
VERSION_LESS
Function Documentation
the MATLAB version can probably be deleted (always save a copy in case this is wrong!)
find_package (MatlabMex REQUIRED)
Definition at line 5 of file CMakeLists.txt.
test cpp RESULT_VARIABLE MEX_RESULT_TRASH OUTPUT_VARIABLE MEX_OUTPUT ERROR_VARIABLE MEX_ERROR_TRASH string (REGEX MATCH`Warning: You are using`MEX_WARNING`${MEX_OUTPUT}`))[^\`]
Definition at line 18 of file CMakeLists.txt.
Referenced by mlpack::data::Extension(), mlpack::data::LoadCSV::GetMatrixSize(), mlpack::data::LoadCSV::GetTransposeMatrixSize(), mlpack::data::IncrementPolicy::MapTokens(), mlpack::data::LoadCSV::NonTranposeParse(), mlpack::util::PrefixedOutStream::PrefixedOutStream(), mlpack::range::RSModel::RandomBasis(), mlpack::neighbor::NSModel< SortPolicy >::RandomBasis(), mlpack::util::StringTypeParam(), mlpack::Timers::Timers(), and mlpack::data::LoadCSV::TranposeParseImpl().
string (REGEX REPLACE`.*currently supported with MEX is \`([0-9.]*)*\`.*``\\1`MEX_COMPILER_VERSION`${MEX_OUTPUT}` [^\`])
Definition at line 27 of file CMakeLists.txt.
Variable Documentation
the MATLAB version can probably be see n http
Definition at line 56 of file CMakeLists.txt.
VERSION_LESS
Initial value:
{OTHER_COMPILER_VERSION}"))
        set(NEED_TO_WARN 0)
      endif(NOT ("${MEX_COMPILER_VERSION}" VERSION_LESS
          "${OTHER_COMPILER_VERSION}"))
    endif()
    if(NEED_TO_WARN EQUAL 1)
      message(WARNING "The MATLAB runtime glibc is different than the system "
          " glibc. This can (and probably will) cause the MLPACK bindings "
          "generated by this build script to fail with odd GLIBCXX_a_b_c "
          "version complaints when they are run. Assuming that the system "
          "glibc is newer than the MATLAB-provided version
Definition at line 38 of file CMakeLists.txt.