mlpack::ann::SoftplusFunction Class Reference
The softplus function, defined by.
Static Public Member Functions
static double Deriv (const double y)
Computes the first derivative of the softplus function.
template<typename InputVecType , typename OutputVecType >
static void Deriv (const InputVecType &y, OutputVecType &x)
Computes the first derivatives of the softplus function.
static double Fn (const double x)
Computes the softplus function.
template<typename InputVecType , typename OutputVecType >
static void Fn (const InputVecType &x, OutputVecType &y)
Computes the softplus function.
static double Inv (const double y)
Computes the inverse of the softplus function.
template<typename InputVecType , typename OutputVecType >
static void Inv (const InputVecType &y, OutputVecType &x)
Computes the inverse of the softplus function.
Detailed Description
The softplus function, defined by.
 f(x) &=& \ln(1 + e^{x}) \\ f'(x) &=& \frac{1}{1 + e^{-x}} \\ f^{-1}(y) &=& \ln(e^{y} - 1) 
Definition at line 43 of file softplus_function.hpp.
Member Function Documentation
static double mlpack::ann::SoftplusFunction::Deriv (const double y) [inline], [static]
Computes the first derivative of the softplus function.
Parameters
y Input data.
Returns
f'(x)
Definition at line 81 of file softplus_function.hpp.
template<typename InputVecType , typename OutputVecType > static void mlpack::ann::SoftplusFunction::Deriv (const InputVecType & y, OutputVecType & x) [inline], [static]
Computes the first derivatives of the softplus function.
Parameters
y Input activations.
x The resulting derivatives.
Definition at line 93 of file softplus_function.hpp.
static double mlpack::ann::SoftplusFunction::Fn (const double x) [inline], [static]
Computes the softplus function.
Parameters
x Input data.
Returns
f(x).
Definition at line 53 of file softplus_function.hpp.
Referenced by Fn().
template<typename InputVecType , typename OutputVecType > static void mlpack::ann::SoftplusFunction::Fn (const InputVecType & x, OutputVecType & y) [inline], [static]
Computes the softplus function.
Parameters
x Input data.
y The resulting output activation.
Definition at line 67 of file softplus_function.hpp.
References Fn().
static double mlpack::ann::SoftplusFunction::Inv (const double y) [inline], [static]
Computes the inverse of the softplus function.
Parameters
y Input data.
Returns
f^{-1}(y)
Definition at line 104 of file softplus_function.hpp.
Referenced by Inv().
template<typename InputVecType , typename OutputVecType > static void mlpack::ann::SoftplusFunction::Inv (const InputVecType & y, OutputVecType & x) [inline], [static]
Computes the inverse of the softplus function.
Parameters
y Input data.
x The resulting inverse of the input data.
Definition at line 116 of file softplus_function.hpp.
References Inv().
The documentation for this class was generated from the following file:
src/mlpack/methods/ann/activation_functions/softplus_function.hpp