mlpack::optimization::test::RosenbrockFunction Class Reference
The Rosenbrock function, defined by f(x) = f1(x) + f2(x) f1(x) = 100 (x2 - x1^2)^2 f2(x) = (1 - x1)^2 x_0 = [-1.2, 1].
Public Member Functions
RosenbrockFunction ()
double Evaluate (const arma::mat &coordinates)
const arma::mat & GetInitialPoint () const
void Gradient (const arma::mat &coordinates, arma::mat &gradient)
Private Attributes
arma::mat initialPoint
Detailed Description
The Rosenbrock function, defined by f(x) = f1(x) + f2(x) f1(x) = 100 (x2 - x1^2)^2 f2(x) = (1 - x1)^2 x_0 = [-1.2, 1].
This should optimize to f(x) = 0, at x = [1, 1].
`An automatic method for finding the greatest or least value of a function.` H.H. Rosenbrock. 1960. Comput. J. 3., 175-184.
Definition at line 53 of file test_functions.hpp.
Constructor & Destructor Documentation
mlpack::optimization::test::RosenbrockFunction::RosenbrockFunction ()
Member Function Documentation
double mlpack::optimization::test::RosenbrockFunction::Evaluate (const arma::mat & coordinates)
Referenced by mlpack::optimization::test::GeneralizedRosenbrockFunction::NumFunctions().
const arma::mat& mlpack::optimization::test::RosenbrockFunction::GetInitialPoint () const
Referenced by mlpack::optimization::test::GeneralizedRosenbrockFunction::NumFunctions().
void mlpack::optimization::test::RosenbrockFunction::Gradient (const arma::mat & coordinates, arma::mat & gradient)
Referenced by mlpack::optimization::test::GeneralizedRosenbrockFunction::NumFunctions().
Member Data Documentation
arma::mat mlpack::optimization::test::RosenbrockFunction::initialPoint [private]
Definition at line 64 of file test_functions.hpp.
The documentation for this class was generated from the following file:
src/mlpack/core/optimizers/lbfgs/test_functions.hpp