mlpack::ann::RectifierFunction Class Reference
The rectifier function, defined by.
Static Public Member Functions
static double Deriv (const double y)
Computes the first derivative of the rectifier function.
template<typename InputType , typename OutputType >
static void Deriv (const InputType &y, OutputType &x)
Computes the first derivatives of the rectifier function.
static double Fn (const double x)
Computes the rectifier function.
template<typename eT >
static void Fn (const arma::Mat< eT > &x, arma::Mat< eT > &y)
Computes the rectifier function using a dense matrix as input.
template<typename eT >
static void Fn (const arma::Cube< eT > &x, arma::Cube< eT > &y)
Computes the rectifier function using a 3rd-order tensor as input.
Detailed Description
The rectifier function, defined by.
 f(x) &=& \max(0, x) \\ f'(x) &=& \left\{ \begin{array}{lr} 1 & : x > 0 \\ 0 & : x \le 0 \end{array} \right. 
Definition at line 45 of file rectifier_function.hpp.
Member Function Documentation
static double mlpack::ann::RectifierFunction::Deriv (const double y) [inline], [static]
Computes the first derivative of the rectifier function.
Parameters
x Input data.
Returns
f'(x)
Definition at line 91 of file rectifier_function.hpp.
Referenced by Deriv().
template<typename InputType , typename OutputType > static void mlpack::ann::RectifierFunction::Deriv (const InputType & y, OutputType & x) [inline], [static]
Computes the first derivatives of the rectifier function.
Parameters
y Input activations.
x The resulting derivatives.
Definition at line 103 of file rectifier_function.hpp.
References Deriv().
static double mlpack::ann::RectifierFunction::Fn (const double x) [inline], [static]
Computes the rectifier function.
Parameters
x Input data.
Returns
f(x).
Definition at line 54 of file rectifier_function.hpp.
Referenced by Fn().
template<typename eT > static void mlpack::ann::RectifierFunction::Fn (const arma::Mat< eT > & x, arma::Mat< eT > & y) [inline], [static]
Computes the rectifier function using a dense matrix as input.
Parameters
x Input data.
y The resulting output activation.
Definition at line 66 of file rectifier_function.hpp.
template<typename eT > static void mlpack::ann::RectifierFunction::Fn (const arma::Cube< eT > & x, arma::Cube< eT > & y) [inline], [static]
Computes the rectifier function using a 3rd-order tensor as input.
Parameters
x Input data.
y The resulting output activation.
Definition at line 78 of file rectifier_function.hpp.
References Fn().
The documentation for this class was generated from the following file:
src/mlpack/methods/ann/activation_functions/rectifier_function.hpp