mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType > Class Template Reference
A rectangle type tree tree, such as an R-tree or X-tree.
Classes
class DualTreeTraverser
A dual tree traverser for rectangle type trees.
class SingleTreeTraverser
A single traverser for rectangle type trees.
Public Types
typedef AuxiliaryInformationType< RectangleTree > AuxiliaryInformation
The auxiliary information type held by the tree.
typedef MatType::elem_type ElemType
The element type held by the matrix type.
typedef MatType Mat
So other classes can use TreeType::Mat.
Public Member Functions
RectangleTree (const MatType &data, const size_t maxLeafSize=20, const size_t minLeafSize=8, const size_t maxNumChildren=5, const size_t minNumChildren=2, const size_t firstDataIndex=0)
Construct this as the root node of a rectangle type tree using the given dataset.
RectangleTree (MatType &&data, const size_t maxLeafSize=20, const size_t minLeafSize=8, const size_t maxNumChildren=5, const size_t minNumChildren=2, const size_t firstDataIndex=0)
Construct this as the root node of a rectangle tree type using the given dataset, and taking ownership of the given dataset.
RectangleTree (RectangleTree *parentNode, const size_t numMaxChildren=0)
Construct this as an empty node with the specified parent.
RectangleTree (const RectangleTree &other, const bool deepCopy=true, RectangleTree *newParent=NULL)
Create a rectangle tree by copying the other tree.
RectangleTree (RectangleTree &&other)
Create a rectangle tree by moving the other tree.
template<typename Archive >
RectangleTree (Archive &ar, const typename std::enable_if_t< Archive::is_loading::value > *=0)
Construct the tree from a boost::serialization archive.
~RectangleTree ()
Deletes this node, deallocating the memory for the children and calling their destructors in turn.
const AuxiliaryInformationType< RectangleTree > & AuxiliaryInfo () const
Return the auxiliary information object of this node.
AuxiliaryInformationType< RectangleTree > & AuxiliaryInfo ()
Modify the split object of this node.
size_t Begin () const
Return the index of the beginning point of this subset.
size_t & Begin ()
Modify the index of the beginning point of this subset.
const bound::HRectBound< MetricType > & Bound () const
Return the bound object for this node.
bound::HRectBound< MetricType > & Bound ()
Modify the bound object for this node.
void Center (arma::vec &center)
Get the centroid of the node and store it in the given vector.
RectangleTree & Child (const size_t child) const
Get the specified child.
RectangleTree & Child (const size_t child)
Modify the specified child.
void CondenseTree (const arma::vec &point, std::vector< bool > &relevels, const bool usePoint)
Condense the bounding rectangles for this node based on the removal of the point specified by the arma::vec&.
size_t Count () const
Return the number of points in this subset.
size_t & Count ()
Modify the number of points in this subset.
const MatType & Dataset () const
Get the dataset which the tree is built on.
MatType & Dataset ()
Modify the dataset which the tree is built on. Be careful!
bool DeletePoint (const size_t point)
Deletes a point from the treeand, updates the bounding rectangle.
bool DeletePoint (const size_t point, std::vector< bool > &relevels)
Deletes a point from the tree, updates the bounding rectangle, tracking levels.
size_t Descendant (const size_t index) const
Return the index (with reference to the dataset) of a particular descendant of this node.
RectangleTree * ExactClone ()
Make an exact copy of this node, pointers and everything.
const RectangleTree * FindByBeginCount (size_t begin, size_t count) const
Find a node in this tree by its begin and count (const).
RectangleTree * FindByBeginCount (size_t begin, size_t count)
Find a node in this tree by its begin and count.
ElemType FurthestDescendantDistance () const
Return the furthest possible descendant distance.
ElemType FurthestPointDistance () const
Return the furthest distance to a point held in this node.
template<typename VecType >
size_t GetFurthestChild (const VecType &point, typename std::enable_if_t< IsVector< VecType >::value > *=0)
Return the index of the furthest child node to the given query point.
size_t GetFurthestChild (const RectangleTree &queryNode)
Return the index of the furthest child node to the given query node.
template<typename VecType >
size_t GetNearestChild (const VecType &point, typename std::enable_if_t< IsVector< VecType >::value > *=0)
Return the index of the nearest child node to the given query point.
size_t GetNearestChild (const RectangleTree &queryNode)
Return the index of the nearest child node to the given query node.
void InsertNode (RectangleTree *node, const size_t level, std::vector< bool > &relevels)
Inserts a node into the tree, tracking which levels have been inserted into.
void InsertPoint (const size_t point)
Inserts a point into the tree.
void InsertPoint (const size_t point, std::vector< bool > &relevels)
Inserts a point into the tree, tracking which levels have been inserted into.
bool IsLeaf () const
Return whether or not this node is a leaf (true if it has no children).
ElemType MaxDistance (const RectangleTree &other) const
Return the maximum distance to another node.
template<typename VecType >
ElemType MaxDistance (const VecType &point, typename std::enable_if_t< IsVector< VecType >::value > *=0) const
Return the maximum distance to another point.
size_t MaxLeafSize () const
Return the maximum leaf size.
size_t & MaxLeafSize ()
Modify the maximum leaf size.
size_t MaxNumChildren () const
Return the maximum number of children (in a non-leaf node).
size_t & MaxNumChildren ()
Modify the maximum number of children (in a non-leaf node).
MetricType Metric () const
Get the metric which the tree uses.
ElemType MinDistance (const RectangleTree &other) const
Return the minimum distance to another node.
template<typename VecType >
ElemType MinDistance (const VecType &point, typename std::enable_if_t< IsVector< VecType >::value > *=0) const
Return the minimum distance to another point.
ElemType MinimumBoundDistance () const
Return the minimum distance from the center to any edge of the bound.
size_t MinLeafSize () const
Return the minimum leaf size.
size_t & MinLeafSize ()
Modify the minimum leaf size.
size_t MinNumChildren () const
Return the minimum number of children (in a non-leaf node).
size_t & MinNumChildren ()
Modify the minimum number of children (in a non-leaf node).
void NullifyData ()
Nullify the auxiliary information.
size_t NumChildren () const
Return the number of child nodes. (One level beneath this one only.)
size_t & NumChildren ()
Modify the number of child nodes. Be careful.
size_t NumDescendants () const
Return the number of descendants of this node.
size_t NumPoints () const
Return the number of points in this node (returns 0 if this node is not a leaf).
RectangleTree * Parent () const
Gets the parent of this node.
RectangleTree *& Parent ()
Modify the parent of this node.
ElemType ParentDistance () const
Return the distance from the center of this node to the center of the parent node.
ElemType & ParentDistance ()
Modify the distance from the center of this node to the center of the parent node.
size_t Point (const size_t index) const
Return the index (with reference to the dataset) of a particular point in this node.
size_t & Point (const size_t index)
Modify the index of a particular point in this node.
math::RangeType< ElemType > RangeDistance (const RectangleTree &other) const
Return the minimum and maximum distance to another node.
template<typename VecType >
math::RangeType< ElemType > RangeDistance (const VecType &point, typename std::enable_if_t< IsVector< VecType >::value > *=0) const
Return the minimum and maximum distance to another point.
bool RemoveNode (const RectangleTree *node, std::vector< bool > &relevels)
Removes a node from the tree.
template<typename Archive >
void Serialize (Archive &ar, const unsigned int)
Serialize the tree.
bool ShrinkBoundForBound (const bound::HRectBound< MetricType > &changedBound)
Shrink the bound object of this node for the removal of a child node.
bool ShrinkBoundForPoint (const arma::vec &point)
Shrink the bound object of this node for the removal of a point.
void SoftDelete ()
Delete this node of the tree, but leave the stuff contained in it intact.
const StatisticType & Stat () const
Return the statistic object for this node.
StatisticType & Stat ()
Modify the statistic object for this node.
size_t TreeDepth () const
Obtains the number of levels below this node in the tree, starting with this.
size_t TreeSize () const
Obtains the number of nodes in the tree, starting with this.
Protected Member Functions
RectangleTree ()
A default constructor.
Protected Attributes
friend AuxiliaryInformation
Give friend access for AuxiliaryInformationType.
friend DescentType
Give friend access for DescentType.
friend SplitType
Give friend access for SplitType.
Private Member Functions
void SplitNode (std::vector< bool > &relevels)
Splits the current node, recursing up the tree.
Private Attributes
AuxiliaryInformationType< RectangleTree > auxiliaryInfo
A tree-specific information.
size_t begin
The index of the first point in the dataset contained in this node (and its children).
bound::HRectBound< metric::EuclideanDistance, ElemType > bound
The bound object for this node.
std::vector< RectangleTree * > children
The child nodes (Starting at 0 and ending at (numChildren-1)).
size_t count
The number of points in the dataset contained in this node (and its children).
const MatType * dataset
The dataset.
size_t maxLeafSize
The max leaf size.
size_t maxNumChildren
The max number of child nodes a non-leaf node can have.
size_t minLeafSize
The minimum leaf size.
size_t minNumChildren
The minimum number of child nodes a non-leaf node can have.
size_t numChildren
The number of child nodes actually in use (0 if this is a leaf node).
size_t numDescendants
The number of descendants of this node.
bool ownsDataset
Whether or not we are responsible for deleting the dataset.
RectangleTree * parent
The parent node (NULL if this is the root of the tree).
ElemType parentDistance
The distance from the centroid of this node to the centroid of the parent.
std::vector< size_t > points
The mapping to the dataset.
StatisticType stat
Any extra data contained in the node.
Detailed Description
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation>
*
class mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >
A rectangle type tree tree, such as an R-tree or X-tree.
Once the bound and type of dataset is defined, the tree will construct itself. Call the constructor with the dataset to build the tree on, and the entire tree will be built.
This tree does allow growth, so you can add and delete nodes from it.
Template Parameters
MetricType This must be EuclideanDistance, but the template parameter is required to satisfy the TreeType API.
StatisticType Extra data contained in the node. See statistic.hpp for the necessary skeleton interface.
MatType The dataset class.
SplitType The type of split to use when inserting points.
DescentType The heuristic to use when descending the tree to insert points.
AuxiliaryInformationType An auxiliary information contained in the node. This information depends on the type of the RectangleTree.
Definition at line 53 of file rectangle_tree.hpp.
Member Typedef Documentation
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> typedef AuxiliaryInformationType<RectangleTree> mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::AuxiliaryInformation
The auxiliary information type held by the tree.
Definition at line 65 of file rectangle_tree.hpp.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> typedef MatType::elem_type mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::ElemType
The element type held by the matrix type.
Definition at line 63 of file rectangle_tree.hpp.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> typedef MatType mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Mat
So other classes can use TreeType::Mat.
Definition at line 57 of file rectangle_tree.hpp.
Constructor & Destructor Documentation
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::RectangleTree (const MatType & data, const size_t maxLeafSize = 20, const size_t minLeafSize = 8, const size_t maxNumChildren = 5, const size_t minNumChildren = 2, const size_t firstDataIndex = 0)
Construct this as the root node of a rectangle type tree using the given dataset.
This will modify the ordering of the points in the dataset!
Parameters
data Dataset from which to create the tree. This will be modified!
maxLeafSize Maximum size of each leaf in the tree.
minLeafSize Minimum size of each leaf in the tree.
maxNumChildren The maximum number of child nodes a non-leaf node may have.
minNumChildren The minimum number of child nodes a non-leaf node may have.
firstDataIndex The index of the first data point. UNUSED UNLESS WE ADD SUPPORT FOR HAVING A `CENTERAL` DATA MATRIX.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::RectangleTree (MatType && data, const size_t maxLeafSize = 20, const size_t minLeafSize = 8, const size_t maxNumChildren = 5, const size_t minNumChildren = 2, const size_t firstDataIndex = 0)
Construct this as the root node of a rectangle tree type using the given dataset, and taking ownership of the given dataset.
Parameters
data Dataset from which to create the tree.
maxLeafSize Maximum size of each leaf in the tree.
minLeafSize Minimum size of each leaf in the tree.
maxNumChildren The maximum number of child nodes a non-leaf node may have.
minNumChildren The minimum number of child nodes a non-leaf node may have.
firstDataIndex The index of the first data point. UNUSED UNLESS WE ADD SUPPORT FOR HAVING A `CENTERAL` DATA MATRIX.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::RectangleTree (RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType > * parentNode, const size_t numMaxChildren = 0) [explicit]
Construct this as an empty node with the specified parent.
Copying the parameters (maxLeafSize, minLeafSize, maxNumChildren, minNumChildren, firstDataIndex) from the parent.
Parameters
parentNode The parent of the node that is being constructed.
numMaxChildren The max number of child nodes (used in x-trees).
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::RectangleTree (const RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType > & other, const bool deepCopy = true, RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType > * newParent = NULL)
Create a rectangle tree by copying the other tree.
Be careful! This can take a long time and use a lot of memory.
Parameters
other The tree to be copied.
deepCopy If false, the children are not recursively copied.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::RectangleTree (RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType > && other)
Create a rectangle tree by moving the other tree.
Parameters
other The tree to be copied.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> template<typename Archive > mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::RectangleTree (Archive & ar, const typename std::enable_if_t< Archive::is_loading::value > * = 0)
Construct the tree from a boost::serialization archive.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::~RectangleTree ()
Deletes this node, deallocating the memory for the children and calling their destructors in turn.
This will invalidate any younters or references to any nodes which are children of this one.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::RectangleTree () [protected]
A default constructor.
This is meant to only be used with boost::serialization, which is allowed with the friend declaration below. This does not return a valid tree! This method must be protected, so that the serialization shim can work with the default constructor.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Count().
Member Function Documentation
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> const AuxiliaryInformationType<RectangleTree>& mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::AuxiliaryInfo () const [inline]
Return the auxiliary information object of this node.
Definition at line 309 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::auxiliaryInfo.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> AuxiliaryInformationType<RectangleTree>& mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::AuxiliaryInfo () [inline]
Modify the split object of this node.
Definition at line 312 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::auxiliaryInfo, and mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::IsLeaf().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Begin () const [inline]
Return the index of the beginning point of this subset.
Definition at line 527 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::begin.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t& mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Begin () [inline]
Modify the index of the beginning point of this subset.
Definition at line 529 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::begin.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> const bound::HRectBound<MetricType>& mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Bound () const [inline]
Return the bound object for this node.
Definition at line 299 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::bound.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::MaxDistance(), mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::MinDistance(), and mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::RangeDistance().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> bound::HRectBound<MetricType>& mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Bound () [inline]
Modify the bound object for this node.
Definition at line 301 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::bound.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> void mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Center (arma::vec & center) [inline]
Get the centroid of the node and store it in the given vector.
Definition at line 352 of file rectangle_tree.hpp.
References mlpack::bound::HRectBound< MetricType, ElemType >::Center().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> RectangleTree& mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Child (const size_t child) const [inline]
Get the specified child.
Parameters
child Index of child to return.
Definition at line 421 of file rectangle_tree.hpp.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> RectangleTree& mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Child (const size_t child) [inline]
Modify the specified child.
Parameters
child Index of child to return.
Definition at line 431 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Descendant(), mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::NumDescendants(), and mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::NumPoints().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> void mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::CondenseTree (const arma::vec & point, std::vector< bool > & relevels, const bool usePoint)
Condense the bounding rectangles for this node based on the removal of the point specified by the arma::vec&.
This recurses up the tree. If a node goes below the minimum fill, this function will fix the tree.
Parameters
point The arma::vec& of the point that was removed to require this condesation of the tree.
usePoint True if we use the optimized version of the algorithm that is possible when we now what point was deleted. False otherwise (eg. if we deleted a node instead of a point).
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Count () const [inline]
Return the number of points in this subset.
Definition at line 532 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::count.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t& mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Count () [inline]
Modify the number of points in this subset.
Definition at line 534 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::count, mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::RectangleTree(), and mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::SplitNode().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> const MatType& mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Dataset () const [inline]
Get the dataset which the tree is built on.
Definition at line 344 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::dataset.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> MatType& mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Dataset () [inline]
Modify the dataset which the tree is built on. Be careful!
Definition at line 346 of file rectangle_tree.hpp.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> bool mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::DeletePoint (const size_t point)
Deletes a point from the treeand, updates the bounding rectangle.
However, the point will be kept in the centeral dataset. (The user may remove it from there if he wants, but he must not change the indices of the other points.) Returns true if the point is successfully removed and false if it is not. (ie. the point is not in the tree)
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> bool mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::DeletePoint (const size_t point, std::vector< bool > & relevels)
Deletes a point from the tree, updates the bounding rectangle, tracking levels.
However, the point will be kept in the centeral dataset. (The user may remove it from there if he wants, but he must not change the indices of the other points.) Returns true if the point is successfully removed and false if it is not. (ie. the point is not in the tree)
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Descendant (const size_t index) const
Return the index (with reference to the dataset) of a particular descendant of this node.
The index should be greater than zero but less than the number of descendants.
Parameters
index Index of the descendant.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Child().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> RectangleTree* mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::ExactClone ()
Make an exact copy of this node, pointers and everything.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> const RectangleTree* mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::FindByBeginCount (size_t begin, size_t count) const
Find a node in this tree by its begin and count (const).
Every node is uniquely identified by these two numbers. This is useful for communicating position over the network, when pointers would be invalid.
Parameters
begin The begin() of the node to find.
count The count() of the node to find.
Returns
The found node, or NULL if not found.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> RectangleTree* mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::FindByBeginCount (size_t begin, size_t count)
Find a node in this tree by its begin and count.
Every node is uniquely identified by these two numbers. This is useful for communicating position over the network, when pointers would be invalid.
Parameters
begin The begin() of the node to find.
count The count() of the node to find.
Returns
The found node, or NULL if not found.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> ElemType mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::FurthestDescendantDistance () const
Return the furthest possible descendant distance.
This returns the maximum distance from the centroid to the edge of the bound and not the empirical quantity which is the actual furthest descendant distance. So the actual furthest descendant distance may be less than what this method returns (but it will never be greater than this).
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::NumChildren().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> ElemType mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::FurthestPointDistance () const
Return the furthest distance to a point held in this node.
If this is not a leaf node, then the distance is 0 because the node holds no points.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::NumChildren().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> template<typename VecType > size_t mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::GetFurthestChild (const VecType & point, typename std::enable_if_t< IsVector< VecType >::value > * = 0)
Return the index of the furthest child node to the given query point.
If this is a leaf node, it will return NumChildren() (invalid index).
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::NumChildren().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::GetFurthestChild (const RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType > & queryNode)
Return the index of the furthest child node to the given query node.
If it can't decide, it will return NumChildren() (invalid index).
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> template<typename VecType > size_t mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::GetNearestChild (const VecType & point, typename std::enable_if_t< IsVector< VecType >::value > * = 0)
Return the index of the nearest child node to the given query point.
If this is a leaf node, it will return NumChildren() (invalid index).
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::NumChildren().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::GetNearestChild (const RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType > & queryNode)
Return the index of the nearest child node to the given query node.
If it can't decide, it will return NumChildren() (invalid index).
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> void mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::InsertNode (RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType > * node, const size_t level, std::vector< bool > & relevels)
Inserts a node into the tree, tracking which levels have been inserted into.
The node will be inserted so that the tree remains valid.
Parameters
node The node to be inserted.
level The depth that should match the node where this node is finally inserted. This should be the number returned by calling TreeDepth() from the node that originally contained `node`.
relevels The levels that have been reinserted to on this top level insertion.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> void mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::InsertPoint (const size_t point)
Inserts a point into the tree.
Parameters
point The index of a point in the dataset.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> void mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::InsertPoint (const size_t point, std::vector< bool > & relevels)
Inserts a point into the tree, tracking which levels have been inserted into.
Parameters
point The index of a point in the dataset.
relevels The levels that have been reinserted to on this top level insertion.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> bool mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::IsLeaf () const
Return whether or not this node is a leaf (true if it has no children).
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::AuxiliaryInfo().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> ElemType mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::MaxDistance (const RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType > & other) const [inline]
Return the maximum distance to another node.
Definition at line 477 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Bound(), and mlpack::bound::HRectBound< MetricType, ElemType >::MaxDistance().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> template<typename VecType > ElemType mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::MaxDistance (const VecType & point, typename std::enable_if_t< IsVector< VecType >::value > * = 0) const [inline]
Return the maximum distance to another point.
Definition at line 499 of file rectangle_tree.hpp.
References mlpack::bound::HRectBound< MetricType, ElemType >::MaxDistance().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::MaxLeafSize () const [inline]
Return the maximum leaf size.
Definition at line 319 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::maxLeafSize.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t& mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::MaxLeafSize () [inline]
Modify the maximum leaf size.
Definition at line 321 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::maxLeafSize.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::MaxNumChildren () const [inline]
Return the maximum number of children (in a non-leaf node).
Definition at line 329 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::maxNumChildren.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t& mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::MaxNumChildren () [inline]
Modify the maximum number of children (in a non-leaf node).
Definition at line 331 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::maxNumChildren.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> MetricType mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Metric () const [inline]
Get the metric which the tree uses.
Definition at line 349 of file rectangle_tree.hpp.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> ElemType mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::MinDistance (const RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType > & other) const [inline]
Return the minimum distance to another node.
Definition at line 471 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Bound(), and mlpack::bound::HRectBound< MetricType, ElemType >::MinDistance().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> template<typename VecType > ElemType mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::MinDistance (const VecType & point, typename std::enable_if_t< IsVector< VecType >::value > * = 0) const [inline]
Return the minimum distance to another point.
Definition at line 490 of file rectangle_tree.hpp.
References mlpack::bound::HRectBound< MetricType, ElemType >::MinDistance().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> ElemType mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::MinimumBoundDistance () const [inline]
Return the minimum distance from the center to any edge of the bound.
Currently, this returns 0, which doesn't break algorithms, but it isn't necessarily correct, either.
Definition at line 407 of file rectangle_tree.hpp.
References mlpack::bound::HRectBound< MetricType, ElemType >::MinWidth().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::MinLeafSize () const [inline]
Return the minimum leaf size.
Definition at line 324 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::minLeafSize.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t& mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::MinLeafSize () [inline]
Modify the minimum leaf size.
Definition at line 326 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::minLeafSize.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::MinNumChildren () const [inline]
Return the minimum number of children (in a non-leaf node).
Definition at line 334 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::minNumChildren.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t& mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::MinNumChildren () [inline]
Modify the minimum number of children (in a non-leaf node).
Definition at line 336 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::minNumChildren.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> void mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::NullifyData ()
Nullify the auxiliary information.
Used for memory management. Be cafeful.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::NumChildren () const [inline]
Return the number of child nodes. (One level beneath this one only.)
Definition at line 355 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::numChildren.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t& mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::NumChildren () [inline]
Modify the number of child nodes. Be careful.
Definition at line 357 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::FurthestDescendantDistance(), mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::FurthestPointDistance(), mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::GetFurthestChild(), mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::GetNearestChild(), and mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::numChildren.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::NumDescendants () const
Return the number of descendants of this node.
For a non-leaf in a binary space tree, this is the number of points at the descendant leaves. For a leaf, this is the number of points in the leaf.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Child().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::NumPoints () const
Return the number of points in this node (returns 0 if this node is not a leaf).
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Child().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> RectangleTree* mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Parent () const [inline]
Gets the parent of this node.
Definition at line 339 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::parent.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> RectangleTree*& mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Parent () [inline]
Modify the parent of this node.
Definition at line 341 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::parent.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> ElemType mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::ParentDistance () const [inline]
Return the distance from the center of this node to the center of the parent node.
Definition at line 411 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::parentDistance.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> ElemType& mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::ParentDistance () [inline]
Modify the distance from the center of this node to the center of the parent node.
Definition at line 414 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::parentDistance.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Point (const size_t index) const [inline]
Return the index (with reference to the dataset) of a particular point in this node.
This will happily return invalid indices if the given index is greater than the number of points in this node (obtained with NumPoints()) -- be careful.
Parameters
index Index of point for which a dataset index is wanted.
Definition at line 464 of file rectangle_tree.hpp.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t& mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Point (const size_t index) [inline]
Modify the index of a particular point in this node.
Be very careful when you do this! You may make the tree invalid.
Definition at line 468 of file rectangle_tree.hpp.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> math::RangeType<ElemType> mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::RangeDistance (const RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType > & other) const [inline]
Return the minimum and maximum distance to another node.
Definition at line 483 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Bound(), and mlpack::bound::HRectBound< MetricType, ElemType >::RangeDistance().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> template<typename VecType > math::RangeType<ElemType> mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::RangeDistance (const VecType & point, typename std::enable_if_t< IsVector< VecType >::value > * = 0) const [inline]
Return the minimum and maximum distance to another point.
Definition at line 508 of file rectangle_tree.hpp.
References mlpack::bound::HRectBound< MetricType, ElemType >::RangeDistance(), mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::TreeDepth(), and mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::TreeSize().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> bool mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::RemoveNode (const RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType > * node, std::vector< bool > & relevels)
Removes a node from the tree.
You are responsible for deleting it if you wish to do so.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> template<typename Archive > void mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Serialize (Archive & ar, const unsigned int)
Serialize the tree.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> bool mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::ShrinkBoundForBound (const bound::HRectBound< MetricType > & changedBound)
Shrink the bound object of this node for the removal of a child node.
Parameters
bound The HRectBound<>& of the bound that was removed to reqire this shrinking.
Returns
true if the bound needed to be changed, false if it did not.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> bool mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::ShrinkBoundForPoint (const arma::vec & point)
Shrink the bound object of this node for the removal of a point.
Parameters
point The arma::vec& of the point that was removed to require this shrinking.
Returns
true if the bound needed to be changed, false if it did not.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> void mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::SoftDelete ()
Delete this node of the tree, but leave the stuff contained in it intact.
This is used when splitting a node, where the data in this tree is moved to two other trees.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> void mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::SplitNode (std::vector< bool > & relevels) [private]
Splits the current node, recursing up the tree.
Parameters
relevels Vector to track which levels have been inserted to.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Count().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> const StatisticType& mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Stat () const [inline]
Return the statistic object for this node.
Definition at line 304 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::stat.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> StatisticType& mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Stat () [inline]
Modify the statistic object for this node.
Definition at line 306 of file rectangle_tree.hpp.
References mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::stat.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::TreeDepth () const
Obtains the number of levels below this node in the tree, starting with this.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::RangeDistance().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::TreeSize () const
Obtains the number of nodes in the tree, starting with this.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::RangeDistance().
Member Data Documentation
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> AuxiliaryInformationType<RectangleTree> mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::auxiliaryInfo [private]
A tree-specific information.
Definition at line 105 of file rectangle_tree.hpp.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::AuxiliaryInfo().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> friend mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::AuxiliaryInformation [protected]
Give friend access for AuxiliaryInformationType.
Definition at line 563 of file rectangle_tree.hpp.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::begin [private]
The index of the first point in the dataset contained in this node (and its children).
THIS IS ALWAYS 0 AT THE MOMENT. IT EXISTS MERELY IN CASE I THINK OF A WAY TO CHANGE THAT. IN OTHER WORDS, IT WILL PROBABLY BE REMOVED.
Definition at line 81 of file rectangle_tree.hpp.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Begin().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> bound::HRectBound<metric::EuclideanDistance, ElemType> mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::bound [private]
The bound object for this node.
Definition at line 92 of file rectangle_tree.hpp.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Bound().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> std::vector<RectangleTree*> mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::children [private]
The child nodes (Starting at 0 and ending at (numChildren-1)).
Definition at line 74 of file rectangle_tree.hpp.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::count [private]
The number of points in the dataset contained in this node (and its children).
Definition at line 84 of file rectangle_tree.hpp.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Count().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> const MatType* mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::dataset [private]
The dataset.
Definition at line 98 of file rectangle_tree.hpp.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Dataset().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> friend mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::DescentType [protected]
Give friend access for DescentType.
Definition at line 557 of file rectangle_tree.hpp.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::maxLeafSize [private]
The max leaf size.
Definition at line 88 of file rectangle_tree.hpp.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::MaxLeafSize().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::maxNumChildren [private]
The max number of child nodes a non-leaf node can have.
Definition at line 68 of file rectangle_tree.hpp.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::MaxNumChildren().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::minLeafSize [private]
The minimum leaf size.
Definition at line 90 of file rectangle_tree.hpp.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::MinLeafSize().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::minNumChildren [private]
The minimum number of child nodes a non-leaf node can have.
Definition at line 70 of file rectangle_tree.hpp.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::MinNumChildren().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::numChildren [private]
The number of child nodes actually in use (0 if this is a leaf node).
Definition at line 72 of file rectangle_tree.hpp.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::NumChildren().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> size_t mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::numDescendants [private]
The number of descendants of this node.
Definition at line 86 of file rectangle_tree.hpp.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> bool mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::ownsDataset [private]
Whether or not we are responsible for deleting the dataset.
This is probably not aligned well...
Definition at line 101 of file rectangle_tree.hpp.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> RectangleTree* mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::parent [private]
The parent node (NULL if this is the root of the tree).
Definition at line 76 of file rectangle_tree.hpp.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Parent().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> ElemType mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::parentDistance [private]
The distance from the centroid of this node to the centroid of the parent.
Definition at line 96 of file rectangle_tree.hpp.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::ParentDistance().
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> std::vector<size_t> mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::points [private]
The mapping to the dataset.
Definition at line 103 of file rectangle_tree.hpp.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> friend mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::SplitType [protected]
Give friend access for SplitType.
Definition at line 560 of file rectangle_tree.hpp.
template<typename MetricType = metric::EuclideanDistance, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, typename SplitType = RTreeSplit, typename DescentType = RTreeDescentHeuristic, template< typename > class AuxiliaryInformationType = NoAuxiliaryInformation> StatisticType mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::stat [private]
Any extra data contained in the node.
Definition at line 94 of file rectangle_tree.hpp.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Stat().
The documentation for this class was generated from the following file:
src/mlpack/core/tree/rectangle_tree/rectangle_tree.hpp