mlpack::ann::SVDConvolution< BorderMode > Class Template Reference
Computes the two-dimensional convolution using singular value decomposition.
Static Public Member Functions
template<typename eT >
static void Convolution (const arma::Mat< eT > &input, const arma::Mat< eT > &filter, arma::Mat< eT > &output)
template<typename eT >
static void Convolution (const arma::Cube< eT > &input, const arma::Cube< eT > &filter, arma::Cube< eT > &output)
template<typename eT >
static void Convolution (const arma::Mat< eT > &input, const arma::Cube< eT > &filter, arma::Cube< eT > &output)
template<typename eT >
static void Convolution (const arma::Cube< eT > &input, const arma::Mat< eT > &filter, arma::Cube< eT > &output)
Detailed Description
template<typename BorderMode = FullConvolution>
*
class mlpack::ann::SVDConvolution< BorderMode >
Computes the two-dimensional convolution using singular value decomposition.
This class allows specification of the type of the border type. The convolution can be compute with the valid border type of the full border type (default).
FullConvolution: returns the full two-dimensional convolution. ValidConvolution: returns only those parts of the convolution that are computed without the zero-padded edges.
Template Parameters
BorderMode Type of the border mode (FullConvolution or ValidConvolution).
Definition at line 38 of file svd_convolution.hpp.
Member Function Documentation
template<typename BorderMode = FullConvolution> template<typename eT > static void mlpack::ann::SVDConvolution< BorderMode >::Convolution (const arma::Mat< eT > & input, const arma::Mat< eT > & filter, arma::Mat< eT > & output) [inline], [static]
Definition at line 56 of file svd_convolution.hpp.
References mlpack::ann::NaiveConvolution< BorderMode >::Convolution(), and mlpack::ann::FFTConvolution< BorderMode, padLastDim >::Convolution().
Referenced by mlpack::ann::SVDConvolution< BorderMode >::Convolution().
template<typename BorderMode = FullConvolution> template<typename eT > static void mlpack::ann::SVDConvolution< BorderMode >::Convolution (const arma::Cube< eT > & input, const arma::Cube< eT > & filter, arma::Cube< eT > & output) [inline], [static]
Definition at line 122 of file svd_convolution.hpp.
References mlpack::ann::SVDConvolution< BorderMode >::Convolution().
template<typename BorderMode = FullConvolution> template<typename eT > static void mlpack::ann::SVDConvolution< BorderMode >::Convolution (const arma::Mat< eT > & input, const arma::Cube< eT > & filter, arma::Cube< eT > & output) [inline], [static]
Definition at line 153 of file svd_convolution.hpp.
References mlpack::ann::SVDConvolution< BorderMode >::Convolution().
template<typename BorderMode = FullConvolution> template<typename eT > static void mlpack::ann::SVDConvolution< BorderMode >::Convolution (const arma::Cube< eT > & input, const arma::Mat< eT > & filter, arma::Cube< eT > & output) [inline], [static]
Definition at line 183 of file svd_convolution.hpp.
References mlpack::ann::SVDConvolution< BorderMode >::Convolution().
The documentation for this class was generated from the following file:
src/mlpack/methods/ann/convolution_rules/svd_convolution.hpp