mlpack::regression::LogisticRegression< MatType > Class Template Reference
The LogisticRegression class implements an L2-regularized logistic regression model, and supports training with multiple optimizers and classification.
Public Member Functions
LogisticRegression (const MatType &predictors, const arma::Row< size_t > &responses, const double lambda=0)
Construct the LogisticRegression class with the given labeled training data.
LogisticRegression (const MatType &predictors, const arma::Row< size_t > &responses, const arma::vec &initialPoint, const double lambda=0)
Construct the LogisticRegression class with the given labeled training data.
LogisticRegression (const size_t dimensionality=0, const double lambda=0)
Construct the LogisticRegression class without performing any training.
template<template< typename, typename... > class OptimizerType, typename... OptimizerTypeArgs>
LogisticRegression (OptimizerType< LogisticRegressionFunction< MatType >, OptimizerTypeArgs... > &optimizer)
Construct the LogisticRegression class with the given labeled training data.
template<typename VecType >
size_t Classify (const VecType &point, const double decisionBoundary=0.5) const
Classify the given point.
void Classify (const MatType &dataset, arma::Row< size_t > &labels, const double decisionBoundary=0.5) const
Classify the given points, returning the predicted labels for each point.
void Classify (const MatType &dataset, arma::mat &probabilities) const
Classify the given points, returning class probabilities for each point.
double ComputeAccuracy (const MatType &predictors, const arma::Row< size_t > &responses, const double decisionBoundary=0.5) const
Compute the accuracy of the model on the given predictors and responses, optionally using the given decision boundary.
double ComputeError (const MatType &predictors, const arma::Row< size_t > &responses) const
Compute the error of the model.
const double & Lambda () const
Return the lambda value for L2-regularization.
double & Lambda ()
Modify the lambda value for L2-regularization.
const arma::vec & Parameters () const
Return the parameters (the b vector).
arma::vec & Parameters ()
Modify the parameters (the b vector).
mlpack_deprecated void Predict (const MatType &predictors, arma::Row< size_t > &responses, const double decisionBoundary=0.5) const
Predict the responses to a given set of predictors.
template<typename Archive >
void Serialize (Archive &ar, const unsigned int)
Serialize the model.
template<template< typename > class OptimizerType = mlpack::optimization::L_BFGS>
void Train (const MatType &predictors, const arma::Row< size_t > &responses)
Train the LogisticRegression model on the given input data.
template<template< typename, typename... > class OptimizerType = mlpack::optimization::L_BFGS, typename... OptimizerTypeArgs>
void Train (OptimizerType< LogisticRegressionFunction< MatType >, OptimizerTypeArgs... > &optimizer)
Train the LogisticRegression model with the given instantiated optimizer.
Private Attributes
double lambda
L2-regularization penalty parameter.
arma::vec parameters
Vector of trained parameters (size: dimensionality plus one).
Detailed Description
template<typename MatType = arma::mat>
*
class mlpack::regression::LogisticRegression< MatType >
The LogisticRegression class implements an L2-regularized logistic regression model, and supports training with multiple optimizers and classification.
The class supports different observation types via the MatType template parameter; for instance, logistic regression can be performed on sparse datasets by specifying arma::sp_mat as the MatType parameter.
Template Parameters
MatType Type of data matrix.
Definition at line 35 of file logistic_regression.hpp.
Constructor & Destructor Documentation
template<typename MatType = arma::mat> mlpack::regression::LogisticRegression< MatType >::LogisticRegression (const MatType & predictors, const arma::Row< size_t > & responses, const double lambda = 0)
Construct the LogisticRegression class with the given labeled training data.
This will train the model. Optionally, specify lambda, which is the penalty parameter for L2-regularization. If not specified, it is set to 0, which results in standard (unregularized) logistic regression.
It is not possible to set a custom optimizer with this constructor. Either use a constructor that does not train and call Train() with a custom optimizer type, or use the constructor that takes an instantiated optimizer. (This unfortunate situation is a language restriction of C++.)
Parameters
predictors Input training variables.
responses Outputs resulting from input training variables.
lambda L2-regularization parameter.
template<typename MatType = arma::mat> mlpack::regression::LogisticRegression< MatType >::LogisticRegression (const MatType & predictors, const arma::Row< size_t > & responses, const arma::vec & initialPoint, const double lambda = 0)
Construct the LogisticRegression class with the given labeled training data.
This will train the model. Optionally, specify lambda, which is the penalty parameter for L2-regularization. If not specified, it is set to 0, which results in standard (unregularized) logistic regression.
It is not possible to set a custom optimizer with this constructor. Either use a constructor that does not train and call Train() with a custom optimizer type, or use the constructor that takes an instantiated optimizer. (This unfortunate situation is a language restriction of C++.)
Parameters
predictors Input training variables.
responses Outputs results from input training variables.
initialPoint Initial model to train with.
lambda L2-regularization parameter.
template<typename MatType = arma::mat> mlpack::regression::LogisticRegression< MatType >::LogisticRegression (const size_t dimensionality = 0, const double lambda = 0)
Construct the LogisticRegression class without performing any training.
The dimensionality of the data (which will be used to set the size of the parameters vector) must be specified, and all of the parameters in the model will be set to 0. Note that the dimensionality may be changed later by directly modifying the parameters vector (using Parameters()).
Parameters
dimensionality Dimensionality of the data.
lambda L2-regularization parameter.
template<typename MatType = arma::mat> template<template< typename, typename... > class OptimizerType, typename... OptimizerTypeArgs> mlpack::regression::LogisticRegression< MatType >::LogisticRegression (OptimizerType< LogisticRegressionFunction< MatType >, OptimizerTypeArgs... > & optimizer)
Construct the LogisticRegression class with the given labeled training data.
This will train the model. This overload takes an already instantiated optimizer (which holds the LogisticRegressionFunction error function, which must also be instantiated), so that the optimizer can be configured before the training is run by this constructor. The update policy of the optimizer can be set through the policy argument. The predictors and responses and initial point are all taken from the error function contained in the optimizer.
Parameters
optimizer Instantiated optimizer with instantiated error function.
Member Function Documentation
template<typename MatType = arma::mat> template<typename VecType > size_t mlpack::regression::LogisticRegression< MatType >::Classify (const VecType & point, const double decisionBoundary = 0.5) const
Classify the given point.
The predicted label is returned. Optionally, specify the decision boundary; logistic regression returns a value between 0 and 1. If the value is greater than the decision boundary, the response is taken to be 1; otherwise, it is 0. By default the decision boundary is 0.5.
Parameters
point Point to classify.
decisionBoundary Decision boundary (default 0.5).
Returns
Predicted label of point.
Referenced by mlpack::regression::LogisticRegression< MatType >::Lambda().
template<typename MatType = arma::mat> void mlpack::regression::LogisticRegression< MatType >::Classify (const MatType & dataset, arma::Row< size_t > & labels, const double decisionBoundary = 0.5) const
Classify the given points, returning the predicted labels for each point.
Optionally, specify the decision boundary; logistic regression returns a value between 0 and 1. If the value is greater than the decision boundary, the response is taken to be 1; otherwise, it is 0. By default the decision boundary is 0.5.
Parameters
dataset Set of points to classify.
labels Predicted labels for each point.
decisionBoundary Decision boundary (default 0.5).
template<typename MatType = arma::mat> void mlpack::regression::LogisticRegression< MatType >::Classify (const MatType & dataset, arma::mat & probabilities) const
Classify the given points, returning class probabilities for each point.
Parameters
dataset Set of points to classify.
probabilities Class probabilities for each point (output).
template<typename MatType = arma::mat> double mlpack::regression::LogisticRegression< MatType >::ComputeAccuracy (const MatType & predictors, const arma::Row< size_t > & responses, const double decisionBoundary = 0.5) const
Compute the accuracy of the model on the given predictors and responses, optionally using the given decision boundary.
The responses should be either 0 or 1. Logistic regression returns a value between 0 and 1. If the value is greater than the decision boundary, the response is taken to be 1; otherwise, it is 0. By default, the decision boundary is 0.5.
The accuracy is returned as a percentage, between 0 and 100.
Parameters
predictors Input predictors.
responses Vector of responses.
decisionBoundary Decision boundary (default 0.5).
Returns
Percentage of responses that are predicted correctly.
Referenced by mlpack::regression::LogisticRegression< MatType >::Lambda().
template<typename MatType = arma::mat> double mlpack::regression::LogisticRegression< MatType >::ComputeError (const MatType & predictors, const arma::Row< size_t > & responses) const
Compute the error of the model.
This returns the negative objective function of the logistic regression log-likelihood function. For the model to be optimal, the negative log-likelihood function should be minimized.
Parameters
predictors Input predictors.
responses Vector of responses.
Referenced by mlpack::regression::LogisticRegression< MatType >::Lambda().
template<typename MatType = arma::mat> const double& mlpack::regression::LogisticRegression< MatType >::Lambda () const [inline]
Return the lambda value for L2-regularization.
Definition at line 157 of file logistic_regression.hpp.
References mlpack::regression::LogisticRegression< MatType >::lambda.
template<typename MatType = arma::mat> double& mlpack::regression::LogisticRegression< MatType >::Lambda () [inline]
Modify the lambda value for L2-regularization.
Definition at line 159 of file logistic_regression.hpp.
References mlpack::regression::LogisticRegression< MatType >::Classify(), mlpack::regression::LogisticRegression< MatType >::ComputeAccuracy(), mlpack::regression::LogisticRegression< MatType >::ComputeError(), mlpack::regression::LogisticRegression< MatType >::lambda, mlpack_deprecated, mlpack::regression::LogisticRegression< MatType >::Predict(), and mlpack::regression::LogisticRegression< MatType >::Serialize().
template<typename MatType = arma::mat> const arma::vec& mlpack::regression::LogisticRegression< MatType >::Parameters () const [inline]
Return the parameters (the b vector).
Definition at line 152 of file logistic_regression.hpp.
References mlpack::regression::LogisticRegression< MatType >::parameters.
template<typename MatType = arma::mat> arma::vec& mlpack::regression::LogisticRegression< MatType >::Parameters () [inline]
Modify the parameters (the b vector).
Definition at line 154 of file logistic_regression.hpp.
References mlpack::regression::LogisticRegression< MatType >::parameters.
template<typename MatType = arma::mat> mlpack_deprecated void mlpack::regression::LogisticRegression< MatType >::Predict (const MatType & predictors, arma::Row< size_t > & responses, const double decisionBoundary = 0.5) const
Predict the responses to a given set of predictors.
The responses will be either 0 or 1. Optionally, specify the decision boundary; logistic regression returns a value between 0 and 1. If the value is greater than the decision boundary, the response is taken to be 1; otherwise, it is 0. By default the decision boundary is 0.5.
This method is deprecated---you should use Classify() instead.
Parameters
predictors Input predictors.
responses Vector to put output predictions of responses into.
decisionBoundary Decision boundary (default 0.5).
Referenced by mlpack::regression::LogisticRegression< MatType >::Lambda().
template<typename MatType = arma::mat> template<typename Archive > void mlpack::regression::LogisticRegression< MatType >::Serialize (Archive & ar, const unsigned int)
Serialize the model.
Referenced by mlpack::regression::LogisticRegression< MatType >::Lambda().
template<typename MatType = arma::mat> template<template< typename > class OptimizerType = mlpack::optimization::L_BFGS> void mlpack::regression::LogisticRegression< MatType >::Train (const MatType & predictors, const arma::Row< size_t > & responses)
Train the LogisticRegression model on the given input data.
By default, the L-BFGS optimization algorithm is used, but others can be specified (such as mlpack::optimization::SGD).
This will use the existing model parameters as a starting point for the optimization. If this is not what you want, then you should access the parameters vector directly with Parameters() and modify it as desired.
Template Parameters
OptimizerType Type of optimizer to use to train the model.
Parameters
predictors Input training variables.
responses Outputs results from input training variables.
template<typename MatType = arma::mat> template<template< typename, typename... > class OptimizerType = mlpack::optimization::L_BFGS, typename... OptimizerTypeArgs> void mlpack::regression::LogisticRegression< MatType >::Train (OptimizerType< LogisticRegressionFunction< MatType >, OptimizerTypeArgs... > & optimizer)
Train the LogisticRegression model with the given instantiated optimizer.
Using this overload allows configuring the instantiated optimizer before training is performed.
Note that the initial point of the optimizer (optimizer.Function().GetInitialPoint()) will be used as the initial point of the optimization, overwriting any existing trained model. If you don't want to overwrite the existing model, set optimizer.Function().GetInitialPoint() to the current parameters vector, accessible via Parameters().
Parameters
optimizer Instantiated optimizer with instantiated error function.
Template Parameters
OptimizerTypeArgs Optimizer arguments to customize the behavior of the optimizer.
Member Data Documentation
template<typename MatType = arma::mat> double mlpack::regression::LogisticRegression< MatType >::lambda [private]
L2-regularization penalty parameter.
Definition at line 254 of file logistic_regression.hpp.
Referenced by mlpack::regression::LogisticRegression< MatType >::Lambda().
template<typename MatType = arma::mat> arma::vec mlpack::regression::LogisticRegression< MatType >::parameters [private]
Vector of trained parameters (size: dimensionality plus one).
Definition at line 252 of file logistic_regression.hpp.
Referenced by mlpack::regression::LogisticRegression< MatType >::Parameters().
The documentation for this class was generated from the following file:
src/mlpack/methods/logistic_regression/logistic_regression.hpp