mlpack::ann::LeakyReLU< InputDataType, OutputDataType > Class Template Reference
The LeakyReLU activation function, defined by.
Public Member Functions
LeakyReLU (const double alpha=0.03)
Create the LeakyReLU object using the specified parameters.
double const & Alpha () const
Get the non zero gradient.
double & Alpha ()
Modify the non zero gradient.
template<typename DataType >
void Backward (const DataType &&input, DataType &&gy, DataType &&g)
Ordinary feed backward pass of a neural network, calculating the function f(x) by propagating x backwards through f.
OutputDataType const & Delta () const
Get the delta.
OutputDataType & Delta ()
Modify the delta.
template<typename InputType , typename OutputType >
void Forward (const InputType &&input, OutputType &&output)
Ordinary feed forward pass of a neural network, evaluating the function f(x) by propagating the activity forward through f.
InputDataType const & InputParameter () const
Get the input parameter.
InputDataType & InputParameter ()
Modify the input parameter.
OutputDataType const & OutputParameter () const
Get the output parameter.
OutputDataType & OutputParameter ()
Modify the output parameter.
template<typename Archive >
void Serialize (Archive &ar, const unsigned int)
Serialize the layer.
Private Member Functions
double Deriv (const double x)
Computes the first derivative of the LeakyReLU function.
template<typename InputType , typename OutputType >
void Deriv (const InputType &x, OutputType &y)
Computes the first derivative of the LeakyReLU function.
double Fn (const double x)
Computes the LeakReLU function.
template<typename eT >
void Fn (const arma::Mat< eT > &x, arma::Mat< eT > &y)
Computes the Leaky ReLU function using a dense matrix as input.
Private Attributes
double alpha
Leakyness Parameter in the range 0 <alpha< 1.
OutputDataType delta
Locally-stored delta object.
InputDataType inputParameter
Locally-stored input parameter object.
OutputDataType outputParameter
Locally-stored output parameter object.
Detailed Description
template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat>
*
class mlpack::ann::LeakyReLU< InputDataType, OutputDataType >
The LeakyReLU activation function, defined by.
 f(x) &=& \max(x, alpha*x) \\ f'(x) &=& \left\{ \begin{array}{lr} 1 & : x > 0 \\ alpha & : x \le 0 \end{array} \right. 
Template Parameters
InputDataType Type of the input data (arma::colvec, arma::mat, arma::sp_mat or arma::cube).
OutputDataType Type of the output data (arma::colvec, arma::mat, arma::sp_mat or arma::cube).
Definition at line 44 of file leaky_relu.hpp.
Constructor & Destructor Documentation
template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat> mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::LeakyReLU (const double alpha = 0.03)
Create the LeakyReLU object using the specified parameters.
The non zero gradient can be adjusted by specifying tha parameter alpha in the range 0 to 1. Default (alpha = 0.03)
Parameters
alpha Non zero gradient
Member Function Documentation
template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat> double const& mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::Alpha () const [inline]
Get the non zero gradient.
Definition at line 94 of file leaky_relu.hpp.
References mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::alpha.
template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat> double& mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::Alpha () [inline]
Modify the non zero gradient.
Definition at line 96 of file leaky_relu.hpp.
References mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::alpha, and mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::Serialize().
template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat> template<typename DataType > void mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::Backward (const DataType && input, DataType && gy, DataType && g)
Ordinary feed backward pass of a neural network, calculating the function f(x) by propagating x backwards through f.
Using the results from the feed forward pass.
Parameters
input The propagated input activation.
gy The backpropagated error.
g The calculated gradient.
template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat> OutputDataType const& mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::Delta () const [inline]
Get the delta.
Definition at line 89 of file leaky_relu.hpp.
References mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::delta.
template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat> OutputDataType& mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::Delta () [inline]
Modify the delta.
Definition at line 91 of file leaky_relu.hpp.
References mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::delta.
template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat> double mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::Deriv (const double x) [inline], [private]
Computes the first derivative of the LeakyReLU function.
Parameters
x Input data.
Returns
f'(x)
Definition at line 134 of file leaky_relu.hpp.
References mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::alpha.
Referenced by mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::Deriv().
template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat> template<typename InputType , typename OutputType > void mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::Deriv (const InputType & x, OutputType & y) [inline], [private]
Computes the first derivative of the LeakyReLU function.
Parameters
y Input activations.
x The resulting derivatives.
Definition at line 147 of file leaky_relu.hpp.
References mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::Deriv().
template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat> double mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::Fn (const double x) [inline], [private]
Computes the LeakReLU function.
Parameters
x Input data.
Returns
f(x).
Definition at line 111 of file leaky_relu.hpp.
References mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::alpha.
template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat> template<typename eT > void mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::Fn (const arma::Mat< eT > & x, arma::Mat< eT > & y) [inline], [private]
Computes the Leaky ReLU function using a dense matrix as input.
Parameters
x Input data.
y The resulting output activation.
Definition at line 123 of file leaky_relu.hpp.
References mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::alpha.
template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat> template<typename InputType , typename OutputType > void mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::Forward (const InputType && input, OutputType && output)
Ordinary feed forward pass of a neural network, evaluating the function f(x) by propagating the activity forward through f.
Parameters
input Input data used for evaluating the specified function.
output Resulting output activation.
template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat> InputDataType const& mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::InputParameter () const [inline]
Get the input parameter.
Definition at line 79 of file leaky_relu.hpp.
References mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::inputParameter.
template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat> InputDataType& mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::InputParameter () [inline]
Modify the input parameter.
Definition at line 81 of file leaky_relu.hpp.
References mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::inputParameter.
template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat> OutputDataType const& mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::OutputParameter () const [inline]
Get the output parameter.
Definition at line 84 of file leaky_relu.hpp.
References mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::outputParameter.
template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat> OutputDataType& mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::OutputParameter () [inline]
Modify the output parameter.
Definition at line 86 of file leaky_relu.hpp.
References mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::outputParameter.
template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat> template<typename Archive > void mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::Serialize (Archive & ar, const unsigned int)
Serialize the layer.
Referenced by mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::Alpha().
Member Data Documentation
template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat> double mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::alpha [private]
Leakyness Parameter in the range 0 <alpha< 1.
Definition at line 167 of file leaky_relu.hpp.
Referenced by mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::Alpha(), mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::Deriv(), and mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::Fn().
template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat> OutputDataType mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::delta [private]
Locally-stored delta object.
Definition at line 158 of file leaky_relu.hpp.
Referenced by mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::Delta().
template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat> InputDataType mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::inputParameter [private]
Locally-stored input parameter object.
Definition at line 161 of file leaky_relu.hpp.
Referenced by mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::InputParameter().
template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat> OutputDataType mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::outputParameter [private]
Locally-stored output parameter object.
Definition at line 164 of file leaky_relu.hpp.
Referenced by mlpack::ann::LeakyReLU< InputDataType, OutputDataType >::OutputParameter().
The documentation for this class was generated from the following file:
src/mlpack/methods/ann/layer/leaky_relu.hpp