mlpack::util::PrefixedOutStream Class Reference
Allows us to output to an ostream with a prefix at the beginning of each line, in the same way we would output to cout or cerr.
Public Member Functions
PrefixedOutStream (std::ostream &destination, const char *prefix, bool ignoreInput=false, bool fatal=false)
Set up the PrefixedOutStream.
PrefixedOutStream & operator<< (bool val)
Write a bool to the stream.
PrefixedOutStream & operator<< (short val)
Write a short to the stream.
PrefixedOutStream & operator<< (unsigned short val)
Write an unsigned short to the stream.
PrefixedOutStream & operator<< (int val)
Write an int to the stream.
PrefixedOutStream & operator<< (unsigned int val)
Write an unsigned int to the stream.
PrefixedOutStream & operator<< (long val)
Write a long to the stream.
PrefixedOutStream & operator<< (unsigned long val)
Write an unsigned long to the stream.
PrefixedOutStream & operator<< (float val)
Write a float to the stream.
PrefixedOutStream & operator<< (double val)
Write a double to the stream.
PrefixedOutStream & operator<< (long double val)
Write a long double to the stream.
PrefixedOutStream & operator<< (void *val)
Write a void pointer to the stream.
PrefixedOutStream & operator<< (const char *str)
Write a character array to the stream.
PrefixedOutStream & operator<< (std::string &str)
Write a string to the stream.
PrefixedOutStream & operator<< (std::streambuf *sb)
Write a streambuf to the stream.
PrefixedOutStream & operator<< (std::ostream &(*pf)(std::ostream &))
Write an ostream manipulator function to the stream.
PrefixedOutStream & operator<< (std::ios &(*pf)(std::ios &))
Write an ios manipulator function to the stream.
PrefixedOutStream & operator<< (std::ios_base &(*pf)(std::ios_base &))
Write an ios_base manipulator function to the stream.
template<typename T >
PrefixedOutStream & operator<< (const T &s)
Write anything else to the stream.
Public Attributes
std::ostream & destination
The output stream that all data is to be sent to; example: std::cout.
bool ignoreInput
Discards input, prints nothing if true.
Private Member Functions
template<typename T >
std::enable_if<!arma::is_arma_type< T >::value >::type BaseLogic (const T &val)
Conducts the base logic required in all the operator << overloads.
template<typename T >
std::enable_if< arma::is_arma_type< T >::value >::type BaseLogic (const T &val)
Conducts the base logic required in all the operator << overloads.
void PrefixIfNeeded ()
Output the prefix, but only if we need to and if we are allowed to.
Private Attributes
bool carriageReturned
If true, the previous call to operator<< encountered a CR, and a prefix will be necessary.
bool fatal
If true, a std::runtime_error exception will be thrown when a CR is encountered.
std::string prefix
Contains the prefix we must prepend to each line.
Detailed Description
Allows us to output to an ostream with a prefix at the beginning of each line, in the same way we would output to cout or cerr.
The prefix is specified in the constructor (as well as the destination ostream). A newline must be passed to the stream, and then the prefix will be prepended to the next line. For example,
PrefixedOutStream outstr(std::cout, "[TEST] ");
outstr << "Hello world I like " << 7.5;
outstr << "...Continue" << std::endl;
outstr << "After the CR\n" << std::endl;
would give, on std::cout,
[TEST] Hello world I like 7.5...Continue
[TEST] After the CR
[TEST]
These objects are used for the mlpack::Log levels (DEBUG, INFO, WARN, and FATAL).
Definition at line 46 of file prefixedoutstream.hpp.
Constructor & Destructor Documentation
mlpack::util::PrefixedOutStream::PrefixedOutStream (std::ostream & destination, const char * prefix, bool ignoreInput = false, bool fatal = false) [inline]
Set up the PrefixedOutStream.
Parameters
destination ostream which receives output from this object.
prefix The prefix to prepend to each line.
ignoreInput If true, the stream will not be printed.
fatal If true, a std::runtime_error exception is thrown after printing a newline.
Definition at line 58 of file prefixedoutstream.hpp.
References operator<<(), and string().
Member Function Documentation
template<typename T > std::enable_if<!arma::is_arma_type<T>::value>::type mlpack::util::PrefixedOutStream::BaseLogic (const T & val) [private]
Conducts the base logic required in all the operator << overloads.
Mostly just a good idea to reduce copy-pasta.
This overload is for non-Armadillo objects, which need special handling during printing.
Template Parameters
T The type of the data to output.
Parameters
val The The data to be output.
template<typename T > std::enable_if<arma::is_arma_type<T>::value>::type mlpack::util::PrefixedOutStream::BaseLogic (const T & val) [private]
Conducts the base logic required in all the operator << overloads.
Mostly just a good idea to reduce copy-pasta.
This overload is for Armadillo objects, which need special handling during printing.
Template Parameters
T The type of the data to output.
Parameters
val The The data to be output.
PrefixedOutStream& mlpack::util::PrefixedOutStream::operator<< (bool val)
Write a bool to the stream.
Referenced by PrefixedOutStream().
PrefixedOutStream& mlpack::util::PrefixedOutStream::operator<< (short val)
Write a short to the stream.
PrefixedOutStream& mlpack::util::PrefixedOutStream::operator<< (unsigned short val)
Write an unsigned short to the stream.
PrefixedOutStream& mlpack::util::PrefixedOutStream::operator<< (int val)
Write an int to the stream.
PrefixedOutStream& mlpack::util::PrefixedOutStream::operator<< (unsigned int val)
Write an unsigned int to the stream.
PrefixedOutStream& mlpack::util::PrefixedOutStream::operator<< (long val)
Write a long to the stream.
PrefixedOutStream& mlpack::util::PrefixedOutStream::operator<< (unsigned long val)
Write an unsigned long to the stream.
PrefixedOutStream& mlpack::util::PrefixedOutStream::operator<< (float val)
Write a float to the stream.
PrefixedOutStream& mlpack::util::PrefixedOutStream::operator<< (double val)
Write a double to the stream.
PrefixedOutStream& mlpack::util::PrefixedOutStream::operator<< (long double val)
Write a long double to the stream.
PrefixedOutStream& mlpack::util::PrefixedOutStream::operator<< (void * val)
Write a void pointer to the stream.
PrefixedOutStream& mlpack::util::PrefixedOutStream::operator<< (const char * str)
Write a character array to the stream.
PrefixedOutStream& mlpack::util::PrefixedOutStream::operator<< (std::string & str)
Write a string to the stream.
PrefixedOutStream& mlpack::util::PrefixedOutStream::operator<< (std::streambuf * sb)
Write a streambuf to the stream.
PrefixedOutStream& mlpack::util::PrefixedOutStream::operator<< (std::ostream &(*)(std::ostream &) pf)
Write an ostream manipulator function to the stream.
PrefixedOutStream& mlpack::util::PrefixedOutStream::operator<< (std::ios &(*)(std::ios &) pf)
Write an ios manipulator function to the stream.
PrefixedOutStream& mlpack::util::PrefixedOutStream::operator<< (std::ios_base &(*)(std::ios_base &) pf)
Write an ios_base manipulator function to the stream.
template<typename T > PrefixedOutStream& mlpack::util::PrefixedOutStream::operator<< (const T & s)
Write anything else to the stream.
void mlpack::util::PrefixedOutStream::PrefixIfNeeded () [inline], [private]
Output the prefix, but only if we need to and if we are allowed to.
Member Data Documentation
bool mlpack::util::PrefixedOutStream::carriageReturned [private]
If true, the previous call to operator<< encountered a CR, and a prefix will be necessary.
Definition at line 155 of file prefixedoutstream.hpp.
std::ostream& mlpack::util::PrefixedOutStream::destination
The output stream that all data is to be sent to; example: std::cout.
Definition at line 111 of file prefixedoutstream.hpp.
bool mlpack::util::PrefixedOutStream::fatal [private]
If true, a std::runtime_error exception will be thrown when a CR is encountered.
Definition at line 159 of file prefixedoutstream.hpp.
bool mlpack::util::PrefixedOutStream::ignoreInput
Discards input, prints nothing if true.
Definition at line 114 of file prefixedoutstream.hpp.
std::string mlpack::util::PrefixedOutStream::prefix [private]
Contains the prefix we must prepend to each line.
Definition at line 151 of file prefixedoutstream.hpp.
The documentation for this class was generated from the following file:
src/mlpack/core/util/prefixedoutstream.hpp