mlpack::data::IncrementPolicy Class Reference
IncrementPolicy is used as a helper class for DatasetMapper.
Public Types
using MappedType = size_t
Public Member Functions
template<typename T >
void MapFirstPass (const std::string &string, const size_t dim, std::vector< Datatype > &types)
Determine if the dimension is numeric or categorical.
template<typename MapType , typename T >
T MapString (const std::string &string, const size_t dimension, MapType &maps, std::vector< Datatype > &types)
Given the string and the dimension to which the it belongs, and the maps and types given by the DatasetMapper class, returns its numeric mapping.
template<typename eT , typename MapType >
void MapTokens (const std::vector< std::string > &tokens, size_t &row, arma::Mat< eT > &matrix, MapType &maps, std::vector< Datatype > &types)
MapTokens turns vector of strings into numeric variables and puts them into a given matrix.
Static Public Attributes
static const bool NeedsFirstPass = true
We do need a first pass over the data to set the dimension types right.
Detailed Description
IncrementPolicy is used as a helper class for DatasetMapper.
It tells how the strings should be mapped. Purpose of this policy is to map all dimension if one if the variables in a dimension turns out to be a categorical variable. IncrementPolicy maps strings to incrementing unsigned integers (size_t). The first string to be mapped will be mapped to 0, the next to 1 and so on.
Definition at line 29 of file increment_policy.hpp.
Member Typedef Documentation
using mlpack::data::IncrementPolicy::MappedType = size_t
Definition at line 33 of file increment_policy.hpp.
Member Function Documentation
template<typename T > void mlpack::data::IncrementPolicy::MapFirstPass (const std::string & string, const size_t dim, std::vector< Datatype > & types) [inline]
Determine if the dimension is numeric or categorical.
Definition at line 42 of file increment_policy.hpp.
References mlpack::data::categorical.
template<typename MapType , typename T > T mlpack::data::IncrementPolicy::MapString (const std::string & string, const size_t dimension, MapType & maps, std::vector< Datatype > & types) [inline]
Given the string and the dimension to which the it belongs, and the maps and types given by the DatasetMapper class, returns its numeric mapping.
If no mapping yet exists, the string is added to the list of mappings for the given dimension. This function is used as a helper function for DatasetMapper class.
Template Parameters
MapType Type of unordered_map that contains mapped value pairs
Parameters
string String to find/create mapping for.
dimension Index of the dimension of the string.
maps Unordered map given by the DatasetMapper.
types Vector containing the type information about each dimensions.
Definition at line 81 of file increment_policy.hpp.
References mlpack::data::categorical, and mlpack::data::numeric.
Referenced by MapTokens().
template<typename eT , typename MapType > void mlpack::data::IncrementPolicy::MapTokens (const std::vector< std::string > & tokens, size_t & row, arma::Mat< eT > & matrix, MapType & maps, std::vector< Datatype > & types) [inline]
MapTokens turns vector of strings into numeric variables and puts them into a given matrix.
It is used as a helper function when trying to load files. Each dimension's tokens are given in to this function. If one of the tokens turns out to be a string, all the tokens should be mapped using the MapString() funciton.
Template Parameters
eT Type of armadillo matrix.
MapType Type of unordered_map that contains mapped value pairs.
Parameters
tokens Vector of variables inside a dimension.
row Position of the given tokens.
matrix Matrix to save the data into.
maps Maps given by the DatasetMapper class.
types Types of each dimensions given by the DatasetMapper class.
Definition at line 146 of file increment_policy.hpp.
References MapString(), and string().
Member Data Documentation
const bool mlpack::data::IncrementPolicy::NeedsFirstPass = true [static]
We do need a first pass over the data to set the dimension types right.
Definition at line 36 of file increment_policy.hpp.
The documentation for this class was generated from the following file:
src/mlpack/core/data/map_policies/increment_policy.hpp