mlpack::ann::SoftsignFunction Class Reference
The softsign function, defined by.
Static Public Member Functions
static double Deriv (const double y)
Computes the first derivative of the softsign function.
template<typename InputVecType , typename OutputVecType >
static void Deriv (const InputVecType &y, OutputVecType &x)
Computes the first derivatives of the softsign function.
static double Fn (const double x)
Computes the softsign function.
template<typename InputVecType , typename OutputVecType >
static void Fn (const InputVecType &x, OutputVecType &y)
Computes the softsign function.
static double Inv (const double y)
Computes the inverse of the softsign function.
template<typename InputVecType , typename OutputVecType >
static void Inv (const InputVecType &y, OutputVecType &x)
Computes the inverse of the softsign function.
Detailed Description
The softsign function, defined by.
 f(x) &=& \frac{x}{1 + |x|} \\ f'(x) &=& (1 - |x|)^2 \\ f(x) &=& \left\{ \begin{array}{lr} -\frac{y}{y-1} & : x > 0 \\ \frac{x}{1 + x} & : x \le 0 \end{array} \right. 
Definition at line 47 of file softsign_function.hpp.
Member Function Documentation
static double mlpack::ann::SoftsignFunction::Deriv (const double y) [inline], [static]
Computes the first derivative of the softsign function.
Parameters
y Input data.
Returns
f'(x)
Definition at line 84 of file softsign_function.hpp.
template<typename InputVecType , typename OutputVecType > static void mlpack::ann::SoftsignFunction::Deriv (const InputVecType & y, OutputVecType & x) [inline], [static]
Computes the first derivatives of the softsign function.
Parameters
y Input activations.
x The resulting derivatives.
Definition at line 96 of file softsign_function.hpp.
static double mlpack::ann::SoftsignFunction::Fn (const double x) [inline], [static]
Computes the softsign function.
Parameters
x Input data.
Returns
f(x).
Definition at line 56 of file softsign_function.hpp.
Referenced by Fn().
template<typename InputVecType , typename OutputVecType > static void mlpack::ann::SoftsignFunction::Fn (const InputVecType & x, OutputVecType & y) [inline], [static]
Computes the softsign function.
Parameters
x Input data.
y The resulting output activation.
Definition at line 70 of file softsign_function.hpp.
References Fn().
static double mlpack::ann::SoftsignFunction::Inv (const double y) [inline], [static]
Computes the inverse of the softsign function.
Parameters
y Input data.
Returns
f^{-1}(y)
Definition at line 107 of file softsign_function.hpp.
Referenced by Inv().
template<typename InputVecType , typename OutputVecType > static void mlpack::ann::SoftsignFunction::Inv (const InputVecType & y, OutputVecType & x) [inline], [static]
Computes the inverse of the softsign function.
Parameters
y Input data.
x The resulting inverse of the input data.
Definition at line 122 of file softsign_function.hpp.
References Inv().
The documentation for this class was generated from the following file:
src/mlpack/methods/ann/activation_functions/softsign_function.hpp