mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType > Class Template Reference
A binary space partitioning tree, such as a KD-tree or a ball tree.
Classes
class BreadthFirstDualTreeTraverser
class DualTreeTraverser
A dual-tree traverser for binary space trees; see dual_tree_traverser.hpp.
class SingleTreeTraverser
A single-tree traverser for binary space trees; see single_tree_traverser.hpp for implementation.
Public Types
typedef MatType::elem_type ElemType
The type of element held in MatType.
typedef MatType Mat
So other classes can use TreeType::Mat.
typedef SplitType< BoundType< MetricType >, MatType > Split
Public Member Functions
BinarySpaceTree (const MatType &data, const size_t maxLeafSize=20)
Construct this as the root node of a binary space tree using the given dataset.
BinarySpaceTree (const MatType &data, std::vector< size_t > &oldFromNew, const size_t maxLeafSize=20)
Construct this as the root node of a binary space tree using the given dataset.
BinarySpaceTree (const MatType &data, std::vector< size_t > &oldFromNew, std::vector< size_t > &newFromOld, const size_t maxLeafSize=20)
Construct this as the root node of a binary space tree using the given dataset.
BinarySpaceTree (MatType &&data, const size_t maxLeafSize=20)
Construct this as the root node of a binary space tree using the given dataset.
BinarySpaceTree (MatType &&data, std::vector< size_t > &oldFromNew, const size_t maxLeafSize=20)
Construct this as the root node of a binary space tree using the given dataset.
BinarySpaceTree (MatType &&data, std::vector< size_t > &oldFromNew, std::vector< size_t > &newFromOld, const size_t maxLeafSize=20)
Construct this as the root node of a binary space tree using the given dataset.
BinarySpaceTree (BinarySpaceTree *parent, const size_t begin, const size_t count, SplitType< BoundType< MetricType >, MatType > &splitter, const size_t maxLeafSize=20)
Construct this node as a child of the given parent, starting at column begin and using count points.
BinarySpaceTree (BinarySpaceTree *parent, const size_t begin, const size_t count, std::vector< size_t > &oldFromNew, SplitType< BoundType< MetricType >, MatType > &splitter, const size_t maxLeafSize=20)
Construct this node as a child of the given parent, starting at column begin and using count points.
BinarySpaceTree (BinarySpaceTree *parent, const size_t begin, const size_t count, std::vector< size_t > &oldFromNew, std::vector< size_t > &newFromOld, SplitType< BoundType< MetricType >, MatType > &splitter, const size_t maxLeafSize=20)
Construct this node as a child of the given parent, starting at column begin and using count points.
BinarySpaceTree (const BinarySpaceTree &other)
Create a binary space tree by copying the other tree.
BinarySpaceTree (BinarySpaceTree &&other)
Move constructor for a BinarySpaceTree; possess all the members of the given tree.
template<typename Archive >
BinarySpaceTree (Archive &ar, const typename std::enable_if_t< Archive::is_loading::value > *=0)
Initialize the tree from a boost::serialization archive.
~BinarySpaceTree ()
Deletes this node, deallocating the memory for the children and calling their destructors in turn.
size_t Begin () const
Return the index of the beginning point of this subset.
size_t & Begin ()
Modify the index of the beginning point of this subset.
const BoundType< MetricType > & Bound () const
Return the bound object for this node.
BoundType< MetricType > & Bound ()
Return the bound object for this node.
void Center (arma::vec &center) const
Store the center of the bounding region in the given vector.
BinarySpaceTree & Child (const size_t child) const
Return the specified child (0 will be left, 1 will be right).
BinarySpaceTree *& ChildPtr (const size_t child)
size_t Count () const
Return the number of points in this subset.
size_t & Count ()
Modify the number of points in this subset.
const MatType & Dataset () const
Get the dataset which the tree is built on.
MatType & Dataset ()
Modify the dataset which the tree is built on. Be careful!
size_t Descendant (const size_t index) const
Return the index (with reference to the dataset) of a particular descendant of this node.
ElemType FurthestDescendantDistance () const
Return the furthest possible descendant distance.
ElemType FurthestPointDistance () const
Return the furthest distance to a point held in this node.
template<typename VecType >
size_t GetFurthestChild (const VecType &point, typename std::enable_if_t< IsVector< VecType >::value > *=0)
Return the index of the furthest child node to the given query point.
size_t GetFurthestChild (const BinarySpaceTree &queryNode)
Return the index of the furthest child node to the given query node.
template<typename VecType >
size_t GetNearestChild (const VecType &point, typename std::enable_if_t< IsVector< VecType >::value > *=0)
Return the index of the nearest child node to the given query point.
size_t GetNearestChild (const BinarySpaceTree &queryNode)
Return the index of the nearest child node to the given query node.
bool IsLeaf () const
Return whether or not this node is a leaf (true if it has no children).
BinarySpaceTree * Left () const
Gets the left child of this node.
BinarySpaceTree *& Left ()
Modify the left child of this node.
ElemType MaxDistance (const BinarySpaceTree &other) const
Return the maximum distance to another node.
template<typename VecType >
ElemType MaxDistance (const VecType &point, typename std::enable_if_t< IsVector< VecType >::value > *=0) const
Return the maximum distance to another point.
MetricType Metric () const
Get the metric that the tree uses.
ElemType MinDistance (const BinarySpaceTree &other) const
Return the minimum distance to another node.
template<typename VecType >
ElemType MinDistance (const VecType &point, typename std::enable_if_t< IsVector< VecType >::value > *=0) const
Return the minimum distance to another point.
ElemType MinimumBoundDistance () const
Return the minimum distance from the center of the node to any bound edge.
size_t NumChildren () const
Return the number of children in this node.
size_t NumDescendants () const
Return the number of descendants of this node.
size_t NumPoints () const
Return the number of points in this node (0 if not a leaf).
BinarySpaceTree * Parent () const
Gets the parent of this node.
BinarySpaceTree *& Parent ()
Modify the parent of this node.
ElemType ParentDistance () const
Return the distance from the center of this node to the center of the parent node.
ElemType & ParentDistance ()
Modify the distance from the center of this node to the center of the parent node.
size_t Point (const size_t index) const
Return the index (with reference to the dataset) of a particular point in this node.
math::RangeType< ElemType > RangeDistance (const BinarySpaceTree &other) const
Return the minimum and maximum distance to another node.
template<typename VecType >
math::RangeType< ElemType > RangeDistance (const VecType &point, typename std::enable_if_t< IsVector< VecType >::value > *=0) const
Return the minimum and maximum distance to another point.
BinarySpaceTree * Right () const
Gets the right child of this node.
BinarySpaceTree *& Right ()
Modify the right child of this node.
template<typename Archive >
void Serialize (Archive &ar, const unsigned int version)
Serialize the tree.
const StatisticType & Stat () const
Return the statistic object for this node.
StatisticType & Stat ()
Return the statistic object for this node.
Protected Member Functions
BinarySpaceTree ()
A default constructor.
Private Member Functions
void SplitNode (const size_t maxLeafSize, SplitType< BoundType< MetricType >, MatType > &splitter)
Splits the current node, assigning its left and right children recursively.
void SplitNode (std::vector< size_t > &oldFromNew, const size_t maxLeafSize, SplitType< BoundType< MetricType >, MatType > &splitter)
Splits the current node, assigning its left and right children recursively.
template<typename BoundType2 >
void UpdateBound (BoundType2 &boundToUpdate)
Update the bound of the current node.
void UpdateBound (bound::HollowBallBound< MetricType > &boundToUpdate)
Update the bound of the current node.
Private Attributes
size_t begin
The index of the first point in the dataset contained in this node (and its children).
BoundType< MetricType > bound
The bound object for this node.
size_t count
The number of points of the dataset contained in this node (and its children).
MatType * dataset
The dataset.
ElemType furthestDescendantDistance
The worst possible distance to the furthest descendant, cached to speed things up.
BinarySpaceTree * left
The left child node.
ElemType minimumBoundDistance
The minimum distance from the center to any edge of the bound.
BinarySpaceTree * parent
The parent node (NULL if this is the root of the tree).
ElemType parentDistance
The distance from the centroid of this node to the centroid of the parent.
BinarySpaceTree * right
The right child node.
StatisticType stat
Any extra data contained in the node.
Detailed Description
template<typename MetricType, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit>
*
class mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >
A binary space partitioning tree, such as a KD-tree or a ball tree.
Once the bound and type of dataset is defined, the tree will construct itself. Call the constructor with the dataset to build the tree on, and the entire tree will be built.
This particular tree does not allow growth, so you cannot add or delete nodes from it. If you need to add or delete a node, the better procedure is to rebuild the tree entirely.
This tree does take one runtime parameter in the constructor, which is the max leaf size to be used.
Template Parameters
MetricType The metric used for tree-building. The BoundType may place restrictions on the metrics that can be used.
StatisticType Extra data contained in the node. See statistic.hpp for the necessary skeleton interface.
MatType The dataset class.
BoundType The bound used for each node. HRectBound, the default, requires that an LMetric<> is used for MetricType (so, EuclideanDistance, ManhattanDistance, etc.).
SplitType The class that partitions the dataset/points at a particular node into two parts. Its definition decides the way this split is done.
Definition at line 54 of file binary_space_tree.hpp.
Member Typedef Documentation
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> typedef MatType::elem_type mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::ElemType
The type of element held in MatType.
Definition at line 60 of file binary_space_tree.hpp.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> typedef MatType mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Mat
So other classes can use TreeType::Mat.
Definition at line 58 of file binary_space_tree.hpp.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> typedef SplitType<BoundType<MetricType>, MatType> mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Split
Definition at line 62 of file binary_space_tree.hpp.
Constructor & Destructor Documentation
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::BinarySpaceTree (const MatType & data, const size_t maxLeafSize = 20)
Construct this as the root node of a binary space tree using the given dataset.
This will copy the input matrix; if you don't want this, consider using the constructor that takes an rvalue reference and use std::move().
Parameters
data Dataset to create tree from. This will be copied!
maxLeafSize Size of each leaf in the tree.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::BinarySpaceTree (const MatType & data, std::vector< size_t > & oldFromNew, const size_t maxLeafSize = 20)
Construct this as the root node of a binary space tree using the given dataset.
This will copy the input matrix and modify its ordering; a mapping of the old point indices to the new point indices is filled. If you don't want the matrix to be copied, consider using the constructor that takes an rvalue reference and use std::move().
Parameters
data Dataset to create tree from. This will be copied!
oldFromNew Vector which will be filled with the old positions for each new point.
maxLeafSize Size of each leaf in the tree.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::BinarySpaceTree (const MatType & data, std::vector< size_t > & oldFromNew, std::vector< size_t > & newFromOld, const size_t maxLeafSize = 20)
Construct this as the root node of a binary space tree using the given dataset.
This will copy the input matrix and modify its ordering; a mapping of the old point indices to the new point indices is filled, as well as a mapping of the new point indices to the old point indices. If you don't want the matrix to be copied, consider using the constructor that takes an rvalue reference and use std::move().
Parameters
data Dataset to create tree from. This will be copied!
oldFromNew Vector which will be filled with the old positions for each new point.
newFromOld Vector which will be filled with the new positions for each old point.
maxLeafSize Size of each leaf in the tree.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::BinarySpaceTree (MatType && data, const size_t maxLeafSize = 20)
Construct this as the root node of a binary space tree using the given dataset.
This will take ownership of the data matrix; if you don't want this, consider using the constructor that takes a const reference to a dataset.
Parameters
data Dataset to create tree from.
maxLeafSize Size of each leaf in the tree.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::BinarySpaceTree (MatType && data, std::vector< size_t > & oldFromNew, const size_t maxLeafSize = 20)
Construct this as the root node of a binary space tree using the given dataset.
This will take ownership of the data matrix; a mapping of the old point indices to the new point indices is filled. If you don't want the matrix to have its ownership taken, consider using the constructor that takes a const reference to a dataset.
Parameters
data Dataset to create tree from.
oldFromNew Vector which will be filled with the old positions for each new point.
maxLeafSize Size of each leaf in the tree.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::BinarySpaceTree (MatType && data, std::vector< size_t > & oldFromNew, std::vector< size_t > & newFromOld, const size_t maxLeafSize = 20)
Construct this as the root node of a binary space tree using the given dataset.
This will take ownership of the data matrix; a mapping of the old point indices to the new point indices is filled, as well as a mapping of the new point indices to the old point indices. If you don't want the matrix to have its ownership taken, consider using the constructor that takes a const reference to a dataset.
Parameters
data Dataset to create tree from.
oldFromNew Vector which will be filled with the old positions for each new point.
newFromOld Vector which will be filled with the new positions for each old point.
maxLeafSize Size of each leaf in the tree.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::BinarySpaceTree (BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType > * parent, const size_t begin, const size_t count, SplitType< BoundType< MetricType >, MatType > & splitter, const size_t maxLeafSize = 20)
Construct this node as a child of the given parent, starting at column begin and using count points.
The ordering of that subset of points in the parent's data matrix will be modified! This is used for recursive tree-building by the other constructors which don't specify point indices.
Parameters
parent Parent of this node. Its dataset will be modified!
begin Index of point to start tree construction with.
count Number of points to use to construct tree.
splitter Instantiated node splitter object.
maxLeafSize Size of each leaf in the tree.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::BinarySpaceTree (BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType > * parent, const size_t begin, const size_t count, std::vector< size_t > & oldFromNew, SplitType< BoundType< MetricType >, MatType > & splitter, const size_t maxLeafSize = 20)
Construct this node as a child of the given parent, starting at column begin and using count points.
The ordering of that subset of points in the parent's data matrix will be modified! This is used for recursive tree-building by the other constructors which don't specify point indices.
A mapping of the old point indices to the new point indices is filled, but it is expected that the vector is already allocated with size greater than or equal to (begin + count), and if that is not true, invalid memory reads (and writes) will occur.
Parameters
parent Parent of this node. Its dataset will be modified!
begin Index of point to start tree construction with.
count Number of points to use to construct tree.
oldFromNew Vector which will be filled with the old positions for each new point.
splitter Instantiated node splitter object.
maxLeafSize Size of each leaf in the tree.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::BinarySpaceTree (BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType > * parent, const size_t begin, const size_t count, std::vector< size_t > & oldFromNew, std::vector< size_t > & newFromOld, SplitType< BoundType< MetricType >, MatType > & splitter, const size_t maxLeafSize = 20)
Construct this node as a child of the given parent, starting at column begin and using count points.
The ordering of that subset of points in the parent's data matrix will be modified! This is used for recursive tree-building by the other constructors which don't specify point indices.
A mapping of the old point indices to the new point indices is filled, as well as a mapping of the new point indices to the old point indices. It is expected that the vector is already allocated with size greater than or equal to (begin_in + count_in), and if that is not true, invalid memory reads (and writes) will occur.
Parameters
parent Parent of this node. Its dataset will be modified!
begin Index of point to start tree construction with.
count Number of points to use to construct tree.
oldFromNew Vector which will be filled with the old positions for each new point.
newFromOld Vector which will be filled with the new positions for each old point.
maxLeafSize Size of each leaf in the tree.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::BinarySpaceTree (const BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType > & other)
Create a binary space tree by copying the other tree.
Be careful! This can take a long time and use a lot of memory.
Parameters
other Tree to be replicated.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::BinarySpaceTree (BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType > && other)
Move constructor for a BinarySpaceTree; possess all the members of the given tree.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename Archive > mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::BinarySpaceTree (Archive & ar, const typename std::enable_if_t< Archive::is_loading::value > * = 0)
Initialize the tree from a boost::serialization archive.
Parameters
ar Archive to load tree from. Must be an iarchive, not an oarchive.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::~BinarySpaceTree ()
Deletes this node, deallocating the memory for the children and calling their destructors in turn.
This will invalidate any pointers or references to any nodes which are children of this one.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::BinarySpaceTree () [protected]
A default constructor.
This is meant to only be used with boost::serialization, which is allowed with the friend declaration below. This does not return a valid tree! The method must be protected, so that the serialization shim can work with the default constructor.
Referenced by mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Center().
Member Function Documentation
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> size_t mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Begin () const [inline]
Return the index of the beginning point of this subset.
Definition at line 483 of file binary_space_tree.hpp.
References mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::begin.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> size_t& mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Begin () [inline]
Modify the index of the beginning point of this subset.
Definition at line 485 of file binary_space_tree.hpp.
References mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::begin.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> const BoundType<MetricType>& mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Bound () const [inline]
Return the bound object for this node.
Definition at line 304 of file binary_space_tree.hpp.
References mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::bound.
Referenced by mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::MaxDistance(), mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::MinDistance(), and mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::RangeDistance().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> BoundType<MetricType>& mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Bound () [inline]
Return the bound object for this node.
Definition at line 306 of file binary_space_tree.hpp.
References mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::bound.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> void mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Center (arma::vec & center) const [inline]
Store the center of the bounding region in the given vector.
Definition at line 493 of file binary_space_tree.hpp.
References mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::BinarySpaceTree(), mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::SplitNode(), and mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::UpdateBound().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> BinarySpaceTree& mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Child (const size_t child) const
Return the specified child (0 will be left, 1 will be right).
If the index is greater than 1, this will return the right child.
Parameters
child Index of child to return.
Referenced by mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::ParentDistance().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> BinarySpaceTree*& mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::ChildPtr (const size_t child) [inline]
Definition at line 405 of file binary_space_tree.hpp.
References mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Descendant(), mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::NumDescendants(), mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::NumPoints(), mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Point(), and mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::right.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> size_t mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Count () const [inline]
Return the number of points in this subset.
Definition at line 488 of file binary_space_tree.hpp.
References mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::count.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> size_t& mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Count () [inline]
Modify the number of points in this subset.
Definition at line 490 of file binary_space_tree.hpp.
References mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::count.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> const MatType& mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Dataset () const [inline]
Get the dataset which the tree is built on.
Definition at line 332 of file binary_space_tree.hpp.
References mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::dataset.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> MatType& mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Dataset () [inline]
Modify the dataset which the tree is built on. Be careful!
Definition at line 334 of file binary_space_tree.hpp.
References mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::dataset.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> size_t mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Descendant (const size_t index) const
Return the index (with reference to the dataset) of a particular descendant of this node.
The index should be greater than zero but less than the number of descendants.
Parameters
index Index of the descendant.
Referenced by mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::ChildPtr().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> ElemType mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::FurthestDescendantDistance () const
Return the furthest possible descendant distance.
This returns the maximum distance from the centroid to the edge of the bound and not the empirical quantity which is the actual furthest descendant distance. So the actual furthest descendant distance may be less than what this method returns (but it will never be greater than this).
Referenced by mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Metric().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> ElemType mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::FurthestPointDistance () const
Return the furthest distance to a point held in this node.
If this is not a leaf node, then the distance is 0 because the node holds no points.
Referenced by mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Metric().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename VecType > size_t mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::GetFurthestChild (const VecType & point, typename std::enable_if_t< IsVector< VecType >::value > * = 0)
Return the index of the furthest child node to the given query point.
If this is a leaf node, it will return NumChildren() (invalid index).
Referenced by mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Metric().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> size_t mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::GetFurthestChild (const BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType > & queryNode)
Return the index of the furthest child node to the given query node.
If it can't decide, it will return NumChildren() (invalid index).
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename VecType > size_t mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::GetNearestChild (const VecType & point, typename std::enable_if_t< IsVector< VecType >::value > * = 0)
Return the index of the nearest child node to the given query point.
If this is a leaf node, it will return NumChildren() (invalid index).
Referenced by mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Metric().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> size_t mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::GetNearestChild (const BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType > & queryNode)
Return the index of the nearest child node to the given query node.
If it can't decide, it will return NumChildren() (invalid index).
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> bool mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::IsLeaf () const
Return whether or not this node is a leaf (true if it has no children).
Referenced by mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Stat().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> BinarySpaceTree* mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Left () const [inline]
Gets the left child of this node.
Definition at line 317 of file binary_space_tree.hpp.
References mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::left.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> BinarySpaceTree*& mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Left () [inline]
Modify the left child of this node.
Definition at line 319 of file binary_space_tree.hpp.
References mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::left.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> ElemType mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::MaxDistance (const BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType > & other) const [inline]
Return the maximum distance to another node.
Definition at line 444 of file binary_space_tree.hpp.
References mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Bound().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename VecType > ElemType mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::MaxDistance (const VecType & point, typename std::enable_if_t< IsVector< VecType >::value > * = 0) const [inline]
Return the maximum distance to another point.
Definition at line 466 of file binary_space_tree.hpp.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> MetricType mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Metric () const [inline]
Get the metric that the tree uses.
Definition at line 337 of file binary_space_tree.hpp.
References mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::FurthestDescendantDistance(), mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::FurthestPointDistance(), mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::GetFurthestChild(), mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::GetNearestChild(), mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::MinimumBoundDistance(), and mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::NumChildren().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> ElemType mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::MinDistance (const BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType > & other) const [inline]
Return the minimum distance to another node.
Definition at line 438 of file binary_space_tree.hpp.
References mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Bound().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename VecType > ElemType mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::MinDistance (const VecType & point, typename std::enable_if_t< IsVector< VecType >::value > * = 0) const [inline]
Return the minimum distance to another point.
Definition at line 457 of file binary_space_tree.hpp.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> ElemType mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::MinimumBoundDistance () const
Return the minimum distance from the center of the node to any bound edge.
Referenced by mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Metric().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> size_t mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::NumChildren () const
Return the number of children in this node.
Referenced by mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Metric().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> size_t mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::NumDescendants () const
Return the number of descendants of this node.
For a non-leaf in a binary space tree, this is the number of points at the descendant leaves. For a leaf, this is the number of points in the leaf.
Referenced by mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::ChildPtr().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> size_t mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::NumPoints () const
Return the number of points in this node (0 if not a leaf).
Referenced by mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::ChildPtr().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> BinarySpaceTree* mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Parent () const [inline]
Gets the parent of this node.
Definition at line 327 of file binary_space_tree.hpp.
References mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::parent.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> BinarySpaceTree*& mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Parent () [inline]
Modify the parent of this node.
Definition at line 329 of file binary_space_tree.hpp.
References mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::parent.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> ElemType mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::ParentDistance () const [inline]
Return the distance from the center of this node to the center of the parent node.
Definition at line 392 of file binary_space_tree.hpp.
References mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::parentDistance.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> ElemType& mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::ParentDistance () [inline]
Modify the distance from the center of this node to the center of the parent node.
Definition at line 395 of file binary_space_tree.hpp.
References mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Child(), and mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::parentDistance.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> size_t mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Point (const size_t index) const
Return the index (with reference to the dataset) of a particular point in this node.
This will happily return invalid indices if the given index is greater than the number of points in this node (obtained with NumPoints()) -- be careful.
Parameters
index Index of point for which a dataset index is wanted.
Referenced by mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::ChildPtr().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> math::RangeType<ElemType> mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::RangeDistance (const BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType > & other) const [inline]
Return the minimum and maximum distance to another node.
Definition at line 450 of file binary_space_tree.hpp.
References mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Bound().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename VecType > math::RangeType<ElemType> mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::RangeDistance (const VecType & point, typename std::enable_if_t< IsVector< VecType >::value > * = 0) const [inline]
Return the minimum and maximum distance to another point.
Definition at line 476 of file binary_space_tree.hpp.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> BinarySpaceTree* mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Right () const [inline]
Gets the right child of this node.
Definition at line 322 of file binary_space_tree.hpp.
References mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::right.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> BinarySpaceTree*& mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Right () [inline]
Modify the right child of this node.
Definition at line 324 of file binary_space_tree.hpp.
References mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::right.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename Archive > void mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Serialize (Archive & ar, const unsigned int version)
Serialize the tree.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> void mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::SplitNode (const size_t maxLeafSize, SplitType< BoundType< MetricType >, MatType > & splitter) [private]
Splits the current node, assigning its left and right children recursively.
Parameters
maxLeafSize Maximum number of points held in a leaf.
splitter Instantiated SplitType object.
Referenced by mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Center().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> void mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::SplitNode (std::vector< size_t > & oldFromNew, const size_t maxLeafSize, SplitType< BoundType< MetricType >, MatType > & splitter) [private]
Splits the current node, assigning its left and right children recursively.
Also returns a list of the changed indices.
Parameters
oldFromNew Vector holding permuted indices.
maxLeafSize Maximum number of points held in a leaf.
splitter Instantiated SplitType object.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> const StatisticType& mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Stat () const [inline]
Return the statistic object for this node.
Definition at line 309 of file binary_space_tree.hpp.
References mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::stat.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> StatisticType& mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Stat () [inline]
Return the statistic object for this node.
Definition at line 311 of file binary_space_tree.hpp.
References mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::IsLeaf(), and mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::stat.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> template<typename BoundType2 > void mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::UpdateBound (BoundType2 & boundToUpdate) [private]
Update the bound of the current node.
This method does not take into account bound-specific properties.
Parameters
boundToUpdate The bound to update.
Referenced by mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Center().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> void mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::UpdateBound (bound::HollowBallBound< MetricType > & boundToUpdate) [private]
Update the bound of the current node.
This method is designed for HollowBallBound only.
Parameters
boundToUpdate The bound to update.
Member Data Documentation
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> size_t mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::begin [private]
The index of the first point in the dataset contained in this node (and its children).
Definition at line 73 of file binary_space_tree.hpp.
Referenced by mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Begin().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> BoundType<MetricType> mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::bound [private]
The bound object for this node.
Definition at line 78 of file binary_space_tree.hpp.
Referenced by mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Bound().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> size_t mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::count [private]
The number of points of the dataset contained in this node (and its children).
Definition at line 76 of file binary_space_tree.hpp.
Referenced by mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Count().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> MatType* mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::dataset [private]
The dataset.
If we are the root of the tree, we own the dataset and must delete it.
Definition at line 90 of file binary_space_tree.hpp.
Referenced by mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Dataset().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> ElemType mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::furthestDescendantDistance [private]
The worst possible distance to the furthest descendant, cached to speed things up.
Definition at line 85 of file binary_space_tree.hpp.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> BinarySpaceTree* mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::left [private]
The left child node.
Definition at line 66 of file binary_space_tree.hpp.
Referenced by mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Left().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> ElemType mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::minimumBoundDistance [private]
The minimum distance from the center to any edge of the bound.
Definition at line 87 of file binary_space_tree.hpp.
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> BinarySpaceTree* mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::parent [private]
The parent node (NULL if this is the root of the tree).
Definition at line 70 of file binary_space_tree.hpp.
Referenced by mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Parent().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> ElemType mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::parentDistance [private]
The distance from the centroid of this node to the centroid of the parent.
Definition at line 82 of file binary_space_tree.hpp.
Referenced by mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::ParentDistance().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> BinarySpaceTree* mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::right [private]
The right child node.
Definition at line 68 of file binary_space_tree.hpp.
Referenced by mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::ChildPtr(), and mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Right().
template<typename MetricType , typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename... > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit> StatisticType mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::stat [private]
Any extra data contained in the node.
Definition at line 80 of file binary_space_tree.hpp.
Referenced by mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::Stat().
The documentation for this class was generated from the following file:
src/mlpack/core/tree/binary_space_tree/binary_space_tree.hpp