mlpack::ann::NaiveConvolution< BorderMode > Class Template Reference
Computes the two-dimensional convolution.
Static Public Member Functions
template<typename eT , typename Border = BorderMode>
static std::enable_if< std::is_same< Border, ValidConvolution >::value, void >::type Convolution (const arma::Mat< eT > &input, const arma::Mat< eT > &filter, arma::Mat< eT > &output, const size_t dW=1, const size_t dH=1)
template<typename eT , typename Border = BorderMode>
static std::enable_if< std::is_same< Border, FullConvolution >::value, void >::type Convolution (const arma::Mat< eT > &input, const arma::Mat< eT > &filter, arma::Mat< eT > &output, const size_t dW=1, const size_t dH=1)
template<typename eT >
static void Convolution (const arma::Cube< eT > &input, const arma::Cube< eT > &filter, arma::Cube< eT > &output, const size_t dW=1, const size_t dH=1)
template<typename eT >
static void Convolution (const arma::Mat< eT > &input, const arma::Cube< eT > &filter, arma::Cube< eT > &output, const size_t dW=1, const size_t dH=1)
template<typename eT >
static void Convolution (const arma::Cube< eT > &input, const arma::Mat< eT > &filter, arma::Cube< eT > &output, const size_t dW=1, const size_t dH=1)
Detailed Description
template<typename BorderMode = FullConvolution>
*
class mlpack::ann::NaiveConvolution< BorderMode >
Computes the two-dimensional convolution.
This class allows specification of the type of the border type. The convolution can be compute with the valid border type of the full border type (default).
FullConvolution: returns the full two-dimensional convolution. ValidConvolution: returns only those parts of the convolution that are computed without the zero-padded edges.
Template Parameters
BorderMode Type of the border mode (FullConvolution or ValidConvolution).
Definition at line 35 of file naive_convolution.hpp.
Member Function Documentation
template<typename BorderMode = FullConvolution> template<typename eT , typename Border = BorderMode> static std::enable_if< std::is_same<Border, ValidConvolution>::value, void>::type mlpack::ann::NaiveConvolution< BorderMode >::Convolution (const arma::Mat< eT > & input, const arma::Mat< eT > & filter, arma::Mat< eT > & output, const size_t dW = 1, const size_t dH = 1) [inline], [static]
Definition at line 50 of file naive_convolution.hpp.
Referenced by mlpack::ann::SVDConvolution< BorderMode >::Convolution(), and mlpack::ann::NaiveConvolution< BorderMode >::Convolution().
template<typename BorderMode = FullConvolution> template<typename eT , typename Border = BorderMode> static std::enable_if< std::is_same<Border, FullConvolution>::value, void>::type mlpack::ann::NaiveConvolution< BorderMode >::Convolution (const arma::Mat< eT > & input, const arma::Mat< eT > & filter, arma::Mat< eT > & output, const size_t dW = 1, const size_t dH = 1) [inline], [static]
Definition at line 90 of file naive_convolution.hpp.
References mlpack::ann::NaiveConvolution< BorderMode >::Convolution().
template<typename BorderMode = FullConvolution> template<typename eT > static void mlpack::ann::NaiveConvolution< BorderMode >::Convolution (const arma::Cube< eT > & input, const arma::Cube< eT > & filter, arma::Cube< eT > & output, const size_t dW = 1, const size_t dH = 1) [inline], [static]
Definition at line 120 of file naive_convolution.hpp.
References mlpack::ann::NaiveConvolution< BorderMode >::Convolution().
template<typename BorderMode = FullConvolution> template<typename eT > static void mlpack::ann::NaiveConvolution< BorderMode >::Convolution (const arma::Mat< eT > & input, const arma::Cube< eT > & filter, arma::Cube< eT > & output, const size_t dW = 1, const size_t dH = 1) [inline], [static]
Definition at line 152 of file naive_convolution.hpp.
References mlpack::ann::NaiveConvolution< BorderMode >::Convolution().
template<typename BorderMode = FullConvolution> template<typename eT > static void mlpack::ann::NaiveConvolution< BorderMode >::Convolution (const arma::Cube< eT > & input, const arma::Mat< eT > & filter, arma::Cube< eT > & output, const size_t dW = 1, const size_t dH = 1) [inline], [static]
Definition at line 184 of file naive_convolution.hpp.
References mlpack::ann::NaiveConvolution< BorderMode >::Convolution().
The documentation for this class was generated from the following file:
src/mlpack/methods/ann/convolution_rules/naive_convolution.hpp