src/mlpack/CMakeLists.txt File Reference
Functions
add_subdirectory (${dir}) endforeach() if(BUILD_TESTS) add_subdirectory(tests) endif() add_library(mlpack $
*h file (GLOB_RECURSE INCLUDE_HPP_FILES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}*.hpp) set(INCLUDE_FILES $
if ((NOT FORCE_CXX11) AND(NOT(${CMAKE_MAJOR_VERSION}LESS 3 OR(${CMAKE_MAJOR_VERSION}EQUAL 3 AND ${CMAKE_MINOR_VERSION}LESS 1)))) include(../../CMake/NewCXX11.cmake) endif() set_target_properties(mlpack PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS ON) include(GenerateExportHeader) generate_export_header(mlpack EXPORT_FILE_NAME mlpack_export.hpp) if(NOT BUILD_SHARED_LIBS) add_definitions(-DMLPACK_STATIC_DEFINE) endif() target_link_libraries(mlpack $
include_directories (..) include_directories($
set (MLPACK_SRCS ${MLPACK_SRCS}`${CMAKE_CURRENT_SOURCE_DIR}/core.hpp`) set(DIRS bindings core methods) foreach(dir $
set_target_properties (mlpack PROPERTIES VERSION 2.0 SOVERSION 2) if(CMAKE_SYSTEM_NAME STREQUAL`Linux`) if(LIBBFD_FOUND AND LIBDL_FOUND AND DEBUG) target_link_libraries(mlpack $
target_link_libraries (mlpack ${LIBDL_LIBRARIES}) endif() endif() file(GLOB_RECURSE INCLUDE_H_FILES RELATIVE $
Function Documentation
add_subdirectory (${dir})
Definition at line 15 of file CMakeLists.txt.
References add_library().
Referenced by macro(), and set().
* h file (GLOB_RECURSE INCLUDE_HPP_FILES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}*. hpp)
Definition at line 64 of file CMakeLists.txt.
References add_custom_command(), and install().
Referenced by add_library(), set(), and target_link_libraries().
[if((NOT FORCE_CXX11) AND(NOT($CMAKE_MAJOR_VERSIONLESS 3 OR($CMAKE_MAJOR_VERSIONEQUAL 3 AND $CMAKE_MINOR_VERSIONLESS 1)))) include(../../CMake/NewCXX11.cmake) endif() set_target_properties(mlpack PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS ON) include(GenerateExportHeader) generate_export_header(mlpack EXPORT_FILE_NAME mlpack_export.hpp) if(NOT BUILD_SHARED_LIBS) add_definitions(-DMLPACK_STATIC_DEFINE) endif() target_link_libraries(mlpack $]if ((NOT FORCE_CXX11) AND(NOT(${CMAKE_MAJOR_VERSION}LESS 3 OR(${CMAKE_MAJOR_VERSION}EQUAL 3 AND ${CMAKE_MINOR_VERSION}LESS 1))))
Definition at line 28 of file CMakeLists.txt.
References set_target_properties(), and target_link_libraries().
include_directories (..)
Definition at line 1 of file CMakeLists.txt.
set (MLPACK_SRCS ${MLPACK_SRCS}`${CMAKE_CURRENT_SOURCE_DIR}/core.hpp`)
Definition at line 5 of file CMakeLists.txt.
set_target_properties (mlpack PROPERTIES VERSION 2.0 SOVERSION 2)
Definition at line 48 of file CMakeLists.txt.
Referenced by if().
target_link_libraries (mlpack ${LIBDL_LIBRARIES})
Definition at line 58 of file CMakeLists.txt.
References file().
Referenced by if(), and macro().