src/mlpack/methods/CMakeLists.txt File Reference
Functions
macro (add_cli_executable name) if(BUILD_CLI_EXECUTABLES) add_executable(mlpack_ $
Function Documentation
macro (add_cli_executable name)
Definition at line 4 of file CMakeLists.txt.
References add_subdirectory(), install(), and target_link_libraries().