librule(name="tpiemm",
		    headers=lglob("*.h"),
				deplibs=["fastlib:fastlib",
							   "libsigsegv.a"]
		);
binrule(
		name="test",
		sources=["memory_manager_unit.cc"],
		headers=lglob("*.h"),
		deplibs=[":tpiemm"]
		);
