trigger:
  branches:
    include:
    - '*'
pr:
  branches:
    include:
    - '*'

jobs:
- job: Linux
  timeoutInMinutes: 360
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      Plain:
        CMakeArgs: '-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_JULIA_BINDINGS=OFF -DBUILD_GO_BINDINGS=OFF -DBUILD_R_BINDINGS=OFF'
      Python:
        binding: 'python'
        python.version: '3.7'
        CMakeArgs: '-DDEBUG=OFF -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=ON -DPYTHON_EXECUTABLE=/usr/bin/python3 -DBUILD_GO_BINDINGS=OFF -DBUILD_JULIA_BINDINGS=OFF -DBUILD_R_BINDINGS=OFF'
      Julia:
        julia.version: '1.3.0'
        CMakeArgs: '-DDEBUG=OFF -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_JULIA_BINDINGS=ON -DBUILD_GO_BINDINGS=OFF -DJULIA_EXECUTABLE=/opt/julia-1.3.0/bin/julia -DBUILD_R_BINDINGS=OFF'
      Go:
        binding: 'go'
        go.version: '1.11.0'
        CMakeArgs: '-DDEBUG=OFF -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_JULIA_BINDINGS=OFF -DBUILD_GO_BINDINGS=ON -DBUILD_R_BINDINGS=OFF'
      Markdown:
        CMakeArgs: '-DDEBUG=OFF -DPROFILE=OFF -DBUILD_MARKDOWN_BINDINGS=ON -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_GO_BINDINGS=OFF -DBUILD_JULIA_BINDINGS=OFF -DBUILD_R_BINDINGS=OFF'

  steps:
  - template: linux-steps.yaml

- job: macOS
  timeoutInMinutes: 360
  pool:
    vmImage: macOS-10.14
  strategy:
    matrix:
      Plain:
        CMakeArgs: '-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_JULIA_BINDINGS=OFF -DBUILD_GO_BINDINGS=OFF -DBUILD_R_BINDINGS=OFF'
        python.version: '2.7'
      Python:
        binding: 'python'
        python.version: '3.7'
        CMakeArgs: '-DDEBUG=OFF -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=ON -DBUILD_JULIA_BINDINGS=OFF -DBUILD_GO_BINDINGS=OFF -DBUILD_R_BINDINGS=OFF'
      Julia:
        python.version: '2.7'
        julia.version: '1.3.0'
        CMakeArgs: '-DDEBUG=OFF -DPROFILE=OFF -DBUILD_JULIA_BINDINGS=ON -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_GO_BINDINGS=OFF -DBUILD_R_BINDINGS=OFF'
      Go:
        binding: 'go'
        python.version: '2.7'
        go.version: '1.11.0'
        CMakeArgs: '-DDEBUG=OFF -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_JULIA_BINDINGS=OFF -DBUILD_GO_BINDINGS=ON -DBUILD_R_BINDINGS=OFF'

  steps:
  - template: macos-steps.yaml

- job: WindowsVS15
  timeoutInMinutes: 360
  displayName: Windows VS15
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      Plain:
        CMakeArgs: '-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_GO_BINDINGS=OFF -DBUILD_R_BINDINGS=OFF'
        python.version: '2.7'
        CMakeGenerator: '-G "Visual Studio 15 2017 Win64"'
        MSBuildVersion: '15.0'
        ArchiveNoLibs: 'mlpack-windows-vs15-no-libs.zip'
        ArchiveLibs: 'mlpack-windows-vs15.zip'
        ArchiveTests: 'mlpack_test-vs15.xml'

  steps:
  - template: windows-steps.yaml

- job: WindowsVS16
  timeoutInMinutes: 360
  displayName: Windows VS16
  pool:
    vmImage: windows-2019
  strategy:
    matrix:
      Plain:
        CMakeArgs: '-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_GO_BINDINGS=OFF -DBUILD_R_BINDINGS=OFF'
        python.version: '2.7'
        CMakeGenerator: '-G "Visual Studio 16 2019"'
        MSBuildVersion: '16.0'
        ArchiveNoLibs: 'mlpack-windows-vs16-no-libs.zip'
        ArchiveLibs: 'mlpack-windows-vs16.zip'
        ArchiveTests: 'mlpack_test-vs16.xml'

  steps:
  - template: windows-steps.yaml
