jobs:
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      Plain:
        CMakeArgs: '-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF'
        python.version: '2.7'
      Python27:
        python.version: '2.7'
        CMakeArgs: '-DDEBUG=OFF -DPROFILE=OFF -DPYTHON_EXECUTABLE=/usr/bin/python'
      Python37:
        python.version: '3.7'
        CMakeArgs: '-DDEBUG=OFF -DPROFILE=OFF -DPYTHON_EXECUTABLE=/usr/bin/python3'
      Markdown:
        python.version: '2.7'
        CMakeArgs: '-DDEBUG=OFF -DPROFILE=OFF -DBUILD_MARKDOWN_BINDINGS=ON -DBUILD_PYTHON_BINDINGS=OFF'

  steps:
  - template: linux-steps.yaml

- job: macOS
  pool:
    vmImage: macOS-10.13
  strategy:
    matrix:
      Plain:
        CMakeArgs: '-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF'
        python.version: '2.7'
      Python27:
        python.version: '2.7'
        CMakeArgs: '-DDEBUG=OFF -DPROFILE=OFF'
      Python37:
        python.version: '3.7'
        CMakeArgs: '-DDEBUG=OFF -DPROFILE=OFF'

  steps:
  - template: macos-steps.yaml

- job: WindowsVS14
  timeoutInMinutes: 360
  displayName: Windows VS14
  pool:
    vmImage: vs2015-win2012r2
  strategy:
    matrix:
      Plain:
        CMakeArgs: '-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF'
        CMakeGenerator: '-G "Visual Studio 14 2015 Win64"'
        MSBuildVersion: '14.0'
        ArchiveNoLibs: 'mlpack-windows-vs14-no-libs.zip'
        ArchiveLibs: 'mlpack-windows-vs14.zip'
        ArchiveTests: 'mlpack_test-vs14.xml'
  steps:
  - template: windows-steps.yaml

- job: WindowsVS15
  timeoutInMinutes: 360
  displayName: Windows VS15
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      Plain:
        CMakeArgs: '-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF'
        python.version: '2.7'
        CMakeGenerator: '-G "Visual Studio 15 2017 Win64"'
        MSBuildVersion: '15.0'
        ArchiveNoLibs: 'mlpack-windows-vs15-no-libs.zip'
        ArchiveLibs: 'mlpack-windows-vs15.zip'
        ArchiveTests: 'mlpack_test-vs15.xml'

  steps:
  - template: windows-steps.yaml

- job: WindowsVS16
  timeoutInMinutes: 360
  displayName: Windows VS16
  pool:
    vmImage: windows-2019
  strategy:
    matrix:
      Plain:
        CMakeArgs: '-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF'
        python.version: '2.7'
        CMakeGenerator: '-G "Visual Studio 16 2019"'
        MSBuildVersion: '16.0'
        ArchiveNoLibs: 'mlpack-windows-vs16-no-libs.zip'
        ArchiveLibs: 'mlpack-windows-vs16.zip'
        ArchiveTests: 'mlpack_test-vs16.xml'

  steps:
  - template: windows-steps.yaml
