 /**
 * @file cne.hpp
 * @author Bang Liu
 *
 * Definition of CNE class.
 */
#ifndef MLPACK_METHODS_NE_CNE_HPP
#define MLPACK_METHODS_NE_CNE_HPP

#include <cstdio>

#include <mlpack/core.hpp>

#include "link_gene.hpp"
#include "neuron_gene.hpp"
#include "genome.hpp"
#include "species.hpp"
#include "tasks.hpp"
#include "parameters.hpp"

namespace mlpack {
namespace ne {

/**
 * This class implements Conventional Neuro-evolution (CNE): weight
 * evolution on topologically fixed neural networks.
 */
template<typename TaskType>
class CNE
{
 public:
  /**
   * Parametric constructor.
   *
   * @param task The task to solve.
   * @param seedGenome The genome to initialize population.
   * @param params The Parameter object that contains algorithm parameters.
   */
  CNE(TaskType task, Genome& seedGenome, Parameters& params)
  {
    aTask = task;
    aSeedGenome = seedGenome;
    aSpeciesSize = params.aSpeciesSize;
    aMaxGeneration = params.aMaxGeneration;
    aMutateRate = params.aMutateRate;
    aMutateSize = params.aMutateSize;
    aElitePercentage = params.aElitePercentage;
  }

  /** 
   * Soft weight mutation: add a Gaussian random value to genome link weights.
   *
   * @param genome The genome to mutate.
   * @param mutateProb The probability to mutate the genome's weight.
   * @param mutateSize The variance of Gaussian noise added to genome weights.
   */
  static void MutateWeightsBiased(Genome& genome, double mutateProb, double mutateSize)
  {
    for (int i=0; i<genome.aLinkGenes.size(); ++i)
    {
      double p = mlpack::math::Random();  // rand 0~1
      if (p < mutateProb)
      {
        double deltaW = mlpack::math::RandNormal(0, mutateSize);
        double oldW = genome.aLinkGenes[i].Weight();
        genome.aLinkGenes[i].Weight(oldW + deltaW);
      }
    }
  }

  /** 
   * Hard weight mutation: replace genome link weights with Gaussian random values.
   *
   * @param genome The genome to mutate.
   * @param mutateProb The probability to mutate the genome's weight.
   * @param mutateSize The variance of Gaussian noise added to genome weights.
   */
  static void MutateWeightsUnbiased(Genome& genome, double mutateProb, double mutateSize)
  {
    for (int i=0; i<genome.aLinkGenes.size(); ++i)
    {
      double p = mlpack::math::Random();
      if (p < mutateProb)
      {
        double weight = mlpack::math::RandNormal(0, mutateSize);
        genome.aLinkGenes[i].Weight(weight);
      }
    }
  }

  /**
   * Crossover two genomes' weights to generate two child genomes.
   *
   * NOTICE: child genomes need to set genome id based on its population's max id.
   *
   * @param momGenome The mother genome of two child genomes.
   * @param dadGenome The father genome of two child genomes.
   * @param child1Genome One child genome generated by crossover.
   * @param child2Genmoe Another child genome generated by crossover.
   */
  static void CrossoverWeights(Genome& momGenome, 
                               Genome& dadGenome, 
                               Genome& child1Genome, 
                               Genome& child2Genome)
  {
    child1Genome = momGenome;
    child2Genome = dadGenome;
    for (int i=0; i<momGenome.aLinkGenes.size(); ++i)
    { // assume genome are the same structure.
      double t = mlpack::math::RandNormal();
      if (t>0)
      {  // prob = 0.5
        child1Genome.aLinkGenes[i].Weight(momGenome.aLinkGenes[i].Weight());
        child2Genome.aLinkGenes[i].Weight(dadGenome.aLinkGenes[i].Weight());
      } else
      {
        child1Genome.aLinkGenes[i].Weight(dadGenome.aLinkGenes[i].Weight());
        child2Genome.aLinkGenes[i].Weight(momGenome.aLinkGenes[i].Weight());
      }
    }
  }

  /** 
   * Create initial species from seed genome and species size.
   */
  void InitSpecies()
  {
    aSpecies = Species(aSeedGenome, aSpeciesSize);
  }

  /**
   * Reproduce the next species. Heart function for CNE.
   *
   * Select parents from previous generation based on genomes' fitness.
   * Apply search operators to parents and produce offspring which
   * form next generation.
   */
  void Reproduce()
  {
    // Sort species by fitness
    aSpecies.SortGenomes();

    // Select parents from elite genomes and crossover.
    int numElite = floor(aElitePercentage * aSpeciesSize);
    int numDrop = floor((aSpeciesSize - numElite) / 2) * 2;  // Make sure even number.
    numElite = aSpeciesSize - numDrop;
    for (int i=numElite; i<aSpeciesSize-1; ++i)
    {
      // Randomly select two parents from elite genomes.
      int idx1 = RandInt(0, numElite);
      int idx2 = RandInt(0, numElite);

      // Crossover to get two children genomes.
      CrossoverWeights(aSpecies.aGenomes[idx1], aSpecies.aGenomes[idx2],
                       aSpecies.aGenomes[i], aSpecies.aGenomes[i+1]);
    }

    // Keep the best genome and mutate the rests.
    for (int i=1; i<aSpeciesSize; ++i)
    {
      MutateWeightsBiased(aSpecies.aGenomes[i], aMutateRate, aMutateSize);
    }
  }

  /**
   * Evolution of species.
   *
   * The whole process of CNE algorithm.
   * Iteratively evolve genomes for a number of generations to get a solution
   * genome for a specific task.
   */
  bool Evolve()
  {
    // Generate initial species at random.
    int generation = 0;
    InitSpecies();
    
    // Repeat
    while (generation < aMaxGeneration)
    {
    	// Evaluate all genomes in the species.
      for (int i=0; i<aSpecies.SpeciesSize(); ++i)
      {
        double fitness = aTask.EvalFitness(aSpecies.aGenomes[i]);
        aSpecies.aGenomes[i].Fitness(fitness);
      }
      aSpecies.SetBestFitnessAndGenome();

    	// Output some information.
      printf("Generation: %zu\tBest fitness: %f\n", generation, aSpecies.BestFitness());
      if (aTask.Success())
      {
        printf("Task succeed in %zu iterations.\n", generation);
        return true;
      }

    	// Reproduce next generation.
      Reproduce();
      ++generation;
    }

    return false;
  }

 private:
  //! Task.
  TaskType aTask;

  //! Seed genome. It is used for init species.
  Genome aSeedGenome;

  //! Species to evolve.
  Species aSpecies;

  //! Species size.
  int aSpeciesSize;

  //! Max number of generation to evolve.
  int aMaxGeneration;

  //! Mutation rate.
  double aMutateRate;

  //! Mutate size. For normal distribution, it is mutate variance.
  double aMutateSize;

  //! Elite percentage.
  double aElitePercentage;

};

}  // namespace ne
}  // namespace mlpack

#endif  // MLPACK_METHODS_NE_CNE_HPP
