function f = ComputeFullObjective(D, S, T, lambda)
%function f = ComputeFullObjective(D, S, T, lambda)

n = size(S, 2);

f = sum(accumarray((1:n)', 1:n, [],  ...
		   @(i) ComputeSparseCodesObjective(D, ...
						  S(:,i), ...
						  D' * T(:,i), ...
						  lambda)));
