librule(
    name = "compression",
    sources = ["adler32.c",
               "compress.c",
               "crc32.c",
               "deflate.c",
               "example.c",
               "gzio.c",
               "infback.c",
               "inffast.c",
               "inflate.c",
               "inftrees.c",
               "minigzip.c",
               "trees.c",
               "uncompr.c",
               "zutil.c"],
    tests = ["compression_test.cc"
             ],
    headers = ["compressed_matrix.h",
               "crc32.h",
               "deflate.h",
               "inffast.h",
               "inffixed.h",
               "inflate.h",
               "inftrees.h",
               "trees.h",
               "zconf.h",
               "zconf.in.h",
               "zlib.h",
               "zutil.h"],    
    deplibs = ["fastlib:fastlib_int",
               "contrib/dongryel/proximity_project:proximity_project",
               "contrib/dongryel/nested_summation_template:nested_summation_template",
               "mlpack/series_expansion:series_expansion"]
    )
