# Default image contents: https://hub.docker.com/r/mlpack/jenkins-amd64-debian
# Choose different variants available at: https://hub.docker.com/u/mlpack
ARG VARIANT=jenkins-amd64-debian
FROM mlpack/${VARIANT}

# Additional options here... 
# RUN apt update && apt upgrade -y 

# and so on...
