# Makefile for dirlib ~/g/npt
# Created by awm on:  Wed May 17 12:24:18 EDT 2000

here		= npt

includes	= m2p.h npt.h matcher.h napi.h npt2.h npt3.h projnpt.h

sources		= m2p.c npt.c matcher.c napi.c npt2.c npt3.c projnpt.c

private_sources = 

siblings	= mrkd dset extra draw utils

t:=debug
include .g/Make.common

