/net/hc293/niche/fastlib/u/niche/tree/kdtree: /net/hc293/niche/fastlib/u/niche/tree/Makefile /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/u/niche/tree/kdtree
	@echo '... Making /net/hc293/niche/fastlib/u/niche/tree/kdtree'
	@rm -f /net/hc293/niche/fastlib/u/niche/tree/kdtree
	@ln -s -f /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/u/niche/tree/kdtree /net/hc293/niche/fastlib/u/niche/tree/kdtree
	@echo '*** Created 1 symlinks in /net/hc293/niche/fastlib/u/niche/tree/.'
/net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/u/niche/tree/kdtree: /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libu_niche_tree_kdtree__auto.a /net/hc293/niche/fastlib/bin_keep/x86_64_Linux_COMMON_gcc_COMMON/libblaspack.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libcol_col.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libmath_math.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libfile_file.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libbase_base.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libfx_fx.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libla_la.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libdata_data.a
	@echo '... Making bin/x86_64_Linux_check_gcc_/u/niche/tree/kdtree'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/u/niche/tree
	@g++ -o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/u/niche/tree/kdtree -O2 -finline-functions -finline-limit=2000 -g -DDEBUG  /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libu_niche_tree_kdtree__auto.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libmath_math.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libdata_data.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libfile_file.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libfx_fx.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libla_la.a /net/hc293/niche/fastlib/bin_keep/x86_64_Linux_COMMON_gcc_COMMON/libblaspack.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libcol_col.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libbase_base.a -lm -lpthread -lg2c
pseudo_4: /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libu_niche_tree_kdtree__auto.a /net/hc293/niche/fastlib/bin_keep/x86_64_Linux_COMMON_gcc_COMMON/libblaspack.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libcol_col.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libmath_math.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libfile_file.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libbase_base.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libfx_fx.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libla_la.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libdata_data.a
	@echo '*** Done with /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libu_niche_tree_kdtree__auto.a /net/hc293/niche/fastlib/bin_keep/x86_64_Linux_COMMON_gcc_COMMON/libblaspack.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libcol_col.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libmath_math.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libfile_file.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libbase_base.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libfx_fx.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libla_la.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libdata_data.a'
/net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libu_niche_tree_kdtree__auto.a: /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/u_niche_tree_kdtree.o
	@echo '... Making bin/x86_64_Linux_check_gcc_/libu_niche_tree_kdtree__auto.a'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_
	@ar r /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libu_niche_tree_kdtree__auto.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/u_niche_tree_kdtree.o
/net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/u_niche_tree_kdtree.o: /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libfastlib_fastlib.h /net/hc293/niche/fastlib/u/niche/tree/kdtree.cc
	@echo '... Making bin/x86_64_Linux_check_gcc_/obj/u_niche_tree_kdtree.o'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj
	@cd /net/hc293/niche/fastlib/u/niche/tree && g++ -Wall -Woverloaded-virtual -fno-exceptions -Wparentheses -fno-exceptions -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_ -I/net/hc293/niche/fastlib -O2 -finline-functions -finline-limit=2000 -g -DDEBUG   -c kdtree.cc -o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/u_niche_tree_kdtree.o
/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libfastlib_fastlib.h: /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libla_la.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libfx_fx.h /net/hc293/niche/fastlib/fastlib/fastlib.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libmath_math.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libfile_file.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libcol_col.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libbase_base.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libdata_data.h
	@echo '... Making bin/x86_64_Linux_COMMON_gcc_COMMON/libfastlib_fastlib.h'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON
	@touch /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libfastlib_fastlib.h
/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libmath_math.h: /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libcol_col.h /net/hc293/niche/fastlib/math/kernel.h /net/hc293/niche/fastlib/math/discrete.h /net/hc293/niche/fastlib/math/geometry.h /net/hc293/niche/fastlib/math/math.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libbase_base.h
	@echo '... Making bin/x86_64_Linux_COMMON_gcc_COMMON/libmath_math.h'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON
	@touch /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libmath_math.h
/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libdata_data.h: /net/hc293/niche/fastlib/data/crossvalidation.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libla_la.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libfile_file.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libbase_base.h /net/hc293/niche/fastlib/data/dataset.h
	@echo '... Making bin/x86_64_Linux_COMMON_gcc_COMMON/libdata_data.h'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON
	@touch /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libdata_data.h
/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libfx_fx.h: /net/hc293/niche/fastlib/fx/datastore.h /net/hc293/niche/fastlib/fx/timer.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libbase_base.h /net/hc293/niche/fastlib/fx/fx.h
	@echo '... Making bin/x86_64_Linux_COMMON_gcc_COMMON/libfx_fx.h'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON
	@touch /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libfx_fx.h
pseudo_13: /net/hc293/niche/fastlib/bin_keep/x86_64_Linux_COMMON_gcc_COMMON/libblaspack.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libcol_col.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libmath_math.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libfile_file.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libbase_base.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libfx_fx.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libla_la.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libdata_data.a
	@echo '*** Done with /net/hc293/niche/fastlib/bin_keep/x86_64_Linux_COMMON_gcc_COMMON/libblaspack.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libcol_col.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libmath_math.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libfile_file.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libbase_base.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libfx_fx.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libla_la.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libdata_data.a'
pseudo_15: /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libcol_col.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libbase_base.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libmath_math.a
	@echo '*** Done with /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libcol_col.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libbase_base.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libmath_math.a'
/net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libmath_math.a: /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/math_geometry.o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/math_discrete.o
	@echo '... Making bin/x86_64_Linux_check_gcc_/libmath_math.a'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_
	@ar r /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libmath_math.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/math_discrete.o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/math_geometry.o
/net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/math_geometry.o: /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libcol_col.h /net/hc293/niche/fastlib/math/kernel.h /net/hc293/niche/fastlib/math/discrete.h /net/hc293/niche/fastlib/math/geometry.h /net/hc293/niche/fastlib/math/geometry.cc /net/hc293/niche/fastlib/math/math.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libbase_base.h
	@echo '... Making bin/x86_64_Linux_check_gcc_/obj/math_geometry.o'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj
	@cd /net/hc293/niche/fastlib/math && g++ -Wall -Woverloaded-virtual -fno-exceptions -Wparentheses -fno-exceptions -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_ -I/net/hc293/niche/fastlib -O2 -finline-functions -finline-limit=2000 -g -DDEBUG   -c geometry.cc -o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/math_geometry.o
/net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/math_discrete.o: /net/hc293/niche/fastlib/math/discrete.cc /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libcol_col.h /net/hc293/niche/fastlib/math/kernel.h /net/hc293/niche/fastlib/math/discrete.h /net/hc293/niche/fastlib/math/geometry.h /net/hc293/niche/fastlib/math/math.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libbase_base.h
	@echo '... Making bin/x86_64_Linux_check_gcc_/obj/math_discrete.o'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj
	@cd /net/hc293/niche/fastlib/math && g++ -Wall -Woverloaded-virtual -fno-exceptions -Wparentheses -fno-exceptions -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_ -I/net/hc293/niche/fastlib -O2 -finline-functions -finline-limit=2000 -g -DDEBUG   -c discrete.cc -o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/math_discrete.o
pseudo_25: /net/hc293/niche/fastlib/bin_keep/x86_64_Linux_COMMON_gcc_COMMON/libblaspack.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libcol_col.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libfile_file.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libbase_base.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libla_la.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libdata_data.a
	@echo '*** Done with /net/hc293/niche/fastlib/bin_keep/x86_64_Linux_COMMON_gcc_COMMON/libblaspack.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libcol_col.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libfile_file.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libbase_base.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libla_la.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libdata_data.a'
/net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libdata_data.a: /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/data_dataset.o
	@echo '... Making bin/x86_64_Linux_check_gcc_/libdata_data.a'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_
	@ar r /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libdata_data.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/data_dataset.o
/net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/data_dataset.o: /net/hc293/niche/fastlib/data/dataset.cc /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libla_la.h /net/hc293/niche/fastlib/data/crossvalidation.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libfile_file.h /net/hc293/niche/fastlib/data/dataset.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libbase_base.h
	@echo '... Making bin/x86_64_Linux_check_gcc_/obj/data_dataset.o'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj
	@cd /net/hc293/niche/fastlib/data && g++ -Wall -Woverloaded-virtual -fno-exceptions -Wparentheses -fno-exceptions -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_ -I/net/hc293/niche/fastlib -O2 -finline-functions -finline-limit=2000 -g -DDEBUG   -c dataset.cc -o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/data_dataset.o
/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libla_la.h: /net/hc293/niche/fastlib/la/uselapack.h /net/hc293/niche/fastlib/la/la.h /net/hc293/niche/fastlib/la/clapack.h /net/hc293/niche/fastlib/la/blas.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libcol_col.h /net/hc293/niche/fastlib/la/matrix.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libbase_base.h
	@echo '... Making bin/x86_64_Linux_COMMON_gcc_COMMON/libla_la.h'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON
	@touch /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libla_la.h
/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libfile_file.h: /net/hc293/niche/fastlib/file/textfile.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libbase_base.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libcol_col.h
	@echo '... Making bin/x86_64_Linux_COMMON_gcc_COMMON/libfile_file.h'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON
	@touch /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libfile_file.h
pseudo_33: /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libcol_col.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libfile_file.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libbase_base.a
	@echo '*** Done with /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libcol_col.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libfile_file.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libbase_base.a'
/net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libfile_file.a: /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/file_textfile.o
	@echo '... Making bin/x86_64_Linux_check_gcc_/libfile_file.a'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_
	@ar r /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libfile_file.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/file_textfile.o
/net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/file_textfile.o: /net/hc293/niche/fastlib/file/textfile.cc /net/hc293/niche/fastlib/file/textfile.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libbase_base.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libcol_col.h
	@echo '... Making bin/x86_64_Linux_check_gcc_/obj/file_textfile.o'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj
	@cd /net/hc293/niche/fastlib/file && g++ -Wall -Woverloaded-virtual -fno-exceptions -Wparentheses -fno-exceptions -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_ -I/net/hc293/niche/fastlib -O2 -finline-functions -finline-limit=2000 -g -DDEBUG   -c textfile.cc -o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/file_textfile.o
pseudo_38: /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libbase_base.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libfx_fx.a
	@echo '*** Done with /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libbase_base.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libfx_fx.a'
/net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libfx_fx.a: /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/fx_timer.o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/fx_datastore.o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/fx_fx.o
	@echo '... Making bin/x86_64_Linux_check_gcc_/libfx_fx.a'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_
	@ar r /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libfx_fx.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/fx_datastore.o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/fx_timer.o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/fx_fx.o
/net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/fx_fx.o: /net/hc293/niche/fastlib/fx/datastore.h /net/hc293/niche/fastlib/fx/timer.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libbase_base.h /net/hc293/niche/fastlib/fx/fx.c /net/hc293/niche/fastlib/fx/fx.h
	@echo '... Making bin/x86_64_Linux_check_gcc_/obj/fx_fx.o'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj
	@cd /net/hc293/niche/fastlib/fx && gcc -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_ -I/net/hc293/niche/fastlib -O2 -finline-functions -finline-limit=2000 -g -DDEBUG   -c fx.c -o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/fx_fx.o -Wall
/net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/fx_timer.o: /net/hc293/niche/fastlib/fx/datastore.h /net/hc293/niche/fastlib/fx/timer.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libbase_base.h /net/hc293/niche/fastlib/fx/fx.h /net/hc293/niche/fastlib/fx/timer.c
	@echo '... Making bin/x86_64_Linux_check_gcc_/obj/fx_timer.o'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj
	@cd /net/hc293/niche/fastlib/fx && gcc -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_ -I/net/hc293/niche/fastlib -O2 -finline-functions -finline-limit=2000 -g -DDEBUG   -c timer.c -o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/fx_timer.o -Wall
/net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/fx_datastore.o: /net/hc293/niche/fastlib/fx/datastore.h /net/hc293/niche/fastlib/fx/timer.h /net/hc293/niche/fastlib/fx/datastore.c /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libbase_base.h /net/hc293/niche/fastlib/fx/fx.h
	@echo '... Making bin/x86_64_Linux_check_gcc_/obj/fx_datastore.o'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj
	@cd /net/hc293/niche/fastlib/fx && gcc -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_ -I/net/hc293/niche/fastlib -O2 -finline-functions -finline-limit=2000 -g -DDEBUG   -c datastore.c -o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/fx_datastore.o -Wall
pseudo_49: /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libcol_col.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libbase_base.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libla_la.a /net/hc293/niche/fastlib/bin_keep/x86_64_Linux_COMMON_gcc_COMMON/libblaspack.a
	@echo '*** Done with /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libcol_col.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libbase_base.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libla_la.a /net/hc293/niche/fastlib/bin_keep/x86_64_Linux_COMMON_gcc_COMMON/libblaspack.a'
/net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libla_la.a: /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/la_uselapack.o
	@echo '... Making bin/x86_64_Linux_check_gcc_/libla_la.a'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_
	@ar r /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libla_la.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/la_uselapack.o
/net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/la_uselapack.o: /net/hc293/niche/fastlib/la/uselapack.h /net/hc293/niche/fastlib/la/la.h /net/hc293/niche/fastlib/la/uselapack.cc /net/hc293/niche/fastlib/la/clapack.h /net/hc293/niche/fastlib/la/blas.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libcol_col.h /net/hc293/niche/fastlib/la/matrix.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libbase_base.h
	@echo '... Making bin/x86_64_Linux_check_gcc_/obj/la_uselapack.o'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj
	@cd /net/hc293/niche/fastlib/la && g++ -Wall -Woverloaded-virtual -fno-exceptions -Wparentheses -fno-exceptions -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_ -I/net/hc293/niche/fastlib -O2 -finline-functions -finline-limit=2000 -g -DDEBUG   -c uselapack.cc -o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/la_uselapack.o
/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libcol_col.h: /net/hc293/niche/fastlib/col/string.h /net/hc293/niche/fastlib/col/rangeset.h /net/hc293/niche/fastlib/col/fastalloc.h /net/hc293/niche/fastlib/col/intmap.h /net/hc293/niche/fastlib/col/arraylist.h /net/hc293/niche/fastlib/col/queue.h /net/hc293/niche/fastlib/col/heap.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libbase_base.h
	@echo '... Making bin/x86_64_Linux_COMMON_gcc_COMMON/libcol_col.h'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON
	@touch /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libcol_col.h
/net/hc293/niche/fastlib/bin_keep/x86_64_Linux_COMMON_gcc_COMMON/libblaspack.a: /net/hc293/niche/fastlib/la/blaspack.tgz
	@echo '... Making /net/hc293/niche/fastlib/bin_keep/x86_64_Linux_COMMON_gcc_COMMON/libblaspack.a'
	@mkdir -p /net/hc293/niche/fastlib/bin_keep/x86_64_Linux_COMMON_gcc_COMMON
	@echo '... Extracting FORTRAN files...'
	@mkdir -p /net/hc293/niche/fastlib/bin_keep/x86_64_Linux_COMMON_gcc_COMMON/libblaspack_workspace
	@cd /net/hc293/niche/fastlib/bin_keep/x86_64_Linux_COMMON_gcc_COMMON/libblaspack_workspace && tar -xzf /net/hc293/niche/fastlib/la/blaspack.tgz
	@echo '*** Compiling LAPACK with BLAS reference implementation.'
	@echo '!!! LAPACK WARNING: For better performance, install ATLAS or Intel MKL.'
	@echo '... Our compilation differs slightly from regular LAPACK/BLAS:'
	@echo '... NOTE 2: We omit complex-number routines (halves compile time).'
	@echo '... NOTE 3: We require case sensitivity for LAPACK/BLAS string parameters.'
	@echo '... This may take several minutes (about 800 FORTRAN files).'
	@cd /net/hc293/niche/fastlib/bin_keep/x86_64_Linux_COMMON_gcc_COMMON/libblaspack_workspace && g77 -O2 -c src/*.f
	@echo '... Almost done with LAPACK/BLAS...'
	@cd /net/hc293/niche/fastlib/bin_keep/x86_64_Linux_COMMON_gcc_COMMON/libblaspack_workspace && g77 -O0 -c src/dlamch.f src/slamch.f
	@cd /net/hc293/niche/fastlib/bin_keep/x86_64_Linux_COMMON_gcc_COMMON/libblaspack_workspace && ar r /net/hc293/niche/fastlib/bin_keep/x86_64_Linux_COMMON_gcc_COMMON/libblaspack.a *.o
	@echo '... Created archive, cleaning up.'
	@rm -rf /net/hc293/niche/fastlib/bin_keep/x86_64_Linux_COMMON_gcc_COMMON/libblaspack_workspace
	@echo '*** Done with LAPACK and BLAS!'
/net/hc293/niche/fastlib/la/blaspack.tgz: 
	@echo '... Making /net/hc293/niche/fastlib/la/blaspack.tgz'
	@echo 'Downloading the file using curl...'
	@cd /net/hc293/niche/fastlib/la && curl -L -o blaspack.tgz "http://www.cc.gatech.edu/~garryb/fastlib/blaspack.tgz"
pseudo_61: /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libcol_col.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libbase_base.a
	@echo '*** Done with /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libcol_col.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libbase_base.a'
/net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libcol_col.a: /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/col_col.o
	@echo '... Making bin/x86_64_Linux_check_gcc_/libcol_col.a'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_
	@ar r /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libcol_col.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/col_col.o
/net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/col_col.o: /net/hc293/niche/fastlib/col/string.h /net/hc293/niche/fastlib/col/rangeset.h /net/hc293/niche/fastlib/col/fastalloc.h /net/hc293/niche/fastlib/col/intmap.h /net/hc293/niche/fastlib/col/arraylist.h /net/hc293/niche/fastlib/col/col.cc /net/hc293/niche/fastlib/col/queue.h /net/hc293/niche/fastlib/col/heap.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libbase_base.h
	@echo '... Making bin/x86_64_Linux_check_gcc_/obj/col_col.o'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj
	@cd /net/hc293/niche/fastlib/col && g++ -Wall -Woverloaded-virtual -fno-exceptions -Wparentheses -fno-exceptions -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_ -I/net/hc293/niche/fastlib -O2 -finline-functions -finline-limit=2000 -g -DDEBUG   -c col.cc -o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/col_col.o
/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libbase_base.h: /net/hc293/niche/fastlib/base/otrav.h /net/hc293/niche/fastlib/base/ccmem.h /net/hc293/niche/fastlib/base/scale.h /net/hc293/niche/fastlib/base/compiler_impl.h /net/hc293/niche/fastlib/base/otrav_impl.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/base/basic_types.h /net/hc293/niche/fastlib/base/common.h /net/hc293/niche/fastlib/base/cc.h /net/hc293/niche/fastlib/base/fortran.h /net/hc293/niche/fastlib/base/debug.h /net/hc293/niche/fastlib/base/test.h /net/hc293/niche/fastlib/base/compiler.h
	@echo '... Making bin/x86_64_Linux_COMMON_gcc_COMMON/libbase_base.h'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON
	@touch /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/libbase_base.h
pseudo_73: /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libbase_base.a
	@echo '*** Done with /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libbase_base.a'
/net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libbase_base.a: /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/base_otrav.o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/base_common.o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/base_cc.o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/base_ccmem.o
	@echo '... Making bin/x86_64_Linux_check_gcc_/libbase_base.a'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_
	@ar r /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/libbase_base.a /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/base_common.o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/base_cc.o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/base_ccmem.o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/base_otrav.o
/net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/base_otrav.o: /net/hc293/niche/fastlib/base/otrav.cc /net/hc293/niche/fastlib/base/otrav.h /net/hc293/niche/fastlib/base/ccmem.h /net/hc293/niche/fastlib/base/scale.h /net/hc293/niche/fastlib/base/compiler_impl.h /net/hc293/niche/fastlib/base/otrav_impl.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/base/basic_types.h /net/hc293/niche/fastlib/base/common.h /net/hc293/niche/fastlib/base/cc.h /net/hc293/niche/fastlib/base/fortran.h /net/hc293/niche/fastlib/base/debug.h /net/hc293/niche/fastlib/base/test.h /net/hc293/niche/fastlib/base/compiler.h
	@echo '... Making bin/x86_64_Linux_check_gcc_/obj/base_otrav.o'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj
	@cd /net/hc293/niche/fastlib/base && g++ -Wall -Woverloaded-virtual -fno-exceptions -Wparentheses -fno-exceptions -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_ -I/net/hc293/niche/fastlib -O2 -finline-functions -finline-limit=2000 -g -DDEBUG   -c otrav.cc -o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/base_otrav.o
/net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/base_ccmem.o: /net/hc293/niche/fastlib/base/otrav.h /net/hc293/niche/fastlib/base/ccmem.h /net/hc293/niche/fastlib/base/scale.h /net/hc293/niche/fastlib/base/compiler_impl.h /net/hc293/niche/fastlib/base/otrav_impl.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/base/basic_types.h /net/hc293/niche/fastlib/base/common.h /net/hc293/niche/fastlib/base/cc.h /net/hc293/niche/fastlib/base/fortran.h /net/hc293/niche/fastlib/base/debug.h /net/hc293/niche/fastlib/base/ccmem.cc /net/hc293/niche/fastlib/base/test.h /net/hc293/niche/fastlib/base/compiler.h
	@echo '... Making bin/x86_64_Linux_check_gcc_/obj/base_ccmem.o'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj
	@cd /net/hc293/niche/fastlib/base && g++ -Wall -Woverloaded-virtual -fno-exceptions -Wparentheses -fno-exceptions -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_ -I/net/hc293/niche/fastlib -O2 -finline-functions -finline-limit=2000 -g -DDEBUG   -c ccmem.cc -o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/base_ccmem.o
/net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/base_cc.o: /net/hc293/niche/fastlib/base/otrav.h /net/hc293/niche/fastlib/base/ccmem.h /net/hc293/niche/fastlib/base/scale.h /net/hc293/niche/fastlib/base/cc.cc /net/hc293/niche/fastlib/base/compiler_impl.h /net/hc293/niche/fastlib/base/otrav_impl.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/base/basic_types.h /net/hc293/niche/fastlib/base/common.h /net/hc293/niche/fastlib/base/cc.h /net/hc293/niche/fastlib/base/fortran.h /net/hc293/niche/fastlib/base/debug.h /net/hc293/niche/fastlib/base/test.h /net/hc293/niche/fastlib/base/compiler.h
	@echo '... Making bin/x86_64_Linux_check_gcc_/obj/base_cc.o'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj
	@cd /net/hc293/niche/fastlib/base && g++ -Wall -Woverloaded-virtual -fno-exceptions -Wparentheses -fno-exceptions -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_ -I/net/hc293/niche/fastlib -O2 -finline-functions -finline-limit=2000 -g -DDEBUG   -c cc.cc -o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/base_cc.o
/net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/base_common.o: /net/hc293/niche/fastlib/base/otrav.h /net/hc293/niche/fastlib/base/ccmem.h /net/hc293/niche/fastlib/base/scale.h /net/hc293/niche/fastlib/base/compiler_impl.h /net/hc293/niche/fastlib/base/otrav_impl.h /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/base/basic_types.h /net/hc293/niche/fastlib/base/common.h /net/hc293/niche/fastlib/base/cc.h /net/hc293/niche/fastlib/base/fortran.h /net/hc293/niche/fastlib/base/debug.h /net/hc293/niche/fastlib/base/test.h /net/hc293/niche/fastlib/base/compiler.h /net/hc293/niche/fastlib/base/common.c
	@echo '... Making bin/x86_64_Linux_check_gcc_/obj/base_common.o'
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj
	@cd /net/hc293/niche/fastlib/base && gcc -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON -I/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_ -I/net/hc293/niche/fastlib -O2 -finline-functions -finline-limit=2000 -g -DDEBUG   -c common.c -o /net/hc293/niche/fastlib/bin/x86_64_Linux_check_gcc_/obj/base_common.o -Wall
/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/base/basic_types.h: /net/hc293/niche/fastlib/script/config.py /net/hc293/niche/fastlib/base/config/template_types.c
	@echo '... Making bin/x86_64_Linux_COMMON_gcc_COMMON/base/basic_types.h'
	@/net/hc293/niche/fastlib/script/config.py --genfiles_dir=/net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON --source_dir=/net/hc293/niche/fastlib
	@mkdir -p /net/hc293/niche/fastlib/bin/x86_64_Linux_COMMON_gcc_COMMON/base
clean:
	@echo 'Removing the bin/ directory.'
	rm -rf /net/hc293/niche/fastlib/bin/*
