function data_files=GetDataFiles()  
  root_path = GetRootPath();
  % this function retrurns the available data files
  data_files = {[root_path 'LayoutHistogram.csv'], ...
                [root_path 'LayoutHistogram-rnd.csv'],...
                [root_path 'mnist10k_test.csv'],...
                [root_path 'mnist60k_train.csv'],...
                [root_path 'synthetic_gaussians.csv']};
