# cotire.cmake 1.7.10 generated file
# /home/adarsh/gsoc/mlpack/CMake/src/mlpack/tests/mlpack_test_CXX_cotire.cmake
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_EXTENSIONS "inc;inl;ipp")
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_PATH "")
set (COTIRE_CLEAN_ALL_TARGET_NAME "clean_cotire")
set (COTIRE_CLEAN_TARGET_SUFFIX "_clean_cotire")
set (COTIRE_CMAKE_MODULE_FILE "/home/adarsh/gsoc/mlpack/CMake/cotire.cmake")
set (COTIRE_CMAKE_MODULE_VERSION "1.7.10")
set (COTIRE_DEBUG "OFF")
set (COTIRE_INTDIR "cotire")
set (COTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES "0")
set (COTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES "3")
set (COTIRE_PCH_ALL_TARGET_NAME "all_pch")
set (COTIRE_PCH_TARGET_SUFFIX "_pch")
set (COTIRE_PREFIX_HEADER_FILENAME_SUFFIX "_prefix")
set (COTIRE_TARGETS_FOLDER "cotire")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_NONE "ARMA_NO_DEBUG;NDEBUG;MLPACK_GIT_VERSION;MLPACK_SUPPRESS_FATAL")
set (COTIRE_TARGET_COMPILE_FLAGS_NONE "-Wall;-Wextra;-ftemplate-depth=1000;-Wno-unused-function;-O3;-fopenmp;-std=gnu++14")
set (COTIRE_TARGET_CONFIGURATION_TYPES "None")
set (COTIRE_TARGET_CXX_COMPILER_LAUNCHER "COTIRE_TARGET_CXX_COMPILER_LAUNCHER-NOTFOUND")
set (COTIRE_TARGET_IGNORE_PATH "/home/adarsh/gsoc/mlpack")
set (COTIRE_TARGET_INCLUDE_DIRECTORIES_NONE "/home/adarsh/gsoc/mlpack/src")
set (COTIRE_TARGET_INCLUDE_PRIORITY_PATH "")
set (COTIRE_TARGET_LANGUAGE "CXX")
set (COTIRE_TARGET_MAXIMUM_NUMBER_OF_INCLUDES "")
set (COTIRE_TARGET_POST_UNDEFS "")
set (COTIRE_TARGET_PRE_UNDEFS "")
set (COTIRE_TARGET_SOURCES "/home/adarsh/gsoc/mlpack/src/mlpack/bindings/tests/clean_memory.cpp;/home/adarsh/gsoc/mlpack/src/mlpack/bindings/tests/test_function_map.cpp;ann/activation_functions_test.cpp;ann/ann_dist_test.cpp;ann/layer_test.cpp;ann/ann_regularizer_test.cpp;ann/convolutional_network_test.cpp;ann/convolution_test.cpp;ann/feedforward_network_test.cpp;ann/init_rules_test.cpp;ann/ksinit_test.cpp;ann/loss_functions_test.cpp;ann/recurrent_network_test.cpp;ann/async_learning_test.cpp;ann/augmented_rnns_tasks_test.cpp;ann/reward_clipping_test.cpp;ann/rl_components_test.cpp;adaboost_test.cpp;akfn_test.cpp;aknn_test.cpp;armadillo_svd_test.cpp;arma_extend_test.cpp;bayesian_linear_regression_test.cpp;bias_svd_test.cpp;binarize_test.cpp;block_krylov_svd_test.cpp;callback_test.cpp;cf_test.cpp;cli_binding_test.cpp;cosine_tree_test.cpp;cv_test.cpp;dbscan_test.cpp;decision_tree_regressor_test.cpp;decision_tree_test.cpp;det_test.cpp;digamma_test.cpp;distribution_test.cpp;drusilla_select_test.cpp;emst_test.cpp;facilities_test.cpp;fastmks_test.cpp;gmm_test.cpp;hmm_test.cpp;hpt_test.cpp;hoeffding_tree_test.cpp;hyperplane_test.cpp;image_load_test.cpp;imputation_test.cpp;io_test.cpp;kde_test.cpp;kernel_pca_test.cpp;kernel_test.cpp;kernel_traits_test.cpp;kfn_test.cpp;kmeans_test.cpp;knn_test.cpp;krann_search_test.cpp;lars_test.cpp;lin_alg_test.cpp;linear_regression_test.cpp;lmnn_test.cpp;linear_svm_test.cpp;load_save_test.cpp;local_coordinate_coding_test.cpp;logistic_regression_test.cpp;log_test.cpp;lsh_test.cpp;main.cpp;math_test.cpp;matrix_completion_test.cpp;maximal_inputs_test.cpp;metric_test.cpp;mean_shift_test.cpp;nbc_test.cpp;nca_test.cpp;nmf_test.cpp;nystroem_method_test.cpp;octree_test.cpp;one_hot_encoding_test.cpp;pca_test.cpp;perceptron_test.cpp;prefixedoutstream_test.cpp;python_binding_test.cpp;qdafn_test.cpp;quic_svd_test.cpp;q_learning_test.cpp;radical_test.cpp;random_forest_test.cpp;random_test.cpp;randomized_svd_test.cpp;range_search_test.cpp;rectangle_tree_test.cpp;regularized_svd_test.cpp;scaling_test.cpp;size_checks_test.cpp;serialization.cpp;serialization_test.cpp;sfinae_test.cpp;softmax_regression_test.cpp;sort_policy_test.cpp;sparse_autoencoder_test.cpp;sparse_coding_test.cpp;spill_tree_test.cpp;split_data_test.cpp;string_encoding_test.cpp;sumtree_test.cpp;svd_batch_test.cpp;svd_incremental_test.cpp;svdplusplus_test.cpp;termination_policy_test.cpp;timer_test.cpp;tree_test.cpp;tree_traits_test.cpp;trigamma_test.cpp;ub_tree_test.cpp;union_find_test.cpp;vantage_point_tree_test.cpp;xgboost_test.cpp;main_tests/adaboost_test.cpp;main_tests/adaboost_train_test.cpp;main_tests/adaboost_classify_test.cpp;main_tests/adaboost_probabilities_test.cpp;main_tests/approx_kfn_test.cpp;main_tests/bayesian_linear_regression_test.cpp;main_tests/cf_test.cpp;main_tests/dbscan_test.cpp;main_tests/decision_tree_test.cpp;main_tests/det_test.cpp;main_tests/emst_test.cpp;main_tests/fastmks_test.cpp;main_tests/gmm_generate_test.cpp;main_tests/gmm_probability_test.cpp;main_tests/gmm_train_test.cpp;main_tests/hmm_generate_test.cpp;main_tests/hmm_loglik_test.cpp;main_tests/hmm_train_test.cpp;main_tests/hmm_viterbi_test.cpp;main_tests/hoeffding_tree_test.cpp;main_tests/image_converter_test.cpp;main_tests/kde_test.cpp;main_tests/kernel_pca_test.cpp;main_tests/kfn_test.cpp;main_tests/kmeans_test.cpp;main_tests/knn_test.cpp;main_tests/krann_test.cpp;main_tests/linear_regression_test.cpp;main_tests/linear_regression_train_test.cpp;main_tests/linear_regression_predict_test.cpp;main_tests/linear_svm_test.cpp;main_tests/lmnn_test.cpp;main_tests/local_coordinate_coding_test.cpp;main_tests/logistic_regression_test.cpp;main_tests/lsh_test.cpp;main_tests/mean_shift_test.cpp;main_tests/nbc_test.cpp;main_tests/nca_test.cpp;main_tests/nmf_test.cpp;main_tests/pca_test.cpp;main_tests/perceptron_test.cpp;main_tests/preprocess_binarize_test.cpp;main_tests/preprocess_imputer_test.cpp;main_tests/preprocess_one_hot_encode_test.cpp;main_tests/preprocess_scale_test.cpp;main_tests/preprocess_split_test.cpp;main_tests/radical_test.cpp;main_tests/random_forest_test.cpp;main_tests/range_search_test.cpp;main_tests/softmax_regression_test.cpp;main_tests/sparse_coding_test.cpp")
set (COTIRE_UNITY_BUILD_ALL_TARGET_NAME "all_unity")
set (COTIRE_UNITY_BUILD_TARGET_SUFFIX "_unity")
set (COTIRE_UNITY_OUTPUT_DIRECTORY "")
set (COTIRE_UNITY_SOURCE_EXCLUDE_EXTENSIONS "m;mm")
set (COTIRE_UNITY_SOURCE_FILENAME_SUFFIX "_unity")
set (CMAKE_GENERATOR "Unix Makefiles")
set (CMAKE_BUILD_TYPE "")
set (CMAKE_CXX_COMPILER_ID "GNU")
set (CMAKE_CXX_COMPILER_VERSION "9.4.0")
set (CMAKE_CXX_COMPILER "/usr/bin/c++")
set (CMAKE_CXX_COMPILER_ARG1 "")
set (CMAKE_INCLUDE_FLAG_CXX "-I")
set (CMAKE_INCLUDE_SYSTEM_FLAG_CXX "-isystem ")
set (CMAKE_CXX_SOURCE_FILE_EXTENSIONS "C;M;c++;cc;cpp;cxx;mm;CPP")
