function data_files=GetDataFiles()
% this function retrurns the available data files
  data_files = {'/net/hg200/dongryel/MLPACK_test_datasets/LayoutHistogram.csv', '/net/hg200/dongryel/MLPACK_test_datasets/LayoutHistogram-rnd.csv',...
      '/net/hg200/dongryel/MLPACK_test_datasets/mnist10k_test.csv', '/net/hg200/dongryel/MLPACK_test_datasets/mnist60k_train.csv',...
      '/scratch/nips2008_datasets/sj2-50000-2.csv'};
