# Makefile for dirlib ~/g/kdtree
# Created by awm on:  Sat Sep 18 04:01:32 EDT 1999

here		= kdtree

includes	= kdtree.h my_time.h timing_dyvs.h dymutil.h

sources		= kdtree.c my_time.c timing_dyvs.c dymutil.c

private_sources = 

siblings	= mrkd extra dset utils

#t:=fastdebug
include .g/Make.common

