#! /bin/sh

EXTRA_ARGS=$@


cmake \
  -D CMAKE_BUILD_TYPE:STRING=DEBUG \
  -D CMAKE_VERBOSE_MAKEFILE:BOOL=TRUE \
  -D Trilinos_ENABLE_TESTS:BOOL=OFF \
  -D Trilinos_ENABLE_DEBUG:BOOL=OFF \
  -D Trilinos_ENABLE_Anasazi:BOOL=ON \
  -D Trilinos_ENABLE_AztecOO:BOOL=ON \
  -D Trilinos_ENABLE_Epetra:BOOL=ON \
  -D Trilinos_ENABLE_Ifpack:BOOL=ON \
  -D BUILD_SHARED_LIBS:BOOL=ON \
  $EXTRA_ARGS \
  ..

# -D CMAKE_INSTALL_PREFIX:PATH=/where/ever
