#!/bin/bash

./generate --type=discrete --profile=class_neg.dis --length=100 --numseq=50 --seqfile=seq_neg.out --statefile=state_neg.out

./generate --type=discrete --profile=class_pos.dis --length=100 --numseq=50 --seqfile=seq_pos.out --statefile=state_pos.out
