if (CMAKE_CROSSCOMPILING)
  include(board/flags-config.cmake)
  if(NOT CMAKE_SYSROOT AND (NOT TOOLCHAIN_PREFIX))
    message(FATAL_ERROR "Neither of CMAKE_SYSROOT or TOOLCHAIN_PREFIX is set, please set both of them and try again")
  elseif(NOT CMAKE_SYSROOT)
    message(FATAL_ERROR "Can not proceed CMAKE_SYSROOT is not set")
  elseif(NOT TOOLCHAIN_PREFIX)
    message(FATAL_ERROR "Cant not proceed TOOLCHAIN_PREFIXN is not set")
  endif()
endif()

macro(search_openblas version)
  set(BLA_STATIC ON)
  find_package(BLAS)
  if (NOT BLAS_FOUND OR (NOT BLAS_LIBARAIES))
    get_deps(https://github.com/xianyi/OpenBLAS/releases/download/v${version}/OpenBLAS-${version}.tar.gz OpenBLAS OpenBLAS-${version}.tar.gz)
    if (NOT MSVC)
      if (NOT EXISTS "${CMAKE_BINARY_DIR}/deps/OpenBLAS-${version}/libopenblas.a")
        execute_process(COMMAND make TARGET=ARMV8 BINARY=64 HOSTCC=gcc CC=${CMAKE_C_COMPILER} FC=${CMAKE_FORTRAN_COMPILER} NO_SHARED=1
                        WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/deps/OpenBLAS-${version})
      endif()
      file(GLOB OPENBLAS_LIBARAIES "${CMAKE_BINARY_DIR}/deps/OpenBLAS-${version}/libopenblas.a")
      set(BLAS_openblas_LIBRARY ${OPENBLAS_LIBARAIES})
      set(BLA_VENDOR OpenBLAS)
    endif()
    message(STATUS "OPENBLAS LIBRARY: ${BLAS_openblas_LIBRARY}")
    message(STATUS "BLAS LIBRARY: ${BLAS_LIBRARY}")
  endif()
  find_library(GFORTRAN NAMES libgfortran.a)
  find_library(PTHREAD NAMES libpthread.a)
  set(COMPILER_SUPPORT_LIBRARIES ${COMPILER_SUPPORT_LIBRARIES} ${GFORTRAN} ${PTHREAD})
endmacro()
