filenames = cell(0);

filenames{end+1} = ...
    'p300_filtered_lambda0_correct_results_120.mat';
filenames{end+1} = ...
    'p300_filtered_lambda5Eneg9_correct_results_120.mat';
filenames{end+1} = ...
    'p300_filtered_lambda1Eneg8_correct_results_120.mat';
filenames{end+1} = ...
    'p300_filtered_lambda16034Eneg8_correct_results_120.mat';
filenames{end+1} = ...
    'p300_filtered_lambda3Eneg8_correct_results_120.mat';
filenames{end+1} = ...
    'p300_filtered_lambda5Eneg8_correct_results_120.mat';
filenames{end+1} = ...
    'p300_filtered_lambda75Eneg8_correct_results_120.mat';
filenames{end+1} = ...
    'p300_filtered_lambda1Eneg7_correct_results_120.mat';
filenames{end+1} = ...
    'p300_filtered_lambda125Eneg7_correct_results_120.mat';
filenames{end+1} = ...
    'p300_filtered_lambda15Eneg7_correct_results_120.mat';
filenames{end+1} = ...
    'p300_filtered_lambda3Eneg7_correct_results_120.mat';
filenames{end+1} = ...
    'p300_filtered_lambda45Eneg7_correct_results_120.mat';
filenames{end+1} = ...
    'p300_filtered_lambda5Eneg7_correct_results_120.mat';
filenames{end+1} = ...
    'p300_filtered_lambda1Eneg6_correct_results_120.mat';
filenames{end+1} = ...
    'p300_filtered_lambda2Eneg6_correct_results_120.mat';
filenames{end+1} = ...
    'p300_filtered_lambda3Eneg6_correct_results_120.mat';
filenames{end+1} = ...
    'p300_filtered_lambda66Eneg6_correct_results_120.mat';


CommonParams = load('p300_filtered_lambda66Eneg6_correct_results_120.mat');
t = CommonParams.t;
responses = CommonParams.responses;
mybasis = CommonParams.mybasis;
basis_inner_products = CommonParams.basis_inner_products;


rest_of_data = responses(:,5221:end);

rest_of_data_myfd = data2fd(rest_of_data, t, mybasis);

mean_result = pca_fd(rest_of_data_myfd, 0);

centered_rest_of_data_coef = ...
    getcoef(rest_of_data_myfd) - ...
    repmat(getcoef(mean_result.meanfd), ...
	   1, ...
	   size(getcoef(rest_of_data_myfd), 2));

centered_rest_of_data_myfd = fd(centered_rest_of_data_coef, mybasis);




for i = 1:length(filenames)
  fprintf('processing experiment %d\n', i);
  [lambda(i), Q(i)] = ...
      get_ICA_improvement(filenames{i}, ...
			  centered_rest_of_data_coef, ...
			  basis_inner_products);
end

%plot(lambda, diff_sum_H);