prelim_funcica;

%[h_Y1_train_set, h_Y2_train_set, h_Y_train_set, h_Y1_test_set, ...
% h_Y2_test_set, h_Y_test_set, ...
% h_P1_train_set, h_P2_train_set, h_P_train_set, h_P1_test_set, ...
% h_P2_test_set, h_P_test_set] = ...
test_smooth_funcica
%(data, t, s);
