/home/trace/cod/fastlib/u/angela/npoint/naive_test: /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/u/angela/npoint/naive_test /home/trace/cod/fastlib/u/angela/npoint/Makefile
	@echo '... Making /home/trace/cod/fastlib/u/angela/npoint/naive_test'
	@rm -f /home/trace/cod/fastlib/u/angela/npoint/naive_test
	@ln -s -f /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/u/angela/npoint/naive_test /home/trace/cod/fastlib/u/angela/npoint/naive_test
	@echo '*** Created 1 symlinks in /home/trace/cod/fastlib/u/angela/npoint/.'
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/u/angela/npoint/naive_test: /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libla/la.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libcol/col.a /home/trace/cod/fastlib/bin_keep/i686_Linux_COMMON_gcc/libblaspack.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint/metrics.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfile/file.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint/u/angela/npoint/naive_test__auto.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libdata/data.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libmath/math.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfx/fx.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint/matcher.a
	@echo '... Making bin/i686_Linux_check_gcc/u/angela/npoint/naive_test'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/u/angela/npoint
	@g++ -o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/u/angela/npoint/naive_test -O2 -finline-functions -g -DDEBUG  /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint/u/angela/npoint/naive_test__auto.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint/matcher.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint/metrics.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libmath/math.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libdata/data.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfile/file.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfx/fx.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libla/la.a /home/trace/cod/fastlib/bin_keep/i686_Linux_COMMON_gcc/libblaspack.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libcol/col.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a -lm -lpthread -lg2c
pseudo_4: /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libla/la.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libcol/col.a /home/trace/cod/fastlib/bin_keep/i686_Linux_COMMON_gcc/libblaspack.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint/metrics.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfile/file.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint/u/angela/npoint/naive_test__auto.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libdata/data.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libmath/math.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfx/fx.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint/matcher.a
	@echo '*** Done with /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libla/la.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libcol/col.a /home/trace/cod/fastlib/bin_keep/i686_Linux_COMMON_gcc/libblaspack.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint/metrics.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfile/file.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint/u/angela/npoint/naive_test__auto.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libdata/data.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libmath/math.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfx/fx.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint/matcher.a'
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint/u/angela/npoint/naive_test__auto.a: /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/u_angela_npoint_naive_test.o
	@echo '... Making bin/i686_Linux_check_gcc/libu/angela/npoint/u/angela/npoint/naive_test__auto.a'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint/u/angela/npoint
	@ar r /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint/u/angela/npoint/naive_test__auto.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/u_angela_npoint_naive_test.o
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/u_angela_npoint_naive_test.o: /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libu/angela/npoint/metrics.h /home/trace/cod/fastlib/u/angela/npoint/naive_test.cc /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libfastlib/fastlib.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libu/angela/npoint/matcher.h
	@echo '... Making bin/i686_Linux_check_gcc/obj/u_angela_npoint_naive_test.o'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj
	@cd /home/trace/cod/fastlib/u/angela/npoint && g++ -I/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc -I/home/trace/cod/fastlib -O2 -finline-functions -g -DDEBUG  -c naive_test.cc -o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/u_angela_npoint_naive_test.o -Wall -Woverloaded-virtual -fno-exceptions -Wparentheses -fno-exceptions
/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libu/angela/npoint/matcher.h: /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libu/angela/npoint/metrics.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libfastlib/fastlib.h /home/trace/cod/fastlib/u/angela/npoint/matcher.h
	@echo '... Making bin/i686_Linux_COMMON_gcc/libu/angela/npoint/matcher.h'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libu/angela/npoint
	@touch /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libu/angela/npoint/matcher.h
pseudo_9: /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libla/la.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libcol/col.a /home/trace/cod/fastlib/bin_keep/i686_Linux_COMMON_gcc/libblaspack.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint/metrics.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfile/file.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libdata/data.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libmath/math.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfx/fx.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint/matcher.a
	@echo '*** Done with /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libla/la.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libcol/col.a /home/trace/cod/fastlib/bin_keep/i686_Linux_COMMON_gcc/libblaspack.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint/metrics.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfile/file.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libdata/data.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libmath/math.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfx/fx.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint/matcher.a'
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint/matcher.a: /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/u_angela_npoint_matcher.o
	@echo '... Making bin/i686_Linux_check_gcc/libu/angela/npoint/matcher.a'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint
	@ar r /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint/matcher.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/u_angela_npoint_matcher.o
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/u_angela_npoint_matcher.o: /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libu/angela/npoint/metrics.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libfastlib/fastlib.h /home/trace/cod/fastlib/u/angela/npoint/matcher.cc /home/trace/cod/fastlib/u/angela/npoint/matcher.h
	@echo '... Making bin/i686_Linux_check_gcc/obj/u_angela_npoint_matcher.o'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj
	@cd /home/trace/cod/fastlib/u/angela/npoint && g++ -I/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc -I/home/trace/cod/fastlib -O2 -finline-functions -g -DDEBUG  -c matcher.cc -o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/u_angela_npoint_matcher.o -Wall -Woverloaded-virtual -fno-exceptions -Wparentheses -fno-exceptions
/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libu/angela/npoint/metrics.h: /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libfastlib/fastlib.h /home/trace/cod/fastlib/u/angela/npoint/metrics.h
	@echo '... Making bin/i686_Linux_COMMON_gcc/libu/angela/npoint/metrics.h'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libu/angela/npoint
	@touch /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libu/angela/npoint/metrics.h
pseudo_15: /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libla/la.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libcol/col.a /home/trace/cod/fastlib/bin_keep/i686_Linux_COMMON_gcc/libblaspack.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint/metrics.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfile/file.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libdata/data.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libmath/math.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfx/fx.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a
	@echo '*** Done with /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libla/la.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libcol/col.a /home/trace/cod/fastlib/bin_keep/i686_Linux_COMMON_gcc/libblaspack.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint/metrics.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfile/file.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libdata/data.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libmath/math.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfx/fx.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a'
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint/metrics.a: /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/u_angela_npoint_metrics.o
	@echo '... Making bin/i686_Linux_check_gcc/libu/angela/npoint/metrics.a'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint
	@ar r /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libu/angela/npoint/metrics.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/u_angela_npoint_metrics.o
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/u_angela_npoint_metrics.o: /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libfastlib/fastlib.h /home/trace/cod/fastlib/u/angela/npoint/metrics.cc /home/trace/cod/fastlib/u/angela/npoint/metrics.h
	@echo '... Making bin/i686_Linux_check_gcc/obj/u_angela_npoint_metrics.o'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj
	@cd /home/trace/cod/fastlib/u/angela/npoint && g++ -I/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc -I/home/trace/cod/fastlib -O2 -finline-functions -g -DDEBUG  -c metrics.cc -o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/u_angela_npoint_metrics.o -Wall -Woverloaded-virtual -fno-exceptions -Wparentheses -fno-exceptions
/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libfastlib/fastlib.h: /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libfx/fx.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libmath/math.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libcol/col.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libla/la.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libdata/data.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libfile/file.h /home/trace/cod/fastlib/fastlib/fastlib.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libbase/base.h
	@echo '... Making bin/i686_Linux_COMMON_gcc/libfastlib/fastlib.h'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libfastlib
	@touch /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libfastlib/fastlib.h
/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libmath/math.h: /home/trace/cod/fastlib/math/discrete.h /home/trace/cod/fastlib/math/math.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libcol/col.h /home/trace/cod/fastlib/math/geometry.h /home/trace/cod/fastlib/math/kernel.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libbase/base.h
	@echo '... Making bin/i686_Linux_COMMON_gcc/libmath/math.h'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libmath
	@touch /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libmath/math.h
/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libdata/data.h: /home/trace/cod/fastlib/data/crossvalidation.h /home/trace/cod/fastlib/data/dataset.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libbase/base.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libla/la.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libfile/file.h
	@echo '... Making bin/i686_Linux_COMMON_gcc/libdata/data.h'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libdata
	@touch /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libdata/data.h
/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libfx/fx.h: /home/trace/cod/fastlib/fx/datastore.h /home/trace/cod/fastlib/fx/timer.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libbase/base.h /home/trace/cod/fastlib/fx/fx.h
	@echo '... Making bin/i686_Linux_COMMON_gcc/libfx/fx.h'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libfx
	@touch /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libfx/fx.h
pseudo_25: /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libla/la.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libcol/col.a /home/trace/cod/fastlib/bin_keep/i686_Linux_COMMON_gcc/libblaspack.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfile/file.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libdata/data.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libmath/math.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfx/fx.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a
	@echo '*** Done with /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libla/la.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libcol/col.a /home/trace/cod/fastlib/bin_keep/i686_Linux_COMMON_gcc/libblaspack.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfile/file.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libdata/data.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libmath/math.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfx/fx.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a'
pseudo_27: /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libmath/math.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libcol/col.a
	@echo '*** Done with /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libmath/math.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libcol/col.a'
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libmath/math.a: /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/math_geometry.o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/math_discrete.o
	@echo '... Making bin/i686_Linux_check_gcc/libmath/math.a'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libmath
	@ar r /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libmath/math.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/math_discrete.o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/math_geometry.o
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/math_geometry.o: /home/trace/cod/fastlib/math/discrete.h /home/trace/cod/fastlib/math/math.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libcol/col.h /home/trace/cod/fastlib/math/geometry.h /home/trace/cod/fastlib/math/kernel.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libbase/base.h /home/trace/cod/fastlib/math/geometry.cc
	@echo '... Making bin/i686_Linux_check_gcc/obj/math_geometry.o'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj
	@cd /home/trace/cod/fastlib/math && g++ -I/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc -I/home/trace/cod/fastlib -O2 -finline-functions -g -DDEBUG  -c geometry.cc -o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/math_geometry.o -Wall -Woverloaded-virtual -fno-exceptions -Wparentheses -fno-exceptions
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/math_discrete.o: /home/trace/cod/fastlib/math/discrete.cc /home/trace/cod/fastlib/math/discrete.h /home/trace/cod/fastlib/math/math.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libcol/col.h /home/trace/cod/fastlib/math/geometry.h /home/trace/cod/fastlib/math/kernel.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libbase/base.h
	@echo '... Making bin/i686_Linux_check_gcc/obj/math_discrete.o'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj
	@cd /home/trace/cod/fastlib/math && g++ -I/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc -I/home/trace/cod/fastlib -O2 -finline-functions -g -DDEBUG  -c discrete.cc -o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/math_discrete.o -Wall -Woverloaded-virtual -fno-exceptions -Wparentheses -fno-exceptions
pseudo_37: /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libla/la.a /home/trace/cod/fastlib/bin_keep/i686_Linux_COMMON_gcc/libblaspack.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfile/file.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libdata/data.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libcol/col.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a
	@echo '*** Done with /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libla/la.a /home/trace/cod/fastlib/bin_keep/i686_Linux_COMMON_gcc/libblaspack.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfile/file.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libdata/data.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libcol/col.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a'
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libdata/data.a: /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/data_dataset.o
	@echo '... Making bin/i686_Linux_check_gcc/libdata/data.a'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libdata
	@ar r /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libdata/data.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/data_dataset.o
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/data_dataset.o: /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libfile/file.h /home/trace/cod/fastlib/data/crossvalidation.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libbase/base.h /home/trace/cod/fastlib/data/dataset.cc /home/trace/cod/fastlib/data/dataset.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libla/la.h
	@echo '... Making bin/i686_Linux_check_gcc/obj/data_dataset.o'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj
	@cd /home/trace/cod/fastlib/data && g++ -I/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc -I/home/trace/cod/fastlib -O2 -finline-functions -g -DDEBUG  -c dataset.cc -o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/data_dataset.o -Wall -Woverloaded-virtual -fno-exceptions -Wparentheses -fno-exceptions
/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libla/la.h: /home/trace/cod/fastlib/la/blas.h /home/trace/cod/fastlib/la/clapack.h /home/trace/cod/fastlib/la/uselapack.h /home/trace/cod/fastlib/la/la.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libbase/base.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libcol/col.h /home/trace/cod/fastlib/la/matrix.h
	@echo '... Making bin/i686_Linux_COMMON_gcc/libla/la.h'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libla
	@touch /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libla/la.h
/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libfile/file.h: /home/trace/cod/fastlib/file/serialize.h /home/trace/cod/fastlib/file/textfile.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libbase/base.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libcol/col.h
	@echo '... Making bin/i686_Linux_COMMON_gcc/libfile/file.h'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libfile
	@touch /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libfile/file.h
pseudo_45: /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfile/file.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libcol/col.a
	@echo '*** Done with /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfile/file.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libcol/col.a'
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfile/file.a: /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/file_textfile.o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/file_serialize.o
	@echo '... Making bin/i686_Linux_check_gcc/libfile/file.a'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfile
	@ar r /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfile/file.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/file_textfile.o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/file_serialize.o
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/file_serialize.o: /home/trace/cod/fastlib/file/serialize.h /home/trace/cod/fastlib/file/textfile.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libbase/base.h /home/trace/cod/fastlib/file/serialize.cc /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libcol/col.h
	@echo '... Making bin/i686_Linux_check_gcc/obj/file_serialize.o'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj
	@cd /home/trace/cod/fastlib/file && g++ -I/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc -I/home/trace/cod/fastlib -O2 -finline-functions -g -DDEBUG  -c serialize.cc -o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/file_serialize.o -Wall -Woverloaded-virtual -fno-exceptions -Wparentheses -fno-exceptions
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/file_textfile.o: /home/trace/cod/fastlib/file/serialize.h /home/trace/cod/fastlib/file/textfile.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libbase/base.h /home/trace/cod/fastlib/file/textfile.cc /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libcol/col.h
	@echo '... Making bin/i686_Linux_check_gcc/obj/file_textfile.o'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj
	@cd /home/trace/cod/fastlib/file && g++ -I/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc -I/home/trace/cod/fastlib -O2 -finline-functions -g -DDEBUG  -c textfile.cc -o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/file_textfile.o -Wall -Woverloaded-virtual -fno-exceptions -Wparentheses -fno-exceptions
pseudo_53: /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfx/fx.a
	@echo '*** Done with /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfx/fx.a'
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfx/fx.a: /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/fx_fx.o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/fx_timer.o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/fx_datastore.o
	@echo '... Making bin/i686_Linux_check_gcc/libfx/fx.a'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfx
	@ar r /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libfx/fx.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/fx_datastore.o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/fx_timer.o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/fx_fx.o
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/fx_fx.o: /home/trace/cod/fastlib/fx/datastore.h /home/trace/cod/fastlib/fx/timer.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libbase/base.h /home/trace/cod/fastlib/fx/fx.h /home/trace/cod/fastlib/fx/fx.c
	@echo '... Making bin/i686_Linux_check_gcc/obj/fx_fx.o'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj
	@cd /home/trace/cod/fastlib/fx && gcc -I/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc -I/home/trace/cod/fastlib -O2 -finline-functions -g -DDEBUG  -c fx.c -o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/fx_fx.o -Wall
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/fx_timer.o: /home/trace/cod/fastlib/fx/datastore.h /home/trace/cod/fastlib/fx/timer.h /home/trace/cod/fastlib/fx/timer.c /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libbase/base.h /home/trace/cod/fastlib/fx/fx.h
	@echo '... Making bin/i686_Linux_check_gcc/obj/fx_timer.o'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj
	@cd /home/trace/cod/fastlib/fx && gcc -I/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc -I/home/trace/cod/fastlib -O2 -finline-functions -g -DDEBUG  -c timer.c -o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/fx_timer.o -Wall
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/fx_datastore.o: /home/trace/cod/fastlib/fx/datastore.h /home/trace/cod/fastlib/fx/timer.h /home/trace/cod/fastlib/fx/datastore.c /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libbase/base.h /home/trace/cod/fastlib/fx/fx.h
	@echo '... Making bin/i686_Linux_check_gcc/obj/fx_datastore.o'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj
	@cd /home/trace/cod/fastlib/fx && gcc -I/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc -I/home/trace/cod/fastlib -O2 -finline-functions -g -DDEBUG  -c datastore.c -o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/fx_datastore.o -Wall
pseudo_64: /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libla/la.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a /home/trace/cod/fastlib/bin_keep/i686_Linux_COMMON_gcc/libblaspack.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libcol/col.a
	@echo '*** Done with /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libla/la.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a /home/trace/cod/fastlib/bin_keep/i686_Linux_COMMON_gcc/libblaspack.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libcol/col.a'
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libla/la.a: /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/la_uselapack.o
	@echo '... Making bin/i686_Linux_check_gcc/libla/la.a'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libla
	@ar r /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libla/la.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/la_uselapack.o
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/la_uselapack.o: /home/trace/cod/fastlib/la/uselapack.cc /home/trace/cod/fastlib/la/blas.h /home/trace/cod/fastlib/la/clapack.h /home/trace/cod/fastlib/la/uselapack.h /home/trace/cod/fastlib/la/la.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libbase/base.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libcol/col.h /home/trace/cod/fastlib/la/matrix.h
	@echo '... Making bin/i686_Linux_check_gcc/obj/la_uselapack.o'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj
	@cd /home/trace/cod/fastlib/la && g++ -I/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc -I/home/trace/cod/fastlib -O2 -finline-functions -g -DDEBUG  -c uselapack.cc -o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/la_uselapack.o -Wall -Woverloaded-virtual -fno-exceptions -Wparentheses -fno-exceptions
/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libcol/col.h: /home/trace/cod/fastlib/col/string.h /home/trace/cod/fastlib/col/arraylist.h /home/trace/cod/fastlib/col/fastalloc.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libbase/base.h /home/trace/cod/fastlib/col/heap.h
	@echo '... Making bin/i686_Linux_COMMON_gcc/libcol/col.h'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libcol
	@touch /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libcol/col.h
/home/trace/cod/fastlib/bin_keep/i686_Linux_COMMON_gcc/libblaspack.a: /home/trace/cod/fastlib/la/blaspack.tgz
	@echo '... Making /home/trace/cod/fastlib/bin_keep/i686_Linux_COMMON_gcc/libblaspack.a'
	@mkdir -p /home/trace/cod/fastlib/bin_keep/i686_Linux_COMMON_gcc
	@echo '... Extracting FORTRAN files...'
	@mkdir -p /home/trace/cod/fastlib/bin_keep/i686_Linux_COMMON_gcc/libblaspack_workspace
	@cd /home/trace/cod/fastlib/bin_keep/i686_Linux_COMMON_gcc/libblaspack_workspace && tar -xzf /home/trace/cod/fastlib/la/blaspack.tgz
	@echo '*** Compiling LAPACK with BLAS reference implementation.'
	@echo '... Our compilation differs slightly from regular LAPACK/BLAS:'
	@echo '... NOTE 1: We omit complex-number routines (halves compile time).'
	@echo '... NOTE 2: We require case sensitivity for LAPACK/BLAS string parameters.'
	@echo '... This may take several minutes (about 800 FORTRAN files).'
	@cd /home/trace/cod/fastlib/bin_keep/i686_Linux_COMMON_gcc/libblaspack_workspace && g77 -O2 -c src/*.f
	@echo '... Almost done with LAPACK/BLAS...'
	@cd /home/trace/cod/fastlib/bin_keep/i686_Linux_COMMON_gcc/libblaspack_workspace && g77 -O0 -c src/dlamch.f src/slamch.f
	@cd /home/trace/cod/fastlib/bin_keep/i686_Linux_COMMON_gcc/libblaspack_workspace && ar r /home/trace/cod/fastlib/bin_keep/i686_Linux_COMMON_gcc/libblaspack.a *.o
	@echo '... Created archive, cleaning up.'
	@rm -rf /home/trace/cod/fastlib/bin_keep/i686_Linux_COMMON_gcc/libblaspack_workspace
	@echo '*** Done with LAPACK and BLAS!'
/home/trace/cod/fastlib/la/blaspack.tgz: 
	@echo '... Making /home/trace/cod/fastlib/la/blaspack.tgz'
	@echo 'Downloading the file using curl...'
	@cd /home/trace/cod/fastlib/la && curl -L -o blaspack.tgz "http://www.cc.gatech.edu/~garryb/fastlib/blaspack.tgz"
pseudo_76: /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libcol/col.a
	@echo '*** Done with /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libcol/col.a'
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libcol/col.a: /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/col_col.o
	@echo '... Making bin/i686_Linux_check_gcc/libcol/col.a'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libcol
	@ar r /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libcol/col.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/col_col.o
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/col_col.o: /home/trace/cod/fastlib/col/string.h /home/trace/cod/fastlib/col/fastalloc.h /home/trace/cod/fastlib/col/heap.h /home/trace/cod/fastlib/col/arraylist.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libbase/base.h /home/trace/cod/fastlib/col/col.cc
	@echo '... Making bin/i686_Linux_check_gcc/obj/col_col.o'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj
	@cd /home/trace/cod/fastlib/col && g++ -I/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc -I/home/trace/cod/fastlib -O2 -finline-functions -g -DDEBUG  -c col.cc -o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/col_col.o -Wall -Woverloaded-virtual -fno-exceptions -Wparentheses -fno-exceptions
/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libbase/base.h: /home/trace/cod/fastlib/base/test.h /home/trace/cod/fastlib/base/ccmem.h /home/trace/cod/fastlib/base/fortran.h /home/trace/cod/fastlib/base/scale.h /home/trace/cod/fastlib/base/otrav.h /home/trace/cod/fastlib/base/compiler.h /home/trace/cod/fastlib/base/debug.h /home/trace/cod/fastlib/base/compiler_impl.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/base/basic_types.h /home/trace/cod/fastlib/base/common.h /home/trace/cod/fastlib/base/cc.h
	@echo '... Making bin/i686_Linux_COMMON_gcc/libbase/base.h'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libbase
	@touch /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/libbase/base.h
pseudo_85: /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a
	@echo '*** Done with /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a'
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a: /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/base_ccmem.o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/base_common.o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/base_cc.o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/base_otrav.o
	@echo '... Making bin/i686_Linux_check_gcc/libbase/base.a'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase
	@ar r /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/libbase/base.a /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/base_common.o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/base_cc.o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/base_ccmem.o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/base_otrav.o
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/base_otrav.o: /home/trace/cod/fastlib/base/test.h /home/trace/cod/fastlib/base/ccmem.h /home/trace/cod/fastlib/base/fortran.h /home/trace/cod/fastlib/base/scale.h /home/trace/cod/fastlib/base/otrav.h /home/trace/cod/fastlib/base/compiler.h /home/trace/cod/fastlib/base/debug.h /home/trace/cod/fastlib/base/otrav.cc /home/trace/cod/fastlib/base/compiler_impl.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/base/basic_types.h /home/trace/cod/fastlib/base/common.h /home/trace/cod/fastlib/base/cc.h
	@echo '... Making bin/i686_Linux_check_gcc/obj/base_otrav.o'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj
	@cd /home/trace/cod/fastlib/base && g++ -I/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc -I/home/trace/cod/fastlib -O2 -finline-functions -g -DDEBUG  -c otrav.cc -o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/base_otrav.o -Wall -Woverloaded-virtual -fno-exceptions -Wparentheses -fno-exceptions
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/base_ccmem.o: /home/trace/cod/fastlib/base/test.h /home/trace/cod/fastlib/base/ccmem.h /home/trace/cod/fastlib/base/fortran.h /home/trace/cod/fastlib/base/scale.h /home/trace/cod/fastlib/base/otrav.h /home/trace/cod/fastlib/base/compiler.h /home/trace/cod/fastlib/base/debug.h /home/trace/cod/fastlib/base/ccmem.cc /home/trace/cod/fastlib/base/compiler_impl.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/base/basic_types.h /home/trace/cod/fastlib/base/common.h /home/trace/cod/fastlib/base/cc.h
	@echo '... Making bin/i686_Linux_check_gcc/obj/base_ccmem.o'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj
	@cd /home/trace/cod/fastlib/base && g++ -I/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc -I/home/trace/cod/fastlib -O2 -finline-functions -g -DDEBUG  -c ccmem.cc -o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/base_ccmem.o -Wall -Woverloaded-virtual -fno-exceptions -Wparentheses -fno-exceptions
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/base_cc.o: /home/trace/cod/fastlib/base/test.h /home/trace/cod/fastlib/base/ccmem.h /home/trace/cod/fastlib/base/fortran.h /home/trace/cod/fastlib/base/scale.h /home/trace/cod/fastlib/base/otrav.h /home/trace/cod/fastlib/base/compiler.h /home/trace/cod/fastlib/base/cc.cc /home/trace/cod/fastlib/base/debug.h /home/trace/cod/fastlib/base/compiler_impl.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/base/basic_types.h /home/trace/cod/fastlib/base/common.h /home/trace/cod/fastlib/base/cc.h
	@echo '... Making bin/i686_Linux_check_gcc/obj/base_cc.o'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj
	@cd /home/trace/cod/fastlib/base && g++ -I/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc -I/home/trace/cod/fastlib -O2 -finline-functions -g -DDEBUG  -c cc.cc -o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/base_cc.o -Wall -Woverloaded-virtual -fno-exceptions -Wparentheses -fno-exceptions
/home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/base_common.o: /home/trace/cod/fastlib/base/test.h /home/trace/cod/fastlib/base/ccmem.h /home/trace/cod/fastlib/base/fortran.h /home/trace/cod/fastlib/base/scale.h /home/trace/cod/fastlib/base/otrav.h /home/trace/cod/fastlib/base/compiler.h /home/trace/cod/fastlib/base/common.c /home/trace/cod/fastlib/base/debug.h /home/trace/cod/fastlib/base/compiler_impl.h /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/base/basic_types.h /home/trace/cod/fastlib/base/common.h /home/trace/cod/fastlib/base/cc.h
	@echo '... Making bin/i686_Linux_check_gcc/obj/base_common.o'
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj
	@cd /home/trace/cod/fastlib/base && gcc -I/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc -I/home/trace/cod/fastlib -O2 -finline-functions -g -DDEBUG  -c common.c -o /home/trace/cod/fastlib/bin/i686_Linux_check_gcc/obj/base_common.o -Wall
/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/base/basic_types.h: /home/trace/cod/fastlib/script/config.py /home/trace/cod/fastlib/base/config/template_types.c
	@echo '... Making bin/i686_Linux_COMMON_gcc/base/basic_types.h'
	@/home/trace/cod/fastlib/script/config.py --genfiles_dir=/home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc --source_dir=/home/trace/cod/fastlib
	@mkdir -p /home/trace/cod/fastlib/bin/i686_Linux_COMMON_gcc/base
clean:
	@echo 'Removing the bin/ directory.'
	rm -rf /home/trace/cod/fastlib/bin/*
