.TH "/home/aakash/mlpack/src/mlpack/methods/ann/dists Directory Reference" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/aakash/mlpack/src/mlpack/methods/ann/dists Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbernoulli_distribution\&.hpp\fP"
.br
.ti -1c
.RI "file \fBnormal_distribution\&.hpp\fP"
.br
.in -1c
