.TH "/home/aakash/mlpack/src/mlpack/core/cereal Directory Reference" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/aakash/mlpack/src/mlpack/core/cereal Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBarray_wrapper\&.hpp\fP"
.br
.ti -1c
.RI "file \fBis_loading\&.hpp\fP"
.br
.ti -1c
.RI "file \fBis_saving\&.hpp\fP"
.br
.ti -1c
.RI "file \fBpair_associative_container\&.hpp\fP"
.br
.RI "This file is backported from cereal 1\&.3 to support the serialization of objects of type associative containers (std::map, std::pair, etc\&.) "
.ti -1c
.RI "file \fBpointer_variant_wrapper\&.hpp\fP"
.br
.ti -1c
.RI "file \fBpointer_vector_variant_wrapper\&.hpp\fP"
.br
.ti -1c
.RI "file \fBpointer_vector_wrapper\&.hpp\fP"
.br
.ti -1c
.RI "file \fBpointer_wrapper\&.hpp\fP"
.br
.ti -1c
.RI "file \fBunordered_map\&.hpp\fP"
.br
.RI "This file is backported from cereal 1\&.3 to support the serialization of objects of type associative containers (std::map, std::pair, etc\&.) "
.in -1c
