.TH "/home/aakash/mlpack/src/mlpack/methods/det Directory Reference" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/aakash/mlpack/src/mlpack/methods/det Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdt_utils\&.hpp\fP"
.br
.ti -1c
.RI "file \fBdtree\&.hpp\fP"
.br
.in -1c
