.TH "/home/aakash/mlpack/src/mlpack/core/cv/metrics Directory Reference" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/aakash/mlpack/src/mlpack/core/cv/metrics Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaccuracy\&.hpp\fP"
.br
.ti -1c
.RI "file \fBaverage_strategy\&.hpp\fP"
.br
.ti -1c
.RI "file \fBf1\&.hpp\fP"
.br
.ti -1c
.RI "file \fBfacilities\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmse\&.hpp\fP"
.br
.ti -1c
.RI "file \fBprecision\&.hpp\fP"
.br
.ti -1c
.RI "file \fBr2_score\&.hpp\fP"
.br
.ti -1c
.RI "file \fBrecall\&.hpp\fP"
.br
.ti -1c
.RI "file \fBsilhouette_score\&.hpp\fP"
.br
.in -1c
