.TH "/home/aakash/mlpack/src/mlpack/methods/ann/loss_functions/binary_cross_entropy_loss.hpp" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/aakash/mlpack/src/mlpack/methods/ann/loss_functions/binary_cross_entropy_loss.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBCELoss< InputDataType, OutputDataType >\fP"
.br
.RI "The binary-cross-entropy performance function measures the Binary Cross Entropy between the target and the output\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmlpack\fP"
.br
.RI "Linear algebra utility functions, generally performed on matrices or vectors\&. "
.ti -1c
.RI " \fBmlpack::ann\fP"
.br
.RI "Artificial Neural Network\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "template<typename InputDataType  = arma::mat, typename OutputDataType  = arma::mat> using \fBCrossEntropyError\fP = BCELoss< InputDataType, OutputDataType >"
.br
.RI "Adding alias of \fBBCELoss\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
