.TH "/home/aakash/mlpack/src/mlpack/core.hpp" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/aakash/mlpack/src/mlpack/core.hpp \- Include all of the base components required to write mlpack methods, and the main mlpack Doxygen documentation\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Include all of the base components required to write mlpack methods, and the main mlpack Doxygen documentation\&. 

mlpack is free software; you may redistribute it and/or modify it under the terms of the 3-clause BSD license\&. You should have received a copy of the 3-clause BSD license along with mlpack\&. If not, see http://www.opensource.org/licenses/BSD-3-Clause for more information\&. 
.PP
Definition in file \fBcore\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
