.TH "/home/aakash/mlpack/src/mlpack/bindings/markdown/get_printable_param_name.hpp" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/aakash/mlpack/src/mlpack/bindings/markdown/get_printable_param_name.hpp
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmlpack\fP"
.br
.RI "Linear algebra utility functions, generally performed on matrices or vectors\&. "
.ti -1c
.RI " \fBmlpack::bindings\fP"
.br
.ti -1c
.RI " \fBmlpack::bindings::markdown\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > void \fBGetPrintableParamName\fP (util::ParamData &d, const void *, void *output)"
.br
.RI "Get the parameter's name as seen by the user\&. "
.ti -1c
.RI "template<typename T > std::string \fBGetPrintableParamName\fP (util::ParamData &data, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::disable_if< data::HasSerialize< T >>::type *=0, const typename boost::disable_if< std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>>::type *=0)"
.br
.RI "Get the parameter name for a type that has no special handling\&. "
.ti -1c
.RI "template<typename T > std::string \fBGetPrintableParamName\fP (util::ParamData &data, const typename boost::disable_if< arma::is_arma_type< T >>::type *=0, const typename boost::enable_if< data::HasSerialize< T >>::type *=0)"
.br
.RI "Get the parameter name for a serializable model type (where the user has to pass the file that holds the matrix)\&. "
.ti -1c
.RI "template<typename T > std::string \fBGetPrintableParamName\fP (util::ParamData &data, const typename boost::enable_if< arma::is_arma_type< T >>::type *=0)"
.br
.RI "Get the parameter name for a matrix type (where the user has to pass the file that holds the matrix)\&. "
.ti -1c
.RI "template<typename T > std::string \fBGetPrintableParamName\fP (util::ParamData &data, const typename boost::enable_if< std::is_same< T, std::tuple< data::DatasetInfo, arma::mat >>>::type *=0)"
.br
.RI "Get the parameter name for a mapped matrix type (where the user has to pass the file that holds the matrix)\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Ryan Curtin
.RE
.PP
Return the parameter name that the user would specify on the command line, with different behavior for different parameter types\&.
.PP
mlpack is free software; you may redistribute it and/or modify it under the terms of the 3-clause BSD license\&. You should have received a copy of the 3-clause BSD license along with mlpack\&. If not, see http://www.opensource.org/licenses/BSD-3-Clause for more information\&. 
.PP
Definition in file \fBget_printable_param_name\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
