.TH "/home/aakash/mlpack/src/mlpack/tests/main_tests/hmm_test_utils.hpp" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/aakash/mlpack/src/mlpack/tests/main_tests/hmm_test_utils.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBInitHMMModel\fP"
.br
.ti -1c
.RI "struct \fBTrainHMMModel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Daivik Nema
.RE
.PP
Structs for initializing and training HMMs (either of Discrete, Gaussian, GMM, or Diagonal GMM HMMs)\&. These structs are passed as template parameters to the PerformAction function of an HMMModel object\&. These structs have been adapted from the structs in mlpack/methods/hmm/hmm_train_main\&.cpp\&.
.PP
mlpack is free software; you may redistribute it and/or modify it under the terms of the 3-clause BSD license\&. You should have received a copy of the 3-clause BSD license along with mlpack\&. If not, see http://www.opensource.org/licenses/BSD-3-Clause for more information\&. 
.PP
Definition in file \fBhmm_test_utils\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
