.TH "/home/aakash/mlpack/src/mlpack/methods/kde/kde.hpp" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/aakash/mlpack/src/mlpack/methods/kde/kde.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBKDE< KernelType, MetricType, MatType, TreeType, DualTreeTraversalType, SingleTreeTraversalType >\fP"
.br
.RI "The \fBKDE\fP class is a template class for performing Kernel Density Estimations\&. "
.ti -1c
.RI "struct \fBKDEDefaultParams\fP"
.br
.RI "\fBKDEDefaultParams\fP contains the default input parameter values for \fBKDE\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmlpack\fP"
.br
.RI "Linear algebra utility functions, generally performed on matrices or vectors\&. "
.ti -1c
.RI " \fBmlpack::kde\fP"
.br
.RI "Kernel Density Estimation\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBKDEMode\fP { \fBDUAL_TREE_MODE\fP, \fBSINGLE_TREE_MODE\fP }
.RI "KDEMode represents the ways in which KDE algorithm can be executed\&. ""
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Roberto Hueso
.RE
.PP
Kernel Density Estimation\&.
.PP
mlpack is free software; you may redistribute it and/or modify it under the terms of the 3-clause BSD license\&. You should have received a copy of the 3-clause BSD license along with mlpack\&. If not, see http://www.opensource.org/licenses/BSD-3-Clause for more information\&. 
.PP
Definition in file \fBkde\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
