.TH "/home/aakash/mlpack/src/mlpack/methods/kde/kde_model.hpp" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/aakash/mlpack/src/mlpack/methods/kde/kde_model.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBKDEModel\fP"
.br
.RI "The \fBKDEModel\fP provides an abstraction for the \fBKDE\fP class, abstracting away the KernelType and TreeType parameters and allowing those to be specified at runtime\&. "
.ti -1c
.RI "class \fBKDEWrapper< KernelType, TreeType >\fP"
.br
.RI "\fBKDEWrapper\fP is a wrapper class for all \fBKDE\fP types supported by \fBKDEModel\fP\&. "
.ti -1c
.RI "class \fBKDEWrapperBase\fP"
.br
.RI "\fBKDEWrapperBase\fP is a base wrapper class for holding all \fBKDE\fP types supported by \fBKDEModel\fP\&. "
.ti -1c
.RI "class \fBKernelNormalizer\fP"
.br
.RI "\fBKernelNormalizer\fP holds a set of methods to normalize estimations applying in each case the appropiate kernel normalizer function\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmlpack\fP"
.br
.RI "Linear algebra utility functions, generally performed on matrices or vectors\&. "
.ti -1c
.RI " \fBmlpack::kde\fP"
.br
.RI "Kernel Density Estimation\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Roberto Hueso
.RE
.PP
Model for KDE\&. It abstracts different types of tree, kernels, etc\&.
.PP
mlpack is free software; you may redistribute it and/or modify it under the terms of the 3-clause BSD license\&. You should have received a copy of the 3-clause BSD license along with mlpack\&. If not, see http://www.opensource.org/licenses/BSD-3-Clause for more information\&. 
.PP
Definition in file \fBkde_model\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
