.TH "LayerNameVisitor" 3 "Sun Aug 22 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayerNameVisitor \- Implementation of a class that returns the string representation of the name of the given layer\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits static_visitor< std::string >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLayerNameVisitor\fP ()"
.br
.RI "Create the \fBLayerNameVisitor\fP object\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBAdaptiveMaxPooling\fP<> *) const"
.br
.RI "Return the name of the given layer of type AdaptiveMaxPooling as string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBAdaptiveMeanPooling\fP<> *) const"
.br
.RI "Return the name of the given layer of type AdaptiveMeanPooling as string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBAtrousConvolution\fP<> *) const"
.br
.RI "Return the name of the given layer of type AtrousConvolution as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBAlphaDropout\fP<> *) const"
.br
.RI "Return the name of the given layer of type AlphaDropout as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBBatchNorm\fP<> *) const"
.br
.RI "Return the name of the given layer of type BatchNorm as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBConstant\fP<> *) const"
.br
.RI "Return the name of the given layer of type Constant as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBConvolution\fP<> *) const"
.br
.RI "Return the name of the given layer of type Convolution as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBDropConnect\fP<> *) const"
.br
.RI "Return the name of the given layer of type DropConnect as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBDropout\fP<> *) const"
.br
.RI "Return the name of the given layer of type Dropout as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBFlexibleReLU\fP<> *) const"
.br
.RI "Return the name of the given layer of type FlexibleReLU as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBLayerNorm\fP<> *) const"
.br
.RI "Return the name of the given layer of type LayerNorm as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBLinear\fP<> *) const"
.br
.RI "Return the name of the given layer of type Linear as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBLinearNoBias\fP<> *) const"
.br
.RI "Return the name of the given layer of type LinearNoBias as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBNoisyLinear\fP<> *) const"
.br
.RI "Return the name of the given layer of type NoisyLinear as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBMaxPooling\fP<> *) const"
.br
.RI "Return the name of the given layer of type MaxPooling as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBMeanPooling\fP<> *) const"
.br
.RI "Return the name of the given layer of type MeanPooling as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBLpPooling\fP<> *) const"
.br
.RI "Return the name of the given layer of type LpPooling as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBMultiplyConstant\fP<> *) const"
.br
.RI "Return the name of the given layer of type MultiplyConstant as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBReLULayer\fP<> *) const"
.br
.RI "Return the name of the given layer of type ReLULayer as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBTransposedConvolution\fP<> *) const"
.br
.RI "Return the name of the given layer of type TransposedConvolution as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBIdentityLayer\fP<> *) const"
.br
.RI "Return the name of the given layer of type IdentityLayer as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBTanHLayer\fP<> *) const"
.br
.RI "Return the name of the given layer of type TanHLayer as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBELU\fP<> *) const"
.br
.RI "Return the name of the given layer of type ELU as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBHardTanH\fP<> *) const"
.br
.RI "Return the name of the given layer of type HardTanH as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBLeakyReLU\fP<> *) const"
.br
.RI "Return the name of the given layer of type LeakyReLU as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBPReLU\fP<> *) const"
.br
.RI "Return the name of the given layer of type PReLU as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBSigmoidLayer\fP<> *) const"
.br
.RI "Return the name of the given layer of type SigmoidLayer as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBLogSoftMax\fP<> *) const"
.br
.RI "Return the name of the given layer of type LogSoftMax as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBLSTM\fP<> *) const"
.br
.ti -1c
.RI "std::string \fBLayerString\fP (\fBCReLU\fP<> *) const"
.br
.RI "Return the name of the given layer of type CReLU as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBHighway\fP<> *) const"
.br
.RI "Return the name of the given layer of type Highway as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBGRU\fP<> *) const"
.br
.RI "Return the name of the given layer of type GRU as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBGlimpse\fP<> *) const"
.br
.RI "Return the name of the given layer of type Glimpse as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBFastLSTM\fP<> *) const"
.br
.RI "Return the name of the given layer of type FastLSTM as a string\&. "
.ti -1c
.RI "std::string \fBLayerString\fP (\fBWeightNorm\fP<> *) const"
.br
.RI "Return the name of the given layer of type WeightNorm as a string\&. "
.ti -1c
.RI "template<typename T > std::string \fBLayerString\fP (T *) const"
.br
.RI "Return the name of the layer of specified type as a string\&. "
.ti -1c
.RI "std::string \fBoperator()\fP (\fBMoreTypes\fP layer) const"
.br
.RI "Overload function call\&. "
.ti -1c
.RI "template<typename LayerType > std::string \fBoperator()\fP (LayerType *layer) const"
.br
.RI "Overload function call\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implementation of a class that returns the string representation of the name of the given layer\&. 
.PP
Definition at line 25 of file layer_names\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBLayerNameVisitor\fP ()\fC [inline]\fP"

.PP
Create the \fBLayerNameVisitor\fP object\&. 
.PP
Definition at line 29 of file layer_names\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string LayerString (\fBAdaptiveMaxPooling\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type AdaptiveMaxPooling as string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type AdaptiveMaxPooling\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 39 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBAdaptiveMeanPooling\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type AdaptiveMeanPooling as string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type AdaptiveMeanPooling\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 50 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBAtrousConvolution\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type AtrousConvolution as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type AtrousConvolution\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 61 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBAlphaDropout\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type AlphaDropout as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type AlphaDropout\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 72 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBBatchNorm\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type BatchNorm as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type BatchNorm\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 83 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBConstant\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type Constant as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type Constant\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 94 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBConvolution\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type Convolution as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type Convolution\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 105 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBDropConnect\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type DropConnect as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type DropConnect\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 116 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBDropout\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type Dropout as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type Dropout\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 127 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBFlexibleReLU\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type FlexibleReLU as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type FlexibleReLU\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 138 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBLayerNorm\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type LayerNorm as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type LayerNorm\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 149 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBLinear\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type Linear as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type Linear\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 160 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBLinearNoBias\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type LinearNoBias as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type LinearNoBias\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 171 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBNoisyLinear\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type NoisyLinear as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type NoisyLinear\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 182 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBMaxPooling\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type MaxPooling as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type MaxPooling\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 193 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBMeanPooling\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type MeanPooling as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type MeanPooling\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 204 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBLpPooling\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type LpPooling as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type LpPooling\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 215 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBMultiplyConstant\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type MultiplyConstant as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type MultiplyConstant\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 226 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBReLULayer\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type ReLULayer as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type ReLULayer\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 237 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBTransposedConvolution\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type TransposedConvolution as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type TransposedConvolution\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 249 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBIdentityLayer\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type IdentityLayer as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type IdentityLayer\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 260 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBTanHLayer\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type TanHLayer as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type TanHLayer\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 271 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBELU\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type ELU as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type ELU\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 282 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBHardTanH\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type HardTanH as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type HardTanH\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 293 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBLeakyReLU\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type LeakyReLU as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type LeakyReLU\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 304 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBPReLU\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type PReLU as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type PReLU\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 315 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBSigmoidLayer\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type SigmoidLayer as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type SigmoidLayer\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 326 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBLogSoftMax\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type LogSoftMax as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type LogSoftMax\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 337 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBLSTM\fP<> *) const\fC [inline]\fP"

.PP
Definition at line 348 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBCReLU\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type CReLU as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type CReLU\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 359 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBHighway\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type Highway as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type Highway\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 370 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBGRU\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type GRU as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type GRU\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 381 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBGlimpse\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type Glimpse as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type Glimpse\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 392 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBFastLSTM\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type FastLSTM as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type FastLSTM\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 403 of file layer_names\&.hpp\&.
.SS "std::string LayerString (\fBWeightNorm\fP<> *) const\fC [inline]\fP"

.PP
Return the name of the given layer of type WeightNorm as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of type WeightNorm\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The string representation of the layer\&. 
.RE
.PP

.PP
Definition at line 414 of file layer_names\&.hpp\&.
.SS "std::string LayerString (T *) const\fC [inline]\fP"

.PP
Return the name of the layer of specified type as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP Given layer of any type\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string declaring that the layer is unsupported\&. 
.RE
.PP

.PP
Definition at line 426 of file layer_names\&.hpp\&.
.SS "std::string operator() (\fBMoreTypes\fP layer) const\fC [inline]\fP"

.PP
Overload function call\&. 
.PP
Definition at line 432 of file layer_names\&.hpp\&.
.SS "std::string operator() (LayerType * layer) const\fC [inline]\fP"

.PP
Overload function call\&. 
.PP
Definition at line 439 of file layer_names\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
