.TH "QueueFrame< TreeType, TraversalInfoType >" 3 "Sun Aug 22 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QueueFrame< TreeType, TraversalInfoType >
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBqueryDepth\fP"
.br
.ti -1c
.RI "TreeType * \fBqueryNode\fP"
.br
.ti -1c
.RI "TreeType * \fBreferenceNode\fP"
.br
.ti -1c
.RI "double \fBscore\fP"
.br
.ti -1c
.RI "TraversalInfoType \fBtraversalInfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename TreeType, typename TraversalInfoType>
.br
struct mlpack::tree::QueueFrame< TreeType, TraversalInfoType >"

.PP
Definition at line 27 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "size_t queryDepth"

.PP
Definition at line 31 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "TreeType* queryNode"

.PP
Definition at line 29 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "TreeType* referenceNode"

.PP
Definition at line 30 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "double score"

.PP
Definition at line 32 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "TraversalInfoType traversalInfo"

.PP
Definition at line 33 of file breadth_first_dual_tree_traverser\&.hpp\&.
.PP
Referenced by BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::BreadthFirstDualTreeTraverser< RuleType >::NumBaseCases()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
