.TH "LiSHTFunction" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LiSHTFunction \- The LiSHT function, defined by\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static double \fBDeriv\fP (const double y)"
.br
.RI "Computes the first derivative of the LiSHT function\&. "
.ti -1c
.RI "template<typename InputVecType , typename OutputVecType > static void \fBDeriv\fP (const InputVecType &y, OutputVecType &x)"
.br
.RI "Computes the first derivatives of the LiSHT function\&. "
.ti -1c
.RI "static double \fBFn\fP (const double x)"
.br
.RI "Computes the LiSHT function\&. "
.ti -1c
.RI "template<typename InputVecType , typename OutputVecType > static void \fBFn\fP (const InputVecType &x, OutputVecType &y)"
.br
.RI "Computes the LiSHT function\&. "
.in -1c
.SH "Detailed Description"
.PP 
The LiSHT function, defined by\&. 

\begin{eqnarray*} f(x) = x * tanh(x) f'(x) = tanh(x) + x * (1 - tanh^{2}(x)) \end{eqnarray*} 
.PP
Definition at line 42 of file lisht_function\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static double Deriv (const double y)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the first derivative of the LiSHT function\&. 
.PP
\fBParameters\fP
.RS 4
\fIy\fP Input data\&. 
.RE
.PP
\fBReturns\fP
.RS 4
f'(x) 
.RE
.PP

.PP
Definition at line 74 of file lisht_function\&.hpp\&.
.SS "static void Deriv (const InputVecType & y, OutputVecType & x)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the first derivatives of the LiSHT function\&. 
.PP
\fBParameters\fP
.RS 4
\fIy\fP Input data\&. 
.br
\fIx\fP The resulting derivatives\&. 
.RE
.PP

.PP
Definition at line 86 of file lisht_function\&.hpp\&.
.SS "static double Fn (const double x)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the LiSHT function\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Input data\&. 
.RE
.PP
\fBReturns\fP
.RS 4
f(x)\&. 
.RE
.PP

.PP
Definition at line 51 of file lisht_function\&.hpp\&.
.SS "static void Fn (const InputVecType & x, OutputVecType & y)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the LiSHT function\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Input data\&. 
.br
\fIy\fP The resulting output activation\&. 
.RE
.PP

.PP
Definition at line 63 of file lisht_function\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
