.TH "HMMModel" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HMMModel \- A serializable \fBHMM\fP model that also stores the type\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHMMModel\fP (const \fBHMMType\fP type=HMMType::DiscreteHMM)"
.br
.RI "Construct a model of the given type\&. "
.ti -1c
.RI "\fBHMMModel\fP (const \fBHMMModel\fP &other)"
.br
.RI "Copy another model\&. "
.ti -1c
.RI "\fBHMMModel\fP (\fBHMMModel\fP &&other)"
.br
.RI "Take ownership of another model\&. "
.ti -1c
.RI "\fB~HMMModel\fP ()"
.br
.RI "Clean memory\&. "
.ti -1c
.RI "\fBHMM\fP< \fBgmm::DiagonalGMM\fP > * \fBDiagGMMHMM\fP ()"
.br
.ti -1c
.RI "\fBHMM\fP< \fBdistribution::DiscreteDistribution\fP > * \fBDiscreteHMM\fP ()"
.br
.RI "Accessor methods for discreteHMM, gaussianHMM, gmmHMM, and diagGMMHMM\&. "
.ti -1c
.RI "\fBHMM\fP< \fBdistribution::GaussianDistribution\fP > * \fBGaussianHMM\fP ()"
.br
.ti -1c
.RI "\fBHMM\fP< \fBgmm::GMM\fP > * \fBGMMHMM\fP ()"
.br
.ti -1c
.RI "\fBHMMModel\fP & \fBoperator=\fP (const \fBHMMModel\fP &other)"
.br
.RI "Copy assignment operator\&. "
.ti -1c
.RI "\fBHMMModel\fP & \fBoperator=\fP (\fBHMMModel\fP &&other)"
.br
.RI "Move assignment operator\&. "
.ti -1c
.RI "template<typename ActionType , typename ExtraInfoType > void \fBPerformAction\fP (ExtraInfoType *x)"
.br
.RI "Given a functor type, perform that functor with the optional extra info on the \fBHMM\fP\&. "
.ti -1c
.RI "template<typename Archive > void \fBserialize\fP (Archive &ar, const uint32_t)"
.br
.RI "Serialize the model\&. "
.ti -1c
.RI "\fBHMMType\fP \fBType\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A serializable \fBHMM\fP model that also stores the type\&. 
.PP
Definition at line 33 of file hmm_model\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBHMMModel\fP (const \fBHMMType\fP type = \fCHMMType::DiscreteHMM\fP)\fC [inline]\fP"

.PP
Construct a model of the given type\&. 
.PP
Definition at line 49 of file hmm_model\&.hpp\&.
.PP
References mlpack::hmm::DiagonalGaussianMixtureModelHMM, mlpack::hmm::DiscreteHMM, mlpack::hmm::GaussianHMM, and mlpack::hmm::GaussianMixtureModelHMM\&.
.SS "\fBHMMModel\fP (const \fBHMMModel\fP & other)\fC [inline]\fP"

.PP
Copy another model\&. 
.PP
Definition at line 67 of file hmm_model\&.hpp\&.
.PP
References mlpack::hmm::DiagonalGaussianMixtureModelHMM, mlpack::hmm::DiscreteHMM, mlpack::hmm::GaussianHMM, and mlpack::hmm::GaussianMixtureModelHMM\&.
.SS "\fBHMMModel\fP (\fBHMMModel\fP && other)\fC [inline]\fP"

.PP
Take ownership of another model\&. 
.PP
Definition at line 87 of file hmm_model\&.hpp\&.
.PP
References mlpack::hmm::DiscreteHMM\&.
.SS "~\fBHMMModel\fP ()\fC [inline]\fP"

.PP
Clean memory\&. 
.PP
Definition at line 153 of file hmm_model\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBHMM\fP<\fBgmm::DiagonalGMM\fP>* DiagGMMHMM ()\fC [inline]\fP"

.PP
Definition at line 234 of file hmm_model\&.hpp\&.
.SS "\fBHMM\fP<\fBdistribution::DiscreteDistribution\fP>* DiscreteHMM ()\fC [inline]\fP"

.PP
Accessor methods for discreteHMM, gaussianHMM, gmmHMM, and diagGMMHMM\&. Note that an instatiation of this class will only contain one type of \fBHMM\fP (as indicated by the 'type' instance variable) - the other two pointers will be NULL\&.
.PP
For instance, if the \fBHMMModel\fP object holds a discrete \fBHMM\fP, then: type --> DiscreteHMM gaussianHMM --> NULL gmmHMM --> NULL diagGMMHMM --> NULL discreteHMM --> HMM<DiscreteDistribution> object and hence, calls to \fBGMMHMM()\fP, \fBDiagGMMHMM()\fP and \fBGaussianHMM()\fP will return NULL\&. Only the call to \fBDiscreteHMM()\fP will return a non NULL pointer\&.
.PP
Hence, in practice, a user should be careful to first check the type of \fBHMM\fP (by calling the \fBType()\fP accessor) and then perform subsequent actions, to avoid null pointer dereferences\&. 
.PP
Definition at line 231 of file hmm_model\&.hpp\&.
.SS "\fBHMM\fP<\fBdistribution::GaussianDistribution\fP>* GaussianHMM ()\fC [inline]\fP"

.PP
Definition at line 232 of file hmm_model\&.hpp\&.
.SS "\fBHMM\fP<\fBgmm::GMM\fP>* GMMHMM ()\fC [inline]\fP"

.PP
Definition at line 233 of file hmm_model\&.hpp\&.
.SS "\fBHMMModel\fP& operator= (const \fBHMMModel\fP & other)\fC [inline]\fP"

.PP
Copy assignment operator\&. 
.PP
Definition at line 102 of file hmm_model\&.hpp\&.
.PP
References mlpack::hmm::DiagonalGaussianMixtureModelHMM, mlpack::hmm::DiscreteHMM, mlpack::hmm::GaussianHMM, and mlpack::hmm::GaussianMixtureModelHMM\&.
.SS "\fBHMMModel\fP& operator= (\fBHMMModel\fP && other)\fC [inline]\fP"

.PP
Move assignment operator\&. 
.PP
Definition at line 133 of file hmm_model\&.hpp\&.
.PP
References mlpack::hmm::DiscreteHMM\&.
.SS "void PerformAction (ExtraInfoType * x)\fC [inline]\fP"

.PP
Given a functor type, perform that functor with the optional extra info on the \fBHMM\fP\&. 
.PP
Definition at line 167 of file hmm_model\&.hpp\&.
.PP
References mlpack::hmm::DiagonalGaussianMixtureModelHMM, mlpack::hmm::DiscreteHMM, mlpack::hmm::GaussianHMM, and mlpack::hmm::GaussianMixtureModelHMM\&.
.SS "void serialize (Archive & ar, const uint32_t)\fC [inline]\fP"

.PP
Serialize the model\&. 
.PP
Definition at line 181 of file hmm_model\&.hpp\&.
.PP
References CEREAL_POINTER, mlpack::hmm::DiagonalGaussianMixtureModelHMM, mlpack::hmm::DiscreteHMM, mlpack::hmm::GaussianHMM, and mlpack::hmm::GaussianMixtureModelHMM\&.
.SS "\fBHMMType\fP Type ()\fC [inline]\fP"

.PP
Definition at line 210 of file hmm_model\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
