.TH "RandomPointSelection" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RandomPointSelection \- This class can be used to randomly select the next point to use for \fBDBSCAN\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename MatType > size_t \fBSelect\fP (const size_t, const MatType &data)"
.br
.RI "Select the next point to use, randomly\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class can be used to randomly select the next point to use for \fBDBSCAN\fP\&. 
.PP
Definition at line 23 of file random_point_selection\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "size_t Select (const size_t, const MatType & data)\fC [inline]\fP"

.PP
Select the next point to use, randomly\&. 
.PP
\fBParameters\fP
.RS 4
\fI*\fP (point) Unused data\&. 
.br
\fIdata\fP Dataset to cluster\&. 
.RE
.PP

.PP
Definition at line 33 of file random_point_selection\&.hpp\&.
.PP
References mlpack::math::RandInt()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
