.TH "LRegularizer< TPower >" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LRegularizer< TPower > \- The L_p regularizer for arbitrary integer p\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLRegularizer\fP (double \fBfactor\fP=1\&.0)"
.br
.RI "Create the regularizer object\&. "
.ti -1c
.RI "template<typename MatType > void \fBEvaluate\fP (const MatType &weight, MatType &gradient)"
.br
.RI "Calculate the gradient for regularization\&. "
.ti -1c
.RI "template<typename Archive > void \fBserialize\fP (Archive &ar, const uint32_t)"
.br
.RI "Serialize the regularizer (nothing to do)\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBfactor\fP"
.br
.RI "The constant for the regularization\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBPower\fP = TPower"
.br
.RI "The power of the regularizer\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<int TPower>
.br
class mlpack::ann::LRegularizer< TPower >"
The L_p regularizer for arbitrary integer p\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIPower\fP Power of regularizer; i\&.e\&. Power = 1 gives the L1-regularization\&. 
.RE
.PP

.PP
Definition at line 27 of file lregularizer\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBLRegularizer\fP (double factor = \fC1\&.0\fP)"

.PP
Create the regularizer object\&. 
.PP
\fBParameters\fP
.RS 4
\fIfactor\fP The factor for regularization\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Evaluate (const MatType & weight, MatType & gradient)"

.PP
Calculate the gradient for regularization\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIMatType\fP Type of weight matrix\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIweight\fP The weight matrix to be regularized\&. 
.br
\fIgradient\fP The calculated gradient\&. 
.RE
.PP

.SS "void serialize (Archive & ar, const uint32_t)"

.PP
Serialize the regularizer (nothing to do)\&. 
.SH "Member Data Documentation"
.PP 
.SS "double factor"

.PP
The constant for the regularization\&. 
.PP
Definition at line 55 of file lregularizer\&.hpp\&.
.SS "const int Power = TPower\fC [static]\fP"

.PP
The power of the regularizer\&. 
.PP
Definition at line 52 of file lregularizer\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
