.TH "Backtrace" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Backtrace \- Provides a backtrace\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBacktrace\fP ()"
.br
.RI "Constructor initialize fields and call GetAddress to retrieve addresses for each frame of backtrace\&. "
.ti -1c
.RI "std::string \fBToString\fP ()"
.br
.RI "Returns string of backtrace\&. "
.in -1c
.SH "Detailed Description"
.PP 
Provides a backtrace\&. 

The \fBBacktrace\fP class retrieve addresses of each called function from the stack and decode file name, function & line number\&. Retrieved information can be printed in form:
.PP
.PP
.nf
[b]: (count) /directory/to/file\&.cpp:function(args):line_number
.fi
.PP
.PP
\fBBacktrace\fP is printed always when \fBLog::Assert\fP failed\&. An example is given below\&.
.PP
.PP
.nf
if (!someImportantCondition())
{
  Log::Fatal << "someImportantCondition() is not satisfied! Terminating\&.";
  Log::Fatal << std::endl;
}
.fi
.PP
.PP
\fBNote\fP
.RS 4
\fBLog::Assert\fP will not be shown when compiling in non-debug mode\&.
.RE
.PP
\fBSee also\fP
.RS 4
PrefixedOutStream, \fBLog\fP 
.RE
.PP

.PP
Definition at line 46 of file backtrace\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBBacktrace\fP ()"

.PP
Constructor initialize fields and call GetAddress to retrieve addresses for each frame of backtrace\&. 
.SH "Member Function Documentation"
.PP 
.SS "std::string ToString ()"

.PP
Returns string of backtrace\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
