.TH "mlpack" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack \- Linear algebra utility functions, generally performed on matrices or vectors\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBadaboost\fP"
.br
.ti -1c
.RI " \fBamf\fP"
.br
.RI "Alternating Matrix Factorization\&. "
.ti -1c
.RI " \fBann\fP"
.br
.RI "Artificial Neural Network\&. "
.ti -1c
.RI " \fBbindings\fP"
.br
.ti -1c
.RI " \fBbound\fP"
.br
.ti -1c
.RI " \fBcf\fP"
.br
.RI "Collaborative filtering\&. "
.ti -1c
.RI " \fBcv\fP"
.br
.ti -1c
.RI " \fBdata\fP"
.br
.RI "Functions to load and save matrices and models\&. "
.ti -1c
.RI " \fBdbscan\fP"
.br
.ti -1c
.RI " \fBdet\fP"
.br
.RI "Density Estimation Trees\&. "
.ti -1c
.RI " \fBdistribution\fP"
.br
.RI "Probability distributions\&. "
.ti -1c
.RI " \fBemst\fP"
.br
.RI "Euclidean Minimum Spanning Trees\&. "
.ti -1c
.RI " \fBfastmks\fP"
.br
.RI "Fast max-kernel search\&. "
.ti -1c
.RI " \fBgmm\fP"
.br
.RI "Gaussian Mixture Models\&. "
.ti -1c
.RI " \fBhmm\fP"
.br
.RI "Hidden Markov Models\&. "
.ti -1c
.RI " \fBhpt\fP"
.br
.ti -1c
.RI " \fBkde\fP"
.br
.RI "Kernel Density Estimation\&. "
.ti -1c
.RI " \fBkernel\fP"
.br
.RI "Kernel functions\&. "
.ti -1c
.RI " \fBkmeans\fP"
.br
.RI "K-Means clustering\&. "
.ti -1c
.RI " \fBkpca\fP"
.br
.ti -1c
.RI " \fBlcc\fP"
.br
.ti -1c
.RI " \fBlmnn\fP"
.br
.RI "Large Margin Nearest Neighbor\&. "
.ti -1c
.RI " \fBmath\fP"
.br
.RI "Miscellaneous math routines\&. "
.ti -1c
.RI " \fBmatrix_completion\fP"
.br
.ti -1c
.RI " \fBmeanshift\fP"
.br
.RI "Mean shift clustering\&. "
.ti -1c
.RI " \fBmetric\fP"
.br
.ti -1c
.RI " \fBmvu\fP"
.br
.ti -1c
.RI " \fBnaive_bayes\fP"
.br
.RI "The Naive Bayes Classifier\&. "
.ti -1c
.RI " \fBnca\fP"
.br
.RI "Neighborhood Components Analysis\&. "
.ti -1c
.RI " \fBneighbor\fP"
.br
.ti -1c
.RI " \fBnn\fP"
.br
.ti -1c
.RI " \fBpca\fP"
.br
.ti -1c
.RI " \fBperceptron\fP"
.br
.ti -1c
.RI " \fBradical\fP"
.br
.ti -1c
.RI " \fBrange\fP"
.br
.RI "Range-search routines\&. "
.ti -1c
.RI " \fBregression\fP"
.br
.RI "Regression methods\&. "
.ti -1c
.RI " \fBrl\fP"
.br
.ti -1c
.RI " \fBsfinae\fP"
.br
.ti -1c
.RI " \fBsparse_coding\fP"
.br
.ti -1c
.RI " \fBsvd\fP"
.br
.ti -1c
.RI " \fBsvm\fP"
.br
.ti -1c
.RI " \fBtree\fP"
.br
.RI "Trees and tree-building procedures\&. "
.ti -1c
.RI " \fButil\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBacktrace\fP"
.br
.RI "Provides a backtrace\&. "
.ti -1c
.RI "class \fBIO\fP"
.br
.RI "Parses the command line for parameters and holds user-specified parameters\&. "
.ti -1c
.RI "class \fBLog\fP"
.br
.RI "Provides a convenient way to give formatted output\&. "
.ti -1c
.RI "class \fBTimer\fP"
.br
.RI "The timer class provides a way for mlpack methods to be timed\&. "
.ti -1c
.RI "class \fBTimers\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBCheckMatrices\fP (const arma::cube &x, const arma::cube &xmlX, const arma::cube &jsonX, const arma::cube &binaryX)"
.br
.ti -1c
.RI "void \fBCheckMatrices\fP (const arma::mat &x, const arma::mat &xmlX, const arma::mat &jsonX, const arma::mat &binaryX)"
.br
.ti -1c
.RI "void \fBCheckMatrices\fP (const arma::Mat< size_t > &x, const arma::Mat< size_t > &xmlX, const arma::Mat< size_t > &jsonX, const arma::Mat< size_t > &binaryX)"
.br
.ti -1c
.RI "template<typename T > T::elem_type * \fBGetMemory\fP (T &m)"
.br
.RI "Return the matrix's allocated memory pointer, unless the matrix is using its internal preallocated memory, in which case we copy that and return a pointer to the memory we just made\&. "
.ti -1c
.RI "template<typename T , typename IArchiveType , typename OArchiveType > void \fBSerializeObject\fP (T &t, T &newT)"
.br
.ti -1c
.RI "template<typename T > void \fBSerializeObjectAll\fP (T &t, T &xmlT, T &jsonT, T &binaryT)"
.br
.ti -1c
.RI "template<typename T , typename IArchiveType , typename OArchiveType > void \fBSerializePointerObject\fP (T *t, T *&newT)"
.br
.ti -1c
.RI "template<typename T > void \fBSerializePointerObjectAll\fP (T *t, T *&xmlT, T *&jsonT, T *&binaryT)"
.br
.ti -1c
.RI "template<typename CubeType > void \fBTestAllArmadilloSerialization\fP (arma::Cube< CubeType > &x)"
.br
.ti -1c
.RI "template<typename MatType > void \fBTestAllArmadilloSerialization\fP (MatType &x)"
.br
.ti -1c
.RI "template<typename CubeType , typename IArchiveType , typename OArchiveType > void \fBTestArmadilloSerialization\fP (arma::Cube< CubeType > &x)"
.br
.ti -1c
.RI "template<typename MatType , typename IArchiveType , typename OArchiveType > void \fBTestArmadilloSerialization\fP (MatType &x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Linear algebra utility functions, generally performed on matrices or vectors\&. 

This class is used to update the weightVectors matrix according to the simple update rule as discussed by Rosenblatt:
.PP
if a vector x has been incorrectly classified by a weight w, then w = w - x and w'= w'+ x
.PP
where w' is the weight vector which correctly classifies x\&. 
.SH "Function Documentation"
.PP 
.SS "void mlpack::CheckMatrices (const arma::cube & x, const arma::cube & xmlX, const arma::cube & jsonX, const arma::cube & binaryX)"

.SS "void mlpack::CheckMatrices (const arma::mat & x, const arma::mat & xmlX, const arma::mat & jsonX, const arma::mat & binaryX)"

.SS "void mlpack::CheckMatrices (const arma::Mat< size_t > & x, const arma::Mat< size_t > & xmlX, const arma::Mat< size_t > & jsonX, const arma::Mat< size_t > & binaryX)"

.SS "T::elem_type* mlpack::GetMemory (T & m)\fC [inline]\fP"

.PP
Return the matrix's allocated memory pointer, unless the matrix is using its internal preallocated memory, in which case we copy that and return a pointer to the memory we just made\&. 
.PP
Definition at line 27 of file arma_util\&.hpp\&.
.SS "void mlpack::SerializeObject (T & t, T & newT)"

.PP
Definition at line 145 of file serialization\&.hpp\&.
.PP
References mlpack::data::binary, and FilterFileName()\&.
.PP
Referenced by SerializeObjectAll()\&.
.SS "void mlpack::SerializeObjectAll (T & t, T & xmlT, T & jsonT, T & binaryT)"

.PP
Definition at line 172 of file serialization\&.hpp\&.
.PP
References SerializeObject()\&.
.SS "void mlpack::SerializePointerObject (T * t, T *& newT)"

.PP
Definition at line 184 of file serialization\&.hpp\&.
.PP
References mlpack::data::binary, CEREAL_POINTER, and FilterFileName()\&.
.PP
Referenced by SerializePointerObjectAll()\&.
.SS "void mlpack::SerializePointerObjectAll (T * t, T *& xmlT, T *& jsonT, T *& binaryT)"

.PP
Definition at line 206 of file serialization\&.hpp\&.
.PP
References SerializePointerObject()\&.
.SS "void mlpack::TestAllArmadilloSerialization (arma::Cube< CubeType > & x)"

.PP
Definition at line 78 of file serialization\&.hpp\&.
.PP
References TestArmadilloSerialization()\&.
.SS "void mlpack::TestAllArmadilloSerialization (MatType & x)"

.PP
Definition at line 132 of file serialization\&.hpp\&.
.PP
References TestArmadilloSerialization()\&.
.SS "void mlpack::TestArmadilloSerialization (arma::Cube< CubeType > & x)"

.PP
Definition at line 26 of file serialization\&.hpp\&.
.PP
References mlpack::data::binary, and FilterFileName()\&.
.PP
Referenced by TestAllArmadilloSerialization()\&.
.SS "void mlpack::TestArmadilloSerialization (MatType & x)"

.PP
Definition at line 92 of file serialization\&.hpp\&.
.PP
References mlpack::data::binary, and FilterFileName()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
