.TH "mlpack::bound" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::bound
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBaddr\fP"
.br
.ti -1c
.RI " \fBmeta\fP"
.br
.RI "Metaprogramming utilities\&. "
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBallBound\fP"
.br
.RI "Ball bound encloses a set of points at a specific distance (radius) from a specific point (center)\&. "
.ti -1c
.RI "struct \fBBoundTraits\fP"
.br
.RI "A class to obtain compile-time traits about BoundType classes\&. "
.ti -1c
.RI "struct \fBBoundTraits< BallBound< MetricType, VecType > >\fP"
.br
.RI "A specialization of \fBBoundTraits\fP for this bound type\&. "
.ti -1c
.RI "struct \fBBoundTraits< CellBound< MetricType, ElemType > >\fP"
.br
.ti -1c
.RI "struct \fBBoundTraits< HollowBallBound< MetricType, ElemType > >\fP"
.br
.RI "A specialization of \fBBoundTraits\fP for this bound type\&. "
.ti -1c
.RI "struct \fBBoundTraits< HRectBound< MetricType, ElemType > >\fP"
.br
.ti -1c
.RI "class \fBCellBound\fP"
.br
.RI "The \fBCellBound\fP class describes a bound that consists of a number of hyperrectangles\&. "
.ti -1c
.RI "class \fBHollowBallBound\fP"
.br
.RI "Hollow ball bound encloses a set of points at a specific distance (radius) from a specific point (center) except points at a specific distance from another point (the center of the hole)\&. "
.ti -1c
.RI "class \fBHRectBound\fP"
.br
.RI "Hyper-rectangle bound for an L-metric\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
