.TH "RewardSetVisitor" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RewardSetVisitor \- \fBRewardSetVisitor\fP set the reward parameter given the reward value\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits static_visitor< void >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRewardSetVisitor\fP (const double reward)"
.br
.RI "Set the reward parameter given the reward value\&. "
.ti -1c
.RI "template<typename LayerType > void \fBoperator()\fP (LayerType *layer) const"
.br
.RI "Set the reward parameter\&. "
.ti -1c
.RI "void \fBoperator()\fP (\fBMoreTypes\fP layer) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBRewardSetVisitor\fP set the reward parameter given the reward value\&. 
.PP
Definition at line 26 of file reward_set_visitor\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBRewardSetVisitor\fP (const double reward)"

.PP
Set the reward parameter given the reward value\&. 
.SH "Member Function Documentation"
.PP 
.SS "void operator() (LayerType * layer) const"

.PP
Set the reward parameter\&. 
.SS "void operator() (\fBMoreTypes\fP layer) const"


.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
