.TH "GaussianKernel" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GaussianKernel \- The standard Gaussian kernel\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGaussianKernel\fP ()"
.br
.RI "Default constructor; sets bandwidth to 1\&.0\&. "
.ti -1c
.RI "\fBGaussianKernel\fP (const double bandwidth)"
.br
.RI "Construct the Gaussian kernel with a custom bandwidth\&. "
.ti -1c
.RI "double \fBBandwidth\fP () const"
.br
.RI "Get the bandwidth\&. "
.ti -1c
.RI "void \fBBandwidth\fP (const double bandwidth)"
.br
.RI "Modify the bandwidth\&. "
.ti -1c
.RI "template<typename VecTypeA , typename VecTypeB > double \fBConvolutionIntegral\fP (const VecTypeA &a, const VecTypeB &b)"
.br
.RI "Obtain a convolution integral of the Gaussian kernel\&. "
.ti -1c
.RI "template<typename VecTypeA , typename VecTypeB > double \fBEvaluate\fP (const VecTypeA &a, const VecTypeB &b) const"
.br
.RI "Evaluation of the Gaussian kernel\&. "
.ti -1c
.RI "double \fBEvaluate\fP (const double t) const"
.br
.RI "Evaluation of the Gaussian kernel given the distance between two points\&. "
.ti -1c
.RI "double \fBGamma\fP () const"
.br
.RI "Get the precalculated constant\&. "
.ti -1c
.RI "double \fBGradient\fP (const double t) const"
.br
.RI "Evaluation of the gradient of Gaussian kernel given the distance between two points\&. "
.ti -1c
.RI "double \fBGradientForSquaredDistance\fP (const double t) const"
.br
.RI "Evaluation of the gradient of Gaussian kernel given the squared distance between two points\&. "
.ti -1c
.RI "double \fBNormalizer\fP (const size_t dimension)"
.br
.RI "Obtain the normalization constant of the Gaussian kernel\&. "
.ti -1c
.RI "template<typename Archive > void \fBserialize\fP (Archive &ar, const uint32_t)"
.br
.RI "Serialize the kernel\&. "
.in -1c
.SH "Detailed Description"
.PP 
The standard Gaussian kernel\&. 

Given two vectors $ x $, $ y $, and a bandwidth $ \mu $ (set in the constructor),
.PP
\[ K(x, y) = \exp(-\frac{|| x - y ||^2}{2 \mu^2}). \].PP
The implementation is all in the header file because it is so simple\&. 
.PP
Definition at line 34 of file gaussian_kernel\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBGaussianKernel\fP ()\fC [inline]\fP"

.PP
Default constructor; sets bandwidth to 1\&.0\&. 
.PP
Definition at line 40 of file gaussian_kernel\&.hpp\&.
.SS "\fBGaussianKernel\fP (const double bandwidth)\fC [inline]\fP"

.PP
Construct the Gaussian kernel with a custom bandwidth\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbandwidth\fP The bandwidth of the kernel ( $\mu$)\&. 
.RE
.PP

.PP
Definition at line 48 of file gaussian_kernel\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "double Bandwidth () const\fC [inline]\fP"

.PP
Get the bandwidth\&. 
.PP
Definition at line 135 of file gaussian_kernel\&.hpp\&.
.SS "void Bandwidth (const double bandwidth)\fC [inline]\fP"

.PP
Modify the bandwidth\&. This takes an argument because we must update the precalculated constant (gamma)\&. 
.PP
Definition at line 139 of file gaussian_kernel\&.hpp\&.
.SS "double ConvolutionIntegral (const VecTypeA & a, const VecTypeB & b)\fC [inline]\fP"

.PP
Obtain a convolution integral of the Gaussian kernel\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP First vector\&. 
.br
\fIb\fP Second vector\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The convolution integral\&. 
.RE
.PP

.PP
Definition at line 127 of file gaussian_kernel\&.hpp\&.
.PP
References GaussianKernel::Evaluate(), LMetric< TPower, TTakeRoot >::Evaluate(), and GaussianKernel::Normalizer()\&.
.SS "double Evaluate (const VecTypeA & a, const VecTypeB & b) const\fC [inline]\fP"

.PP
Evaluation of the Gaussian kernel\&. This could be generalized to use any distance metric, not the Euclidean distance, but for now, the Euclidean distance is used\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIVecType\fP Type of vector (likely arma::vec or arma::spvec)\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIa\fP First vector\&. 
.br
\fIb\fP Second vector\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
K(a, b) using the bandwidth ( $\mu$) specified in the constructor\&. 
.RE
.PP

.PP
Definition at line 65 of file gaussian_kernel\&.hpp\&.
.PP
References LMetric< TPower, TTakeRoot >::Evaluate()\&.
.PP
Referenced by GaussianKernel::ConvolutionIntegral()\&.
.SS "double Evaluate (const double t) const\fC [inline]\fP"

.PP
Evaluation of the Gaussian kernel given the distance between two points\&. 
.PP
\fBParameters:\fP
.RS 4
\fIt\fP The distance between the two points the kernel is evaluated on\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
K(t) using the bandwidth ( $\mu$) specified in the constructor\&. 
.RE
.PP

.PP
Definition at line 78 of file gaussian_kernel\&.hpp\&.
.SS "double Gamma () const\fC [inline]\fP"

.PP
Get the precalculated constant\&. 
.PP
Definition at line 146 of file gaussian_kernel\&.hpp\&.
.SS "double Gradient (const double t) const\fC [inline]\fP"

.PP
Evaluation of the gradient of Gaussian kernel given the distance between two points\&. 
.PP
\fBParameters:\fP
.RS 4
\fIt\fP The distance between the two points the kernel is evaluated on\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
K(t) using the bandwidth ( $\mu$) specified in the constructor\&. 
.RE
.PP

.PP
Definition at line 92 of file gaussian_kernel\&.hpp\&.
.SS "double GradientForSquaredDistance (const double t) const\fC [inline]\fP"

.PP
Evaluation of the gradient of Gaussian kernel given the squared distance between two points\&. 
.PP
\fBParameters:\fP
.RS 4
\fIt\fP The squared distance between the two points 
.RE
.PP
\fBReturns:\fP
.RS 4
K(t) using the bandwidth ( $\mu$) specified in the constructor\&. 
.RE
.PP

.PP
Definition at line 104 of file gaussian_kernel\&.hpp\&.
.SS "double Normalizer (const size_t dimension)\fC [inline]\fP"

.PP
Obtain the normalization constant of the Gaussian kernel\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdimension\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
the normalization constant 
.RE
.PP

.PP
Definition at line 114 of file gaussian_kernel\&.hpp\&.
.PP
References M_PI\&.
.PP
Referenced by GaussianKernel::ConvolutionIntegral()\&.
.SS "void serialize (Archive & ar, const uint32_t)\fC [inline]\fP"

.PP
Serialize the kernel\&. 
.PP
Definition at line 150 of file gaussian_kernel\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
