.TH "NeighborSearchStat< SortPolicy >" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NeighborSearchStat< SortPolicy > \- Extra data for each node in the tree\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNeighborSearchStat\fP ()"
.br
.RI "Initialize the statistic with the worst possible distance according to our sorting policy\&. "
.ti -1c
.RI "template<typename TreeType > \fBNeighborSearchStat\fP (TreeType &)"
.br
.RI "Initialization for a fully initialized node\&. "
.ti -1c
.RI "double \fBAuxBound\fP () const"
.br
.RI "Get the aux bound\&. "
.ti -1c
.RI "double & \fBAuxBound\fP ()"
.br
.RI "Modify the aux bound\&. "
.ti -1c
.RI "double \fBFirstBound\fP () const"
.br
.RI "Get the first bound\&. "
.ti -1c
.RI "double & \fBFirstBound\fP ()"
.br
.RI "Modify the first bound\&. "
.ti -1c
.RI "double \fBLastDistance\fP () const"
.br
.RI "Get the last distance calculation\&. "
.ti -1c
.RI "double & \fBLastDistance\fP ()"
.br
.RI "Modify the last distance calculation\&. "
.ti -1c
.RI "void \fBReset\fP ()"
.br
.RI "Reset statistic parameters to initial values\&. "
.ti -1c
.RI "double \fBSecondBound\fP () const"
.br
.RI "Get the second bound\&. "
.ti -1c
.RI "double & \fBSecondBound\fP ()"
.br
.RI "Modify the second bound\&. "
.ti -1c
.RI "template<typename Archive > void \fBserialize\fP (Archive &ar, const uint32_t)"
.br
.RI "Serialize the statistic to/from an archive\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename SortPolicy>
.br
class mlpack::neighbor::NeighborSearchStat< SortPolicy >"
Extra data for each node in the tree\&. 

For neighbor searches, each node only needs to store a bound on neighbor distances\&. 
.PP
Definition at line 26 of file neighbor_search_stat\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBNeighborSearchStat\fP ()\fC [inline]\fP"

.PP
Initialize the statistic with the worst possible distance according to our sorting policy\&. 
.PP
Definition at line 48 of file neighbor_search_stat\&.hpp\&.
.SS "\fBNeighborSearchStat\fP (TreeType &)\fC [inline]\fP"

.PP
Initialization for a fully initialized node\&. In this case, we don't need to worry about the node\&. 
.PP
Definition at line 59 of file neighbor_search_stat\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "double AuxBound () const\fC [inline]\fP"

.PP
Get the aux bound\&. 
.PP
Definition at line 85 of file neighbor_search_stat\&.hpp\&.
.SS "double& AuxBound ()\fC [inline]\fP"

.PP
Modify the aux bound\&. 
.PP
Definition at line 87 of file neighbor_search_stat\&.hpp\&.
.SS "double FirstBound () const\fC [inline]\fP"

.PP
Get the first bound\&. 
.PP
Definition at line 77 of file neighbor_search_stat\&.hpp\&.
.SS "double& FirstBound ()\fC [inline]\fP"

.PP
Modify the first bound\&. 
.PP
Definition at line 79 of file neighbor_search_stat\&.hpp\&.
.SS "double LastDistance () const\fC [inline]\fP"

.PP
Get the last distance calculation\&. 
.PP
Definition at line 89 of file neighbor_search_stat\&.hpp\&.
.SS "double& LastDistance ()\fC [inline]\fP"

.PP
Modify the last distance calculation\&. 
.PP
Definition at line 91 of file neighbor_search_stat\&.hpp\&.
.SS "void Reset ()\fC [inline]\fP"

.PP
Reset statistic parameters to initial values\&. 
.PP
Definition at line 68 of file neighbor_search_stat\&.hpp\&.
.SS "double SecondBound () const\fC [inline]\fP"

.PP
Get the second bound\&. 
.PP
Definition at line 81 of file neighbor_search_stat\&.hpp\&.
.SS "double& SecondBound ()\fC [inline]\fP"

.PP
Modify the second bound\&. 
.PP
Definition at line 83 of file neighbor_search_stat\&.hpp\&.
.SS "void serialize (Archive & ar, const uint32_t)\fC [inline]\fP"

.PP
Serialize the statistic to/from an archive\&. 
.PP
Definition at line 95 of file neighbor_search_stat\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
