.TH "KernelTraits< CosineDistance >" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KernelTraits< CosineDistance > \- Kernel traits for the cosine distance\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBIsNormalized\fP = true"
.br
.RI "The cosine kernel is normalized: K(x, x) = 1 for all x\&. "
.ti -1c
.RI "static const bool \fBUsesSquaredDistance\fP = false"
.br
.RI "The cosine kernel doesn't include a squared distance\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
class mlpack::kernel::KernelTraits< CosineDistance >"
Kernel traits for the cosine distance\&. 
.PP
Definition at line 51 of file cosine_distance\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "const bool IsNormalized = true\fC [static]\fP"

.PP
The cosine kernel is normalized: K(x, x) = 1 for all x\&. 
.PP
Definition at line 55 of file cosine_distance\&.hpp\&.
.SS "const bool UsesSquaredDistance = false\fC [static]\fP"

.PP
The cosine kernel doesn't include a squared distance\&. 
.PP
Definition at line 58 of file cosine_distance\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
