.TH "SeeAlso" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SeeAlso
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSeeAlso\fP (const std::string &description, const std::string &link)"
.br
.RI "Construct a \fBSeeAlso\fP object\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 72 of file program_doc\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBSeeAlso\fP (const std::string & description, const std::string & link)"

.PP
Construct a \fBSeeAlso\fP object\&. When constructed, it will register itself with \fBIO\fP\&.
.PP
\fBParameters\fP
.RS 4
\fIdescription\fP Description of \fBSeeAlso\fP\&. 
.br
\fIlink\fP Link of \fBSeeAlso\fP\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
