.TH "InitTraits< KathirvalavakumarSubavathiInitialization >" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InitTraits< KathirvalavakumarSubavathiInitialization > \- Initialization traits of the kathirvalavakumar subavath initialization rule\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBUseLayer\fP = false"
.br
.RI "The kathirvalavakumar subavath initialization rule is applied over the entire network\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
class mlpack::ann::InitTraits< KathirvalavakumarSubavathiInitialization >"
Initialization traits of the kathirvalavakumar subavath initialization rule\&. 
.PP
Definition at line 156 of file kathirvalavakumar_subavathi_init\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "const bool UseLayer = false\fC [static]\fP"

.PP
The kathirvalavakumar subavath initialization rule is applied over the entire network\&. 
.PP
Definition at line 161 of file kathirvalavakumar_subavathi_init\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
