.TH "IsSpillTree< TreeType >" 3 "Sun Aug 22 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IsSpillTree< TreeType >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBvalue\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename TreeType>
.br
struct mlpack::tree::IsSpillTree< TreeType >"

.PP
Definition at line 21 of file is_spill_tree\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "const bool value = false\fC [static]\fP"

.PP
Definition at line 23 of file is_spill_tree\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
