.TH "KFoldCV< MLAlgorithm, Metric, MatType, PredictionsType, WeightsType >" 3 "Sun Aug 22 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KFoldCV< MLAlgorithm, Metric, MatType, PredictionsType, WeightsType > \- The class \fBKFoldCV\fP implements k-fold cross-validation for regression and classification algorithms\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKFoldCV\fP (const size_t k, const MatType &xs, const PredictionsType &ys, const bool shuffle=true)"
.br
.RI "This constructor can be used for regression algorithms and for binary classification algorithms\&. "
.ti -1c
.RI "\fBKFoldCV\fP (const size_t k, const MatType &xs, const PredictionsType &ys, const size_t numClasses, const bool shuffle=true)"
.br
.RI "This constructor can be used for multiclass classification algorithms\&. "
.ti -1c
.RI "\fBKFoldCV\fP (const size_t k, const MatType &xs, const \fBdata::DatasetInfo\fP &datasetInfo, const PredictionsType &ys, const size_t numClasses, const bool shuffle=true)"
.br
.RI "This constructor can be used for multiclass classification algorithms that can take a \fBdata::DatasetInfo\fP parameter\&. "
.ti -1c
.RI "\fBKFoldCV\fP (const size_t k, const MatType &xs, const PredictionsType &ys, const WeightsType &weights, const bool shuffle=true)"
.br
.RI "This constructor can be used for regression and binary classification algorithms that support weighted learning\&. "
.ti -1c
.RI "\fBKFoldCV\fP (const size_t k, const MatType &xs, const PredictionsType &ys, const size_t numClasses, const WeightsType &weights, const bool shuffle=true)"
.br
.RI "This constructor can be used for multiclass classification algorithms that support weighted learning\&. "
.ti -1c
.RI "\fBKFoldCV\fP (const size_t k, const MatType &xs, const \fBdata::DatasetInfo\fP &datasetInfo, const PredictionsType &ys, const size_t numClasses, const WeightsType &weights, const bool shuffle=true)"
.br
.RI "This constructor can be used for multiclass classification algorithms that can take a \fBdata::DatasetInfo\fP parameter and support weighted learning\&. "
.ti -1c
.RI "template<typename\&.\&.\&. MLAlgorithmArgs> double \fBEvaluate\fP (const MLAlgorithmArgs &\&.\&.\&.args)"
.br
.RI "Run k-fold cross-validation\&. "
.ti -1c
.RI "MLAlgorithm & \fBModel\fP ()"
.br
.RI "Access and modify a model from the last run of k-fold cross-validation\&. "
.ti -1c
.RI "template<bool Enabled = !Base::MIE::SupportsWeights, typename  = typename std::enable_if<Enabled>::type> void \fBShuffle\fP ()"
.br
.RI "Shuffle the data\&. "
.ti -1c
.RI "template<bool Enabled = Base::MIE::SupportsWeights, typename  = typename std::enable_if<Enabled>::type, typename  = void> void \fBShuffle\fP ()"
.br
.RI "Shuffle the data\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename MLAlgorithm, typename Metric, typename MatType = arma::mat, typename PredictionsType = typename MetaInfoExtractor<MLAlgorithm, MatType>::PredictionsType, typename WeightsType = typename MetaInfoExtractor<MLAlgorithm, MatType,                 PredictionsType>::WeightsType>
.br
class mlpack::cv::KFoldCV< MLAlgorithm, Metric, MatType, PredictionsType, WeightsType >"
The class \fBKFoldCV\fP implements k-fold cross-validation for regression and classification algorithms\&. 

To construct a \fBKFoldCV\fP object you need to pass the k parameter and arguments that specify data\&. For example, you can run 10-fold cross-validation for SoftmaxRegression in the following way\&.
.PP
.PP
.nf
// 100-point 5-dimensional random dataset\&.
arma::mat data = arma::randu<arma::mat>(5, 100);
// Random labels in the [0, 4] interval\&.
arma::Row<size_t> labels =
    arma::randi<arma::Row<size_t>>(100, arma::distr_param(0, 4));
size_t numClasses = 5;

KFoldCV<SoftmaxRegression<>, Accuracy> cv(10, data, labels, numClasses);

double lambda = 0\&.1;
double softmaxAccuracy = cv\&.Evaluate(lambda);
.fi
.PP
.PP
Before calling \fC\fBEvaluate()\fP\fP, it is possible to shuffle the data by calling the \fC\fBShuffle()\fP\fP function\&. Shuffling is performed at construction time if the parameter \fCshuffle\fP is set to \fCtrue\fP in the constructor\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIMLAlgorithm\fP A machine learning algorithm\&. 
.br
\fIMetric\fP A metric to assess the quality of a trained model\&. 
.br
\fIMatType\fP The type of data\&. 
.br
\fIPredictionsType\fP The type of predictions (should be passed when the predictions type is a template parameter in Train methods of MLAlgorithm)\&. 
.br
\fIWeightsType\fP The type of weights (should be passed when weighted learning is supported, and the weights type is a template parameter in Train methods of MLAlgorithm)\&. 
.RE
.PP

.PP
Definition at line 65 of file k_fold_cv\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBKFoldCV\fP (const size_t k, const MatType & xs, const PredictionsType & ys, const bool shuffle = \fCtrue\fP)"

.PP
This constructor can be used for regression algorithms and for binary classification algorithms\&. 
.PP
\fBParameters:\fP
.RS 4
\fIk\fP Number of folds (should be at least 2)\&. 
.br
\fIxs\fP Data points to cross-validate on\&. 
.br
\fIys\fP Predictions (labels for classification algorithms and responses for regression algorithms) for each data point\&. 
.br
\fIshuffle\fP Whether or not to shuffle the data during construction\&. 
.RE
.PP

.SS "\fBKFoldCV\fP (const size_t k, const MatType & xs, const PredictionsType & ys, const size_t numClasses, const bool shuffle = \fCtrue\fP)"

.PP
This constructor can be used for multiclass classification algorithms\&. 
.PP
\fBParameters:\fP
.RS 4
\fIk\fP Number of folds (should be at least 2)\&. 
.br
\fIxs\fP Data points to cross-validate on\&. 
.br
\fIys\fP Labels for each data point\&. 
.br
\fInumClasses\fP Number of classes in the dataset\&. 
.br
\fIshuffle\fP Whether or not to shuffle the data during construction\&. 
.RE
.PP

.SS "\fBKFoldCV\fP (const size_t k, const MatType & xs, const \fBdata::DatasetInfo\fP & datasetInfo, const PredictionsType & ys, const size_t numClasses, const bool shuffle = \fCtrue\fP)"

.PP
This constructor can be used for multiclass classification algorithms that can take a \fBdata::DatasetInfo\fP parameter\&. 
.PP
\fBParameters:\fP
.RS 4
\fIk\fP Number of folds (should be at least 2)\&. 
.br
\fIxs\fP Data points to cross-validate on\&. 
.br
\fIdatasetInfo\fP Type information for each dimension of the dataset\&. 
.br
\fIys\fP Labels for each data point\&. 
.br
\fInumClasses\fP Number of classes in the dataset\&. 
.br
\fIshuffle\fP Whether or not to shuffle the data during construction\&. 
.RE
.PP

.SS "\fBKFoldCV\fP (const size_t k, const MatType & xs, const PredictionsType & ys, const WeightsType & weights, const bool shuffle = \fCtrue\fP)"

.PP
This constructor can be used for regression and binary classification algorithms that support weighted learning\&. 
.PP
\fBParameters:\fP
.RS 4
\fIk\fP Number of folds (should be at least 2)\&. 
.br
\fIxs\fP Data points to cross-validate on\&. 
.br
\fIys\fP Predictions (labels for classification algorithms and responses for regression algorithms) for each data point\&. 
.br
\fIweights\fP Observation weights (for boosting)\&. 
.br
\fIshuffle\fP Whether or not to shuffle the data during construction\&. 
.RE
.PP

.SS "\fBKFoldCV\fP (const size_t k, const MatType & xs, const PredictionsType & ys, const size_t numClasses, const WeightsType & weights, const bool shuffle = \fCtrue\fP)"

.PP
This constructor can be used for multiclass classification algorithms that support weighted learning\&. 
.PP
\fBParameters:\fP
.RS 4
\fIk\fP Number of folds (should be at least 2)\&. 
.br
\fIxs\fP Data points to cross-validate on\&. 
.br
\fIys\fP Labels for each data point\&. 
.br
\fInumClasses\fP Number of classes in the dataset\&. 
.br
\fIweights\fP Observation weights (for boosting)\&. 
.br
\fIshuffle\fP Whether or not to shuffle the data during construction\&. 
.RE
.PP

.SS "\fBKFoldCV\fP (const size_t k, const MatType & xs, const \fBdata::DatasetInfo\fP & datasetInfo, const PredictionsType & ys, const size_t numClasses, const WeightsType & weights, const bool shuffle = \fCtrue\fP)"

.PP
This constructor can be used for multiclass classification algorithms that can take a \fBdata::DatasetInfo\fP parameter and support weighted learning\&. 
.PP
\fBParameters:\fP
.RS 4
\fIk\fP Number of folds (should be at least 2)\&. 
.br
\fIxs\fP Data points to cross-validate on\&. 
.br
\fIdatasetInfo\fP Type information for each dimension of the dataset\&. 
.br
\fIys\fP Labels for each data point\&. 
.br
\fInumClasses\fP Number of classes in the dataset\&. 
.br
\fIweights\fP Observation weights (for boosting)\&. 
.br
\fIshuffle\fP Whether or not to shuffle the data during construction\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double Evaluate (const MLAlgorithmArgs &\&.\&.\&. args)"

.PP
Run k-fold cross-validation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP Arguments for MLAlgorithm (in addition to the passed ones in the constructor)\&. 
.RE
.PP

.SS "MLAlgorithm& Model ()"

.PP
Access and modify a model from the last run of k-fold cross-validation\&. 
.SS "void Shuffle ()"

.PP
Shuffle the data\&. This overload is called if weights are not supported by the model type\&. 
.SS "void Shuffle ()"

.PP
Shuffle the data\&. This overload is called if weights are supported by the model type\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
