.TH "ShortDescriptionWrapper" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShortDescriptionWrapper
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShortDescriptionWrapper\fP (const std::string &bindingName, const std::string &shortDescription)"
.br
.RI "Register shortDescription\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file program_doc_wrapper\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBShortDescriptionWrapper\fP (const std::string & bindingName, const std::string & shortDescription)\fC [inline]\fP"

.PP
Register shortDescription\&. 
.PP
Definition at line 43 of file program_doc_wrapper\&.hpp\&.
.PP
References BindingInfo::GetSingleton(), and BindingInfo::map\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
