.TH "mlpack::pca" 3 "Sun Aug 22 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::pca
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBExactSVDPolicy\fP"
.br
.RI "Implementation of the exact SVD policy\&. "
.ti -1c
.RI "class \fBPCA\fP"
.br
.RI "This class implements principal components analysis (\fBPCA\fP)\&. "
.ti -1c
.RI "class \fBQUICSVDPolicy\fP"
.br
.RI "Implementation of the QUIC-SVD policy\&. "
.ti -1c
.RI "class \fBRandomizedBlockKrylovSVDPolicy\fP"
.br
.RI "Implementation of the randomized block krylov SVD policy\&. "
.ti -1c
.RI "class \fBRandomizedSVDPolicy\fP"
.br
.RI "Implementation of the randomized SVD policy\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
