.TH "BinaryRBM" 3 "Sun Aug 22 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BinaryRBM \- For more information, see the following paper:  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
For more information, see the following paper: 


.PP
.nf
@article{Hinton10,
  author    = {Geoffrey Hinton},
  title     = {A Practical Guide to Training Restricted Boltzmann Machines},
  year      = {2010},
  url       = {https://www\&.cs\&.toronto\&.edu/~hinton/absps/guideTR\&.pdf}
}

.fi
.PP
 
.PP
Definition at line 30 of file rbm_policies\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
