.TH "DeduceHyperParameterTypes< T, Args... >::ResultHPType< ArgumentType, IsArithmetic >" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeduceHyperParameterTypes< T, Args... >::ResultHPType< ArgumentType, IsArithmetic > \- A type function to deduce the result hyper-parameter type for ArgumentType\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename T, typename\&.\&.\&. Args>
.br
template<typename ArgumentType, bool IsArithmetic = std::is_arithmetic<ArgumentType>::value>
.br
struct mlpack::hpt::DeduceHyperParameterTypes< T, Args\&.\&.\&. >::ResultHPType< ArgumentType, IsArithmetic >"
A type function to deduce the result hyper-parameter type for ArgumentType\&. 
.PP
Definition at line 56 of file deduce_hp_types\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
