.TH "ParameterType< arma::Row< eT > >" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParameterType< arma::Row< eT > > \- For row vector types, CLI11 will accept a std::string, not an arma::Row<eT> (since it is not clear how to specify a vector on the command-line)\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::tuple< std::string, size_t, size_t > \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename eT>
.br
struct mlpack::bindings::cli::ParameterType< arma::Row< eT > >"
For row vector types, CLI11 will accept a std::string, not an arma::Row<eT> (since it is not clear how to specify a vector on the command-line)\&. 
.PP
Definition at line 66 of file parameter_type\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef std::tuple<std::string, size_t, size_t> \fBtype\fP"

.PP
Definition at line 68 of file parameter_type\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
