.TH "CategoricalSplitInfo" 3 "Sun Aug 22 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CategoricalSplitInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCategoricalSplitInfo\fP (const size_t)"
.br
.ti -1c
.RI "template<typename Archive > void \fBserialize\fP (Archive &, const uint32_t)"
.br
.RI "Serialize the object\&. (Nothing needs to be saved\&.) "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename eT > static size_t \fBCalculateDirection\fP (const eT &value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file categorical_split_info\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCategoricalSplitInfo\fP (const size_t)\fC [inline]\fP"

.PP
Definition at line 23 of file categorical_split_info\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static size_t CalculateDirection (const eT & value)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 26 of file categorical_split_info\&.hpp\&.
.SS "void serialize (Archive &, const uint32_t)\fC [inline]\fP"

.PP
Serialize the object\&. (Nothing needs to be saved\&.) 
.PP
Definition at line 35 of file categorical_split_info\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
