.TH "mlpack::bound::meta" 3 "Sun Aug 22 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::bound::meta \- Metaprogramming utilities\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBIsLMetric\fP"
.br
.RI "Utility struct where Value is true if and only if the argument is of type LMetric\&. "
.ti -1c
.RI "struct \fBIsLMetric< metric::LMetric< Power, TakeRoot > >\fP"
.br
.RI "Specialization for \fBIsLMetric\fP when the argument is of type LMetric\&. "
.in -1c
.SH "Detailed Description"
.PP 
Metaprogramming utilities\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
