.TH "BagOfWordsEncodingPolicy" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BagOfWordsEncodingPolicy \- Definition of the \fBBagOfWordsEncodingPolicy\fP class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Archive > void \fBserialize\fP (Archive &, const uint32_t)"
.br
.RI "Serialize the class to the given archive\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename MatType > static void \fBEncode\fP (MatType &output, const size_t value, const size_t line, const size_t)"
.br
.RI "The function performs the bag of words encoding algorithm i\&.e\&. "
.ti -1c
.RI "template<typename ElemType > static void \fBEncode\fP (std::vector< std::vector< ElemType >> &output, const size_t value, const size_t line, const size_t)"
.br
.RI "The function performs the bag of words encoding algorithm i\&.e\&. "
.ti -1c
.RI "template<typename MatType > static void \fBInitMatrix\fP (MatType &output, const size_t datasetSize, const size_t, const size_t dictionarySize)"
.br
.RI "The function initializes the output matrix\&. "
.ti -1c
.RI "template<typename ElemType > static void \fBInitMatrix\fP (std::vector< std::vector< ElemType >> &output, const size_t datasetSize, const size_t, const size_t dictionarySize)"
.br
.RI "The function initializes the output matrix\&. "
.ti -1c
.RI "static void \fBPreprocessToken\fP (size_t, size_t, size_t)"
.br
.RI "The function is not used by the bag of words encoding policy\&. "
.ti -1c
.RI "static void \fBReset\fP ()"
.br
.RI "Clear the necessary internal variables\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition of the \fBBagOfWordsEncodingPolicy\fP class\&. 

BagOfWords is used as a helper class for \fBStringEncoding\fP\&. The encoder maps each dataset item to a vector of size N, where N is equal to the total unique number of tokens\&. The i-th coordinate of the output vector is equal to the number of times when the i-th token occurs in the corresponding dataset item\&. The order in which the tokens are labeled is defined by the dictionary used by the \fBStringEncoding\fP class\&. The encoder writes data either in the column-major order or in the row-major order depending on the output data type\&. 
.PP
Definition at line 35 of file bag_of_words_encoding_policy\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Encode (MatType & output, const size_t value, const size_t line, const size_t)\fC [inline]\fP, \fC [static]\fP"

.PP
The function performs the bag of words encoding algorithm i\&.e\&. it writes the encoded token to the output\&. The encoder writes data in the column-major order\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIMatType\fP The output matrix type\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIoutput\fP Output matrix to store the encoded results (sp_mat or mat)\&. 
.br
\fIvalue\fP The encoded token\&. 
.br
\fIline\fP The line number at which the encoding is performed\&. 
.br
\fI*\fP (index) The token index in the line\&. 
.RE
.PP

.PP
Definition at line 103 of file bag_of_words_encoding_policy\&.hpp\&.
.SS "static void Encode (std::vector< std::vector< ElemType >> & output, const size_t value, const size_t line, const size_t)\fC [inline]\fP, \fC [static]\fP"

.PP
The function performs the bag of words encoding algorithm i\&.e\&. it writes the encoded token to the output\&. The encoder writes data in the row-major order\&.
.PP
Overloaded function to accept vector<vector<ElemType>> as the output type\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIElemType\fP Type of the output values\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIoutput\fP Output matrix to store the encoded results\&. 
.br
\fIvalue\fP The encoded token\&. 
.br
\fIline\fP The line number at which the encoding is performed\&. 
.br
\fI*\fP (index) The line token number at which the encoding is performed\&. 
.RE
.PP

.PP
Definition at line 128 of file bag_of_words_encoding_policy\&.hpp\&.
.SS "static void InitMatrix (MatType & output, const size_t datasetSize, const size_t, const size_t dictionarySize)\fC [inline]\fP, \fC [static]\fP"

.PP
The function initializes the output matrix\&. The encoder writes data in the column-major order\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIMatType\fP The output matrix type\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIoutput\fP Output matrix to store the encoded results (sp_mat or mat)\&. 
.br
\fIdatasetSize\fP The number of strings in the input dataset\&. 
.br
\fI*\fP (maxNumTokens) The maximum number of tokens in the strings of the input dataset (not used)\&. 
.br
\fIdictionarySize\fP The size of the dictionary\&. 
.RE
.PP

.PP
Definition at line 59 of file bag_of_words_encoding_policy\&.hpp\&.
.SS "static void InitMatrix (std::vector< std::vector< ElemType >> & output, const size_t datasetSize, const size_t, const size_t dictionarySize)\fC [inline]\fP, \fC [static]\fP"

.PP
The function initializes the output matrix\&. The encoder writes data in the row-major order\&.
.PP
Overloaded function to save the result in vector<vector<ElemType>>\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIElemType\fP Type of the output values\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIoutput\fP Output matrix to store the encoded results\&. 
.br
\fIdatasetSize\fP The number of strings in the input dataset\&. 
.br
\fI*\fP (maxNumTokens) The maximum number of tokens in the strings of the input dataset (not used)\&. 
.br
\fIdictionarySize\fP The size of the dictionary\&. 
.RE
.PP

.PP
Definition at line 82 of file bag_of_words_encoding_policy\&.hpp\&.
.SS "static void PreprocessToken (size_t, size_t, size_t)\fC [inline]\fP, \fC [static]\fP"

.PP
The function is not used by the bag of words encoding policy\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP (line) The line number at which the encoding is performed\&. 
.br
\fI*\fP (index) The token sequence number in the line\&. 
.br
\fI*\fP (value) The encoded token\&. 
.RE
.PP

.PP
Definition at line 144 of file bag_of_words_encoding_policy\&.hpp\&.
.SS "static void Reset ()\fC [inline]\fP, \fC [static]\fP"

.PP
Clear the necessary internal variables\&. 
.PP
Definition at line 41 of file bag_of_words_encoding_policy\&.hpp\&.
.SS "void serialize (Archive &, const uint32_t)\fC [inline]\fP"

.PP
Serialize the class to the given archive\&. 
.PP
Definition at line 153 of file bag_of_words_encoding_policy\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
