.TH "BiasSetVisitor" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BiasSetVisitor \- \fBBiasSetVisitor\fP updates the module bias parameters given the parameters set\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits static_visitor< size_t >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBiasSetVisitor\fP (arma::mat &weight, const size_t offset=0)"
.br
.RI "Update the bias parameters given the parameters' set and offset\&. "
.ti -1c
.RI "template<typename LayerType > size_t \fBoperator()\fP (LayerType *layer) const"
.br
.RI "Update the parameters' set\&. "
.ti -1c
.RI "size_t \fBoperator()\fP (\fBMoreTypes\fP layer) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBiasSetVisitor\fP updates the module bias parameters given the parameters set\&. 
.PP
Definition at line 26 of file bias_set_visitor\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBBiasSetVisitor\fP (arma::mat & weight, const size_t offset = \fC0\fP)"

.PP
Update the bias parameters given the parameters' set and offset\&. 
.SH "Member Function Documentation"
.PP 
.SS "size_t operator() (LayerType * layer) const"

.PP
Update the parameters' set\&. 
.SS "size_t operator() (\fBMoreTypes\fP layer) const"


.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
