.TH "DeduceHyperParameterTypes< Args >::ResultHolder< HPTypes >" 3 "Sun Aug 22 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeduceHyperParameterTypes< Args >::ResultHolder< HPTypes >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBTupleType\fP = std::tuple< HPTypes\&.\&.\&. >"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename\&.\&.\&. Args>
.br
template<typename\&.\&.\&. HPTypes>
.br
struct mlpack::hpt::DeduceHyperParameterTypes< Args >::ResultHolder< HPTypes >"

.PP
Definition at line 37 of file deduce_hp_types\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBTupleType\fP =  std::tuple<HPTypes\&.\&.\&.>"

.PP
Definition at line 39 of file deduce_hp_types\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
