.TH "SwishFunction" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SwishFunction \- The swish function, defined by\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static double \fBDeriv\fP (const double y)"
.br
.RI "Computes the first derivative of the swish function\&. "
.ti -1c
.RI "template<typename InputVecType , typename OutputVecType > static void \fBDeriv\fP (const InputVecType &y, OutputVecType &x)"
.br
.RI "Computes the first derivatives of the swish function\&. "
.ti -1c
.RI "template<typename eT > static void \fBFn\fP (const arma::Mat< eT > &x, arma::Mat< eT > &y)"
.br
.RI "Computes the swish function using a matrix as input\&. "
.ti -1c
.RI "static double \fBFn\fP (const double x)"
.br
.RI "Computes the swish function\&. "
.ti -1c
.RI "template<typename InputVecType , typename OutputVecType > static void \fBFn\fP (const InputVecType &x, OutputVecType &y)"
.br
.RI "Computes the swish function\&. "
.in -1c
.SH "Detailed Description"
.PP 
The swish function, defined by\&. 

\begin{eqnarray*} f(x) &=& x \cdot \sigma(x) \\ f'(x) &=& f(x) + \sigma(x) (1 - f(x)) \\ \sigma(x) &=& frac{1}{1 + e^{-x}} \end{eqnarray*} 
.PP
Definition at line 30 of file swish_function\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static double Deriv (const double y)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the first derivative of the swish function\&. 
.PP
\fBParameters\fP
.RS 4
\fIy\fP Input data\&. 
.RE
.PP
\fBReturns\fP
.RS 4
f'(x) 
.RE
.PP

.PP
Definition at line 77 of file swish_function\&.hpp\&.
.SS "static void Deriv (const InputVecType & y, OutputVecType & x)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the first derivatives of the swish function\&. 
.PP
\fBParameters\fP
.RS 4
\fIy\fP Input data\&. 
.br
\fIx\fP The resulting derivatives\&. 
.RE
.PP

.PP
Definition at line 90 of file swish_function\&.hpp\&.
.SS "static void Fn (const arma::Mat< eT > & x, arma::Mat< eT > & y)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the swish function using a matrix as input\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Input data\&. 
.br
\fIy\fP The resulting output activation\&. 
.RE
.PP

.PP
Definition at line 51 of file swish_function\&.hpp\&.
.SS "static double Fn (const double x)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the swish function\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Input data\&. 
.RE
.PP
\fBReturns\fP
.RS 4
f(x)\&. 
.RE
.PP

.PP
Definition at line 39 of file swish_function\&.hpp\&.
.PP
Referenced by SwishFunction::Fn()\&.
.SS "static void Fn (const InputVecType & x, OutputVecType & y)\fC [inline]\fP, \fC [static]\fP"

.PP
Computes the swish function\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Input data\&. 
.br
\fIy\fP The resulting output activation\&. 
.RE
.PP

.PP
Definition at line 63 of file swish_function\&.hpp\&.
.PP
References SwishFunction::Fn()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
