.TH "NumericSplitInfo< ObservationType >" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumericSplitInfo< ObservationType >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNumericSplitInfo\fP ()"
.br
.ti -1c
.RI "\fBNumericSplitInfo\fP (const arma::Col< ObservationType > &splitPoints)"
.br
.ti -1c
.RI "template<typename eT > size_t \fBCalculateDirection\fP (const eT &value) const"
.br
.ti -1c
.RI "template<typename Archive > void \fBserialize\fP (Archive &ar, const uint32_t)"
.br
.RI "Serialize the split (save/load the split points)\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename ObservationType = double>
.br
class mlpack::tree::NumericSplitInfo< ObservationType >"

.PP
Definition at line 21 of file numeric_split_info\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBNumericSplitInfo\fP ()\fC [inline]\fP"

.PP
Definition at line 24 of file numeric_split_info\&.hpp\&.
.SS "\fBNumericSplitInfo\fP (const arma::Col< ObservationType > & splitPoints)\fC [inline]\fP"

.PP
Definition at line 25 of file numeric_split_info\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "size_t CalculateDirection (const eT & value) const\fC [inline]\fP"

.PP
Definition at line 29 of file numeric_split_info\&.hpp\&.
.SS "void serialize (Archive & ar, const uint32_t)\fC [inline]\fP"

.PP
Serialize the split (save/load the split points)\&. 
.PP
Definition at line 41 of file numeric_split_info\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
