.TH "OrderedPointSelection" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OrderedPointSelection \- This class can be used to sequentially select the next point to use for \fBDBSCAN\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename MatType > static size_t \fBSelect\fP (const size_t point, const MatType &)"
.br
.RI "Select the next point to use, sequentially\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class can be used to sequentially select the next point to use for \fBDBSCAN\fP\&. 
.PP
Definition at line 23 of file ordered_point_selection\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static size_t Select (const size_t point, const MatType &)\fC [inline]\fP, \fC [static]\fP"

.PP
Select the next point to use, sequentially\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpoint\fP unvisited Bitset indicating which points are unvisited\&. 
.br
\fI*\fP (data) Unused data\&. 
.RE
.PP

.PP
Definition at line 33 of file ordered_point_selection\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
