.TH "TrainForm< MT, PT, WT, false, true >" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TrainForm< MT, PT, WT, false, true >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTrainFormBase6< PT, WT, const MT &, const PT &, const size_t, const WT & >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename MT, typename PT, typename WT>
.br
struct mlpack::cv::TrainForm< MT, PT, WT, false, true >"

.PP
Definition at line 124 of file meta_info_extractor\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
