.TH "SpillNSWrapper< SortPolicy >" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpillNSWrapper< SortPolicy > \- The \fBSpillNSWrapper\fP class wraps the \fBNeighborSearch\fP class when the spill tree is used\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNSWrapper< SortPolicy, tree::SPTree, tree::SPTree< metric::EuclideanDistance, NeighborSearchStat< SortPolicy >, arma::mat >::template DefeatistDualTreeTraverser, tree::SPTree< metric::EuclideanDistance, NeighborSearchStat< SortPolicy >, arma::mat >::template DefeatistSingleTreeTraverser >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpillNSWrapper\fP (const \fBNeighborSearchMode\fP searchMode, const double epsilon)"
.br
.RI "Construct the \fBSpillNSWrapper\fP\&. "
.ti -1c
.RI "virtual \fB~SpillNSWrapper\fP ()"
.br
.RI "Destruct the \fBSpillNSWrapper\fP\&. "
.ti -1c
.RI "virtual \fBSpillNSWrapper\fP * \fBClone\fP () const"
.br
.RI "Return a copy of the \fBSpillNSWrapper\fP\&. "
.ti -1c
.RI "virtual void \fBSearch\fP (arma::mat &&querySet, const size_t k, arma::Mat< size_t > &neighbors, arma::mat &distances, const size_t leafSize, const double rho)"
.br
.RI "Perform bichromatic search (i\&.e\&. "
.ti -1c
.RI "template<typename Archive > void \fBserialize\fP (Archive &ar, const uint32_t)"
.br
.RI "Serialize the \fBNeighborSearch\fP model\&. "
.ti -1c
.RI "virtual void \fBTrain\fP (arma::mat &&referenceSet, const size_t leafSize, const double tau, const double rho)"
.br
.RI "Train the model using the given parameters\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename SortPolicy>
.br
class mlpack::neighbor::SpillNSWrapper< SortPolicy >"
The \fBSpillNSWrapper\fP class wraps the \fBNeighborSearch\fP class when the spill tree is used\&. 
.PP
Definition at line 253 of file ns_model\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBSpillNSWrapper\fP (const \fBNeighborSearchMode\fP searchMode, const double epsilon)\fC [inline]\fP"

.PP
Construct the \fBSpillNSWrapper\fP\&. 
.PP
Definition at line 266 of file ns_model\&.hpp\&.
.PP
Referenced by SpillNSWrapper< SortPolicy >::Clone()\&.
.SS "virtual ~\fBSpillNSWrapper\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Destruct the \fBSpillNSWrapper\fP\&. 
.PP
Definition at line 283 of file ns_model\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBSpillNSWrapper\fP* Clone () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Return a copy of the \fBSpillNSWrapper\fP\&. 
.PP
Reimplemented from \fBNSWrapper< SortPolicy, tree::SPTree, tree::SPTree< metric::EuclideanDistance, NeighborSearchStat< SortPolicy >, arma::mat >::template DefeatistDualTreeTraverser, tree::SPTree< metric::EuclideanDistance, NeighborSearchStat< SortPolicy >, arma::mat >::template DefeatistSingleTreeTraverser >\fP\&.
.PP
Definition at line 286 of file ns_model\&.hpp\&.
.PP
References SpillNSWrapper< SortPolicy >::SpillNSWrapper()\&.
.SS "virtual void Search (arma::mat && querySet, const size_t k, arma::Mat< size_t > & neighbors, arma::mat & distances, const size_t leafSize, const double rho)\fC [virtual]\fP"

.PP
Perform bichromatic search (i\&.e\&. search with a different query set) using the given parameters\&. 
.PP
Reimplemented from \fBNSWrapper< SortPolicy, tree::SPTree, tree::SPTree< metric::EuclideanDistance, NeighborSearchStat< SortPolicy >, arma::mat >::template DefeatistDualTreeTraverser, tree::SPTree< metric::EuclideanDistance, NeighborSearchStat< SortPolicy >, arma::mat >::template DefeatistSingleTreeTraverser >\fP\&.
.SS "void serialize (Archive & ar, const uint32_t)\fC [inline]\fP"

.PP
Serialize the \fBNeighborSearch\fP model\&. 
.PP
Definition at line 305 of file ns_model\&.hpp\&.
.PP
References NSWrapper< SortPolicy, tree::SPTree, tree::SPTree< metric::EuclideanDistance, NeighborSearchStat< SortPolicy >, arma::mat >::template DefeatistDualTreeTraverser, tree::SPTree< metric::EuclideanDistance, NeighborSearchStat< SortPolicy >, arma::mat >::template DefeatistSingleTreeTraverser >::ns\&.
.SS "virtual void Train (arma::mat && referenceSet, const size_t leafSize, const double tau, const double rho)\fC [virtual]\fP"

.PP
Train the model using the given parameters\&. 
.PP
Reimplemented from \fBNSWrapper< SortPolicy, tree::SPTree, tree::SPTree< metric::EuclideanDistance, NeighborSearchStat< SortPolicy >, arma::mat >::template DefeatistDualTreeTraverser, tree::SPTree< metric::EuclideanDistance, NeighborSearchStat< SortPolicy >, arma::mat >::template DefeatistSingleTreeTraverser >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
