.TH "mlpack::ann::augmented::scorers" 3 "Sun Aug 22 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::ann::augmented::scorers
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename MatType > double \fBSequencePrecision\fP (arma::field< MatType > trueOutputs, arma::field< MatType > predOutputs, double tol=1e\-4)"
.br
.RI "Function that computes the sequences precision (number of correct sequences / number of sequences) of model's answer against ground truth answer\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "double mlpack::ann::augmented::scorers::SequencePrecision (arma::field< MatType > trueOutputs, arma::field< MatType > predOutputs, double tol = \fC1e\-4\fP)"

.PP
Function that computes the sequences precision (number of correct sequences / number of sequences) of model's answer against ground truth answer\&. 
.PP
\fBParameters:\fP
.RS 4
\fItrueOutputs\fP Ground truth sequences\&. 
.br
\fIpredOutputs\fP Sequences predicted by model\&. 
.br
\fItol\fP Minimum absolute difference value which is considered as a model failure\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
