.TH "TrainForm< MT, PT, void, true, false >" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TrainForm< MT, PT, void, true, false >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTrainFormBase5< PT, void, const MT &, const data::DatasetInfo &, const PT & >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename MT, typename PT>
.br
struct mlpack::cv::TrainForm< MT, PT, void, true, false >"

.PP
Definition at line 104 of file meta_info_extractor\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
