.TH "LogCoshLoss< InputDataType, OutputDataType >" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LogCoshLoss< InputDataType, OutputDataType > \- The Log-Hyperbolic-Cosine loss function is often used to improve variational auto encoder\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogCoshLoss\fP (const double a=1\&.0)"
.br
.RI "Create the Log-Hyperbolic-Cosine object with the specified parameters\&. "
.ti -1c
.RI "double \fBA\fP () const"
.br
.RI "Get the value of hyperparameter a\&. "
.ti -1c
.RI "double & \fBA\fP ()"
.br
.RI "Modify the value of hyperparameter a\&. "
.ti -1c
.RI "template<typename PredictionType , typename TargetType , typename LossType > void \fBBackward\fP (const PredictionType &prediction, const TargetType &target, LossType &loss)"
.br
.RI "Ordinary feed backward pass of a neural network\&. "
.ti -1c
.RI "template<typename PredictionType , typename TargetType > PredictionType::elem_type \fBForward\fP (const PredictionType &prediction, const TargetType &target)"
.br
.RI "Computes the Log-Hyperbolic-Cosine loss function\&. "
.ti -1c
.RI "OutputDataType & \fBOutputParameter\fP () const"
.br
.RI "Get the output parameter\&. "
.ti -1c
.RI "OutputDataType & \fBOutputParameter\fP ()"
.br
.RI "Modify the output parameter\&. "
.ti -1c
.RI "template<typename Archive > void \fBserialize\fP (Archive &ar, const uint32_t)"
.br
.RI "Serialize the loss function\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat>
.br
class mlpack::ann::LogCoshLoss< InputDataType, OutputDataType >"
The Log-Hyperbolic-Cosine loss function is often used to improve variational auto encoder\&. 

This function is the log of hyperbolic cosine of difference between true values and predicted values\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIInputDataType\fP Type of the input data (arma::colvec, arma::mat, arma::sp_mat or arma::cube)\&. 
.br
\fIOutputDataType\fP Type of the output data (arma::colvec, arma::mat, arma::sp_mat or arma::cube)\&. 
.RE
.PP

.PP
Definition at line 35 of file log_cosh_loss\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBLogCoshLoss\fP (const double a = \fC1\&.0\fP)"

.PP
Create the Log-Hyperbolic-Cosine object with the specified parameters\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP A double type value for smoothening loss function\&. It must be positive a real number, Sharpness of loss function is directly proportional to a\&. It can also act as a scaling factor hence making the loss function more sensitive to small losses around the origin\&. Default value = 1\&.0\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double A () const\fC [inline]\fP"

.PP
Get the value of hyperparameter a\&. 
.PP
Definition at line 81 of file log_cosh_loss\&.hpp\&.
.SS "double& A ()\fC [inline]\fP"

.PP
Modify the value of hyperparameter a\&. 
.PP
Definition at line 83 of file log_cosh_loss\&.hpp\&.
.PP
References LogCoshLoss< InputDataType, OutputDataType >::serialize()\&.
.SS "void Backward (const PredictionType & prediction, const TargetType & target, LossType & loss)"

.PP
Ordinary feed backward pass of a neural network\&. 
.PP
\fBParameters:\fP
.RS 4
\fIprediction\fP Predictions used for evaluating the specified loss function\&. 
.br
\fItarget\fP The target vector\&. 
.br
\fIloss\fP The calculated error\&. 
.RE
.PP

.SS "PredictionType::elem_type Forward (const PredictionType & prediction, const TargetType & target)"

.PP
Computes the Log-Hyperbolic-Cosine loss function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIprediction\fP Predictions used for evaluating the specified loss function\&. 
.br
\fItarget\fP Target data to compare with\&. 
.RE
.PP

.SS "OutputDataType& OutputParameter () const\fC [inline]\fP"

.PP
Get the output parameter\&. 
.PP
Definition at line 76 of file log_cosh_loss\&.hpp\&.
.SS "OutputDataType& OutputParameter ()\fC [inline]\fP"

.PP
Modify the output parameter\&. 
.PP
Definition at line 78 of file log_cosh_loss\&.hpp\&.
.SS "void serialize (Archive & ar, const uint32_t)"

.PP
Serialize the loss function\&. 
.PP
Referenced by LogCoshLoss< InputDataType, OutputDataType >::A()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
