.TH "Radical" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Radical \- An implementation of RADICAL, an algorithm for independent component analysis (ICA)\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRadical\fP (const double noiseStdDev=0\&.175, const size_t replicates=30, const size_t angles=150, const size_t sweeps=0, const size_t m=0)"
.br
.RI "Set the parameters to RADICAL\&. "
.ti -1c
.RI "size_t & \fBAngles\fP ()"
.br
.RI "Modify the number of angles considered during brute-force search\&. "
.ti -1c
.RI "size_t \fBAngles\fP () const"
.br
.RI "Get the number of angles considered during brute-force search\&. "
.ti -1c
.RI "void \fBCopyAndPerturb\fP (arma::mat &xNew, const arma::mat &x) const"
.br
.RI "Make replicates of each data point (the number of replicates is set in either the constructor or with \fBReplicates()\fP) and perturb data with Gaussian noise with standard deviation noiseStdDev\&. "
.ti -1c
.RI "void \fBDoRadical\fP (const arma::mat &matX, arma::mat &matY, arma::mat &matW)"
.br
.RI "Run RADICAL\&. "
.ti -1c
.RI "double \fBDoRadical2D\fP (const arma::mat &matX)"
.br
.RI "Two-dimensional version of RADICAL\&. "
.ti -1c
.RI "double & \fBNoiseStdDev\fP ()"
.br
.RI "Modify the standard deviation of the additive Gaussian noise\&. "
.ti -1c
.RI "double \fBNoiseStdDev\fP () const"
.br
.RI "Get the standard deviation of the additive Gaussian noise\&. "
.ti -1c
.RI "size_t & \fBReplicates\fP ()"
.br
.RI "Modify the number of Gaussian-perturbed replicates used per point\&. "
.ti -1c
.RI "size_t \fBReplicates\fP () const"
.br
.RI "Get the number of Gaussian-perturbed replicates used per point\&. "
.ti -1c
.RI "size_t & \fBSweeps\fP ()"
.br
.RI "Modify the number of sweeps\&. "
.ti -1c
.RI "size_t \fBSweeps\fP () const"
.br
.RI "Get the number of sweeps\&. "
.ti -1c
.RI "double \fBVasicek\fP (arma::vec &x) const"
.br
.RI "Vasicek's m-spacing estimator of entropy, with overlap modification from (Learned-Miller and Fisher, 2003)\&. "
.in -1c
.SH "Detailed Description"
.PP 
An implementation of RADICAL, an algorithm for independent component analysis (ICA)\&. 

Let X be a matrix where each column is a point and each row a dimension\&. The goal is to find a square unmixing matrix W such that Y = W X and the rows of Y are independent components\&.
.PP
For more details, see the following paper:
.PP
.PP
.nf
@article{learned2003ica,
  title = {ICA Using Spacings Estimates of Entropy},
  author = {Learned-Miller, E\&.G\&. and Fisher III, J\&.W\&.},
  journal = {Journal of Machine Learning Research},
  volume = {4},
  pages = {1271--1295},
  year = {2003}
}
.fi
.PP
 
.PP
Definition at line 43 of file radical\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBRadical\fP (const double noiseStdDev = \fC0\&.175\fP, const size_t replicates = \fC30\fP, const size_t angles = \fC150\fP, const size_t sweeps = \fC0\fP, const size_t m = \fC0\fP)"

.PP
Set the parameters to RADICAL\&. 
.PP
\fBParameters\fP
.RS 4
\fInoiseStdDev\fP Standard deviation of the Gaussian noise added to the replicates of the data points during Radical2D 
.br
\fIreplicates\fP Number of Gaussian-perturbed replicates to use (per point) in Radical2D 
.br
\fIangles\fP Number of angles to consider in brute-force search during Radical2D 
.br
\fIsweeps\fP Number of sweeps\&. Each sweep calls Radical2D once for each pair of dimensions 
.br
\fIm\fP The variable m from Vasicek's m-spacing estimator of entropy\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "size_t& Angles ()\fC [inline]\fP"

.PP
Modify the number of angles considered during brute-force search\&. 
.PP
Definition at line 107 of file radical\&.hpp\&.
.SS "size_t Angles () const\fC [inline]\fP"

.PP
Get the number of angles considered during brute-force search\&. 
.PP
Definition at line 105 of file radical\&.hpp\&.
.SS "void CopyAndPerturb (arma::mat & xNew, const arma::mat & x) const"

.PP
Make replicates of each data point (the number of replicates is set in either the constructor or with \fBReplicates()\fP) and perturb data with Gaussian noise with standard deviation noiseStdDev\&. 
.SS "void DoRadical (const arma::mat & matX, arma::mat & matY, arma::mat & matW)"

.PP
Run RADICAL\&. 
.PP
\fBParameters\fP
.RS 4
\fImatX\fP Input data into the algorithm - a matrix where each column is a point and each row is a dimension\&. 
.br
\fImatY\fP Estimated independent components - a matrix where each column is a point and each row is an estimated independent component\&. 
.br
\fImatW\fP Estimated unmixing matrix, where matY = matW * matX\&. 
.RE
.PP

.SS "double DoRadical2D (const arma::mat & matX)"

.PP
Two-dimensional version of RADICAL\&. 
.SS "double& NoiseStdDev ()\fC [inline]\fP"

.PP
Modify the standard deviation of the additive Gaussian noise\&. 
.PP
Definition at line 97 of file radical\&.hpp\&.
.SS "double NoiseStdDev () const\fC [inline]\fP"

.PP
Get the standard deviation of the additive Gaussian noise\&. 
.PP
Definition at line 95 of file radical\&.hpp\&.
.SS "size_t& Replicates ()\fC [inline]\fP"

.PP
Modify the number of Gaussian-perturbed replicates used per point\&. 
.PP
Definition at line 102 of file radical\&.hpp\&.
.SS "size_t Replicates () const\fC [inline]\fP"

.PP
Get the number of Gaussian-perturbed replicates used per point\&. 
.PP
Definition at line 100 of file radical\&.hpp\&.
.SS "size_t& Sweeps ()\fC [inline]\fP"

.PP
Modify the number of sweeps\&. 
.PP
Definition at line 112 of file radical\&.hpp\&.
.SS "size_t Sweeps () const\fC [inline]\fP"

.PP
Get the number of sweeps\&. 
.PP
Definition at line 110 of file radical\&.hpp\&.
.SS "double Vasicek (arma::vec & x) const"

.PP
Vasicek's m-spacing estimator of entropy, with overlap modification from (Learned-Miller and Fisher, 2003)\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Empirical sample (one-dimensional) over which to estimate entropy\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
