.TH "mlpack::naive_bayes" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::naive_bayes \- The Naive Bayes Classifier\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNaiveBayesClassifier\fP"
.br
.RI "The simple Naive Bayes classifier\&. "
.in -1c
.SH "Detailed Description"
.PP 
The Naive Bayes Classifier\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
