.TH "BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::BreadthFirstDualTreeTraverser< RuleType >" 3 "Sun Aug 22 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::BreadthFirstDualTreeTraverser< RuleType >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBQueueFrame\fP< \fBBinarySpaceTree\fP, typename RuleType::TraversalInfoType > \fBQueueFrameType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBreadthFirstDualTreeTraverser\fP (RuleType &rule)"
.br
.RI "Instantiate the dual-tree traverser with the given rule set\&. "
.ti -1c
.RI "size_t \fBNumBaseCases\fP () const"
.br
.RI "Get the number of times a base case was calculated\&. "
.ti -1c
.RI "size_t & \fBNumBaseCases\fP ()"
.br
.RI "Modify the number of times a base case was calculated\&. "
.ti -1c
.RI "size_t \fBNumPrunes\fP () const"
.br
.RI "Get the number of prunes\&. "
.ti -1c
.RI "size_t & \fBNumPrunes\fP ()"
.br
.RI "Modify the number of prunes\&. "
.ti -1c
.RI "size_t \fBNumScores\fP () const"
.br
.RI "Get the number of times a node combination was scored\&. "
.ti -1c
.RI "size_t & \fBNumScores\fP ()"
.br
.RI "Modify the number of times a node combination was scored\&. "
.ti -1c
.RI "size_t \fBNumVisited\fP () const"
.br
.RI "Get the number of visited combinations\&. "
.ti -1c
.RI "size_t & \fBNumVisited\fP ()"
.br
.RI "Modify the number of visited combinations\&. "
.ti -1c
.RI "void \fBTraverse\fP (\fBBinarySpaceTree\fP &queryNode, \fBBinarySpaceTree\fP &referenceNode)"
.br
.RI "Traverse the two trees\&. "
.ti -1c
.RI "void \fBTraverse\fP (\fBBinarySpaceTree\fP &queryNode, std::priority_queue< \fBQueueFrameType\fP > &referenceQueue)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename MetricType, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename BoundMetricType, typename\&.\&.\&. > class BoundType = bound::HRectBound, template< typename SplitBoundType, typename SplitMatType > class SplitType = MidpointSplit>
.br
template<typename RuleType>
.br
class mlpack::tree::BinarySpaceTree< MetricType, StatisticType, MatType, BoundType, SplitType >::BreadthFirstDualTreeTraverser< RuleType >"

.PP
Definition at line 103 of file binary_space_tree\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef \fBQueueFrame\fP<\fBBinarySpaceTree\fP, typename RuleType::TraversalInfoType> \fBQueueFrameType\fP"

.PP
Definition at line 53 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBBreadthFirstDualTreeTraverser\fP (RuleType & rule)"

.PP
Instantiate the dual-tree traverser with the given rule set\&. 
.SH "Member Function Documentation"
.PP 
.SS "size_t NumBaseCases () const\fC [inline]\fP"

.PP
Get the number of times a base case was calculated\&. 
.PP
Definition at line 82 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "size_t& NumBaseCases ()\fC [inline]\fP"

.PP
Modify the number of times a base case was calculated\&. 
.PP
Definition at line 84 of file breadth_first_dual_tree_traverser\&.hpp\&.
.PP
References QueueFrame< TreeType, TraversalInfoType >::traversalInfo\&.
.SS "size_t NumPrunes () const\fC [inline]\fP"

.PP
Get the number of prunes\&. 
.PP
Definition at line 67 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "size_t& NumPrunes ()\fC [inline]\fP"

.PP
Modify the number of prunes\&. 
.PP
Definition at line 69 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "size_t NumScores () const\fC [inline]\fP"

.PP
Get the number of times a node combination was scored\&. 
.PP
Definition at line 77 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "size_t& NumScores ()\fC [inline]\fP"

.PP
Modify the number of times a node combination was scored\&. 
.PP
Definition at line 79 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "size_t NumVisited () const\fC [inline]\fP"

.PP
Get the number of visited combinations\&. 
.PP
Definition at line 72 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "size_t& NumVisited ()\fC [inline]\fP"

.PP
Modify the number of visited combinations\&. 
.PP
Definition at line 74 of file breadth_first_dual_tree_traverser\&.hpp\&.
.SS "void Traverse (\fBBinarySpaceTree\fP & queryNode, \fBBinarySpaceTree\fP & referenceNode)"

.PP
Traverse the two trees\&. This does not reset the number of prunes\&.
.PP
\fBParameters:\fP
.RS 4
\fIqueryNode\fP The query node to be traversed\&. 
.br
\fIreferenceNode\fP The reference node to be traversed\&. 
.RE
.PP

.SS "void Traverse (\fBBinarySpaceTree\fP & queryNode, std::priority_queue< \fBQueueFrameType\fP > & referenceQueue)"


.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
