.TH "ParamData" 3 "Sun Aug 22 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParamData \- This structure holds all of the information about a single parameter, including its value (which is set when ParseCommandLine() is called)\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBalias\fP"
.br
.RI "Alias for this parameter\&. "
.ti -1c
.RI "std::string \fBcppType\fP"
.br
.RI "The true name of the type, as it would be written in C++\&. "
.ti -1c
.RI "std::string \fBdesc\fP"
.br
.RI "Description of this parameter, if any\&. "
.ti -1c
.RI "bool \fBinput\fP"
.br
.RI "True if this option is an input option (otherwise, it is output)\&. "
.ti -1c
.RI "bool \fBloaded\fP"
.br
.RI "If this is an input parameter that needs extra loading, this indicates whether or not it has been loaded\&. "
.ti -1c
.RI "std::string \fBname\fP"
.br
.RI "Name of this parameter\&. "
.ti -1c
.RI "bool \fBnoTranspose\fP"
.br
.RI "True if this is a matrix that should not be transposed\&. "
.ti -1c
.RI "bool \fBrequired\fP"
.br
.RI "True if this option is required\&. "
.ti -1c
.RI "std::string \fBtname\fP"
.br
.RI "Type information of this parameter\&. "
.ti -1c
.RI "boost::any \fBvalue\fP"
.br
.RI "The actual value that is held\&. "
.ti -1c
.RI "bool \fBwasPassed\fP"
.br
.RI "True if the option was passed to the program\&. "
.in -1c
.SH "Detailed Description"
.PP 
This structure holds all of the information about a single parameter, including its value (which is set when ParseCommandLine() is called)\&. 

It does not hold any information about whether or not it was passed---that is handled elsewhere\&. A \fBParamData\fP struct is only useful in order to get 'static' information about a parameter\&. Note that some parameter types have internal types but also different types that are used by CLI11 (specifically, matrix and model types map to strings)\&.
.PP
This structure is somewhat unwieldy and is likely to be refactored at some point in the future, but for now it does the job fine\&. 
.PP
Definition at line 52 of file param_data\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "char alias"

.PP
Alias for this parameter\&. 
.PP
Definition at line 63 of file param_data\&.hpp\&.
.SS "std::string cppType"

.PP
The true name of the type, as it would be written in C++\&. 
.PP
Definition at line 81 of file param_data\&.hpp\&.
.SS "std::string desc"

.PP
Description of this parameter, if any\&. 
.PP
Definition at line 58 of file param_data\&.hpp\&.
.SS "bool input"

.PP
True if this option is an input option (otherwise, it is output)\&. 
.PP
Definition at line 73 of file param_data\&.hpp\&.
.SS "bool loaded"

.PP
If this is an input parameter that needs extra loading, this indicates whether or not it has been loaded\&. 
.PP
Definition at line 76 of file param_data\&.hpp\&.
.SS "std::string name"

.PP
Name of this parameter\&. This is the name used for HasParam() and GetParam()\&. 
.PP
Definition at line 56 of file param_data\&.hpp\&.
.SS "bool noTranspose"

.PP
True if this is a matrix that should not be transposed\&. Ignored if the parameter is not a matrix\&. 
.PP
Definition at line 69 of file param_data\&.hpp\&.
.SS "bool required"

.PP
True if this option is required\&. 
.PP
Definition at line 71 of file param_data\&.hpp\&.
.SS "std::string tname"

.PP
Type information of this parameter\&. Note that this is \fBTYPENAME()\fP of the user-visible parameter type, not whatever is given by ParameterType<>\&. 
.PP
Definition at line 61 of file param_data\&.hpp\&.
.SS "boost::any value"

.PP
The actual value that is held\&. If the user has passed a different type, this may be a tuple containing multiple values\&. 
.PP
Definition at line 79 of file param_data\&.hpp\&.
.SS "bool wasPassed"

.PP
True if the option was passed to the program\&. Note that wasPassed may be set by either ParseCommandLine() or SetPassed()\&. 
.PP
Definition at line 66 of file param_data\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
