.TH "DualTreeKMeansRules< MetricType, TreeType >" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DualTreeKMeansRules< MetricType, TreeType >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBtree::TraversalInfo\fP< TreeType > \fBTraversalInfoType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDualTreeKMeansRules\fP (const arma::mat &centroids, const arma::mat &dataset, arma::Row< size_t > &assignments, arma::vec &upperBounds, arma::vec &lowerBounds, MetricType &metric, const std::vector< bool > &prunedPoints, const std::vector< size_t > &oldFromNewCentroids, std::vector< bool > &visited)"
.br
.ti -1c
.RI "double \fBBaseCase\fP (const size_t queryIndex, const size_t referenceIndex)"
.br
.ti -1c
.RI "size_t \fBBaseCases\fP () const"
.br
.ti -1c
.RI "size_t & \fBBaseCases\fP ()"
.br
.ti -1c
.RI "size_t \fBMinimumBaseCases\fP () const"
.br
.RI "Get the minimum number of base cases needed for correct results for each query point\&. "
.ti -1c
.RI "double \fBRescore\fP (const size_t queryIndex, TreeType &referenceNode, const double oldScore)"
.br
.ti -1c
.RI "double \fBRescore\fP (TreeType &queryNode, TreeType &referenceNode, const double oldScore)"
.br
.ti -1c
.RI "double \fBScore\fP (const size_t queryIndex, TreeType &referenceNode)"
.br
.ti -1c
.RI "double \fBScore\fP (TreeType &queryNode, TreeType &referenceNode)"
.br
.ti -1c
.RI "size_t \fBScores\fP () const"
.br
.ti -1c
.RI "size_t & \fBScores\fP ()"
.br
.ti -1c
.RI "\fBTraversalInfoType\fP & \fBTraversalInfo\fP ()"
.br
.ti -1c
.RI "const \fBTraversalInfoType\fP & \fBTraversalInfo\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename MetricType, typename TreeType>
.br
class mlpack::kmeans::DualTreeKMeansRules< MetricType, TreeType >"

.PP
Definition at line 23 of file dual_tree_kmeans_rules\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef \fBtree::TraversalInfo\fP<TreeType> \fBTraversalInfoType\fP"

.PP
Definition at line 47 of file dual_tree_kmeans_rules\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBDualTreeKMeansRules\fP (const arma::mat & centroids, const arma::mat & dataset, arma::Row< size_t > & assignments, arma::vec & upperBounds, arma::vec & lowerBounds, MetricType & metric, const std::vector< bool > & prunedPoints, const std::vector< size_t > & oldFromNewCentroids, std::vector< bool > & visited)"

.SH "Member Function Documentation"
.PP 
.SS "double BaseCase (const size_t queryIndex, const size_t referenceIndex)"

.SS "size_t BaseCases () const\fC [inline]\fP"

.PP
Definition at line 52 of file dual_tree_kmeans_rules\&.hpp\&.
.SS "size_t& BaseCases ()\fC [inline]\fP"

.PP
Definition at line 53 of file dual_tree_kmeans_rules\&.hpp\&.
.SS "size_t MinimumBaseCases () const\fC [inline]\fP"

.PP
Get the minimum number of base cases needed for correct results for each query point\&. This only matters in defeatist search mode\&. 
.PP
Definition at line 60 of file dual_tree_kmeans_rules\&.hpp\&.
.SS "double Rescore (const size_t queryIndex, TreeType & referenceNode, const double oldScore)"

.SS "double Rescore (TreeType & queryNode, TreeType & referenceNode, const double oldScore)"

.SS "double Score (const size_t queryIndex, TreeType & referenceNode)"

.SS "double Score (TreeType & queryNode, TreeType & referenceNode)"

.SS "size_t Scores () const\fC [inline]\fP"

.PP
Definition at line 55 of file dual_tree_kmeans_rules\&.hpp\&.
.SS "size_t& Scores ()\fC [inline]\fP"

.PP
Definition at line 56 of file dual_tree_kmeans_rules\&.hpp\&.
.SS "\fBTraversalInfoType\fP& TraversalInfo ()\fC [inline]\fP"

.PP
Definition at line 49 of file dual_tree_kmeans_rules\&.hpp\&.
.SS "const \fBTraversalInfoType\fP& TraversalInfo () const\fC [inline]\fP"

.PP
Definition at line 50 of file dual_tree_kmeans_rules\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
