.TH "Subview< InputDataType, OutputDataType >" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Subview< InputDataType, OutputDataType > \- Implementation of the subview layer\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSubview\fP (const size_t inSize=1, const size_t beginRow=0, const size_t endRow=0, const size_t beginCol=0, const size_t endCol=0)"
.br
.RI "Create the \fBSubview\fP layer object using the specified range of input to accept\&. "
.ti -1c
.RI "template<typename eT > void \fBBackward\fP (const arma::Mat< eT > &, const arma::Mat< eT > &gy, arma::Mat< eT > &g)"
.br
.RI "Ordinary feed backward pass of a neural network, calculating the function f(x) by propagating x backwards trough f\&. "
.ti -1c
.RI "size_t const  & \fBBeginCol\fP () const"
.br
.RI "Get the width of each sample\&. "
.ti -1c
.RI "size_t & \fBBeginCol\fP ()"
.br
.RI "Modify the width of each sample\&. "
.ti -1c
.RI "size_t const  & \fBBeginRow\fP () const"
.br
.RI "Get the starting row index of subview vector or matrix\&. "
.ti -1c
.RI "size_t & \fBBeginRow\fP ()"
.br
.RI "Modify the width of each sample\&. "
.ti -1c
.RI "OutputDataType const  & \fBDelta\fP () const"
.br
.RI "Get the delta\&. "
.ti -1c
.RI "OutputDataType & \fBDelta\fP ()"
.br
.RI "Modify the delta\&. "
.ti -1c
.RI "size_t const  & \fBEndCol\fP () const"
.br
.RI "Get the ending column index of subview vector or matrix\&. "
.ti -1c
.RI "size_t & \fBEndCol\fP ()"
.br
.RI "Modify the width of each sample\&. "
.ti -1c
.RI "size_t const  & \fBEndRow\fP () const"
.br
.RI "Get the ending row index of subview vector or matrix\&. "
.ti -1c
.RI "size_t & \fBEndRow\fP ()"
.br
.RI "Modify the width of each sample\&. "
.ti -1c
.RI "template<typename InputType , typename OutputType > void \fBForward\fP (const InputType &input, OutputType &output)"
.br
.RI "Ordinary feed forward pass of a neural network, evaluating the function f(x) by propagating the activity forward through f\&. "
.ti -1c
.RI "size_t \fBInSize\fP () const"
.br
.RI "Get the width of each sample\&. "
.ti -1c
.RI "OutputDataType const  & \fBOutputParameter\fP () const"
.br
.RI "Get the output parameter\&. "
.ti -1c
.RI "OutputDataType & \fBOutputParameter\fP ()"
.br
.RI "Modify the output parameter\&. "
.ti -1c
.RI "template<typename Archive > void \fBserialize\fP (Archive &ar, const uint32_t)"
.br
.RI "Serialize the layer\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat>
.br
class mlpack::ann::Subview< InputDataType, OutputDataType >"
Implementation of the subview layer\&. 

The subview layer modifies the input to a submatrix of required size\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIInputDataType\fP Type of the input data (arma::colvec, arma::mat, arma::sp_mat or arma::cube)\&. 
.br
\fIOutputDataType\fP Type of the output data (arma::colvec, arma::mat, arma::sp_mat or arma::cube)\&. 
.RE
.PP

.PP
Definition at line 34 of file subview\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBSubview\fP (const size_t inSize = \fC1\fP, const size_t beginRow = \fC0\fP, const size_t endRow = \fC0\fP, const size_t beginCol = \fC0\fP, const size_t endCol = \fC0\fP)\fC [inline]\fP"

.PP
Create the \fBSubview\fP layer object using the specified range of input to accept\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinSize\fP Width of sample\&. 
.br
\fIbeginRow\fP Starting row index\&. 
.br
\fIendRow\fP Ending row index\&. 
.br
\fIbeginCol\fP Starting column index\&. 
.br
\fIendCol\fP Ending column index\&. 
.RE
.PP

.PP
Definition at line 47 of file subview\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Backward (const arma::Mat< eT > &, const arma::Mat< eT > & gy, arma::Mat< eT > & g)\fC [inline]\fP"

.PP
Ordinary feed backward pass of a neural network, calculating the function f(x) by propagating x backwards trough f\&. Using the results from the feed forward pass\&.
.PP
\fBParameters:\fP
.RS 4
\fI*\fP (input) The propagated input activation\&. 
.br
\fIgy\fP The backpropagated error\&. 
.br
\fIg\fP The calculated gradient\&. 
.RE
.PP

.PP
Definition at line 115 of file subview\&.hpp\&.
.SS "size_t const& BeginCol () const\fC [inline]\fP"

.PP
Get the width of each sample\&. 
.PP
Definition at line 146 of file subview\&.hpp\&.
.SS "size_t& BeginCol ()\fC [inline]\fP"

.PP
Modify the width of each sample\&. 
.PP
Definition at line 148 of file subview\&.hpp\&.
.SS "size_t const& BeginRow () const\fC [inline]\fP"

.PP
Get the starting row index of subview vector or matrix\&. 
.PP
Definition at line 136 of file subview\&.hpp\&.
.SS "size_t& BeginRow ()\fC [inline]\fP"

.PP
Modify the width of each sample\&. 
.PP
Definition at line 138 of file subview\&.hpp\&.
.SS "OutputDataType const& Delta () const\fC [inline]\fP"

.PP
Get the delta\&. 
.PP
Definition at line 128 of file subview\&.hpp\&.
.SS "OutputDataType& Delta ()\fC [inline]\fP"

.PP
Modify the delta\&. 
.PP
Definition at line 130 of file subview\&.hpp\&.
.SS "size_t const& EndCol () const\fC [inline]\fP"

.PP
Get the ending column index of subview vector or matrix\&. 
.PP
Definition at line 151 of file subview\&.hpp\&.
.SS "size_t& EndCol ()\fC [inline]\fP"

.PP
Modify the width of each sample\&. 
.PP
Definition at line 153 of file subview\&.hpp\&.
.SS "size_t const& EndRow () const\fC [inline]\fP"

.PP
Get the ending row index of subview vector or matrix\&. 
.PP
Definition at line 141 of file subview\&.hpp\&.
.SS "size_t& EndRow ()\fC [inline]\fP"

.PP
Modify the width of each sample\&. 
.PP
Definition at line 143 of file subview\&.hpp\&.
.SS "void Forward (const InputType & input, OutputType & output)\fC [inline]\fP"

.PP
Ordinary feed forward pass of a neural network, evaluating the function f(x) by propagating the activity forward through f\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinput\fP Input data used for evaluating the specified function\&. 
.br
\fIoutput\fP Resulting output activation\&. 
.RE
.PP

.PP
Definition at line 69 of file subview\&.hpp\&.
.SS "size_t InSize () const\fC [inline]\fP"

.PP
Get the width of each sample\&. 
.PP
Definition at line 133 of file subview\&.hpp\&.
.SS "OutputDataType const& OutputParameter () const\fC [inline]\fP"

.PP
Get the output parameter\&. 
.PP
Definition at line 123 of file subview\&.hpp\&.
.SS "OutputDataType& OutputParameter ()\fC [inline]\fP"

.PP
Modify the output parameter\&. 
.PP
Definition at line 125 of file subview\&.hpp\&.
.SS "void serialize (Archive & ar, const uint32_t)\fC [inline]\fP"

.PP
Serialize the layer\&. 
.PP
Definition at line 159 of file subview\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
