.TH "Recurrent< InputDataType, OutputDataType, CustomLayers >" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Recurrent< InputDataType, OutputDataType, CustomLayers > \- Implementation of the RecurrentLayer class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRecurrent\fP ()"
.br
.RI "Default constructor---this will create a \fBRecurrent\fP object that can't be used, so be careful! Make sure to set all the parameters before use\&. "
.ti -1c
.RI "\fBRecurrent\fP (const \fBRecurrent\fP &)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "template<typename StartModuleType , typename InputModuleType , typename FeedbackModuleType , typename TransferModuleType > \fBRecurrent\fP (const StartModuleType &start, const InputModuleType &input, const FeedbackModuleType &feedback, const TransferModuleType &transfer, const size_t rho)"
.br
.RI "Create the \fBRecurrent\fP object using the specified modules\&. "
.ti -1c
.RI "template<typename eT > void \fBBackward\fP (const arma::Mat< eT > &, const arma::Mat< eT > &gy, arma::Mat< eT > &g)"
.br
.RI "Ordinary feed backward pass of a neural network, calculating the function f(x) by propagating x backwards trough f\&. "
.ti -1c
.RI "OutputDataType const  & \fBDelta\fP () const"
.br
.RI "Get the delta\&. "
.ti -1c
.RI "OutputDataType & \fBDelta\fP ()"
.br
.RI "Modify the delta\&. "
.ti -1c
.RI "bool \fBDeterministic\fP () const"
.br
.RI "The value of the deterministic parameter\&. "
.ti -1c
.RI "bool & \fBDeterministic\fP ()"
.br
.RI "Modify the value of the deterministic parameter\&. "
.ti -1c
.RI "template<typename eT > void \fBForward\fP (const arma::Mat< eT > &input, arma::Mat< eT > &output)"
.br
.RI "Ordinary feed forward pass of a neural network, evaluating the function f(x) by propagating the activity forward through f\&. "
.ti -1c
.RI "template<typename eT > void \fBGradient\fP (const arma::Mat< eT > &input, const arma::Mat< eT > &error, arma::Mat< eT > &)"
.br
.ti -1c
.RI "OutputDataType const  & \fBGradient\fP () const"
.br
.RI "Get the gradient\&. "
.ti -1c
.RI "OutputDataType & \fBGradient\fP ()"
.br
.RI "Modify the gradient\&. "
.ti -1c
.RI "size_t \fBInputShape\fP () const"
.br
.RI "Get the shape of the input\&. "
.ti -1c
.RI "std::vector< \fBLayerTypes\fP< CustomLayers\&.\&.\&. > > & \fBModel\fP ()"
.br
.RI "Get the model modules\&. "
.ti -1c
.RI "OutputDataType const  & \fBOutputParameter\fP () const"
.br
.RI "Get the output parameter\&. "
.ti -1c
.RI "OutputDataType & \fBOutputParameter\fP ()"
.br
.RI "Modify the output parameter\&. "
.ti -1c
.RI "OutputDataType const  & \fBParameters\fP () const"
.br
.RI "Get the parameters\&. "
.ti -1c
.RI "OutputDataType & \fBParameters\fP ()"
.br
.RI "Modify the parameters\&. "
.ti -1c
.RI "size_t const  & \fBRho\fP () const"
.br
.RI "Get the number of steps to backpropagate through time\&. "
.ti -1c
.RI "template<typename Archive > void \fBserialize\fP (Archive &ar, const uint32_t)"
.br
.RI "Serialize the layer\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat, typename\&.\&.\&. CustomLayers>
.br
class mlpack::ann::Recurrent< InputDataType, OutputDataType, CustomLayers >"
Implementation of the RecurrentLayer class\&. 

\fBRecurrent\fP layers can be used similarly to feed-forward layers\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIInputDataType\fP Type of the input data (arma::colvec, arma::mat, arma::sp_mat or arma::cube)\&. 
.br
\fIOutputDataType\fP Type of the output data (arma::colvec, arma::mat, arma::sp_mat or arma::cube)\&. 
.RE
.PP

.PP
Definition at line 153 of file layer_types\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBRecurrent\fP ()"

.PP
Default constructor---this will create a \fBRecurrent\fP object that can't be used, so be careful! Make sure to set all the parameters before use\&. 
.SS "\fBRecurrent\fP (const \fBRecurrent\fP< InputDataType, OutputDataType, CustomLayers > &)"

.PP
Copy constructor\&. 
.SS "\fBRecurrent\fP (const StartModuleType & start, const InputModuleType & input, const FeedbackModuleType & feedback, const TransferModuleType & transfer, const size_t rho)"

.PP
Create the \fBRecurrent\fP object using the specified modules\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstart\fP The start module\&. 
.br
\fIinput\fP The input module\&. 
.br
\fIfeedback\fP The feedback module\&. 
.br
\fItransfer\fP The transfer module\&. 
.br
\fIrho\fP Maximum number of steps to backpropagate through time (BPTT)\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Backward (const arma::Mat< eT > &, const arma::Mat< eT > & gy, arma::Mat< eT > & g)"

.PP
Ordinary feed backward pass of a neural network, calculating the function f(x) by propagating x backwards trough f\&. Using the results from the feed forward pass\&.
.PP
\fBParameters:\fP
.RS 4
\fI*\fP (input) The propagated input activation\&. 
.br
\fIgy\fP The backpropagated error\&. 
.br
\fIg\fP The calculated gradient\&. 
.RE
.PP

.SS "OutputDataType const& Delta () const\fC [inline]\fP"

.PP
Get the delta\&. 
.PP
Definition at line 130 of file recurrent\&.hpp\&.
.SS "OutputDataType& Delta ()\fC [inline]\fP"

.PP
Modify the delta\&. 
.PP
Definition at line 132 of file recurrent\&.hpp\&.
.SS "bool Deterministic () const\fC [inline]\fP"

.PP
The value of the deterministic parameter\&. 
.PP
Definition at line 115 of file recurrent\&.hpp\&.
.SS "bool& Deterministic ()\fC [inline]\fP"

.PP
Modify the value of the deterministic parameter\&. 
.PP
Definition at line 117 of file recurrent\&.hpp\&.
.SS "void Forward (const arma::Mat< eT > & input, arma::Mat< eT > & output)"

.PP
Ordinary feed forward pass of a neural network, evaluating the function f(x) by propagating the activity forward through f\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinput\fP Input data used for evaluating the specified function\&. 
.br
\fIoutput\fP Resulting output activation\&. 
.RE
.PP

.SS "void Gradient (const arma::Mat< eT > & input, const arma::Mat< eT > & error, arma::Mat< eT > &)"

.SS "OutputDataType const& Gradient () const\fC [inline]\fP"

.PP
Get the gradient\&. 
.PP
Definition at line 135 of file recurrent\&.hpp\&.
.SS "OutputDataType& Gradient ()\fC [inline]\fP"

.PP
Modify the gradient\&. 
.PP
Definition at line 137 of file recurrent\&.hpp\&.
.SS "size_t InputShape () const"

.PP
Get the shape of the input\&. 
.PP
Referenced by Recurrent< InputDataType, OutputDataType, CustomLayers >::Rho()\&.
.SS "std::vector<\fBLayerTypes\fP<CustomLayers\&.\&.\&.> >& Model ()\fC [inline]\fP"

.PP
Get the model modules\&. 
.PP
Definition at line 112 of file recurrent\&.hpp\&.
.SS "OutputDataType const& OutputParameter () const\fC [inline]\fP"

.PP
Get the output parameter\&. 
.PP
Definition at line 125 of file recurrent\&.hpp\&.
.SS "OutputDataType& OutputParameter ()\fC [inline]\fP"

.PP
Modify the output parameter\&. 
.PP
Definition at line 127 of file recurrent\&.hpp\&.
.SS "OutputDataType const& Parameters () const\fC [inline]\fP"

.PP
Get the parameters\&. 
.PP
Definition at line 120 of file recurrent\&.hpp\&.
.SS "OutputDataType& Parameters ()\fC [inline]\fP"

.PP
Modify the parameters\&. 
.PP
Definition at line 122 of file recurrent\&.hpp\&.
.SS "size_t const& Rho () const\fC [inline]\fP"

.PP
Get the number of steps to backpropagate through time\&. 
.PP
Definition at line 140 of file recurrent\&.hpp\&.
.PP
References Recurrent< InputDataType, OutputDataType, CustomLayers >::InputShape(), and Recurrent< InputDataType, OutputDataType, CustomLayers >::serialize()\&.
.SS "void serialize (Archive & ar, const uint32_t)"

.PP
Serialize the layer\&. 
.PP
Referenced by Recurrent< InputDataType, OutputDataType, CustomLayers >::Rho()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
