.TH "HoeffdingInformationGain" 3 "Sun Aug 22 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HoeffdingInformationGain
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static double \fBEvaluate\fP (const arma::Mat< size_t > &counts)"
.br
.RI "Given the sufficient statistics of a proposed split, calculate the information gain if that split was to be used\&. "
.ti -1c
.RI "static double \fBRange\fP (const size_t numClasses)"
.br
.RI "Return the range of the information gain for the given number of classes\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file information_gain\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static double Evaluate (const arma::Mat< size_t > & counts)\fC [inline]\fP, \fC [static]\fP"

.PP
Given the sufficient statistics of a proposed split, calculate the information gain if that split was to be used\&. The 'counts' matrix should contain the number of points in each class in each column, so the size of 'counts' is children x classes, where 'children' is the number of child nodes in the proposed split\&.
.PP
\fBParameters:\fP
.RS 4
\fIcounts\fP Matrix of sufficient statistics\&. 
.RE
.PP

.PP
Definition at line 31 of file information_gain\&.hpp\&.
.SS "static double Range (const size_t numClasses)\fC [inline]\fP, \fC [static]\fP"

.PP
Return the range of the information gain for the given number of classes\&. (That is, the difference between the maximum possible value and the minimum possible value\&.) 
.PP
Definition at line 84 of file information_gain\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
