.TH "TrainForm< MT, PT, void, false, false >" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TrainForm< MT, PT, void, false, false >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTrainFormBase4< PT, void, const MT &, const PT &>\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename MT, typename PT>
.br
struct mlpack::cv::TrainForm< MT, PT, void, false, false >"

.PP
Definition at line 100 of file meta_info_extractor\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
