.TH "LecunNormalInitialization" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LecunNormalInitialization \- This class is used to initialize weight matrix with the Lecun Normalization initialization rule\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLecunNormalInitialization\fP ()"
.br
.RI "Initialize the \fBLecunNormalInitialization\fP object\&. "
.ti -1c
.RI "template<typename eT > void \fBInitialize\fP (arma::Cube< eT > &W)"
.br
.RI "Initialize the elements of the specified weight 3rd order tensor with Lecun Normal initialization rule\&. "
.ti -1c
.RI "template<typename eT > void \fBInitialize\fP (arma::Cube< eT > &W, const size_t rows, const size_t cols, const size_t slices)"
.br
.RI "Initialize the elements of the specified weight 3rd order tensor with Lecun Normal initialization rule\&. "
.ti -1c
.RI "template<typename eT > void \fBInitialize\fP (arma::Mat< eT > &W)"
.br
.RI "Initialize the elements of the weight matrix with the Lecun Normal initialization rule\&. "
.ti -1c
.RI "template<typename eT > void \fBInitialize\fP (arma::Mat< eT > &W, const size_t rows, const size_t cols)"
.br
.RI "Initialize the elements of the weight matrix with the Lecun Normal initialization rule\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class is used to initialize weight matrix with the Lecun Normalization initialization rule\&. 

For more information, the following papers can be referred to:
.PP
.PP
.nf
@inproceedings{Klambauer2017,
  itle  = {Self-Normalizing Neural Networks\&.},
  author = {Klambauer, Günter and Unterthiner, Thomas
            and Mayr, Andreas and Hochreiter, Sepp},
  pages  = {972-981},
  year   = {2017}
}

@inproceedings{LeCun1998,
  title  = {Efficient BackProp},
  author = {LeCun, Yann and Bottou, L{\'e}on and Orr, Genevieve B\&.
            and M\"{u}ller, Klaus-Robert},
  year   = {1998},
  pages  = {9--50}
}
.fi
.PP
 
.PP
Definition at line 49 of file lecun_normal_init\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBLecunNormalInitialization\fP ()\fC [inline]\fP"

.PP
Initialize the \fBLecunNormalInitialization\fP object\&. 
.PP
Definition at line 55 of file lecun_normal_init\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Initialize (arma::Cube< eT > & W)\fC [inline]\fP"

.PP
Initialize the elements of the specified weight 3rd order tensor with Lecun Normal initialization rule\&. 
.PP
\fBParameters\fP
.RS 4
\fIW\fP Weight matrix to initialize\&. 
.RE
.PP

.PP
Definition at line 137 of file lecun_normal_init\&.hpp\&.
.PP
References Log::Fatal, and LecunNormalInitialization::Initialize()\&.
.SS "void Initialize (arma::Cube< eT > & W, const size_t rows, const size_t cols, const size_t slices)\fC [inline]\fP"

.PP
Initialize the elements of the specified weight 3rd order tensor with Lecun Normal initialization rule\&. 
.PP
\fBParameters\fP
.RS 4
\fIW\fP Weight matrix to initialize\&. 
.br
\fIrows\fP Number of rows\&. 
.br
\fIcols\fP Number of columns\&. 
.br
\fIslices\fP Number of slices\&. 
.RE
.PP

.PP
Definition at line 118 of file lecun_normal_init\&.hpp\&.
.PP
References LecunNormalInitialization::Initialize()\&.
.SS "void Initialize (arma::Mat< eT > & W)\fC [inline]\fP"

.PP
Initialize the elements of the weight matrix with the Lecun Normal initialization rule\&. 
.PP
\fBParameters\fP
.RS 4
\fIW\fP Weight matrix to initialize\&. 
.RE
.PP

.PP
Definition at line 93 of file lecun_normal_init\&.hpp\&.
.PP
References Log::Fatal, and if()\&.
.SS "void Initialize (arma::Mat< eT > & W, const size_t rows, const size_t cols)\fC [inline]\fP"

.PP
Initialize the elements of the weight matrix with the Lecun Normal initialization rule\&. 
.PP
\fBParameters\fP
.RS 4
\fIW\fP Weight matrix to initialize\&. 
.br
\fIrows\fP Number of rows\&. 
.br
\fIcols\fP Number of columns\&. 
.RE
.PP

.PP
Definition at line 69 of file lecun_normal_init\&.hpp\&.
.PP
Referenced by LecunNormalInitialization::Initialize()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
