.TH "DeduceHyperParameterTypes< T, Args... >::ResultHPType< CollectionType, false >" 3 "Sun Aug 22 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeduceHyperParameterTypes< T, Args... >::ResultHPType< CollectionType, false >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBType\fP = typename CollectionType::value_type"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, typename\&.\&.\&. Args>
.br
template<typename CollectionType>
.br
struct mlpack::hpt::DeduceHyperParameterTypes< T, Args\&.\&.\&. >::ResultHPType< CollectionType, false >"

.PP
Definition at line 84 of file deduce_hp_types\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBType\fP =  typename CollectionType::value_type"

.PP
Definition at line 90 of file deduce_hp_types\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
