.TH "BackwardVisitor" 3 "Sun Aug 22 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BackwardVisitor \- \fBBackwardVisitor\fP executes the Backward() function given the input, error and delta parameter\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits static_visitor< void >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBackwardVisitor\fP (const arma::mat &input, const arma::mat &error, arma::mat &delta)"
.br
.RI "Execute the Backward() function given the input, error and delta parameter\&. "
.ti -1c
.RI "\fBBackwardVisitor\fP (const arma::mat &input, const arma::mat &error, arma::mat &delta, const size_t index)"
.br
.RI "Execute the Backward() function for the layer with the specified index\&. "
.ti -1c
.RI "template<typename LayerType > void \fBoperator()\fP (LayerType *layer) const"
.br
.RI "Execute the Backward() function\&. "
.ti -1c
.RI "void \fBoperator()\fP (\fBMoreTypes\fP layer) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBackwardVisitor\fP executes the Backward() function given the input, error and delta parameter\&. 
.PP
Definition at line 28 of file backward_visitor\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBBackwardVisitor\fP (const arma::mat & input, const arma::mat & error, arma::mat & delta)"

.PP
Execute the Backward() function given the input, error and delta parameter\&. 
.SS "\fBBackwardVisitor\fP (const arma::mat & input, const arma::mat & error, arma::mat & delta, const size_t index)"

.PP
Execute the Backward() function for the layer with the specified index\&. 
.SH "Member Function Documentation"
.PP 
.SS "void operator() (LayerType * layer) const"

.PP
Execute the Backward() function\&. 
.SS "void operator() (\fBMoreTypes\fP layer) const"


.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
