.TH "MountainCar::Action" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MountainCar::Action \- Implementation of action of Mountain Car\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBactions\fP { \fBbackward\fP, \fBstop\fP, \fBforward\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAction::actions\fP \fBaction\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const size_t \fBsize\fP = 3"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of action of Mountain Car\&. 
.PP
Definition at line 79 of file mountain_car\&.hpp\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBactions\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIbackward \fP\fP
.TP
\fB\fIstop \fP\fP
.TP
\fB\fIforward \fP\fP
.PP
Definition at line 82 of file mountain_car\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAction::actions\fP action"

.PP
Definition at line 89 of file mountain_car\&.hpp\&.
.PP
Referenced by MountainCar::Sample()\&.
.SS "const size_t size = 3\fC [static]\fP"

.PP
Definition at line 92 of file mountain_car\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
