.TH "CLIOption< N >" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CLIOption< N > \- A static object whose constructor registers a parameter with the \fBIO\fP class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCLIOption\fP (const N defaultValue, const std::string &identifier, const std::string &description, const std::string &alias, const std::string &cppName, const bool required=false, const bool input=true, const bool noTranspose=false, const std::string &='')"
.br
.RI "Construct an Option object\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename N>
.br
class mlpack::bindings::cli::CLIOption< N >"
A static object whose constructor registers a parameter with the \fBIO\fP class\&. 

This should not be used outside of \fBIO\fP itself, and you should use the \fBPARAM_FLAG()\fP, PARAM_DOUBLE(), PARAM_INT(), PARAM_STRING(), or other similar macros to declare these objects instead of declaring them directly\&.
.PP
\fBSee also\fP
.RS 4
\fBcore/util/io\&.hpp\fP, \fBmlpack::IO\fP 
.RE
.PP

.PP
Definition at line 48 of file cli_option\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCLIOption\fP (const N defaultValue, const std::string & identifier, const std::string & description, const std::string & alias, const std::string & cppName, const bool required = \fCfalse\fP, const bool input = \fCtrue\fP, const bool noTranspose = \fCfalse\fP, const std::string & = \fC''\fP)\fC [inline]\fP"

.PP
Construct an Option object\&. When constructed, it will register itself with \fBIO\fP\&.
.PP
\fBParameters\fP
.RS 4
\fIdefaultValue\fP Default value this parameter will be initialized to (for flags, this should be false, for instance)\&. 
.br
\fIidentifier\fP The name of the option (no dashes in front; for --help, we would pass 'help')\&. 
.br
\fIdescription\fP A short string describing the option\&. 
.br
\fIalias\fP Short name of the parameter\&. '' for no alias\&. 
.br
\fIcppName\fP Name of the C++ type of this parameter (i\&.e\&. 'int')\&. 
.br
\fIrequired\fP Whether or not the option is required at runtime\&. 
.br
\fIinput\fP Whether or not the option is an input option\&. 
.br
\fInoTranspose\fP If the parameter is a matrix and this is true, then the matrix will not be transposed on loading\&. 
.br
\fI*\fP (testName) Is not used and added for compatibility reasons\&. 
.RE
.PP

.PP
Definition at line 68 of file cli_option\&.hpp\&.
.PP
References IO::Add(), ParamData::alias, BASH_CLEAR, BASH_RED, ParamData::cppType, ParamData::desc, IO::functionMap, IO::GetSingleton(), ParamData::input, ParamData::loaded, mlpack::bindings::cli::MapParameterName(), ParamData::name, ParamData::noTranspose, IO::Parameters(), ParamData::persistent, ParamData::required, ParamData::tname, TYPENAME, ParamData::value, and ParamData::wasPassed\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
