.TH "StringEncodingPolicyTraits< DictionaryEncodingPolicy >" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StringEncodingPolicyTraits< DictionaryEncodingPolicy > \- The specialization provides some information about the dictionary encoding policy\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBonePassEncoding\fP = true"
.br
.RI "Indicates if the policy is able to encode the token at once without any information about other tokens as well as the total tokens count\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
struct mlpack::data::StringEncodingPolicyTraits< DictionaryEncodingPolicy >"
The specialization provides some information about the dictionary encoding policy\&. 
.PP
Definition at line 129 of file dictionary_encoding_policy\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "const bool onePassEncoding = true\fC [static]\fP"

.PP
Indicates if the policy is able to encode the token at once without any information about other tokens as well as the total tokens count\&. 
.PP
Definition at line 135 of file dictionary_encoding_policy\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
