.TH "ValidationRMSETermination< MatType >" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ValidationRMSETermination< MatType > \- This class implements validation termination policy based on RMSE index\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValidationRMSETermination\fP (MatType &V, size_t num_test_points, double tolerance=1e\-5, size_t maxIterations=10000, size_t reverseStepTolerance=3)"
.br
.RI "Create a validation set according to given parameters and nullifies this set in data matrix(training set)\&. "
.ti -1c
.RI "const double & \fBIndex\fP () const"
.br
.RI "Get current value of residue\&. "
.ti -1c
.RI "void \fBInitialize\fP (const MatType &)"
.br
.RI "Initializes the termination policy before stating the factorization\&. "
.ti -1c
.RI "bool \fBIsConverged\fP (arma::mat &W, arma::mat &H)"
.br
.RI "Check if termination criterio is met\&. "
.ti -1c
.RI "const size_t & \fBIteration\fP () const"
.br
.RI "Get current iteration count\&. "
.ti -1c
.RI "size_t & \fBMaxIterations\fP ()"
.br
.ti -1c
.RI "const size_t & \fBMaxIterations\fP () const"
.br
.RI "Access upper limit of iteration count\&. "
.ti -1c
.RI "const size_t & \fBNumTestPoints\fP () const"
.br
.RI "Get number of validation points\&. "
.ti -1c
.RI "double & \fBTolerance\fP ()"
.br
.ti -1c
.RI "const double & \fBTolerance\fP () const"
.br
.RI "Access tolerance value\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class MatType>
.br
class mlpack::amf::ValidationRMSETermination< MatType >"
This class implements validation termination policy based on RMSE index\&. 

The input data matrix is divided into 2 sets, training set and validation set\&. Entries of validation set are nullifed in the input matrix\&. Termination criterion is met when increase in validation set RMSe value drops below the given tolerance\&. To accommodate spikes certain number of successive validation RMSE drops are accepted\&. This upper imit on successive drops can be adjusted with reverseStepCount\&. Secondary termination criterion terminates algorithm when iteration count goes above the threshold\&.
.PP
\fBNote\fP
.RS 4
The input matrix is modified by this termination policy\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBAMF\fP 
.RE
.PP

.PP
Definition at line 37 of file validation_rmse_termination\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBValidationRMSETermination\fP (MatType & V, size_t num_test_points, double tolerance = \fC1e\-5\fP, size_t maxIterations = \fC10000\fP, size_t reverseStepTolerance = \fC3\fP)\fC [inline]\fP"

.PP
Create a validation set according to given parameters and nullifies this set in data matrix(training set)\&. 
.PP
\fBParameters\fP
.RS 4
\fIV\fP Input matrix to be factorized\&. 
.br
\fInum_test_points\fP number of validation test points 
.br
\fItolerance\fP the tolerance value to compare RMSe against 
.br
\fImaxIterations\fP max iteration count before termination 
.br
\fIreverseStepTolerance\fP max successive RMSE drops allowed 
.RE
.PP

.PP
Definition at line 50 of file validation_rmse_termination\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "const double& Index () const\fC [inline]\fP"

.PP
Get current value of residue\&. 
.PP
Definition at line 188 of file validation_rmse_termination\&.hpp\&.
.SS "void Initialize (const MatType &)\fC [inline]\fP"

.PP
Initializes the termination policy before stating the factorization\&. 
.PP
\fBParameters\fP
.RS 4
\fI*\fP (V) Input matrix to be factorized\&. 
.RE
.PP

.PP
Definition at line 95 of file validation_rmse_termination\&.hpp\&.
.SS "bool IsConverged (arma::mat & W, arma::mat & H)\fC [inline]\fP"

.PP
Check if termination criterio is met\&. 
.PP
\fBParameters\fP
.RS 4
\fIW\fP Basis matrix of output\&. 
.br
\fIH\fP Encoding matrix of output\&. 
.RE
.PP

.PP
Definition at line 115 of file validation_rmse_termination\&.hpp\&.
.SS "const size_t& Iteration () const\fC [inline]\fP"

.PP
Get current iteration count\&. 
.PP
Definition at line 191 of file validation_rmse_termination\&.hpp\&.
.SS "size_t& MaxIterations ()\fC [inline]\fP"

.PP
Definition at line 198 of file validation_rmse_termination\&.hpp\&.
.SS "const size_t& MaxIterations () const\fC [inline]\fP"

.PP
Access upper limit of iteration count\&. 
.PP
Definition at line 197 of file validation_rmse_termination\&.hpp\&.
.SS "const size_t& NumTestPoints () const\fC [inline]\fP"

.PP
Get number of validation points\&. 
.PP
Definition at line 194 of file validation_rmse_termination\&.hpp\&.
.SS "double& Tolerance ()\fC [inline]\fP"

.PP
Definition at line 202 of file validation_rmse_termination\&.hpp\&.
.SS "const double& Tolerance () const\fC [inline]\fP"

.PP
Access tolerance value\&. 
.PP
Definition at line 201 of file validation_rmse_termination\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
