.TH "PrioritizedReplay< EnvironmentType >::Transition" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PrioritizedReplay< EnvironmentType >::Transition
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBActionType\fP \fBaction\fP"
.br
.ti -1c
.RI "bool \fBisEnd\fP"
.br
.ti -1c
.RI "\fBStateType\fP \fBnextState\fP"
.br
.ti -1c
.RI "double \fBreward\fP"
.br
.ti -1c
.RI "\fBStateType\fP \fBstate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename EnvironmentType>
.br
struct mlpack::rl::PrioritizedReplay< EnvironmentType >::Transition"

.PP
Definition at line 48 of file prioritized_replay\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBActionType\fP action"

.PP
Definition at line 51 of file prioritized_replay\&.hpp\&.
.PP
Referenced by PrioritizedReplay< EnvironmentType >::Store(), and PrioritizedReplay< EnvironmentType >::Update()\&.
.SS "bool isEnd"

.PP
Definition at line 54 of file prioritized_replay\&.hpp\&.
.PP
Referenced by PrioritizedReplay< EnvironmentType >::Store()\&.
.SS "\fBStateType\fP nextState"

.PP
Definition at line 53 of file prioritized_replay\&.hpp\&.
.PP
Referenced by PrioritizedReplay< EnvironmentType >::Store()\&.
.SS "double reward"

.PP
Definition at line 52 of file prioritized_replay\&.hpp\&.
.PP
Referenced by PrioritizedReplay< EnvironmentType >::Store()\&.
.SS "\fBStateType\fP state"

.PP
Definition at line 50 of file prioritized_replay\&.hpp\&.
.PP
Referenced by PrioritizedReplay< EnvironmentType >::Store()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
