.TH "SpillTree< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::SpillSingleTreeTraverser< MetricType, StatisticType, MatType, HyperplaneType, SplitType >" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpillTree< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::SpillSingleTreeTraverser< MetricType, StatisticType, MatType, HyperplaneType, SplitType > \- A generic single-tree traverser for hybrid spill trees; see \fBspill_single_tree_traverser\&.hpp\fP for implementation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpillSingleTreeTraverser\fP (RuleType &rule)"
.br
.RI "Instantiate the single tree traverser with the given rule set\&. "
.ti -1c
.RI "size_t & \fBNumPrunes\fP ()"
.br
.RI "Modify the number of prunes\&. "
.ti -1c
.RI "size_t \fBNumPrunes\fP () const"
.br
.RI "Get the number of prunes\&. "
.ti -1c
.RI "void \fBTraverse\fP (const size_t queryIndex, \fBSpillTree\fP &referenceNode, const bool bruteForce=false)"
.br
.RI "Traverse the tree with the given point\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename MetricType, typename StatisticType = EmptyStatistic, typename MatType = arma::mat, template< typename HyperplaneMetricType > class HyperplaneType = AxisOrthogonalHyperplane, template< typename SplitMetricType, typename SplitMatType > class SplitType = MidpointSpaceSplit>
.br
template<typename MetricType, typename StatisticType, typename MatType, template< typename HyperplaneMetricType > class HyperplaneType, template< typename SplitMetricType, typename SplitMatType > class SplitType>
.br
class mlpack::tree::SpillTree< MetricType, StatisticType, MatType, HyperplaneType, SplitType >::SpillSingleTreeTraverser< MetricType, StatisticType, MatType, HyperplaneType, SplitType >"
A generic single-tree traverser for hybrid spill trees; see \fBspill_single_tree_traverser\&.hpp\fP for implementation\&. 

The Defeatist template parameter determines if the traverser must do defeatist search on overlapping nodes\&. 
.PP
Definition at line 34 of file spill_single_tree_traverser\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBSpillSingleTreeTraverser\fP (RuleType & rule)"

.PP
Instantiate the single tree traverser with the given rule set\&. 
.SH "Member Function Documentation"
.PP 
.SS "size_t& NumPrunes ()\fC [inline]\fP"

.PP
Modify the number of prunes\&. 
.PP
Definition at line 59 of file spill_single_tree_traverser\&.hpp\&.
.SS "size_t NumPrunes () const\fC [inline]\fP"

.PP
Get the number of prunes\&. 
.PP
Definition at line 57 of file spill_single_tree_traverser\&.hpp\&.
.SS "void Traverse (const size_t queryIndex, \fBSpillTree\fP & referenceNode, const bool bruteForce = \fCfalse\fP)"

.PP
Traverse the tree with the given point\&. 
.PP
\fBParameters\fP
.RS 4
\fIqueryIndex\fP The index of the point in the query set which is being used as the query point\&. 
.br
\fIreferenceNode\fP The tree node to be traversed\&. 
.br
\fIbruteForce\fP If true, then do a brute-force search on the reference node instead of traversing any further\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
