.TH "KernelNormalizer" 3 "Sun Aug 22 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KernelNormalizer \- \fBKernelNormalizer\fP holds a set of methods to normalize estimations applying in each case the appropiate kernel normalizer function\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename KernelType > static void \fBApplyNormalizer\fP (KernelType &, const size_t, arma::vec &, const typename std::enable_if< !HasNormalizer< KernelType, double(KernelType::*)(size_t)>::value >::type *=0)"
.br
.RI "Normalization not needed\&. "
.ti -1c
.RI "template<typename KernelType > static void \fBApplyNormalizer\fP (KernelType &kernel, const size_t dimension, arma::vec &estimations, const typename std::enable_if< HasNormalizer< KernelType, double(KernelType::*)(size_t)>::value >::type *=0)"
.br
.RI "Normalize kernels that have normalizer\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBKernelNormalizer\fP holds a set of methods to normalize estimations applying in each case the appropiate kernel normalizer function\&. 
.PP
Definition at line 34 of file kde_model\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static void ApplyNormalizer (KernelType &, const size_t, arma::vec &, const typename std::enable_if< !HasNormalizer< KernelType, double(KernelType::*)(size_t)>::value >::type * = \fC0\fP)\fC [inline]\fP, \fC [static]\fP"

.PP
Normalization not needed\&. 
.PP
Definition at line 43 of file kde_model\&.hpp\&.
.SS "static void ApplyNormalizer (KernelType & kernel, const size_t dimension, arma::vec & estimations, const typename std::enable_if< HasNormalizer< KernelType, double(KernelType::*)(size_t)>::value >::type * = \fC0\fP)\fC [inline]\fP, \fC [static]\fP"

.PP
Normalize kernels that have normalizer\&. 
.PP
Definition at line 54 of file kde_model\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
