.TH "mlpack::svd" 3 "Sun Aug 22 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::svd
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBiasSVD\fP"
.br
.RI "Bias SVD is an improvement on Regularized SVD which is a matrix factorization techniques\&. "
.ti -1c
.RI "class \fBBiasSVDFunction\fP"
.br
.RI "This class contains methods which are used to calculate the cost of \fBBiasSVD\fP's objective function, to calculate gradient of parameters with respect to the objective function, etc\&. "
.ti -1c
.RI "class \fBQUIC_SVD\fP"
.br
.RI "QUIC-SVD is a matrix factorization technique, which operates in a subspace such that A's approximation in that subspace has minimum error(A being the data matrix)\&. "
.ti -1c
.RI "class \fBRandomizedBlockKrylovSVD\fP"
.br
.RI "Randomized block krylov SVD is a matrix factorization that is based on randomized matrix approximation techniques, developed in in 'Randomized Block Krylov Methods for Stronger and Faster Approximate
Singular Value Decomposition'\&. "
.ti -1c
.RI "class \fBRandomizedSVD\fP"
.br
.RI "Randomized SVD is a matrix factorization that is based on randomized matrix approximation techniques, developed in in 'Finding structure with randomness:
Probabilistic algorithms for constructing approximate matrix decompositions'\&. "
.ti -1c
.RI "class \fBRegularizedSVD\fP"
.br
.RI "Regularized SVD is a matrix factorization technique that seeks to reduce the error on the training set, that is on the examples for which the ratings have been provided by the users\&. "
.ti -1c
.RI "class \fBRegularizedSVDFunction\fP"
.br
.RI "The data is stored in a matrix of type MatType, so that this class can be used with both dense and sparse matrix types\&. "
.ti -1c
.RI "class \fBSVDPlusPlus\fP"
.br
.RI "SVD++ is a matrix decomposition tenique used in collaborative filtering\&. "
.ti -1c
.RI "class \fBSVDPlusPlusFunction\fP"
.br
.RI "This class contains methods which are used to calculate the cost of SVD++'s objective function, to calculate gradient of parameters with respect to the objective function, etc\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
