.TH "TreeTraits< Octree< MetricType, StatisticType, MatType > >" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TreeTraits< Octree< MetricType, StatisticType, MatType > > \- This is a specialization of the \fBTreeTraits\fP class to the \fBOctree\fP tree type\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBBinaryTree\fP = false"
.br
.RI "This is not necessarily a binary tree\&. "
.ti -1c
.RI "static const bool \fBFirstPointIsCentroid\fP = false"
.br
.RI "There is no guarantee that the first point in a node is its centroid\&. "
.ti -1c
.RI "static const bool \fBHasDuplicatedPoints\fP = false"
.br
.RI "Points are not shared across nodes in the octree\&. "
.ti -1c
.RI "static const bool \fBHasOverlappingChildren\fP = false"
.br
.RI "No octree nodes will overlap\&. "
.ti -1c
.RI "static const bool \fBHasSelfChildren\fP = false"
.br
.RI "Points are not contained at multiple levels of the octree\&. "
.ti -1c
.RI "static const bool \fBRearrangesDataset\fP = true"
.br
.RI "Points are rearranged during building of the tree\&. "
.ti -1c
.RI "static const bool \fBUniqueNumDescendants\fP = true"
.br
.RI "NumDescendants() represents the number of unique descendant points\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename MetricType, typename StatisticType, typename MatType>
.br
class mlpack::tree::TreeTraits< Octree< MetricType, StatisticType, MatType > >"
This is a specialization of the \fBTreeTraits\fP class to the \fBOctree\fP tree type\&. 

It defines characteristics of the octree, and is used to help write tree-independent (but still optimized) tree-based algorithms\&. See \fBmlpack/core/tree/tree_traits\&.hpp\fP for more information\&. 
.PP
Definition at line 29 of file traits\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "const bool BinaryTree = false\fC [static]\fP"

.PP
This is not necessarily a binary tree\&. 
.PP
Definition at line 60 of file traits\&.hpp\&.
.SS "const bool FirstPointIsCentroid = false\fC [static]\fP"

.PP
There is no guarantee that the first point in a node is its centroid\&. 
.PP
Definition at line 45 of file traits\&.hpp\&.
.SS "const bool HasDuplicatedPoints = false\fC [static]\fP"

.PP
Points are not shared across nodes in the octree\&. 
.PP
Definition at line 40 of file traits\&.hpp\&.
.SS "const bool HasOverlappingChildren = false\fC [static]\fP"

.PP
No octree nodes will overlap\&. 
.PP
Definition at line 35 of file traits\&.hpp\&.
.SS "const bool HasSelfChildren = false\fC [static]\fP"

.PP
Points are not contained at multiple levels of the octree\&. 
.PP
Definition at line 50 of file traits\&.hpp\&.
.SS "const bool RearrangesDataset = true\fC [static]\fP"

.PP
Points are rearranged during building of the tree\&. 
.PP
Definition at line 55 of file traits\&.hpp\&.
.SS "const bool UniqueNumDescendants = true\fC [static]\fP"

.PP
NumDescendants() represents the number of unique descendant points\&. 
.PP
Definition at line 65 of file traits\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
