.TH "TrainFormBase4< PT, WT, T1, T2 >" 3 "Sun Aug 22 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TrainFormBase4< PT, WT, T1, T2 >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBPredictionsType\fP = PT"
.br
.ti -1c
.RI "template<typename Class , typename RT , typename\&.\&.\&. Ts> using \fBType\fP = RT(Class::*)(T1, T2, Ts\&.\&.\&.)"
.br
.ti -1c
.RI "using \fBWeightsType\fP = WT"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const size_t \fBMinNumberOfAdditionalArgs\fP = 1"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename PT, typename WT, typename T1, typename T2>
.br
struct mlpack::cv::TrainFormBase4< PT, WT, T1, T2 >"

.PP
Definition at line 46 of file meta_info_extractor\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBPredictionsType\fP =  PT"

.PP
Definition at line 48 of file meta_info_extractor\&.hpp\&.
.SS "using \fBType\fP =  RT(Class::*)(T1, T2, Ts\&.\&.\&.)"

.PP
Definition at line 55 of file meta_info_extractor\&.hpp\&.
.SS "using \fBWeightsType\fP =  WT"

.PP
Definition at line 49 of file meta_info_extractor\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "const size_t MinNumberOfAdditionalArgs = 1\fC [static]\fP"

.PP
Definition at line 52 of file meta_info_extractor\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
