.TH "DualTreeKMeans< MetricType, MatType, TreeType >" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DualTreeKMeans< MetricType, MatType, TreeType > \- An algorithm for an exact Lloyd iteration which simply uses dual-tree nearest-neighbor search to find the nearest centroid for each point in the dataset\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "template<typename TreeMetricType , typename IgnoredStatType , typename TreeMatType > using \fBNNSTreeType\fP = TreeType< TreeMetricType, \fBDualTreeKMeansStatistic\fP, TreeMatType >"
.br
.ti -1c
.RI "typedef TreeType< MetricType, \fBDualTreeKMeansStatistic\fP, MatType > \fBTree\fP"
.br
.RI "Convenience typedef\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDualTreeKMeans\fP (const MatType &dataset, MetricType &metric)"
.br
.RI "Construct the \fBDualTreeKMeans\fP object, which will construct a tree on the points\&. "
.ti -1c
.RI "\fB~DualTreeKMeans\fP ()"
.br
.RI "Delete the tree constructed by the \fBDualTreeKMeans\fP object\&. "
.ti -1c
.RI "size_t & \fBDistanceCalculations\fP ()"
.br
.RI "Modify the number of distance calculations\&. "
.ti -1c
.RI "size_t \fBDistanceCalculations\fP () const"
.br
.RI "Return the number of distance calculations\&. "
.ti -1c
.RI "double \fBIterate\fP (const arma::mat &centroids, arma::mat &newCentroids, arma::Col< size_t > &counts)"
.br
.RI "Run a single iteration of the dual-tree nearest neighbor algorithm for k-means, updating the given centroids into the newCentroids matrix\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename MetricType, typename MatType, template< typename TreeMetricType, typename TreeStatType, typename TreeMatType > class TreeType = tree::KDTree>
.br
class mlpack::kmeans::DualTreeKMeans< MetricType, MatType, TreeType >"
An algorithm for an exact Lloyd iteration which simply uses dual-tree nearest-neighbor search to find the nearest centroid for each point in the dataset\&. 

The conditions under which this will perform best are probably limited to the case where k is close to the number of points in the dataset, and the number of iterations of the k-means algorithm will be few\&. 
.PP
Definition at line 41 of file dual_tree_kmeans\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBNNSTreeType\fP =  TreeType<TreeMetricType, \fBDualTreeKMeansStatistic\fP, TreeMatType>"

.PP
Definition at line 50 of file dual_tree_kmeans\&.hpp\&.
.SS "typedef TreeType<MetricType, \fBDualTreeKMeansStatistic\fP, MatType> \fBTree\fP"

.PP
Convenience typedef\&. 
.PP
Definition at line 45 of file dual_tree_kmeans\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBDualTreeKMeans\fP (const MatType & dataset, MetricType & metric)"

.PP
Construct the \fBDualTreeKMeans\fP object, which will construct a tree on the points\&. 
.SS "~\fBDualTreeKMeans\fP ()"

.PP
Delete the tree constructed by the \fBDualTreeKMeans\fP object\&. 
.SH "Member Function Documentation"
.PP 
.SS "size_t& DistanceCalculations ()\fC [inline]\fP"

.PP
Modify the number of distance calculations\&. 
.PP
Definition at line 79 of file dual_tree_kmeans\&.hpp\&.
.SS "size_t DistanceCalculations () const\fC [inline]\fP"

.PP
Return the number of distance calculations\&. 
.PP
Definition at line 77 of file dual_tree_kmeans\&.hpp\&.
.SS "double Iterate (const arma::mat & centroids, arma::mat & newCentroids, arma::Col< size_t > & counts)"

.PP
Run a single iteration of the dual-tree nearest neighbor algorithm for k-means, updating the given centroids into the newCentroids matrix\&. 
.PP
\fBParameters\fP
.RS 4
\fIcentroids\fP Current cluster centroids\&. 
.br
\fInewCentroids\fP New cluster centroids\&. 
.br
\fIcounts\fP Current counts, to be overwritten with new counts\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
