.TH "GradientUpdateVisitor" 3 "Sun Aug 22 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GradientUpdateVisitor \- \fBGradientUpdateVisitor\fP update the gradient parameter given the gradient set\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits static_visitor< size_t >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGradientUpdateVisitor\fP (arma::mat &gradient, size_t offset=0)"
.br
.RI "Update the gradient parameter given the gradient set\&. "
.ti -1c
.RI "template<typename LayerType > size_t \fBoperator()\fP (LayerType *layer) const"
.br
.RI "Update the gradient parameter\&. "
.ti -1c
.RI "size_t \fBoperator()\fP (\fBMoreTypes\fP layer) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGradientUpdateVisitor\fP update the gradient parameter given the gradient set\&. 
.PP
Definition at line 26 of file gradient_update_visitor\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBGradientUpdateVisitor\fP (arma::mat & gradient, size_t offset = \fC0\fP)"

.PP
Update the gradient parameter given the gradient set\&. 
.SH "Member Function Documentation"
.PP 
.SS "size_t operator() (LayerType * layer) const"

.PP
Update the gradient parameter\&. 
.SS "size_t operator() (\fBMoreTypes\fP layer) const"


.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
