.TH "Padding< InputDataType, OutputDataType >" 3 "Sun Aug 22 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Padding< InputDataType, OutputDataType > \- Implementation of the \fBPadding\fP module class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPadding\fP (const size_t padWLeft=0, const size_t padWRight=0, const size_t padHTop=0, const size_t padHBottom=0, const size_t inputWidth=0, const size_t inputHeight=0)"
.br
.RI "Create the \fBPadding\fP object using the specified number of output units\&. "
.ti -1c
.RI "template<typename eT > void \fBBackward\fP (const arma::Mat< eT > &, const arma::Mat< eT > &gy, arma::Mat< eT > &g)"
.br
.RI "Ordinary feed backward pass of a neural network, calculating the function f(x) by propagating x backwards trough f\&. "
.ti -1c
.RI "OutputDataType const  & \fBDelta\fP () const"
.br
.RI "Get the delta\&. "
.ti -1c
.RI "OutputDataType & \fBDelta\fP ()"
.br
.RI "Modify the delta\&. "
.ti -1c
.RI "template<typename eT > void \fBForward\fP (const arma::Mat< eT > &input, arma::Mat< eT > &output)"
.br
.RI "Ordinary feed forward pass of a neural network, evaluating the function f(x) by propagating the activity forward through f\&. "
.ti -1c
.RI "size_t \fBInputHeight\fP () const"
.br
.RI "Get the input height\&. "
.ti -1c
.RI "size_t & \fBInputHeight\fP ()"
.br
.RI "Modify the input height\&. "
.ti -1c
.RI "size_t \fBInputWidth\fP () const"
.br
.RI "Get the input width\&. "
.ti -1c
.RI "size_t & \fBInputWidth\fP ()"
.br
.RI "Modify the input width\&. "
.ti -1c
.RI "size_t \fBOutputHeight\fP () const"
.br
.RI "Get the output height\&. "
.ti -1c
.RI "size_t & \fBOutputHeight\fP ()"
.br
.RI "Modify the output height\&. "
.ti -1c
.RI "OutputDataType const  & \fBOutputParameter\fP () const"
.br
.RI "Get the output parameter\&. "
.ti -1c
.RI "OutputDataType & \fBOutputParameter\fP ()"
.br
.RI "Modify the output parameter\&. "
.ti -1c
.RI "size_t \fBOutputWidth\fP () const"
.br
.RI "Get the output width\&. "
.ti -1c
.RI "size_t & \fBOutputWidth\fP ()"
.br
.RI "Modify the output width\&. "
.ti -1c
.RI "size_t \fBPadHBottom\fP () const"
.br
.RI "Get the bottom padding width\&. "
.ti -1c
.RI "size_t & \fBPadHBottom\fP ()"
.br
.RI "Modify the bottom padding width\&. "
.ti -1c
.RI "size_t \fBPadHTop\fP () const"
.br
.RI "Get the top padding width\&. "
.ti -1c
.RI "size_t & \fBPadHTop\fP ()"
.br
.RI "Modify the top padding width\&. "
.ti -1c
.RI "size_t \fBPadWLeft\fP () const"
.br
.RI "Get the left padding width\&. "
.ti -1c
.RI "size_t & \fBPadWLeft\fP ()"
.br
.RI "Modify the left padding width\&. "
.ti -1c
.RI "size_t \fBPadWRight\fP () const"
.br
.RI "Get the right padding width\&. "
.ti -1c
.RI "size_t & \fBPadWRight\fP ()"
.br
.RI "Modify the right padding width\&. "
.ti -1c
.RI "template<typename Archive > void \fBserialize\fP (Archive &ar, const uint32_t)"
.br
.RI "Serialize the layer\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat>
.br
class mlpack::ann::Padding< InputDataType, OutputDataType >"
Implementation of the \fBPadding\fP module class\&. 

The \fBPadding\fP module applies a bias term to the incoming data\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIInputDataType\fP Type of the input data (arma::colvec, arma::mat, arma::sp_mat or arma::cube)\&. 
.br
\fIOutputDataType\fP Type of the output data (arma::colvec, arma::mat, arma::sp_mat or arma::cube)\&. 
.RE
.PP

.PP
Definition at line 88 of file layer_types\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBPadding\fP (const size_t padWLeft = \fC0\fP, const size_t padWRight = \fC0\fP, const size_t padHTop = \fC0\fP, const size_t padHBottom = \fC0\fP, const size_t inputWidth = \fC0\fP, const size_t inputHeight = \fC0\fP)"

.PP
Create the \fBPadding\fP object using the specified number of output units\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpadWLeft\fP Left padding width of the input\&. 
.br
\fIpadWRight\fP Right padding width of the input\&. 
.br
\fIpadHTop\fP Top padding height of the input\&. 
.br
\fIpadHBottom\fP Bottom padding height of the input\&. 
.br
\fIinputWidth\fP Width of the input\&. 
.br
\fIinputHeight\fP Height of the input\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Backward (const arma::Mat< eT > &, const arma::Mat< eT > & gy, arma::Mat< eT > & g)"

.PP
Ordinary feed backward pass of a neural network, calculating the function f(x) by propagating x backwards trough f\&. Using the results from the feed forward pass\&.
.PP
\fBParameters:\fP
.RS 4
\fI*\fP (input) The propagated input activation\&. 
.br
\fIgy\fP The backpropagated error\&. 
.br
\fIg\fP The calculated gradient\&. 
.RE
.PP

.SS "OutputDataType const& Delta () const\fC [inline]\fP"

.PP
Get the delta\&. 
.PP
Definition at line 84 of file padding\&.hpp\&.
.SS "OutputDataType& Delta ()\fC [inline]\fP"

.PP
Modify the delta\&. 
.PP
Definition at line 86 of file padding\&.hpp\&.
.SS "void Forward (const arma::Mat< eT > & input, arma::Mat< eT > & output)"

.PP
Ordinary feed forward pass of a neural network, evaluating the function f(x) by propagating the activity forward through f\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinput\fP Input data used for evaluating the specified function\&. 
.br
\fIoutput\fP Resulting output activation\&. 
.RE
.PP

.SS "size_t InputHeight () const\fC [inline]\fP"

.PP
Get the input height\&. 
.PP
Definition at line 114 of file padding\&.hpp\&.
.SS "size_t& InputHeight ()\fC [inline]\fP"

.PP
Modify the input height\&. 
.PP
Definition at line 116 of file padding\&.hpp\&.
.SS "size_t InputWidth () const\fC [inline]\fP"

.PP
Get the input width\&. 
.PP
Definition at line 109 of file padding\&.hpp\&.
.SS "size_t& InputWidth ()\fC [inline]\fP"

.PP
Modify the input width\&. 
.PP
Definition at line 111 of file padding\&.hpp\&.
.SS "size_t OutputHeight () const\fC [inline]\fP"

.PP
Get the output height\&. 
.PP
Definition at line 124 of file padding\&.hpp\&.
.SS "size_t& OutputHeight ()\fC [inline]\fP"

.PP
Modify the output height\&. 
.PP
Definition at line 126 of file padding\&.hpp\&.
.PP
References Padding< InputDataType, OutputDataType >::serialize()\&.
.SS "OutputDataType const& OutputParameter () const\fC [inline]\fP"

.PP
Get the output parameter\&. 
.PP
Definition at line 79 of file padding\&.hpp\&.
.SS "OutputDataType& OutputParameter ()\fC [inline]\fP"

.PP
Modify the output parameter\&. 
.PP
Definition at line 81 of file padding\&.hpp\&.
.SS "size_t OutputWidth () const\fC [inline]\fP"

.PP
Get the output width\&. 
.PP
Definition at line 119 of file padding\&.hpp\&.
.SS "size_t& OutputWidth ()\fC [inline]\fP"

.PP
Modify the output width\&. 
.PP
Definition at line 121 of file padding\&.hpp\&.
.SS "size_t PadHBottom () const\fC [inline]\fP"

.PP
Get the bottom padding width\&. 
.PP
Definition at line 104 of file padding\&.hpp\&.
.SS "size_t& PadHBottom ()\fC [inline]\fP"

.PP
Modify the bottom padding width\&. 
.PP
Definition at line 106 of file padding\&.hpp\&.
.SS "size_t PadHTop () const\fC [inline]\fP"

.PP
Get the top padding width\&. 
.PP
Definition at line 99 of file padding\&.hpp\&.
.SS "size_t& PadHTop ()\fC [inline]\fP"

.PP
Modify the top padding width\&. 
.PP
Definition at line 101 of file padding\&.hpp\&.
.SS "size_t PadWLeft () const\fC [inline]\fP"

.PP
Get the left padding width\&. 
.PP
Definition at line 89 of file padding\&.hpp\&.
.SS "size_t& PadWLeft ()\fC [inline]\fP"

.PP
Modify the left padding width\&. 
.PP
Definition at line 91 of file padding\&.hpp\&.
.SS "size_t PadWRight () const\fC [inline]\fP"

.PP
Get the right padding width\&. 
.PP
Definition at line 94 of file padding\&.hpp\&.
.SS "size_t& PadWRight ()\fC [inline]\fP"

.PP
Modify the right padding width\&. 
.PP
Definition at line 96 of file padding\&.hpp\&.
.SS "void serialize (Archive & ar, const uint32_t)"

.PP
Serialize the layer\&. 
.PP
Referenced by Padding< InputDataType, OutputDataType >::OutputHeight()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
