.TH "Highway< InputDataType, OutputDataType, CustomLayers >" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Highway< InputDataType, OutputDataType, CustomLayers > \- Implementation of the \fBHighway\fP layer\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHighway\fP ()"
.br
.RI "Create the \fBHighway\fP object\&. "
.ti -1c
.RI "\fBHighway\fP (const size_t inSize, const bool model=true)"
.br
.RI "Create the \fBHighway\fP object\&. "
.ti -1c
.RI "\fB~Highway\fP ()"
.br
.RI "Destroy the \fBHighway\fP object\&. "
.ti -1c
.RI "template<class LayerType , class\&.\&.\&. Args> void \fBAdd\fP (Args\&.\&.\&. args)"
.br
.RI "\fBAdd\fP a new module to the model\&. "
.ti -1c
.RI "void \fBAdd\fP (\fBLayerTypes\fP< CustomLayers\&.\&.\&. > layer)"
.br
.RI "\fBAdd\fP a new module to the model\&. "
.ti -1c
.RI "template<typename eT > void \fBBackward\fP (const arma::Mat< eT > &, const arma::Mat< eT > &gy, arma::Mat< eT > &g)"
.br
.RI "Ordinary feed-backward pass of a neural network, calculating the function f(x) by propagating x backwards through f\&. "
.ti -1c
.RI "OutputDataType & \fBDelta\fP ()"
.br
.RI "Modify the delta\&. "
.ti -1c
.RI "OutputDataType const  & \fBDelta\fP () const"
.br
.RI "Get the delta\&. "
.ti -1c
.RI "template<typename eT > void \fBForward\fP (const arma::Mat< eT > &input, arma::Mat< eT > &output)"
.br
.RI "Ordinary feed-forward pass of a neural network, evaluating the function f(x) by propagating the activity forward through f\&. "
.ti -1c
.RI "OutputDataType & \fBGradient\fP ()"
.br
.RI "Modify the gradient\&. "
.ti -1c
.RI "OutputDataType const  & \fBGradient\fP () const"
.br
.RI "Get the gradient\&. "
.ti -1c
.RI "template<typename eT > void \fBGradient\fP (const arma::Mat< eT > &input, const arma::Mat< eT > &error, arma::Mat< eT > &gradient)"
.br
.RI "Calculate the gradient using the output delta and the input activation\&. "
.ti -1c
.RI "InputDataType & \fBInputParameter\fP ()"
.br
.RI "Modify the input parameter\&. "
.ti -1c
.RI "InputDataType const  & \fBInputParameter\fP () const"
.br
.RI "Get the input parameter\&. "
.ti -1c
.RI "size_t \fBInputShape\fP () const"
.br
.RI "Get the shape of the input\&. "
.ti -1c
.RI "size_t \fBInSize\fP () const"
.br
.RI "Get the number of input units\&. "
.ti -1c
.RI "std::vector< \fBLayerTypes\fP< CustomLayers\&.\&.\&. > > & \fBModel\fP ()"
.br
.RI "Return the modules of the model\&. "
.ti -1c
.RI "OutputDataType & \fBOutputParameter\fP ()"
.br
.RI "Modify the output parameter\&. "
.ti -1c
.RI "OutputDataType const  & \fBOutputParameter\fP () const"
.br
.RI "Get the output parameter\&. "
.ti -1c
.RI "OutputDataType & \fBParameters\fP ()"
.br
.RI "Modify the parameters\&. "
.ti -1c
.RI "OutputDataType const  & \fBParameters\fP () const"
.br
.RI "Get the parameters\&. "
.ti -1c
.RI "void \fBReset\fP ()"
.br
.RI "Reset the layer parameter\&. "
.ti -1c
.RI "template<typename Archive > void \fBserialize\fP (Archive &ar, const uint32_t)"
.br
.RI "Serialize the layer\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename InputDataType = arma::mat, typename OutputDataType = arma::mat, typename\&.\&.\&. CustomLayers>
.br
class mlpack::ann::Highway< InputDataType, OutputDataType, CustomLayers >"
Implementation of the \fBHighway\fP layer\&. 

The \fBHighway\fP class can vary its behavior between that of feed-forward fully connected network container and that of a layer which simply passes its inputs through depending on the transform gate\&. Note that the size of the input and output matrices of this class should be equal\&.
.PP
For more information, refer the following paper\&.
.PP
.PP
.nf
@article{Srivastava2015,
  author  = {Rupesh Kumar Srivastava, Klaus Greff, Jurgen Schmidhuber},
  title   = {Training Very Deep Networks},
  journal = {Advances in Neural Information Processing Systems},
  year    = {2015},
  url     = {https://arxiv\&.org/abs/1507\&.06228},
}
.fi
.PP
.PP
\fBTemplate Parameters\fP
.RS 4
\fIInputDataType\fP Type of the input data (arma::colvec, arma::mat, arma::sp_mat or arma::cube)\&. 
.br
\fIOutputDataType\fP Type of the output data (arma::colvec, arma::mat, arma::sp_mat or arma::cube)\&. 
.RE
.PP

.PP
Definition at line 60 of file highway\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBHighway\fP ()"

.PP
Create the \fBHighway\fP object\&. 
.SS "\fBHighway\fP (const size_t inSize, const bool model = \fCtrue\fP)"

.PP
Create the \fBHighway\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIinSize\fP The number of input units\&. 
.br
\fImodel\fP Expose all the network modules\&. 
.RE
.PP

.SS "~\fBHighway\fP ()"

.PP
Destroy the \fBHighway\fP object\&. 
.SH "Member Function Documentation"
.PP 
.SS "void \fBAdd\fP (Args\&.\&.\&. args)\fC [inline]\fP"

.PP
\fBAdd\fP a new module to the model\&. 
.PP
\fBParameters\fP
.RS 4
\fIargs\fP The layer parameter\&. 
.RE
.PP

.PP
Definition at line 124 of file highway\&.hpp\&.
.SS "void \fBAdd\fP (\fBLayerTypes\fP< CustomLayers\&.\&.\&. > layer)\fC [inline]\fP"

.PP
\fBAdd\fP a new module to the model\&. 
.PP
\fBParameters\fP
.RS 4
\fIlayer\fP The Layer to be added to the model\&. 
.RE
.PP

.PP
Definition at line 135 of file highway\&.hpp\&.
.SS "void Backward (const arma::Mat< eT > &, const arma::Mat< eT > & gy, arma::Mat< eT > & g)"

.PP
Ordinary feed-backward pass of a neural network, calculating the function f(x) by propagating x backwards through f\&. Using the results from the feed-forward pass\&.
.PP
\fBParameters\fP
.RS 4
\fI*\fP (input) The propagated input activation\&. 
.br
\fIgy\fP The backpropagated error\&. 
.br
\fIg\fP The calculated gradient\&. 
.RE
.PP

.SS "OutputDataType& Delta ()\fC [inline]\fP"

.PP
Modify the delta\&. 
.PP
Definition at line 170 of file highway\&.hpp\&.
.SS "OutputDataType const& Delta () const\fC [inline]\fP"

.PP
Get the delta\&. 
.PP
Definition at line 168 of file highway\&.hpp\&.
.SS "void Forward (const arma::Mat< eT > & input, arma::Mat< eT > & output)"

.PP
Ordinary feed-forward pass of a neural network, evaluating the function f(x) by propagating the activity forward through f\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput\fP Input data used for evaluating the specified function\&. 
.br
\fIoutput\fP Resulting output activation\&. 
.RE
.PP

.SS "OutputDataType& Gradient ()\fC [inline]\fP"

.PP
Modify the gradient\&. 
.PP
Definition at line 175 of file highway\&.hpp\&.
.SS "OutputDataType const& Gradient () const\fC [inline]\fP"

.PP
Get the gradient\&. 
.PP
Definition at line 173 of file highway\&.hpp\&.
.SS "void Gradient (const arma::Mat< eT > & input, const arma::Mat< eT > & error, arma::Mat< eT > & gradient)"

.PP
Calculate the gradient using the output delta and the input activation\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput\fP The input parameter used for calculating the gradient\&. 
.br
\fIerror\fP The calculated error\&. 
.br
\fIgradient\fP The calculated gradient\&. 
.RE
.PP

.SS "InputDataType& InputParameter ()\fC [inline]\fP"

.PP
Modify the input parameter\&. 
.PP
Definition at line 160 of file highway\&.hpp\&.
.SS "InputDataType const& InputParameter () const\fC [inline]\fP"

.PP
Get the input parameter\&. 
.PP
Definition at line 158 of file highway\&.hpp\&.
.SS "size_t InputShape () const\fC [inline]\fP"

.PP
Get the shape of the input\&. 
.PP
Definition at line 181 of file highway\&.hpp\&.
.SS "size_t InSize () const\fC [inline]\fP"

.PP
Get the number of input units\&. 
.PP
Definition at line 178 of file highway\&.hpp\&.
.SS "std::vector<\fBLayerTypes\fP<CustomLayers\&.\&.\&.> >& Model ()\fC [inline]\fP"

.PP
Return the modules of the model\&. 
.PP
Definition at line 142 of file highway\&.hpp\&.
.SS "OutputDataType& OutputParameter ()\fC [inline]\fP"

.PP
Modify the output parameter\&. 
.PP
Definition at line 165 of file highway\&.hpp\&.
.SS "OutputDataType const& OutputParameter () const\fC [inline]\fP"

.PP
Get the output parameter\&. 
.PP
Definition at line 163 of file highway\&.hpp\&.
.SS "OutputDataType& Parameters ()\fC [inline]\fP"

.PP
Modify the parameters\&. 
.PP
Definition at line 155 of file highway\&.hpp\&.
.SS "OutputDataType const& Parameters () const\fC [inline]\fP"

.PP
Get the parameters\&. 
.PP
Definition at line 153 of file highway\&.hpp\&.
.SS "void Reset ()"

.PP
Reset the layer parameter\&. 
.SS "void serialize (Archive & ar, const uint32_t)"

.PP
Serialize the layer\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
