.TH "SingleTreeTraverser< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SingleTreeTraverser< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSingleTreeTraverser\fP (RuleType &rule)"
.br
.RI "Instantiate the traverser with the given rule set\&. "
.ti -1c
.RI "size_t \fBNumPrunes\fP () const"
.br
.RI "Get the number of prunes\&. "
.ti -1c
.RI "size_t & \fBNumPrunes\fP ()"
.br
.RI "Modify the number of prunes\&. "
.ti -1c
.RI "void \fBTraverse\fP (const size_t queryIndex, const RectangleTree &referenceNode)"
.br
.RI "Traverse the tree with the given point\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename MetricType, typename StatisticType, typename MatType, typename SplitType, typename DescentType, template< typename > class AuxiliaryInformationType>
.br
class mlpack::tree::RectangleTree::SingleTreeTraverser< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >"

.PP
Definition at line 31 of file single_tree_traverser\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBSingleTreeTraverser\fP (RuleType & rule)"

.PP
Instantiate the traverser with the given rule set\&. 
.SH "Member Function Documentation"
.PP 
.SS "size_t NumPrunes () const\fC [inline]\fP"

.PP
Get the number of prunes\&. 
.PP
Definition at line 50 of file single_tree_traverser\&.hpp\&.
.SS "size_t& NumPrunes ()\fC [inline]\fP"

.PP
Modify the number of prunes\&. 
.PP
Definition at line 52 of file single_tree_traverser\&.hpp\&.
.SS "void Traverse (const size_t queryIndex, const RectangleTree & referenceNode)"

.PP
Traverse the tree with the given point\&. 
.PP
\fBParameters:\fP
.RS 4
\fIqueryIndex\fP The index of the point in the query set which is being used as the query point\&. 
.br
\fIreferenceNode\fP The tree node to be traversed\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
