.TH "DeduceHyperParameterTypes< T, Args... >::ResultHPType< ArithmeticType, true >" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeduceHyperParameterTypes< T, Args... >::ResultHPType< ArithmeticType, true >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBType\fP = ArithmeticType"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, typename\&.\&.\&. Args>
.br
template<typename ArithmeticType>
.br
struct mlpack::hpt::DeduceHyperParameterTypes< T, Args\&.\&.\&. >::ResultHPType< ArithmeticType, true >"

.PP
Definition at line 59 of file deduce_hp_types\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBType\fP =  ArithmeticType"

.PP
Definition at line 61 of file deduce_hp_types\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
