.TH "QUICSVDPolicy" 3 "Sun Aug 22 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QUICSVDPolicy \- Implementation of the QUIC-SVD policy\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQUICSVDPolicy\fP (const double epsilon=0\&.03, const double delta=0\&.1)"
.br
.RI "Use QUIC-SVD method to perform the principal components analysis (\fBPCA\fP)\&. "
.ti -1c
.RI "void \fBApply\fP (const arma::mat &data, const arma::mat &centeredData, arma::mat &transformedData, arma::vec &eigVal, arma::mat &eigvec, const size_t)"
.br
.RI "Apply Principal Component Analysis to the provided data set using the QUIC-SVD method\&. "
.ti -1c
.RI "double \fBDelta\fP () const"
.br
.RI "Get the cumulative probability for Monte Carlo error lower bound\&. "
.ti -1c
.RI "double & \fBDelta\fP ()"
.br
.RI "Modify the cumulative probability for Monte Carlo error lower bound\&. "
.ti -1c
.RI "double \fBEpsilon\fP () const"
.br
.RI "Get the error tolerance fraction for calculated subspace\&. "
.ti -1c
.RI "double & \fBEpsilon\fP ()"
.br
.RI "Modify the error tolerance fraction for calculated subspace\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implementation of the QUIC-SVD policy\&. 
.PP
Definition at line 26 of file quic_svd_method\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBQUICSVDPolicy\fP (const double epsilon = \fC0\&.03\fP, const double delta = \fC0\&.1\fP)\fC [inline]\fP"

.PP
Use QUIC-SVD method to perform the principal components analysis (\fBPCA\fP)\&. 
.PP
\fBParameters:\fP
.RS 4
\fIepsilon\fP Error tolerance fraction for calculated subspace\&. 
.br
\fIdelta\fP Cumulative probability for Monte Carlo error lower bound\&. 
.RE
.PP

.PP
Definition at line 35 of file quic_svd_method\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Apply (const arma::mat & data, const arma::mat & centeredData, arma::mat & transformedData, arma::vec & eigVal, arma::mat & eigvec, const size_t)\fC [inline]\fP"

.PP
Apply Principal Component Analysis to the provided data set using the QUIC-SVD method\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP Data matrix\&. 
.br
\fIcenteredData\fP Centered data matrix\&. 
.br
\fItransformedData\fP Matrix to put results of \fBPCA\fP into\&. 
.br
\fIeigVal\fP Vector to put eigenvalues into\&. 
.br
\fIeigvec\fP Matrix to put eigenvectors (loadings) into\&. 
.br
\fI*\fP (rank) Rank of the decomposition\&. 
.RE
.PP

.PP
Definition at line 53 of file quic_svd_method\&.hpp\&.
.SS "double Delta () const\fC [inline]\fP"

.PP
Get the cumulative probability for Monte Carlo error lower bound\&. 
.PP
Definition at line 81 of file quic_svd_method\&.hpp\&.
.SS "double& Delta ()\fC [inline]\fP"

.PP
Modify the cumulative probability for Monte Carlo error lower bound\&. 
.PP
Definition at line 83 of file quic_svd_method\&.hpp\&.
.SS "double Epsilon () const\fC [inline]\fP"

.PP
Get the error tolerance fraction for calculated subspace\&. 
.PP
Definition at line 76 of file quic_svd_method\&.hpp\&.
.SS "double& Epsilon ()\fC [inline]\fP"

.PP
Modify the error tolerance fraction for calculated subspace\&. 
.PP
Definition at line 78 of file quic_svd_method\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
