.TH "mlpack::lmnn" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlpack::lmnn \- Large Margin Nearest Neighbor\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConstraints\fP"
.br
.RI "Interface for generating distance based constraints on a given dataset, provided corresponding true labels and a quantity parameter (k) are specified\&. "
.ti -1c
.RI "class \fBLMNN\fP"
.br
.RI "An implementation of Large Margin nearest neighbor metric learning technique\&. "
.ti -1c
.RI "class \fBLMNNFunction\fP"
.br
.RI "The Large Margin Nearest Neighbors function\&. "
.in -1c
.SH "Detailed Description"
.PP 
Large Margin Nearest Neighbor\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
