.TH "AdaBoostModel" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdaBoostModel \- The model to save to disk\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBWeakLearnerTypes\fP { \fBDECISION_STUMP\fP, \fBPERCEPTRON\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAdaBoostModel\fP ()"
.br
.RI "Create an empty \fBAdaBoost\fP model\&. "
.ti -1c
.RI "\fBAdaBoostModel\fP (const arma::Col< size_t > &mappings, const size_t weakLearnerType)"
.br
.RI "Create the \fBAdaBoost\fP model with the given mappings and type\&. "
.ti -1c
.RI "\fBAdaBoostModel\fP (const \fBAdaBoostModel\fP &other)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "\fBAdaBoostModel\fP (\fBAdaBoostModel\fP &&other)"
.br
.RI "Move constructor\&. "
.ti -1c
.RI "\fB~AdaBoostModel\fP ()"
.br
.RI "Clean up memory\&. "
.ti -1c
.RI "void \fBClassify\fP (const arma::mat &testData, arma::Row< size_t > &predictions)"
.br
.RI "Classify test points\&. "
.ti -1c
.RI "void \fBClassify\fP (const arma::mat &testData, arma::Row< size_t > &predictions, arma::mat &probabilities)"
.br
.RI "Classify test points\&. "
.ti -1c
.RI "size_t \fBDimensionality\fP () const"
.br
.RI "Get the dimensionality of the model\&. "
.ti -1c
.RI "size_t & \fBDimensionality\fP ()"
.br
.RI "Modify the dimensionality of the model\&. "
.ti -1c
.RI "const arma::Col< size_t > & \fBMappings\fP () const"
.br
.RI "Get the mappings\&. "
.ti -1c
.RI "arma::Col< size_t > & \fBMappings\fP ()"
.br
.RI "Modify the mappings\&. "
.ti -1c
.RI "\fBAdaBoostModel\fP & \fBoperator=\fP (const \fBAdaBoostModel\fP &other)"
.br
.RI "Copy assignment operator\&. "
.ti -1c
.RI "\fBAdaBoostModel\fP & \fBoperator=\fP (\fBAdaBoostModel\fP &&other)"
.br
.RI "Move assignment operator\&. "
.ti -1c
.RI "template<typename Archive > void \fBserialize\fP (Archive &ar, const uint32_t)"
.br
.RI "Serialize the model\&. "
.ti -1c
.RI "void \fBTrain\fP (const arma::mat &data, const arma::Row< size_t > &labels, const size_t numClasses, const size_t iterations, const double tolerance)"
.br
.RI "Train the model, treat the data is all of the numeric type\&. "
.ti -1c
.RI "size_t \fBWeakLearnerType\fP () const"
.br
.RI "Get the weak learner type\&. "
.ti -1c
.RI "size_t & \fBWeakLearnerType\fP ()"
.br
.RI "Modify the weak learner type\&. "
.in -1c
.SH "Detailed Description"
.PP 
The model to save to disk\&. 
.PP
Definition at line 26 of file adaboost_model\&.hpp\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBWeakLearnerTypes\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDECISION_STUMP \fP\fP
.TP
\fB\fIPERCEPTRON \fP\fP
.PP
Definition at line 29 of file adaboost_model\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBAdaBoostModel\fP ()"

.PP
Create an empty \fBAdaBoost\fP model\&. 
.SS "\fBAdaBoostModel\fP (const arma::Col< size_t > & mappings, const size_t weakLearnerType)"

.PP
Create the \fBAdaBoost\fP model with the given mappings and type\&. 
.SS "\fBAdaBoostModel\fP (const \fBAdaBoostModel\fP & other)"

.PP
Copy constructor\&. 
.SS "\fBAdaBoostModel\fP (\fBAdaBoostModel\fP && other)"

.PP
Move constructor\&. 
.SS "~\fBAdaBoostModel\fP ()"

.PP
Clean up memory\&. 
.SH "Member Function Documentation"
.PP 
.SS "void Classify (const arma::mat & testData, arma::Row< size_t > & predictions)"

.PP
Classify test points\&. 
.PP
Referenced by AdaBoostModel::Dimensionality()\&.
.SS "void Classify (const arma::mat & testData, arma::Row< size_t > & predictions, arma::mat & probabilities)"

.PP
Classify test points\&. 
.SS "size_t Dimensionality () const\fC [inline]\fP"

.PP
Get the dimensionality of the model\&. 
.PP
Definition at line 81 of file adaboost_model\&.hpp\&.
.SS "size_t& Dimensionality ()\fC [inline]\fP"

.PP
Modify the dimensionality of the model\&. 
.PP
Definition at line 83 of file adaboost_model\&.hpp\&.
.PP
References AdaBoostModel::Classify(), and AdaBoostModel::Train()\&.
.SS "const arma::Col<size_t>& Mappings () const\fC [inline]\fP"

.PP
Get the mappings\&. 
.PP
Definition at line 71 of file adaboost_model\&.hpp\&.
.SS "arma::Col<size_t>& Mappings ()\fC [inline]\fP"

.PP
Modify the mappings\&. 
.PP
Definition at line 73 of file adaboost_model\&.hpp\&.
.SS "\fBAdaBoostModel\fP& operator= (const \fBAdaBoostModel\fP & other)"

.PP
Copy assignment operator\&. 
.SS "\fBAdaBoostModel\fP& operator= (\fBAdaBoostModel\fP && other)"

.PP
Move assignment operator\&. 
.SS "void serialize (Archive & ar, const uint32_t)\fC [inline]\fP"

.PP
Serialize the model\&. 
.PP
Definition at line 103 of file adaboost_model\&.hpp\&.
.PP
References CEREAL_POINTER\&.
.SS "void Train (const arma::mat & data, const arma::Row< size_t > & labels, const size_t numClasses, const size_t iterations, const double tolerance)"

.PP
Train the model, treat the data is all of the numeric type\&. 
.PP
Referenced by AdaBoostModel::Dimensionality()\&.
.SS "size_t WeakLearnerType () const\fC [inline]\fP"

.PP
Get the weak learner type\&. 
.PP
Definition at line 76 of file adaboost_model\&.hpp\&.
.SS "size_t& WeakLearnerType ()\fC [inline]\fP"

.PP
Modify the weak learner type\&. 
.PP
Definition at line 78 of file adaboost_model\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
