.TH "KernelTraits< TriangularKernel >" 3 "Sun Aug 22 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KernelTraits< TriangularKernel > \- Kernel traits for the triangular kernel\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBIsNormalized\fP = true"
.br
.RI "The triangular kernel is normalized: K(x, x) = 1 for all x\&. "
.ti -1c
.RI "static const bool \fBUsesSquaredDistance\fP = false"
.br
.RI "The triangular kernel doesn't include a squared distance\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
class mlpack::kernel::KernelTraits< TriangularKernel >"
Kernel traits for the triangular kernel\&. 
.PP
Definition at line 108 of file triangular_kernel\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "const bool IsNormalized = true\fC [static]\fP"

.PP
The triangular kernel is normalized: K(x, x) = 1 for all x\&. 
.PP
Definition at line 112 of file triangular_kernel\&.hpp\&.
.SS "const bool UsesSquaredDistance = false\fC [static]\fP"

.PP
The triangular kernel doesn't include a squared distance\&. 
.PP
Definition at line 114 of file triangular_kernel\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
