.TH "OrderedSelection" 3 "Sun Aug 22 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OrderedSelection
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const arma::Col< size_t > \fBSelect\fP (const arma::mat &, const size_t m)"
.br
.RI "Select the specified number of points in the dataset\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file ordered_selection\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static const arma::Col<size_t> Select (const arma::mat &, const size_t m)\fC [inline]\fP, \fC [static]\fP"

.PP
Select the specified number of points in the dataset\&. 
.PP
\fBParameters:\fP
.RS 4
\fI*\fP (data) Dataset to sample from\&. 
.br
\fIm\fP Number of points to select\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Indices of selected points from the dataset\&. 
.RE
.PP

.PP
Definition at line 32 of file ordered_selection\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
