.TH "KDECleanRules< TreeType >" 3 "Sun Aug 22 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KDECleanRules< TreeType > \- A dual-tree traversal Rules class for cleaning used trees before performing kernel density estimation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBtree::TraversalInfo\fP< TreeType > \fBTraversalInfoType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKDECleanRules\fP ()"
.br
.RI "Construct \fBKDECleanRules\fP\&. "
.ti -1c
.RI "double \fBBaseCase\fP (const size_t, const size_t)"
.br
.RI "Base Case\&. "
.ti -1c
.RI "double \fBRescore\fP (const size_t, TreeType &, const double oldScore) const"
.br
.RI "SingleTree Rescore\&. "
.ti -1c
.RI "double \fBRescore\fP (TreeType &, TreeType &, const double oldScore) const"
.br
.RI "Dual-Tree Rescore\&. "
.ti -1c
.RI "double \fBScore\fP (const size_t, TreeType &referenceNode)"
.br
.RI "SingleTree Score\&. "
.ti -1c
.RI "double \fBScore\fP (TreeType &queryNode, TreeType &referenceNode)"
.br
.RI "Dual-Tree Score\&. "
.ti -1c
.RI "const \fBTraversalInfoType\fP & \fBTraversalInfo\fP () const"
.br
.RI "Get traversal information\&. "
.ti -1c
.RI "\fBTraversalInfoType\fP & \fBTraversalInfo\fP ()"
.br
.RI "Modify traversal information\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename TreeType>
.br
class mlpack::kde::KDECleanRules< TreeType >"
A dual-tree traversal Rules class for cleaning used trees before performing kernel density estimation\&. 
.PP
Definition at line 189 of file kde_rules\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef \fBtree::TraversalInfo\fP<TreeType> \fBTraversalInfoType\fP"

.PP
Definition at line 214 of file kde_rules\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBKDECleanRules\fP ()\fC [inline]\fP"

.PP
Construct \fBKDECleanRules\fP\&. 
.PP
Definition at line 193 of file kde_rules\&.hpp\&.
.PP
References KDERules< MetricType, KernelType, TreeType >::BaseCase(), and KDERules< MetricType, KernelType, TreeType >::Score()\&.
.SH "Member Function Documentation"
.PP 
.SS "double BaseCase (const size_t, const size_t)"

.PP
Base Case\&. 
.SS "double Rescore (const size_t, TreeType &, const double oldScore) const\fC [inline]\fP"

.PP
SingleTree Rescore\&. 
.PP
Definition at line 202 of file kde_rules\&.hpp\&.
.PP
References KDERules< MetricType, KernelType, TreeType >::Score()\&.
.SS "double Rescore (TreeType &, TreeType &, const double oldScore) const\fC [inline]\fP"

.PP
Dual-Tree Rescore\&. 
.PP
Definition at line 210 of file kde_rules\&.hpp\&.
.SS "double Score (const size_t, TreeType & referenceNode)"

.PP
SingleTree Score\&. 
.SS "double Score (TreeType & queryNode, TreeType & referenceNode)"

.PP
Dual-Tree Score\&. 
.SS "const \fBTraversalInfoType\fP& TraversalInfo () const\fC [inline]\fP"

.PP
Get traversal information\&. 
.PP
Definition at line 217 of file kde_rules\&.hpp\&.
.SS "\fBTraversalInfoType\fP& TraversalInfo ()\fC [inline]\fP"

.PP
Modify traversal information\&. 
.PP
Definition at line 220 of file kde_rules\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
