.TH "/home/aakash/mlpack/src/mlpack/core/math/multiply_slices.hpp" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/aakash/mlpack/src/mlpack/core/math/multiply_slices.hpp
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmlpack\fP"
.br
.RI "Linear algebra utility functions, generally performed on matrices or vectors\&. "
.ti -1c
.RI " \fBmlpack::math\fP"
.br
.RI "Miscellaneous math routines\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename CubeType > CubeType \fBMultiplyCube2Cube\fP (const CubeType &cubeA, const CubeType &cubeB, const bool aTranspose=false, const bool bTranspose=false)"
.br
.RI "Matrix multiplication of slices of two cubes\&. "
.ti -1c
.RI "template<typename CubeType , typename MatType > CubeType \fBMultiplyCube2Mat\fP (const CubeType &cubeA, const MatType &matB, const bool aTranspose=false, const bool bTranspose=false)"
.br
.RI "Matrix multiplication of all slices of a cube with a matrix\&. "
.ti -1c
.RI "template<typename MatType , typename CubeType > CubeType \fBMultiplyMat2Cube\fP (const MatType &matA, const CubeType &cubeB, const bool aTranspose=false, const bool bTranspose=false)"
.br
.RI "Matrix multiplication of a matrix and all the slices of a cube\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Mrityunjay Tripathi
.RE
.PP
Function to perform matrix multiplication on cubes\&.
.PP
mlpack is free software; you may redistribute it and/or modify it under the terms of the 3-clause BSD license\&. You should have received a copy of the 3-clause BSD license along with mlpack\&. If not, see http://www.opensource.org/licenses/BSD-3-Clause for more information\&. 
.PP
Definition in file \fBmultiply_slices\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
