.TH "/home/aakash/mlpack/src/mlpack/core/util/param_data.hpp" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/aakash/mlpack/src/mlpack/core/util/param_data.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDatasetMapper< PolicyType, InputType >\fP"
.br
.RI "Auxiliary information for a dataset, including mappings to/from strings (or other types) and the datatype of each dimension\&. "
.ti -1c
.RI "struct \fBParamData\fP"
.br
.RI "This structure holds all of the information about a single parameter, including its value (which is set when ParseCommandLine() is called)\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmlpack\fP"
.br
.RI "Linear algebra utility functions, generally performed on matrices or vectors\&. "
.ti -1c
.RI " \fBmlpack::data\fP"
.br
.RI "Functions to load and save matrices and models\&. "
.ti -1c
.RI " \fBmlpack::util\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTYPENAME\fP(x)   (std::string(typeid(x)\&.name()))"
.br
.RI "The TYPENAME macro is used internally to convert a type into a string\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Ryan Curtin
.RE
.PP
This defines the structure that holds information for each command-line parameter, as well as utility functions it is used with\&.
.PP
mlpack is free software; you may redistribute it and/or modify it under the terms of the 3-clause BSD license\&. You should have received a copy of the 3-clause BSD license along with mlpack\&. If not, see http://www.opensource.org/licenses/BSD-3-Clause for more information\&. 
.PP
Definition in file \fBparam_data\&.hpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define TYPENAME(x)   (std::string(typeid(x)\&.name()))"

.PP
The TYPENAME macro is used internally to convert a type into a string\&. 
.PP
Definition at line 22 of file param_data\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
