.TH "/home/aakash/mlpack/src/mlpack/core/cereal/pointer_variant_wrapper.hpp" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/aakash/mlpack/src/mlpack/core/cereal/pointer_variant_wrapper.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBload_visitor< T >\fP"
.br
.ti -1c
.RI "class \fBPointerVariantWrapper< VariantTypes >\fP"
.br
.RI "The objective of this class is to create a wrapper for boost::variant\&. "
.ti -1c
.RI "class \fBPointerVariantWrapper< VariantTypes >\fP"
.br
.RI "The objective of this class is to create a wrapper for boost::variant\&. "
.ti -1c
.RI "struct \fBsave_visitor< Archive >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBcereal\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCEREAL_VARIANT_POINTER\fP(T)   \fBcereal::make_pointer_variant\fP(T)"
.br
.RI "Cereal does not support the serialization of raw pointer\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. VariantTypes> PointerVariantWrapper< VariantTypes\&.\&.\&. > \fBmake_pointer_variant\fP (boost::variant< VariantTypes\&.\&.\&. > &t)"
.br
.RI "Serialize a boost variant in which the variant it self is a raw pointer\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Omar Shrit
.RE
.PP
Implementation of a boost::variant wrapper to enable the serialization of the pointers inside boost variant in cereal
.PP
mlpack is free software; you may redistribute it and/or modify it under the terms of the 3-clause BSD license\&. You should have received a copy of the 3-clause BSD license along with mlpack\&. If not, see http://www.opensource.org/licenses/BSD-3-Clause for more information\&. 
.PP
Definition in file \fBpointer_variant_wrapper\&.hpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define CEREAL_VARIANT_POINTER(T)   \fBcereal::make_pointer_variant\fP(T)"

.PP
Cereal does not support the serialization of raw pointer\&. This macro enable developers to serialize boost::variant that holds raw pointers by using the above PointerVariantWrapper class which replace the internal raw pointers by smart pointer internally\&.
.PP
\fBParameters:\fP
.RS 4
\fIT\fP boost::variant that holds raw pointer to be serialized\&. 
.RE
.PP

.PP
Definition at line 155 of file pointer_variant_wrapper\&.hpp\&.
.PP
Referenced by PointerVectorVariantWrapper< VariantTypes >::load(), and PointerVectorVariantWrapper< VariantTypes >::save()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
