.TH "/home/aakash/mlpack/src/mlpack/bindings/julia/print_model_type_import.hpp" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/aakash/mlpack/src/mlpack/bindings/julia/print_model_type_import.hpp
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmlpack\fP"
.br
.RI "Linear algebra utility functions, generally performed on matrices or vectors\&. "
.ti -1c
.RI " \fBmlpack::bindings\fP"
.br
.ti -1c
.RI " \fBmlpack::bindings::julia\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > void \fBPrintModelTypeImport\fP (util::ParamData &, const typename std::enable_if< arma::is_arma_type< T >::value >::type *=0)"
.br
.RI "Matrices are serializable but here we also print nothing\&. "
.ti -1c
.RI "template<typename T > void \fBPrintModelTypeImport\fP (util::ParamData &, const typename std::enable_if<!arma::is_arma_type< T >::value >::type *=0, const typename std::enable_if<!data::HasSerialize< T >::value >::type *=0)"
.br
.RI "If the type is not serializable, print nothing\&. "
.ti -1c
.RI "template<typename T > void \fBPrintModelTypeImport\fP (util::ParamData &d, const typename std::enable_if<!arma::is_arma_type< T >::value >::type *=0, const typename std::enable_if< data::HasSerialize< T >::value >::type *=0)"
.br
.RI "For non-matrix serializable types we need to print something\&. "
.ti -1c
.RI "template<typename T > void \fBPrintModelTypeImport\fP (util::ParamData &d, const void *, void *)"
.br
.RI "If the type is serializable, print the definition of a special utility function to set a \fBIO\fP parameter of that type to stdout\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Ryan Curtin
.RE
.PP
If the type is serializable, we need to define a special utility function to set a IO parameter of that type\&.
.PP
mlpack is free software; you may redistribute it and/or modify it under the terms of the 3-clause BSD license\&. You should have received a copy of the 3-clause BSD license along with mlpack\&. If not, see http://www.opensource.org/licenses/BSD-3-Clause for more information\&. 
.PP
Definition in file \fBprint_model_type_import\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
