.TH "std" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "template<bool B, class T  = void> using \fBenable_if_t\fP = typename enable_if< B, T >::type"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , typename\&.\&.\&. Args> std::unique_ptr< T > \fBmake_unique\fP (Args &&\&.\&.\&. args)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBenable_if_t\fP =  typename enable_if<B, T>::type"

.PP
Definition at line 70 of file prereqs\&.hpp\&.
.SH "Function Documentation"
.PP 
.SS "std::unique_ptr<T> std::make_unique (Args &&\&.\&.\&. args)"

.PP
Definition at line 25 of file pointer_wrapper\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
