.TH "/home/aakash/mlpack/src/mlpack/methods/ann/activation_functions/tanh_exponential_function.hpp" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/aakash/mlpack/src/mlpack/methods/ann/activation_functions/tanh_exponential_function.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTanhExpFunction\fP"
.br
.RI "The TanhExp function, defined by\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmlpack\fP"
.br
.RI "Linear algebra utility functions, generally performed on matrices or vectors\&. "
.ti -1c
.RI " \fBmlpack::ann\fP"
.br
.RI "Artificial Neural Network\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Mayank Raj
.RE
.PP
Definition and implementation of the Tanh exponential function\&.
.PP
For more information see the following paper
.PP
.PP
.nf
@misc{The Institution of Engineering and Technology 2015 ,
   title = {TanhExp: A Smooth Activation Function with High Convergence Speed
            for Lightweight Neural Networks},
   author = {Xinyu Liu and Xiaoguang Di},
   year = {2020},
   url = {https://arxiv\&.org/pdf/2003\&.09855v2\&.pdf},
   eprint = {2003\&.09855v2},
   archivePrefix = {arXiv},
   primaryClass = {cs\&.LG} }
.fi
.PP
.PP
mlpack is free software; you may redistribute it and/or modify it under the terms of the 3-clause BSD license\&. You should have received a copy of the 3-clause BSD license along with mlpack\&. If not, see http://www.opensource.org/licenses/BSD-3-Clause for more information\&. 
.PP
Definition in file \fBtanh_exponential_function\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
