.TH "TrainHMMModel" 3 "Thu Jun 24 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TrainHMMModel
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename HMMType > static void \fBApply\fP (HMMType &hmm, vector< arma::mat > *trainSeq)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 202 of file hmm_test_utils\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Apply (HMMType & hmm, vector< arma::mat > * trainSeq)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 205 of file hmm_test_utils\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
