.TH "/home/aakash/mlpack/src/mlpack/core/cereal/unordered_map.hpp" 3 "Sun Jun 20 2021" "Version 3.4.2" "mlpack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/aakash/mlpack/src/mlpack/core/cereal/unordered_map.hpp \- This file is backported from cereal 1\&.3 to support the serialization of objects of type associative containers (std::map, std::pair, etc\&.)  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This file is backported from cereal 1\&.3 to support the serialization of objects of type associative containers (std::map, std::pair, etc\&.) 

This file add the support for serialization of containers for any version of cereal starting from 1\&.1\&.2 that is required by Ubuntu 16\&.04
.PP
Support for types found in <unordered_map> 
.PP
Definition in file \fBunordered_map\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mlpack from the source code\&.
