name: Close inactive issues
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issues-stale: 30
          days-before-issue-close: 7
          stale-issue-label: "s: stale"
          stale-pr-label: "s: stale"
          stale-issue-message: "This issue has been automatically marked as stale because it has not had any recent activity.  It will be closed in 7 days if no further activity occurs.  Thank you for your contributions! :+1:"
          days-before-pr-stale: 30,
          days-before-pr-close: 14
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          exempt-issue-labels: "s: keep open"
          exempt-pr-labels: "s: keep open"
